package main

// Batch 6b: threeDAR, noCode, lifestyle, reading, gaming

func threeDAREx() []S {
	return []S{
		{"Blender", "https://www.blender.org", "开源3D创作套件"},
		{"Cinema 4D", "https://www.maxon.net/cinema-4d", "专业3D软件"},
		{"Maya", "https://www.autodesk.com/products/maya", "工业级3D动画"},
		{"3ds Max", "https://www.autodesk.com/products/3ds-max", "3D建模渲染"},
		{"Houdini", "https://www.sidefx.com", "程序化3D工具"},
		{"ZBrush", "https://www.maxon.net/zbrush", "数字雕刻软件"},
		{"Substance 3D", "https://www.adobe.com/products/substance3d.html", "3D材质工具"},
		{"Marvelous Designer", "https://www.marvelousdesigner.com", "3D服装设计"},
		{"KeyShot", "https://www.keyshot.com", "实时3D渲染"},
		{"V-Ray", "https://www.chaos.com/vray", "专业渲染器"},
		{"Arnold", "https://arnoldrenderer.com", "Autodesk渲染器"},
		{"Octane Render", "https://home.otoy.com/render/octane-render", "GPU渲染器"},
		{"Lumion", "https://lumion.com", "建筑可视化"},
		{"Enscape", "https://enscape3d.com", "实时渲染插件"},
		{"Twinmotion", "https://www.twinmotion.com", "实时沉浸可视化"},
		{"SketchUp", "https://www.sketchup.com", "3D建模工具"},
		{"Rhino 3D", "https://www.rhino3d.com", "NURBS建模"},
		{"Fusion 360", "https://www.autodesk.com/products/fusion-360", "CAD/CAM工具"},
		{"SolidWorks", "https://www.solidworks.com", "工程3D设计"},
		{"OnShape", "https://www.onshape.com", "云端CAD"},
		{"Tinkercad", "https://www.tinkercad.com", "入门级3D建模"},
		{"SculptGL", "https://stephaneginier.com/sculptgl", "Web 3D雕刻"},
		{"Clara.io", "https://clara.io", "在线3D建模"},
		{"Vectary", "https://www.vectary.com", "在线3D设计"},
		{"Spline", "https://spline.design", "Web 3D设计工具"},
		{"Ready Player Me", "https://readyplayer.me", "3D虚拟形象"},
		{"Mixamo", "https://www.mixamo.com", "3D角色动画"},
		{"Sketchfab", "https://sketchfab.com", "3D模型分享平台"},
		{"TurboSquid", "https://www.turbosquid.com", "3D模型市场"},
		{"CGTrader", "https://www.cgtrader.com", "3D模型交易"},
		{"Free3D", "https://free3d.com", "免费3D模型"},
		{"3D Warehouse", "https://3dwarehouse.sketchup.com", "SketchUp模型库"},
		{"Poly Haven", "https://polyhaven.com", "免费3D资源"},
		{"ambientCG", "https://ambientcg.com", "免费PBR材质"},
		{"Quixel Megascans", "https://quixel.com/megascans", "3D扫描资产"},
		{"Poliigon", "https://www.poliigon.com", "3D材质纹理"},
		{"Texture Haven", "https://texturehaven.com", "免费纹理"},
		{"HDRI Haven", "https://hdrihaven.com", "免费HDR环境"},
		{"ARKit", "https://developer.apple.com/augmented-reality", "苹果AR框架"},
		{"ARCore", "https://developers.google.com/ar", "谷歌AR平台"},
		{"Vuforia", "https://developer.vuforia.com", "AR开发平台"},
		{"8th Wall", "https://www.8thwall.com", "WebAR平台"},
		{"Spark AR", "https://sparkar.facebook.com", "Meta AR特效"},
		{"Lens Studio", "https://lensstudio.snapchat.com", "Snap AR工具"},
		{"Niantic Lightship", "https://lightship.dev", "AR开发SDK"},
		{"Reality Composer", "https://developer.apple.com/augmented-reality/tools", "苹果AR创作"},
		{"A-Frame", "https://aframe.io", "WebVR框架"},
		{"WebXR", "https://immersiveweb.dev", "Web沉浸式体验"},
		{"React Three Fiber", "https://docs.pmnd.rs/react-three-fiber", "React 3D库"},
		{"Model Viewer", "https://modelviewer.dev", "Web 3D查看器"},
		{"three.js", "https://threejs.org", "JavaScript 3D库"},
		{"Babylon.js", "https://www.babylonjs.com", "Web 3D引擎"},
		{"Cesium", "https://cesium.com", "3D地理空间平台"},
		{"Mapbox GL", "https://www.mapbox.com/mapbox-gljs", "3D地图渲染"},
		{"GrabCAD", "https://grabcad.com", "工程CAD社区"},
		{"Thingiverse", "https://www.thingiverse.com", "3D打印模型"},
		{"Printables", "https://www.printables.com", "3D打印社区"},
		{"MyMiniFactory", "https://www.myminifactory.com", "3D打印市场"},
		{"Cults3D", "https://cults3d.com", "3D打印设计"},
		{"PrusaPrinters", "https://www.prusa3d.com", "3D打印机品牌"},
		{"Ultimaker", "https://ultimaker.com", "3D打印解决方案"},
		{"Formlabs", "https://formlabs.com", "专业3D打印"},
		{"Shapeways", "https://www.shapeways.com", "3D打印服务"},
		{"i.materialise", "https://i.materialise.com", "3D打印平台"},
		{"花瓣3D", "https://3d.huaban.com", "中文3D素材"},
		{"CG模型网", "https://www.cgmodel.com", "CG模型下载"},
		{"3D侠", "https://www.3dxia.com", "3D模型素材"},
		{"3D溜溜网", "https://www.3d66.com", "室内3D模型"},
		{"建E网", "https://www.justeasy.cn", "室内设计素材"},
		{"知末", "https://www.znzmo.com", "建筑设计素材"},
		{"酷家乐", "https://www.kujiale.com", "3D家装设计"},
		{"三维家", "https://www.3vjia.com", "全屋定制设计"},
		{"Reallusion", "https://www.reallusion.com", "角色动画工具"},
		{"iClone", "https://www.reallusion.com/iclone", "实时3D动画"},
		{"Character Creator", "https://www.reallusion.com/character-creator", "角色创建工具"},
		{"Rokoko", "https://www.rokoko.com", "动作捕捉方案"},
		{"OptiTrack", "https://optitrack.com", "动作捕捉系统"},
		{"Matterport", "https://matterport.com", "3D空间扫描"},
		{"Polycam", "https://poly.cam", "3D扫描App"},
		{"Luma AI", "https://lumalabs.ai", "AI 3D重建"},
		{"NVIDIA Omniverse", "https://www.nvidia.com/omniverse", "3D协作平台"},
		{"Unity MARS", "https://unity.com/products/unity-mars", "Unity AR工具"},
		{"Unreal Engine VR", "https://www.unrealengine.com/vr", "虚幻VR开发"},
		{"WebGL Report", "https://webglreport.com", "WebGL兼容检测"},
		{"Shadertoy", "https://www.shadertoy.com", "着色器创作平台"},
		{"ShaderGraph", "https://unity.com/features/shader-graph", "Unity着色器"},
		{"Material Editor", "https://www.unrealengine.com/features/material-editor", "虚幻材质编辑"},
		{"Normal Map Online", "https://cpetry.github.io/NormalMap-Online", "法线贴图生成"},
		{"Materialize", "https://boundingboxsoftware.com/materialize", "纹理生成工具"},
	}
}

func noCodeEx() []S {
	return []S{
		{"Bubble", "https://bubble.io", "可视化Web开发"},
		{"Webflow", "https://webflow.com", "专业无代码建站"},
		{"Wix", "https://www.wix.com", "拖拽建站平台"},
		{"Squarespace", "https://www.squarespace.com", "精美网站构建"},
		{"WordPress.com", "https://wordpress.com", "博客建站平台"},
		{"Shopify", "https://www.shopify.com", "电商建站平台"},
		{"Carrd", "https://carrd.co", "单页网站构建"},
		{"Framer", "https://www.framer.com", "设计驱动建站"},
		{"Softr", "https://www.softr.io", "Airtable建站"},
		{"Glide", "https://www.glideapps.com", "表格变应用"},
		{"Adalo", "https://www.adalo.com", "无代码App构建"},
		{"Thunkable", "https://thunkable.com", "拖拽App开发"},
		{"FlutterFlow", "https://flutterflow.io", "Flutter可视化"},
		{"Bravo Studio", "https://www.bravostudio.app", "设计稿变App"},
		{"DraftBit", "https://draftbit.com", "移动App构建"},
		{"Airtable", "https://airtable.com", "智能电子表格"},
		{"Notion", "https://www.notion.so", "多功能工作空间"},
		{"Coda", "https://coda.io", "文档即应用"},
		{"AppSheet", "https://about.appsheet.com", "Google无代码"},
		{"Power Apps", "https://powerapps.microsoft.com", "微软低代码"},
		{"Retool", "https://retool.com", "内部工具构建"},
		{"Appsmith", "https://www.appsmith.com", "开源内部工具"},
		{"Tooljet", "https://www.tooljet.com", "开源低代码"},
		{"Budibase", "https://budibase.com", "开源内部应用"},
		{"Baserow", "https://baserow.io", "开源Airtable替代"},
		{"NocoDB", "https://nocodb.com", "开源智能表格"},
		{"Teable", "https://teable.io", "开源Airtable"},
		{"Zapier", "https://zapier.com", "自动化集成"},
		{"Make", "https://www.make.com", "可视化自动化"},
		{"n8n", "https://n8n.io", "开源工作流自动化"},
		{"IFTTT", "https://ifttt.com", "简单自动化"},
		{"Automate.io", "https://automate.io", "云端自动化"},
		{"Pipedream", "https://pipedream.com", "开发者自动化"},
		{"Pabbly Connect", "https://www.pabbly.com/connect", "自动化集成"},
		{"Tray.io", "https://tray.io", "企业自动化"},
		{"Workato", "https://www.workato.com", "企业自动化平台"},
		{"Stacker", "https://www.stackerhq.com", "数据驱动应用"},
		{"Internal.io", "https://www.internal.io", "内部工具平台"},
		{"Jet Admin", "https://www.jetadmin.io", "管理面板构建"},
		{"Forest Admin", "https://www.forestadmin.com", "管理面板生成"},
		{"Directual", "https://www.directual.com", "无代码后端"},
		{"Xano", "https://www.xano.com", "无代码后端API"},
		{"Backendless", "https://backendless.com", "无代码后端服务"},
		{"Supabase", "https://supabase.com", "开源后端服务"},
		{"Firebase", "https://firebase.google.com", "Google后端"},
		{"Memberstack", "https://www.memberstack.com", "会员认证工具"},
		{"Outseta", "https://www.outseta.com", "SaaS工具集"},
		{"Parabola", "https://parabola.io", "可视化数据处理"},
		{"Bardeen", "https://www.bardeen.ai", "AI自动化助手"},
		{"Voiceflow", "https://www.voiceflow.com", "对话AI构建"},
		{"Landbot", "https://landbot.io", "聊天机器人构建"},
		{"Typebot", "https://typebot.io", "开源聊天机器人"},
		{"Tally", "https://tally.so", "免费表单构建"},
		{"Jotform", "https://www.jotform.com", "在线表单工具"},
		{"Paperform", "https://paperform.co", "精美表单构建"},
		{"简道云", "https://www.jiandaoyun.com", "零代码应用平台"},
		{"明道云", "https://www.mingdao.com", "企业低代码"},
		{"轻流", "https://qingflow.com", "业务流程自动化"},
		{"宜搭", "https://www.aliwork.com", "阿里低代码"},
		{"微搭", "https://cloud.tencent.com/product/weda", "腾讯低代码"},
		{"氚云", "https://h3yun.com", "低代码开发平台"},
		{"搭搭云", "https://www.dadayun.cn", "零代码平台"},
		{"维格表", "https://vika.cn", "多维数据表"},
		{"黑帕云", "https://hipacloud.com", "协作数据库"},
		{"织信Informat", "https://www.informat.cn", "低代码平台"},
		{"伙伴云", "https://www.huoban.com", "数据管理平台"},
		{"速融云", "https://www.surongyun.cn", "低代码开发"},
		{"活字格", "https://www.grapecity.com.cn/solutions/huozige", "企业低代码"},
		{"飞书多维表格", "https://www.feishu.cn/product/bitable", "飞书数据应用"},
		{"钉钉宜搭", "https://www.aliwork.com", "钉钉低代码"},
		{"Tencent HiFlow", "https://hiflow.tencent.com", "腾讯自动化"},
		{"百度爱速搭", "https://aisuda.baidu.com", "百度低代码"},
		{"Unbounce", "https://unbounce.com", "落地页构建器"},
		{"Leadpages", "https://www.leadpages.com", "营销页构建"},
		{"ClickFunnels", "https://www.clickfunnels.com", "销售漏斗构建"},
		{"Gumroad", "https://gumroad.com", "数字产品销售"},
		{"Substack", "https://substack.com", "付费通讯平台"},
		{"ConvertKit", "https://convertkit.com", "创作者平台"},
		{"Notion Sites", "https://www.notion.so/product/sites", "Notion建站"},
		{"Super", "https://super.so", "Notion变网站"},
		{"Potion", "https://potion.so", "Notion建站工具"},
		{"Typedream", "https://typedream.com", "简单建站工具"},
		{"Dorik", "https://dorik.com", "AI无代码建站"},
		{"Durable", "https://durable.co", "AI快速建站"},
		{"10Web", "https://10web.io", "AI WordPress建站"},
		{"Mixo", "https://www.mixo.io", "AI创业网站"},
		{"Unicorn Platform", "https://unicornplatform.com", "创业落地页"},
		{"Umso", "https://www.umso.com", "AI启动页"},
		{"Sheet2Site", "https://www.sheet2site.com", "表格变网站"},
		{"Pory", "https://pory.io", "Airtable变应用"},
	}
}

func lifestyleEx() []S {
	return []S{
		{"大众点评", "https://www.dianping.com", "生活服务点评"},
		{"美团", "https://www.meituan.com", "本地生活服务"},
		{"饿了么", "https://www.ele.me", "外卖配送平台"},
		{"口碑", "https://www.koubei.com", "本地生活服务"},
		{"58同城", "https://www.58.com", "分类信息平台"},
		{"赶集网", "https://www.ganji.com", "分类信息网"},
		{"安居客", "https://www.anjuke.com", "房产信息平台"},
		{"链家", "https://www.lianjia.com", "房产交易平台"},
		{"贝壳找房", "https://www.ke.com", "房产服务平台"},
		{"自如", "https://www.ziroom.com", "长租公寓平台"},
		{"蛋壳公寓", "https://www.danke.com", "租房平台"},
		{"闲鱼", "https://www.xianyu.com", "二手交易平台"},
		{"转转", "https://www.zhuanzhuan.com", "二手物品交易"},
		{"多抓鱼", "https://www.duozhuayu.com", "二手书交易"},
		{"Yelp", "https://www.yelp.com", "商家点评平台"},
		{"TripAdvisor", "https://www.tripadvisor.com", "旅行点评"},
		{"Foursquare", "https://foursquare.com", "位置发现服务"},
		{"Google Maps", "https://maps.google.com", "谷歌地图"},
		{"Apple Maps", "https://maps.apple.com", "苹果地图"},
		{"高德地图", "https://www.amap.com", "导航出行"},
		{"百度地图", "https://map.baidu.com", "地图导航"},
		{"腾讯地图", "https://map.qq.com", "地图服务"},
		{"滴滴出行", "https://www.didiglobal.com", "网约车平台"},
		{"Uber", "https://www.uber.com", "全球网约车"},
		{"Lyft", "https://www.lyft.com", "美国网约车"},
		{"Grab", "https://www.grab.com", "东南亚出行"},
		{"嘀嗒出行", "https://www.didachuxing.com", "顺风车出行"},
		{"曹操出行", "https://www.caocaokeji.cn", "新能源网约车"},
		{"哈啰出行", "https://www.hellobike.com", "共享单车出行"},
		{"共享单车", "https://www.mobike.com", "摩拜单车"},
		{"12306", "https://www.12306.cn", "火车票购买"},
		{"去哪儿", "https://www.qunar.com", "机票酒店比价"},
		{"携程", "https://www.ctrip.com", "旅行服务平台"},
		{"飞猪", "https://www.fliggy.com", "旅行购票平台"},
		{"同程旅行", "https://www.ly.com", "旅游服务"},
		{"春秋航空", "https://www.ch.com", "廉价航空"},
		{"TaskRabbit", "https://www.taskrabbit.com", "跑腿服务"},
		{"Thumbtack", "https://www.thumbtack.com", "本地服务匹配"},
		{"Angi", "https://www.angi.com", "家庭服务平台"},
		{"HomeAdvisor", "https://www.homeadvisor.com", "家居服务"},
		{"Handy", "https://www.handy.com", "家庭清洁服务"},
		{"Care.com", "https://www.care.com", "家庭看护服务"},
		{"Rover", "https://www.rover.com", "宠物寄养服务"},
		{"Wag", "https://wagwalking.com", "遛狗服务"},
		{"ClassPass", "https://classpass.com", "健身课程平台"},
		{"Keep", "https://www.gotokeep.com", "运动健身平台"},
		{"MyFitnessPal", "https://www.myfitnesspal.com", "饮食健身追踪"},
		{"Headspace", "https://www.headspace.com", "冥想放松App"},
		{"Calm", "https://www.calm.com", "睡眠冥想应用"},
		{"小睡眠", "https://www.psy-1.com", "助眠白噪音"},
		{"Mint", "https://mint.intuit.com", "个人财务管理"},
		{"YNAB", "https://www.ynab.com", "预算管理工具"},
		{"随手记", "https://www.sui.com", "记账理财"},
		{"挖财", "https://www.wacai.com", "记账工具"},
		{"叮咚买菜", "https://www.100.me", "生鲜电商"},
		{"每日优鲜", "https://www.missfresh.cn", "生鲜配送"},
		{"盒马鲜生", "https://www.freshhema.com", "新零售超市"},
		{"朴朴超市", "https://www.pupu.com", "即时零售"},
		{"山姆会员店", "https://www.samsclub.cn", "会员制超市"},
		{"Costco", "https://www.costco.com", "会员制仓储"},
		{"Instacart", "https://www.instacart.com", "生鲜配送服务"},
		{"DoorDash", "https://www.doordash.com", "外卖配送"},
		{"Grubhub", "https://www.grubhub.com", "美国外卖"},
		{"UberEats", "https://www.ubereats.com", "Uber外卖"},
		{"Deliveroo", "https://deliveroo.com", "英国外卖"},
		{"Nextdoor", "https://nextdoor.com", "邻居社区平台"},
		{"小红书", "https://www.xiaohongshu.com", "生活方式社区"},
		{"什么值得买", "https://www.smzdm.com", "消费决策平台"},
		{"下厨房", "https://www.xiachufang.com", "美食菜谱社区"},
		{"豆果美食", "https://www.douguo.com", "菜谱分享平台"},
		{"AllRecipes", "https://www.allrecipes.com", "食谱分享社区"},
		{"Cookpad", "https://cookpad.com", "全球菜谱平台"},
		{"好大夫", "https://www.haodf.com", "在线问诊平台"},
		{"丁香医生", "https://dxy.com", "健康科普平台"},
		{"春雨医生", "https://www.chunyuyisheng.com", "在线健康咨询"},
		{"微医", "https://www.guahao.com", "挂号问诊平台"},
		{"平安好医生", "https://www.jk.cn", "在线医疗服务"},
		{"知乎", "https://www.zhihu.com", "知识问答社区"},
		{"豆瓣", "https://www.douban.com", "文化社区平台"},
		{"虎扑", "https://www.hupu.com", "体育社区"},
		{"Quora", "https://www.quora.com", "知识问答平台"},
		{"Reddit", "https://www.reddit.com", "社区讨论平台"},
		{"Pinterest", "https://www.pinterest.com", "图片灵感平台"},
		{"Meetup", "https://www.meetup.com", "兴趣活动平台"},
		{"Eventbrite", "https://www.eventbrite.com", "活动票务平台"},
		{"互动吧", "https://www.hdb.com", "活动发布报名"},
		{"活动行", "https://www.huodongxing.com", "活动管理平台"},
		{"百合网", "https://www.baihe.com", "婚恋交友"},
		{"世纪佳缘", "https://www.jiayuan.com", "婚恋平台"},
		{"探探", "https://tantanapp.com", "社交交友App"},
		{"Tinder", "https://tinder.com", "社交约会应用"},
	}
}

func readingEx() []S {
	return []S{
		{"微信读书", "https://weread.qq.com", "微信电子书"},
		{"起点中文网", "https://www.qidian.com", "网络文学平台"},
		{"纵横中文网", "https://www.zongheng.com", "网络小说平台"},
		{"晋江文学城", "https://www.jjwxc.net", "女性文学网站"},
		{"番茄小说", "https://www.fanqienovel.com", "免费小说平台"},
		{"书旗小说", "https://www.shuqi.com", "数字阅读平台"},
		{"QQ阅读", "https://book.qq.com", "QQ阅读平台"},
		{"掌阅", "https://www.zhangyue.com", "数字阅读品牌"},
		{"多看阅读", "https://www.duokan.com", "小米电子书"},
		{"网易蜗牛读书", "https://du.163.com", "精品阅读App"},
		{"当当阅读", "https://e.dangdang.com", "当当电子书"},
		{"京东读书", "https://e.jd.com", "京东电子书"},
		{"Kindle", "https://www.amazon.com/kindle", "亚马逊电子书"},
		{"Apple Books", "https://www.apple.com/apple-books", "苹果电子书"},
		{"Google Play Books", "https://play.google.com/books", "谷歌电子书"},
		{"Kobo", "https://www.kobo.com", "国际电子书"},
		{"Scribd", "https://www.scribd.com", "数字订阅图书馆"},
		{"Audible", "https://www.audible.com", "有声书平台"},
		{"喜马拉雅", "https://www.ximalaya.com", "有声内容平台"},
		{"懒人听书", "https://www.lrts.me", "有声书应用"},
		{"蜻蜓FM", "https://www.qingting.fm", "音频内容平台"},
		{"荔枝FM", "https://www.lizhi.fm", "声音互动平台"},
		{"得到", "https://www.dedao.cn", "知识付费平台"},
		{"樊登读书", "https://www.dushu.io", "书籍解读平台"},
		{"十点读书", "https://www.sdiread.com", "阅读成长平台"},
		{"Medium", "https://medium.com", "英文博客平台"},
		{"Substack", "https://substack.com", "通讯订阅平台"},
		{"Wattpad", "https://www.wattpad.com", "全球故事平台"},
		{"Royal Road", "https://www.royalroad.com", "网络小说平台"},
		{"Archive of Our Own", "https://archiveofourown.org", "同人小说平台"},
		{"Goodreads", "https://www.goodreads.com", "书评社区"},
		{"豆瓣读书", "https://book.douban.com", "书评推荐平台"},
		{"书单来了", "https://www.shudanlaile.com", "书单推荐"},
		{"BookBub", "https://www.bookbub.com", "电子书折扣"},
		{"LibraryThing", "https://www.librarything.com", "图书管理社区"},
		{"StoryGraph", "https://www.thestorygraph.com", "图书推荐工具"},
		{"Literal", "https://literal.club", "社交阅读平台"},
		{"Blinkist", "https://www.blinkist.com", "书籍摘要平台"},
		{"getAbstract", "https://www.getabstract.com", "商业书摘要"},
		{"Instaread", "https://instaread.co", "书籍速读"},
		{"Project Gutenberg", "https://www.gutenberg.org", "免费电子书"},
		{"Open Library", "https://openlibrary.org", "开放图书馆"},
		{"Librivox", "https://librivox.org", "免费有声书"},
		{"Standard Ebooks", "https://standardebooks.org", "精美免费电子书"},
		{"ManyBooks", "https://manybooks.net", "免费电子书库"},
		{"Z-Library", "https://z-lib.org", "电子书搜索引擎"},
		{"Library Genesis", "https://libgen.is", "学术书籍搜索"},
		{"Sci-Hub", "https://sci-hub.se", "学术论文获取"},
		{"Google Scholar", "https://scholar.google.com", "谷歌学术搜索"},
		{"百度学术", "https://xueshu.baidu.com", "百度学术搜索"},
		{"中国知网", "https://www.cnki.net", "学术文献数据库"},
		{"万方数据", "https://www.wanfangdata.com.cn", "学术信息平台"},
		{"维普期刊", "https://www.cqvip.com", "中文期刊数据库"},
		{"JSTOR", "https://www.jstor.org", "学术期刊数据库"},
		{"PubMed", "https://pubmed.ncbi.nlm.nih.gov", "生物医学文献"},
		{"arXiv", "https://arxiv.org", "预印本论文库"},
		{"ResearchGate", "https://www.researchgate.net", "学术社交网络"},
		{"Academia.edu", "https://www.academia.edu", "学术论文共享"},
		{"Semantic Scholar", "https://www.semanticscholar.org", "AI学术搜索"},
		{"Connected Papers", "https://www.connectedpapers.com", "论文关联图"},
		{"Zotero", "https://www.zotero.org", "文献管理工具"},
		{"Mendeley", "https://www.mendeley.com", "学术引用管理"},
		{"EndNote", "https://endnote.com", "文献引用软件"},
		{"Paperpile", "https://paperpile.com", "引用管理工具"},
		{"ReadCube Papers", "https://www.papersapp.com", "文献阅读管理"},
		{"Pocket", "https://getpocket.com", "稍后阅读工具"},
		{"Instapaper", "https://www.instapaper.com", "稍后阅读"},
		{"Readwise", "https://readwise.io", "阅读笔记同步"},
		{"Omnivore", "https://omnivore.app", "开源稍后阅读"},
		{"Raindrop.io", "https://raindrop.io", "书签管理器"},
		{"Hypothesis", "https://web.hypothes.is", "网页注释工具"},
		{"Polar", "https://getpolarized.io", "文档阅读管理"},
		{"calibre", "https://calibre-ebook.com", "电子书管理"},
		{"Sigil", "https://sigil-ebook.com", "EPUB编辑器"},
		{"FBReader", "https://fbreader.org", "电子书阅读器"},
		{"Sumatra PDF", "https://www.sumatrapdfreader.org", "轻量PDF阅读"},
		{"Foxit Reader", "https://www.foxitsoftware.com", "PDF阅读编辑"},
		{"Adobe Acrobat", "https://acrobat.adobe.com", "PDF专业工具"},
		{"MarginNote", "https://www.marginnote.com", "阅读笔记App"},
		{"Notion Web Clipper", "https://www.notion.so/web-clipper", "网页剪藏"},
		{"Evernote Web Clipper", "https://evernote.com/features/webclipper", "印象笔记剪藏"},
		{"RSS阅读器Feedly", "https://feedly.com", "RSS聚合阅读"},
		{"Inoreader", "https://www.inoreader.com", "RSS阅读器"},
		{"NewsBlur", "https://newsblur.com", "开源RSS阅读"},
		{"Miniflux", "https://miniflux.app", "极简RSS阅读"},
		{"FreshRSS", "https://freshrss.org", "自托管RSS"},
		{"Tiny Tiny RSS", "https://tt-rss.org", "开源RSS阅读"},
		{"NetNewsWire", "https://netnewswire.com", "macOS RSS阅读"},
		{"Reeder", "https://reederapp.com", "苹果RSS客户端"},
		{"少数派", "https://sspai.com", "数字生活指南"},
	}
}

func gamingEx() []S {
	return []S{
		{"Steam", "https://store.steampowered.com", "PC游戏平台"},
		{"Epic Games", "https://store.epicgames.com", "Epic游戏商店"},
		{"GOG", "https://www.gog.com", "DRM-free游戏"},
		{"Xbox Game Pass", "https://www.xbox.com/game-pass", "微软游戏订阅"},
		{"PlayStation Store", "https://store.playstation.com", "PS游戏商店"},
		{"Nintendo eShop", "https://www.nintendo.com/store", "任天堂商店"},
		{"Origin", "https://www.ea.com/ea-app", "EA游戏平台"},
		{"Ubisoft Connect", "https://ubisoftconnect.com", "育碧游戏平台"},
		{"Battle.net", "https://www.battle.net", "暴雪游戏平台"},
		{"Humble Store", "https://www.humblebundle.com/store", "慈善游戏商店"},
		{"Itch.io", "https://itch.io", "独立游戏平台"},
		{"Green Man Gaming", "https://www.greenmangaming.com", "游戏key商店"},
		{"Fanatical", "https://www.fanatical.com", "游戏折扣商店"},
		{"CDKeys", "https://www.cdkeys.com", "游戏密钥折扣"},
		{"WeGame", "https://www.wegame.com.cn", "腾讯游戏平台"},
		{"TapTap", "https://www.taptap.cn", "手游发现平台"},
		{"好游快爆", "https://www.3839.com", "手游资讯社区"},
		{"4399", "https://www.4399.com", "小游戏平台"},
		{"7723游戏", "https://www.7723.com", "手游下载"},
		{"九游", "https://www.9game.cn", "手游平台"},
		{"Twitch", "https://www.twitch.tv", "游戏直播平台"},
		{"YouTube Gaming", "https://www.youtube.com/gaming", "YouTube游戏"},
		{"斗鱼", "https://www.douyu.com", "游戏直播"},
		{"虎牙", "https://www.huya.com", "游戏直播平台"},
		{"哔哩哔哩游戏", "https://game.bilibili.com", "B站游戏"},
		{"IGN", "https://www.ign.com", "游戏评测媒体"},
		{"GameSpot", "https://www.gamespot.com", "游戏资讯评测"},
		{"Kotaku", "https://kotaku.com", "游戏文化媒体"},
		{"Polygon", "https://www.polygon.com", "游戏娱乐媒体"},
		{"PC Gamer", "https://www.pcgamer.com", "PC游戏杂志"},
		{"Rock Paper Shotgun", "https://www.rockpapershotgun.com", "PC游戏评论"},
		{"Eurogamer", "https://www.eurogamer.net", "欧洲游戏媒体"},
		{"Destructoid", "https://www.destructoid.com", "游戏评论社区"},
		{"3DM游戏网", "https://www.3dmgame.com", "游戏资讯论坛"},
		{"游侠网", "https://www.ali213.net", "游戏攻略补丁"},
		{"游民星空", "https://www.gamersky.com", "游戏资讯平台"},
		{"NGA玩家社区", "https://bbs.nga.cn", "游戏玩家论坛"},
		{"A9VG", "https://www.a9vg.com", "电玩资讯"},
		{"VGTime", "https://www.vgtime.com", "游戏时光"},
		{"UCG", "https://www.ucg.cn", "游戏媒体"},
		{"触乐", "https://www.chuapp.com", "手游评测媒体"},
		{"篝火营地", "https://gouhuo.qq.com", "游戏社区平台"},
		{"奶牛关", "https://cowlevel.net", "游戏同好社区"},
		{"Metacritic", "https://www.metacritic.com", "游戏评分聚合"},
		{"OpenCritic", "https://opencritic.com", "游戏评分汇总"},
		{"HowLongToBeat", "https://howlongtobeat.com", "游戏时长查询"},
		{"IsThereAnyDeal", "https://isthereanydeal.com", "游戏价格比较"},
		{"SteamDB", "https://steamdb.info", "Steam数据库"},
		{"Steam Charts", "https://steamcharts.com", "Steam在线统计"},
		{"ProtonDB", "https://www.protondb.com", "Linux游戏兼容"},
		{"PCGamingWiki", "https://www.pcgamingwiki.com", "PC游戏百科"},
		{"StrategyWiki", "https://strategywiki.org", "游戏攻略百科"},
		{"GameFAQs", "https://gamefaqs.gamespot.com", "游戏攻略数据库"},
		{"IGN Wiki", "https://www.ign.com/wikis", "IGN游戏百科"},
		{"Fandom", "https://www.fandom.com", "粉丝百科平台"},
		{"Speedrun.com", "https://www.speedrun.com", "速通记录平台"},
		{"RetroAchievements", "https://retroachievements.org", "复古游戏成就"},
		{"Emulation Wiki", "https://emulation.gametechwiki.com", "模拟器百科"},
		{"r/gaming", "https://www.reddit.com/r/gaming", "Reddit游戏板块"},
		{"r/Games", "https://www.reddit.com/r/Games", "Reddit游戏讨论"},
		{"ResetEra", "https://www.resetera.com", "游戏社区论坛"},
		{"NeoGAF", "https://www.neogaf.com", "游戏讨论论坛"},
		{"Discord", "https://discord.com", "游戏社交平台"},
		{"TeamSpeak", "https://www.teamspeak.com", "游戏语音通讯"},
		{"Overwolf", "https://www.overwolf.com", "游戏内叠加层"},
		{"CurseForge", "https://www.curseforge.com", "游戏Mod平台"},
		{"Nexus Mods", "https://www.nexusmods.com", "PC游戏Mod社区"},
		{"ModDB", "https://www.moddb.com", "游戏Mod数据库"},
		{"Steam Workshop", "https://steamcommunity.com/workshop", "Steam创意工坊"},
		{"IGDB", "https://www.igdb.com", "游戏数据库"},
		{"MobyGames", "https://www.mobygames.com", "游戏资料库"},
		{"VGChartz", "https://www.vgchartz.com", "游戏销量统计"},
		{"Newzoo", "https://newzoo.com", "游戏市场分析"},
		{"Sensor Tower", "https://sensortower.com", "移动应用分析"},
		{"AppAnnie", "https://www.data.ai", "应用数据分析"},
		{"游戏陀螺", "https://www.youxituoluo.com", "游戏产业媒体"},
		{"GameLook", "https://www.gamelook.com.cn", "游戏产业资讯"},
		{"手游那点事", "https://www.nadianshi.com", "手游行业分析"},
		{"游戏工委", "https://www.cgigc.com.cn", "游戏出版管理"},
		{"游戏新知", "https://www.youxixinzhi.com", "游戏行业洞察"},
		{"游戏价值论", "https://www.gamezlun.com", "游戏行业观察"},
		{"游戏大观", "https://www.gamedaguan.com", "游戏行业媒体"},
		{"Game Awards", "https://thegameawards.com", "游戏年度颁奖"},
		{"BAFTA Games", "https://www.bafta.org/games", "英国游戏奖"},
		{"Golden Joystick", "https://www.gamesradar.com/goldenjoystick", "金摇杆奖"},
		{"D.I.C.E. Awards", "https://www.interactive.org/awards", "DICE游戏奖"},
		{"GamesRadar+", "https://www.gamesradar.com", "游戏评测资讯"},
		{"Push Square", "https://www.pushsquare.com", "PS游戏资讯"},
		{"Nintendo Life", "https://www.nintendolife.com", "任天堂资讯"},
		{"Pure Xbox", "https://www.purexbox.com", "Xbox游戏资讯"},
		{"Touch Arcade", "https://toucharcade.com", "手游评测"},
		{"Pocket Gamer", "https://www.pocketgamer.com", "手游资讯"},
	}
}
