package main

// Boost2: Additional sites for more categories to reach 10,000+ total.

func newsBoost() []S {
	return []S{
		{"The Guardian", "https://www.theguardian.com", "英国卫报"},
		{"The Washington Post", "https://www.washingtonpost.com", "华盛顿邮报"},
		{"The New York Times", "https://www.nytimes.com", "纽约时报"},
		{"Wall Street Journal", "https://www.wsj.com", "华尔街日报"},
		{"Financial Times", "https://www.ft.com", "金融时报"},
		{"The Economist", "https://www.economist.com", "经济学人"},
		{"Al Jazeera", "https://www.aljazeera.com", "半岛电视台"},
		{"Deutsche Welle", "https://www.dw.com", "德国之声"},
		{"France 24", "https://www.france24.com", "法国24小时"},
		{"NHK World", "https://www3.nhk.or.jp/nhkworld", "日本NHK"},
		{"The Independent", "https://www.independent.co.uk", "英国独立报"},
		{"The Telegraph", "https://www.telegraph.co.uk", "英国电讯报"},
		{"USA Today", "https://www.usatoday.com", "今日美国"},
		{"Los Angeles Times", "https://www.latimes.com", "洛杉矶时报"},
		{"Chicago Tribune", "https://www.chicagotribune.com", "芝加哥论坛报"},
		{"Time", "https://time.com", "时代杂志"},
		{"Newsweek", "https://www.newsweek.com", "新闻周刊"},
		{"Foreign Affairs", "https://www.foreignaffairs.com", "外交事务杂志"},
		{"The Atlantic", "https://www.theatlantic.com", "大西洋月刊"},
		{"Politico", "https://www.politico.com", "政治资讯"},
		{"Axios", "https://www.axios.com", "简明新闻"},
		{"The Verge", "https://www.theverge.com", "科技新闻"},
		{"Wired", "https://www.wired.com", "连线杂志"},
		{"Ars Technica", "https://arstechnica.com", "科技深度报道"},
		{"环球时报英文", "https://www.globaltimes.cn", "环球时报英文版"},
		{"中国日报", "https://www.chinadaily.com.cn", "中国日报"},
		{"参考消息", "https://www.cankaoxiaoxi.com", "参考消息"},
		{"观察者网", "https://www.guancha.cn", "观察者网"},
		{"澎湃新闻", "https://www.thepaper.cn", "澎湃新闻"},
		{"界面新闻", "https://www.jiemian.com", "界面新闻"},
	}
}

func developerBoost() []S {
	return []S{
		{"Codecademy", "https://www.codecademy.com", "编程学习平台"},
		{"freeCodeCamp", "https://www.freecodecamp.org", "免费编程学习"},
		{"LeetCode", "https://leetcode.com", "算法刷题平台"},
		{"HackerRank", "https://www.hackerrank.com", "编程挑战平台"},
		{"Codewars", "https://www.codewars.com", "代码挑战"},
		{"Exercism", "https://exercism.org", "编程练习平台"},
		{"TopCoder", "https://www.topcoder.com", "编程竞赛平台"},
		{"Codeforces", "https://codeforces.com", "算法竞赛"},
		{"AtCoder", "https://atcoder.jp", "日本编程竞赛"},
		{"CodeChef", "https://www.codechef.com", "印度编程竞赛"},
		{"Project Euler", "https://projecteuler.net", "数学编程挑战"},
		{"Advent of Code", "https://adventofcode.com", "圣诞编程挑战"},
		{"Rosetta Code", "https://rosettacode.org", "多语言代码示例"},
		{"GeeksforGeeks", "https://www.geeksforgeeks.org", "编程知识平台"},
		{"Programiz", "https://www.programiz.com", "编程教程"},
		{"W3Schools", "https://www.w3schools.com", "Web技术教程"},
		{"MDN", "https://developer.mozilla.org", "Mozilla开发者"},
		{"Can I Use", "https://caniuse.com", "浏览器兼容查询"},
		{"DevDocs", "https://devdocs.io", "API文档聚合"},
		{"Cheatography", "https://cheatography.com", "速查表集合"},
		{"Roadmap.sh", "https://roadmap.sh", "开发者路线图"},
		{"The Odin Project", "https://www.theodinproject.com", "全栈学习路径"},
		{"Full Stack Open", "https://fullstackopen.com", "全栈公开课"},
		{"CS50", "https://cs50.harvard.edu", "哈佛CS入门课"},
		{"MIT OpenCourseWare", "https://ocw.mit.edu", "MIT公开课"},
		{"Coursera", "https://www.coursera.org", "大学在线课程"},
		{"Udemy", "https://www.udemy.com", "技术课程平台"},
		{"Pluralsight", "https://www.pluralsight.com", "技术培训平台"},
		{"Egghead.io", "https://egghead.io", "前端视频教程"},
		{"Frontend Masters", "https://frontendmasters.com", "前端高级课程"},
	}
}

func toolsBoost() []S {
	return []S{
		{"1Password", "https://1password.com", "密码管理器"},
		{"Bitwarden", "https://bitwarden.com", "开源密码管理"},
		{"LastPass", "https://www.lastpass.com", "密码管理工具"},
		{"Dashlane", "https://www.dashlane.com", "密码安全管理"},
		{"Alfred", "https://www.alfredapp.com", "Mac效率神器"},
		{"Raycast", "https://www.raycast.com", "Mac启动器"},
		{"Wox", "https://github.com/Wox-launcher/Wox", "Windows启动器"},
		{"PowerToys", "https://github.com/microsoft/PowerToys", "Windows实用工具"},
		{"Espanso", "https://espanso.org", "文本扩展工具"},
		{"TextExpander", "https://textexpander.com", "文字快捷输入"},
		{"Bartender", "https://www.macbartender.com", "Mac菜单栏管理"},
		{"Rectangle", "https://rectangleapp.com", "Mac窗口管理"},
		{"Magnet", "https://magnet.crowdcafe.com", "Mac窗口管理"},
		{"Divvy", "https://mizage.com/divvy", "窗口布局工具"},
		{"Karabiner", "https://karabiner-elements.pqrs.org", "Mac键盘自定义"},
		{"AutoHotKey", "https://www.autohotkey.com", "Windows自动化"},
		{"BetterTouchTool", "https://folivora.ai", "Mac触控增强"},
		{"Hazel", "https://www.noodlesoft.com", "Mac文件自动化"},
		{"CleanMyMac", "https://macpaw.com/cleanmymac", "Mac清理工具"},
		{"CCleaner", "https://www.ccleaner.com", "系统清理工具"},
		{"Homebrew", "https://brew.sh", "Mac包管理器"},
		{"Chocolatey", "https://chocolatey.org", "Windows包管理"},
		{"WinGet", "https://learn.microsoft.com/windows/package-manager", "Windows包管理"},
		{"Scoop", "https://scoop.sh", "Windows包管理"},
		{"AppCleaner", "https://freemacsoft.net/appcleaner", "Mac卸载工具"},
		{"The Unarchiver", "https://theunarchiver.com", "Mac解压工具"},
		{"7-Zip", "https://www.7-zip.org", "免费压缩工具"},
		{"PeaZip", "https://peazip.github.io", "开源压缩工具"},
		{"Everything", "https://www.voidtools.com", "Windows快速搜索"},
		{"Listary", "https://www.listary.com", "文件搜索工具"},
	}
}

func designBoost() []S {
	return []S{
		{"Figma Community", "https://www.figma.com/community", "Figma资源社区"},
		{"UI8", "https://ui8.net", "UI设计资源"},
		{"Envato Elements", "https://elements.envato.com", "设计素材订阅"},
		{"Pexels", "https://www.pexels.com", "免费图片素材"},
		{"Pixabay", "https://pixabay.com", "免费图片视频"},
		{"Undraw", "https://undraw.co", "开源SVG插画"},
		{"Drawkit", "https://drawkit.io", "手绘SVG插画"},
		{"Storyset", "https://storyset.com", "免费动画插画"},
		{"LottieFiles", "https://lottiefiles.com", "动画设计平台"},
		{"Rive", "https://rive.app", "交互动画工具"},
		{"FontAwesome", "https://fontawesome.com", "图标字体库"},
		{"Heroicons", "https://heroicons.com", "Tailwind图标"},
		{"Phosphor Icons", "https://phosphoricons.com", "灵活图标库"},
		{"Lucide", "https://lucide.dev", "开源图标集"},
		{"Tabler Icons", "https://tabler-icons.io", "免费SVG图标"},
		{"Iconify", "https://iconify.design", "统一图标框架"},
		{"Google Fonts", "https://fonts.google.com", "谷歌字体库"},
		{"Adobe Fonts", "https://fonts.adobe.com", "Adobe字体服务"},
		{"Font Squirrel", "https://www.fontsquirrel.com", "免费商用字体"},
		{"DaFont", "https://www.dafont.com", "免费字体下载"},
		{"Fontjoy", "https://fontjoy.com", "字体搭配生成"},
		{"Typewolf", "https://www.typewolf.com", "字体灵感推荐"},
		{"Coolors", "https://coolors.co", "配色方案生成"},
		{"Color Hunt", "https://colorhunt.co", "配色方案灵感"},
		{"Adobe Color", "https://color.adobe.com", "Adobe配色工具"},
		{"Paletton", "https://paletton.com", "在线配色工具"},
		{"Happy Hues", "https://www.happyhues.co", "配色灵感"},
		{"Realtime Colors", "https://www.realtimecolors.com", "实时配色预览"},
		{"Muzli", "https://muz.li", "设计灵感插件"},
		{"Mobbin", "https://mobbin.com", "移动UI设计参考"},
	}
}

func videoBoost() []S {
	return []S{
		{"Vimeo", "https://vimeo.com", "专业视频平台"},
		{"Dailymotion", "https://www.dailymotion.com", "法国视频网站"},
		{"PeerTube", "https://joinpeertube.org", "去中心化视频"},
		{"Odysee", "https://odysee.com", "区块链视频平台"},
		{"Rumble", "https://rumble.com", "视频分享平台"},
		{"BitChute", "https://www.bitchute.com", "自由视频平台"},
		{"Internet Archive Video", "https://archive.org/details/movies", "互联网档案视频"},
		{"Nebula", "https://nebula.tv", "创作者视频平台"},
		{"Curiosity Stream", "https://curiositystream.com", "纪录片平台"},
		{"MasterClass", "https://www.masterclass.com", "大师在线课程"},
		{"Skillshare", "https://www.skillshare.com", "创意视频课程"},
		{"Coursera Video", "https://www.coursera.org", "大学视频课程"},
		{"edX", "https://www.edx.org", "大学在线视频"},
		{"Khan Academy", "https://www.khanacademy.org", "免费教育视频"},
		{"TED", "https://www.ted.com", "TED演讲"},
		{"Patreon", "https://www.patreon.com", "创作者赞助视频"},
		{"YouTube Music", "https://music.youtube.com", "YouTube音乐"},
		{"Crunchyroll", "https://www.crunchyroll.com", "日本动漫平台"},
		{"Funimation", "https://www.funimation.com", "动漫流媒体"},
		{"VRV", "https://vrv.co", "动漫流媒体聚合"},
		{"Pluto TV", "https://pluto.tv", "免费电视流媒体"},
		{"Tubi", "https://tubitv.com", "免费电影电视"},
		{"Plex", "https://www.plex.tv", "媒体服务器"},
		{"Jellyfin", "https://jellyfin.org", "开源媒体服务器"},
		{"Emby", "https://emby.media", "媒体服务器"},
		{"Kodi", "https://kodi.tv", "开源媒体中心"},
		{"VLC", "https://www.videolan.org/vlc", "开源播放器"},
		{"mpv", "https://mpv.io", "极简视频播放器"},
		{"IINA", "https://iina.io", "Mac视频播放器"},
		{"PotPlayer", "https://potplayer.daum.net", "强大视频播放器"},
	}
}

func aiBoost() []S {
	return []S{
		{"DeepSeek", "https://www.deepseek.com", "深度求索AI"},
		{"Kimi", "https://kimi.moonshot.cn", "月之暗面AI助手"},
		{"通义千问", "https://tongyi.aliyun.com", "阿里AI助手"},
		{"文心一言", "https://yiyan.baidu.com", "百度AI助手"},
		{"讯飞星火", "https://xinghuo.xfyun.cn", "科大讯飞AI"},
		{"豆包", "https://www.doubao.com", "字节跳动AI"},
		{"智谱清言", "https://chatglm.cn", "智谱AI助手"},
		{"天工AI", "https://www.tiangong.cn", "昆仑万维AI"},
		{"Minimax", "https://www.minimaxi.com", "MiniMax AI"},
		{"零一万物", "https://www.01.ai", "李开复AI公司"},
		{"Sora", "https://openai.com/sora", "OpenAI视频生成"},
		{"Runway", "https://runwayml.com", "AI视频编辑"},
		{"Pika", "https://pika.art", "AI视频生成"},
		{"Luma AI", "https://lumalabs.ai", "AI 3D视频"},
		{"ElevenLabs", "https://elevenlabs.io", "AI语音克隆"},
		{"Synthesia", "https://www.synthesia.io", "AI数字人视频"},
		{"HeyGen", "https://www.heygen.com", "AI视频生成"},
		{"D-ID", "https://www.d-id.com", "AI数字人"},
		{"Suno", "https://suno.com", "AI音乐创作"},
		{"Udio", "https://www.udio.com", "AI音乐生成"},
		{"NotebookLM", "https://notebooklm.google.com", "Google AI笔记"},
		{"Gamma", "https://gamma.app", "AI演示文稿"},
		{"Beautiful.ai", "https://www.beautiful.ai", "AI PPT设计"},
		{"Tome", "https://tome.app", "AI叙事工具"},
		{"Jasper", "https://www.jasper.ai", "AI营销文案"},
		{"Copy.ai", "https://www.copy.ai", "AI文案生成"},
		{"Writesonic", "https://writesonic.com", "AI写作助手"},
		{"Grammarly", "https://www.grammarly.com", "AI写作优化"},
		{"Otter.ai", "https://otter.ai", "AI会议记录"},
		{"Fireflies.ai", "https://fireflies.ai", "AI会议助手"},
	}
}
