package main

func wiki() []S {
	return []S{
		{"Wikipedia", "https://www.wikipedia.org", "维基百科"},
		{"Wikimedia Commons", "https://commons.wikimedia.org", "维基媒体共享"},
		{"Wiktionary", "https://www.wiktionary.org", "维基词典"},
		{"Wikibooks", "https://www.wikibooks.org", "维基教科书"},
		{"Wikiquote", "https://www.wikiquote.org", "维基语录"},
		{"Wikisource", "https://www.wikisource.org", "维基文库"},
		{"Wikidata", "https://www.wikidata.org", "维基数据"},
		{"Wikinews", "https://www.wikinews.org", "维基新闻"},
		{"Wikiversity", "https://www.wikiversity.org", "维基学院"},
		{"百度百科", "https://baike.baidu.com", "百度百科"},
		{"搜狗百科", "https://baike.sogou.com", "搜狗百科"},
		{"互动百科", "https://www.baike.com", "互动百科"},
		{"头条百科", "https://www.baike.com", "今日头条百科"},
		{"MBA智库百科", "https://wiki.mbalib.com", "经管百科"},
		{"医学百科", "https://www.yixue.com", "医学知识百科"},
		{"Britannica", "https://www.britannica.com", "大英百科全书"},
		{"Encyclopedia.com", "https://www.encyclopedia.com", "在线百科全书"},
		{"Scholarpedia", "https://www.scholarpedia.org", "学术百科"},
		{"Stanford Encyclopedia", "https://plato.stanford.edu", "斯坦福哲学百科"},
		{"Citizendium", "https://en.citizendium.org", "公民百科"},
		{"Fandom", "https://www.fandom.com", "粉丝维基社区"},
		{"Wikia", "https://www.fandom.com", "娱乐维基"},
		{"Bulbapedia", "https://bulbapedia.bulbagarden.net", "宝可梦百科"},
		{"Minecraft Wiki", "https://minecraft.wiki", "我的世界百科"},
		{"ArchWiki", "https://wiki.archlinux.org", "Arch Linux百科"},
		{"Gentoo Wiki", "https://wiki.gentoo.org", "Gentoo百科"},
		{"FreeBSD Wiki", "https://wiki.freebsd.org", "FreeBSD百科"},
		{"MDN Web Docs", "https://developer.mozilla.org", "Web开发文档"},
		{"DevDocs", "https://devdocs.io", "API文档聚合"},
		{"W3Schools", "https://www.w3schools.com", "Web教程"},
		{"GeeksforGeeks", "https://www.geeksforgeeks.org", "编程学习百科"},
		{"TutorialsPoint", "https://www.tutorialspoint.com", "编程教程"},
		{"Javatpoint", "https://www.javatpoint.com", "Java编程教程"},
		{"Programiz", "https://www.programiz.com", "编程入门"},
		{"WikiHow", "https://www.wikihow.com", "生活百科指南"},
		{"HowStuffWorks", "https://www.howstuffworks.com", "万物运作原理"},
		{"Investopedia", "https://www.investopedia.com", "投资百科"},
		{"Healthline", "https://www.healthline.com", "健康百科"},
		{"Mayo Clinic", "https://www.mayoclinic.org", "医学百科"},
		{"Internet Archive", "https://archive.org", "互联网档案馆"},
		{"Wayback Machine", "https://web.archive.org", "网页历史快照"},
		{"Project Gutenberg", "https://www.gutenberg.org", "古腾堡免费电子书"},
		{"LibriVox", "https://librivox.org", "免费公共有声书"},
		{"Open Library", "https://openlibrary.org", "开放图书馆"},
		{"Snopes", "https://www.snopes.com", "事实核查网站"},
		{"FactCheck.org", "https://www.factcheck.org", "事实核查"},
		{"PolitiFact", "https://www.politifact.com", "新闻事实核查"},
		{"Full Fact", "https://fullfact.org", "英国事实核查"},
		{"Dictionary.com", "https://www.dictionary.com", "在线英文词典"},
		{"Merriam-Webster", "https://www.merriam-webster.com", "韦氏词典"},
		{"Oxford Dictionaries", "https://www.oxfordlearnersdictionaries.com", "牛津词典"},
		{"Cambridge Dictionary", "https://dictionary.cambridge.org", "剑桥词典"},
	}
}

func cloudService() []S {
	return []S{
		{"AWS", "https://aws.amazon.com", "亚马逊云服务"},
		{"Microsoft Azure", "https://azure.microsoft.com", "微软云平台"},
		{"Google Cloud", "https://cloud.google.com", "Google云平台"},
		{"阿里云", "https://www.aliyun.com", "阿里巴巴云计算"},
		{"腾讯云", "https://cloud.tencent.com", "腾讯云服务"},
		{"华为云", "https://www.huaweicloud.com", "华为云平台"},
		{"百度智能云", "https://cloud.baidu.com", "百度云服务"},
		{"京东云", "https://www.jdcloud.com", "京东云平台"},
		{"字节火山引擎", "https://www.volcengine.com", "字节跳动云"},
		{"金山云", "https://www.ksyun.com", "金山云服务"},
		{"UCloud", "https://www.ucloud.cn", "优刻得云"},
		{"七牛云", "https://www.qiniu.com", "云存储CDN"},
		{"又拍云", "https://www.upyun.com", "CDN云存储"},
		{"青云", "https://www.qingcloud.com", "企业级云平台"},
		{"IBM Cloud", "https://www.ibm.com/cloud", "IBM云服务"},
		{"Oracle Cloud", "https://www.oracle.com/cloud", "Oracle云平台"},
		{"DigitalOcean", "https://www.digitalocean.com", "开发者云平台"},
		{"Linode", "https://www.linode.com", "Akamai云计算"},
		{"Vultr", "https://www.vultr.com", "云服务器"},
		{"Hetzner", "https://www.hetzner.com", "德国云服务商"},
		{"OVHcloud", "https://www.ovhcloud.com", "欧洲云服务"},
		{"Scaleway", "https://www.scaleway.com", "欧洲云平台"},
		{"UpCloud", "https://upcloud.com", "高性能云服务"},
		{"Kamatera", "https://www.kamatera.com", "全球云服务器"},
		{"Vercel", "https://vercel.com", "前端部署平台"},
		{"Netlify", "https://www.netlify.com", "JAMstack部署"},
		{"Railway", "https://railway.app", "应用部署平台"},
		{"Render", "https://render.com", "云应用托管"},
		{"Fly.io", "https://fly.io", "边缘应用平台"},
		{"Heroku", "https://www.heroku.com", "PaaS平台"},
		{"Platform.sh", "https://platform.sh", "PaaS部署"},
		{"Deta", "https://deta.space", "个人云平台"},
		{"Supabase", "https://supabase.com", "开源Firebase替代"},
		{"Firebase", "https://firebase.google.com", "Google后端服务"},
		{"Appwrite", "https://appwrite.io", "开源后端服务"},
		{"PocketBase", "https://pocketbase.io", "轻量后端"},
		{"Nhost", "https://nhost.io", "GraphQL后端"},
		{"Convex", "https://www.convex.dev", "反应式后端"},
		{"PlanetScale", "https://planetscale.com", "无服务器MySQL"},
		{"Neon", "https://neon.tech", "无服务器Postgres"},
		{"Upstash", "https://upstash.com", "无服务器Redis"},
		{"Cloudflare Workers", "https://workers.cloudflare.com", "边缘计算"},
		{"AWS Lambda", "https://aws.amazon.com/lambda", "无服务器计算"},
		{"Azure Functions", "https://azure.microsoft.com/en-us/products/functions", "无服务器函数"},
		{"Google Cloud Functions", "https://cloud.google.com/functions", "Google无服务器"},
		{"Terraform Cloud", "https://app.terraform.io", "基础设施即代码"},
		{"Pulumi", "https://www.pulumi.com", "云基础设施管理"},
		{"MinIO", "https://min.io", "对象存储"},
		{"Backblaze B2", "https://www.backblaze.com/b2", "低价云存储"},
		{"Wasabi", "https://wasabi.com", "热云存储"},
		{"Snowflake", "https://www.snowflake.com", "云数据仓库"},
		{"Databricks", "https://www.databricks.com", "统一数据分析"},
	}
}

func hosting() []S {
	return []S{
		{"GoDaddy", "https://www.godaddy.com", "域名注册与托管"},
		{"Namecheap", "https://www.namecheap.com", "域名注册"},
		{"Cloudflare Registrar", "https://www.cloudflare.com/products/registrar", "域名注册"},
		{"Google Domains", "https://domains.google", "Google域名"},
		{"Name.com", "https://www.name.com", "域名注册"},
		{"Dynadot", "https://www.dynadot.com", "域名注册商"},
		{"Porkbun", "https://porkbun.com", "便宜域名注册"},
		{"Gandi", "https://www.gandi.net", "域名与托管"},
		{"Hover", "https://www.hover.com", "域名注册"},
		{"万网", "https://wanwang.aliyun.com", "阿里云域名"},
		{"DNSPod", "https://www.dnspod.cn", "腾讯域名DNS"},
		{"新网", "https://www.xinnet.com", "域名与云服务"},
		{"西部数码", "https://www.west.cn", "域名与主机"},
		{"易名", "https://www.ename.net", "域名交易"},
		{"爱名网", "https://www.22.cn", "域名服务"},
		{"Bluehost", "https://www.bluehost.com", "WordPress托管"},
		{"SiteGround", "https://www.siteground.com", "Web托管"},
		{"HostGator", "https://www.hostgator.com", "虚拟主机"},
		{"DreamHost", "https://www.dreamhost.com", "Web托管"},
		{"A2 Hosting", "https://www.a2hosting.com", "高速托管"},
		{"InMotion Hosting", "https://www.inmotionhosting.com", "Web托管"},
		{"Hostinger", "https://www.hostinger.com", "便宜主机"},
		{"FastComet", "https://www.fastcomet.com", "SSD云托管"},
		{"Kinsta", "https://kinsta.com", "高端WordPress托管"},
		{"WP Engine", "https://wpengine.com", "WordPress专属托管"},
		{"Flywheel", "https://getflywheel.com", "WordPress托管"},
		{"Pagely", "https://pagely.com", "企业WordPress"},
		{"Cloudways", "https://www.cloudways.com", "云主机托管"},
		{"Nexcess", "https://www.nexcess.net", "电商托管"},
		{"Liquid Web", "https://www.liquidweb.com", "专用服务器"},
		{"Kamatera", "https://www.kamatera.com", "云服务器"},
		{"Contabo", "https://contabo.com", "VPS主机"},
		{"BuyVM", "https://buyvm.net", "便宜VPS"},
		{"RackNerd", "https://www.racknerd.com", "VPS服务"},
		{"搬瓦工", "https://bandwagonhost.com", "VPS服务商"},
		{"Squarespace", "https://www.squarespace.com", "网站建站"},
		{"Wix", "https://www.wix.com", "可视化建站"},
		{"Weebly", "https://www.weebly.com", "简单建站"},
		{"WordPress.com", "https://wordpress.com", "WordPress托管建站"},
		{"Ghost Pro", "https://ghost.org/pricing", "Ghost博客托管"},
		{"Webflow", "https://webflow.com", "可视化Web设计"},
		{"Carrd", "https://carrd.co", "简洁落地页"},
		{"Strikingly", "https://www.strikingly.com", "快速建站"},
		{"Notion.site", "https://www.notion.so/product/sites", "Notion建站"},
		{"Framer", "https://www.framer.com", "设计驱动建站"},
		{"Typedream", "https://typedream.com", "无代码网站"},
		{"Super.so", "https://super.so", "Notion转网站"},
		{"Potion.so", "https://www.potion.so", "Notion建站"},
		{"Softr", "https://www.softr.io", "无代码Web应用"},
		{"Dorik", "https://dorik.com", "网站建造器"},
		{"Hostwinds", "https://www.hostwinds.com", "云主机服务"},
		{"InterServer", "https://www.interserver.net", "Web托管"},
	}
}

func database() []S {
	return []S{
		{"PostgreSQL", "https://www.postgresql.org", "PostgreSQL数据库"},
		{"MySQL", "https://www.mysql.com", "MySQL数据库"},
		{"MariaDB", "https://mariadb.org", "MariaDB数据库"},
		{"SQLite", "https://www.sqlite.org", "嵌入式数据库"},
		{"SQL Server", "https://www.microsoft.com/sql-server", "微软SQL Server"},
		{"Oracle Database", "https://www.oracle.com/database", "Oracle数据库"},
		{"MongoDB", "https://www.mongodb.com", "文档数据库"},
		{"Redis", "https://redis.io", "内存数据库"},
		{"Cassandra", "https://cassandra.apache.org", "分布式数据库"},
		{"CockroachDB", "https://www.cockroachlabs.com", "分布式SQL"},
		{"TiDB", "https://www.pingcap.com", "分布式NewSQL"},
		{"YugabyteDB", "https://www.yugabyte.com", "分布式SQL"},
		{"Couchbase", "https://www.couchbase.com", "NoSQL数据库"},
		{"CouchDB", "https://couchdb.apache.org", "文档数据库"},
		{"Neo4j", "https://neo4j.com", "图数据库"},
		{"ArangoDB", "https://www.arangodb.com", "多模型数据库"},
		{"DynamoDB", "https://aws.amazon.com/dynamodb", "AWS无服务器DB"},
		{"Firestore", "https://firebase.google.com/products/firestore", "Google文档DB"},
		{"InfluxDB", "https://www.influxdata.com", "时序数据库"},
		{"TimescaleDB", "https://www.timescale.com", "时序扩展"},
		{"ClickHouse", "https://clickhouse.com", "列式分析数据库"},
		{"Apache Druid", "https://druid.apache.org", "实时分析数据库"},
		{"Elasticsearch", "https://www.elastic.co", "搜索引擎数据库"},
		{"OpenSearch", "https://opensearch.org", "开源搜索引擎"},
		{"Meilisearch", "https://www.meilisearch.com", "闪电搜索引擎"},
		{"Typesense", "https://typesense.org", "搜索即服务"},
		{"Algolia", "https://www.algolia.com", "搜索即服务API"},
		{"Pinecone", "https://www.pinecone.io", "向量数据库"},
		{"Weaviate", "https://weaviate.io", "AI向量数据库"},
		{"Milvus", "https://milvus.io", "向量相似搜索"},
		{"Qdrant", "https://qdrant.tech", "向量搜索引擎"},
		{"ChromaDB", "https://www.trychroma.com", "AI嵌入数据库"},
		{"PlanetScale", "https://planetscale.com", "无服务器MySQL"},
		{"Neon", "https://neon.tech", "无服务器Postgres"},
		{"Supabase", "https://supabase.com", "Postgres即服务"},
		{"Turso", "https://turso.tech", "边缘SQLite"},
		{"Fauna", "https://fauna.com", "文档关系数据库"},
		{"SurrealDB", "https://surrealdb.com", "多模型数据库"},
		{"Upstash", "https://upstash.com", "无服务器Redis/Kafka"},
		{"Dolt", "https://www.dolthub.com", "Git版本控制数据库"},
		{"RethinkDB", "https://rethinkdb.com", "实时推送数据库"},
		{"ScyllaDB", "https://www.scylladb.com", "高性能NoSQL"},
		{"Apache HBase", "https://hbase.apache.org", "Hadoop数据库"},
		{"Vitess", "https://vitess.io", "MySQL分片中间件"},
		{"etcd", "https://etcd.io", "分布式KV存储"},
		{"FoundationDB", "https://www.foundationdb.org", "Apple分布式DB"},
		{"RocksDB", "https://rocksdb.org", "嵌入式KV存储"},
		{"LevelDB", "https://github.com/google/leveldb", "Google KV存储"},
		{"BadgerDB", "https://dgraph.io/badger", "Go嵌入式KV"},
		{"Dgraph", "https://dgraph.io", "分布式图数据库"},
		{"DB-Engines", "https://db-engines.com", "数据库排名"},
		{"DBeaver", "https://dbeaver.io", "通用数据库工具"},
	}
}

func devops() []S {
	return []S{
		{"Docker", "https://www.docker.com", "容器化平台"},
		{"Docker Hub", "https://hub.docker.com", "容器镜像仓库"},
		{"Kubernetes", "https://kubernetes.io", "容器编排平台"},
		{"Helm", "https://helm.sh", "Kubernetes包管理"},
		{"Rancher", "https://www.rancher.com", "K8s管理平台"},
		{"OpenShift", "https://www.redhat.com/en/technologies/cloud-computing/openshift", "Red Hat容器平台"},
		{"Portainer", "https://www.portainer.io", "容器管理UI"},
		{"Podman", "https://podman.io", "无守护进程容器"},
		{"Containerd", "https://containerd.io", "容器运行时"},
		{"Terraform", "https://www.terraform.io", "基础设施即代码"},
		{"Ansible", "https://www.ansible.com", "自动化运维"},
		{"Puppet", "https://www.puppet.com", "配置管理"},
		{"Chef", "https://www.chef.io", "自动化配置"},
		{"SaltStack", "https://saltproject.io", "自动化管理"},
		{"Pulumi", "https://www.pulumi.com", "现代IaC"},
		{"Jenkins", "https://www.jenkins.io", "CI/CD服务器"},
		{"GitHub Actions", "https://github.com/features/actions", "GitHub CI/CD"},
		{"GitLab CI", "https://docs.gitlab.com/ee/ci", "GitLab持续集成"},
		{"CircleCI", "https://circleci.com", "CI/CD平台"},
		{"Travis CI", "https://www.travis-ci.com", "持续集成"},
		{"Drone", "https://www.drone.io", "容器化CI/CD"},
		{"ArgoCD", "https://argoproj.github.io/cd", "GitOps持续交付"},
		{"Flux", "https://fluxcd.io", "GitOps工具"},
		{"Spinnaker", "https://spinnaker.io", "多云持续交付"},
		{"Tekton", "https://tekton.dev", "云原生CI/CD"},
		{"Prometheus", "https://prometheus.io", "监控系统"},
		{"Grafana", "https://grafana.com", "可视化监控"},
		{"Datadog", "https://www.datadoghq.com", "云监控平台"},
		{"New Relic", "https://newrelic.com", "应用性能监控"},
		{"Splunk", "https://www.splunk.com", "数据分析平台"},
		{"PagerDuty", "https://www.pagerduty.com", "事件管理"},
		{"Opsgenie", "https://www.atlassian.com/software/opsgenie", "告警管理"},
		{"Jaeger", "https://www.jaegertracing.io", "分布式追踪"},
		{"Zipkin", "https://zipkin.io", "分布式追踪系统"},
		{"Sentry", "https://sentry.io", "错误监控"},
		{"ELK Stack", "https://www.elastic.co/elastic-stack", "日志分析栈"},
		{"Loki", "https://grafana.com/oss/loki", "日志聚合"},
		{"Fluentd", "https://www.fluentd.org", "日志收集"},
		{"Vector", "https://vector.dev", "日志管道"},
		{"Nginx", "https://nginx.org", "Web服务器反向代理"},
		{"Apache", "https://httpd.apache.org", "Apache HTTP服务器"},
		{"Caddy", "https://caddyserver.com", "自动HTTPS服务器"},
		{"Traefik", "https://traefik.io", "云原生反向代理"},
		{"HAProxy", "https://www.haproxy.org", "负载均衡器"},
		{"Envoy", "https://www.envoyproxy.io", "服务网格代理"},
		{"Istio", "https://istio.io", "服务网格"},
		{"Consul", "https://www.consul.io", "服务发现"},
		{"Vault", "https://www.vaultproject.io", "密钥管理"},
		{"Nomad", "https://www.nomadproject.io", "工作负载编排"},
		{"Packer", "https://www.packer.io", "镜像构建"},
		{"Vagrant", "https://www.vagrantup.com", "开发环境管理"},
		{"宝塔面板", "https://www.bt.cn", "Linux服务器管理"},
	}
}

func security() []S {
	return []S{
		{"OWASP", "https://owasp.org", "开放Web安全项目"},
		{"CVE", "https://www.cve.org", "漏洞编号数据库"},
		{"NVD", "https://nvd.nist.gov", "国家漏洞数据库"},
		{"Exploit-DB", "https://www.exploit-db.com", "漏洞利用数据库"},
		{"CNVD", "https://www.cnvd.org.cn", "中国国家漏洞库"},
		{"CNNVD", "https://www.cnnvd.org.cn", "中国国家漏洞库"},
		{"HackerOne", "https://www.hackerone.com", "漏洞赏金平台"},
		{"Bugcrowd", "https://www.bugcrowd.com", "众测安全平台"},
		{"Synack", "https://www.synack.com", "安全测试平台"},
		{"VirusTotal", "https://www.virustotal.com", "在线病毒扫描"},
		{"Shodan", "https://www.shodan.io", "IoT搜索引擎"},
		{"Censys", "https://censys.io", "互联网资产搜索"},
		{"ZoomEye", "https://www.zoomeye.org", "网络空间搜索"},
		{"FOFA", "https://fofa.info", "网络资产搜索"},
		{"SecurityTrails", "https://securitytrails.com", "DNS安全数据"},
		{"Have I Been Pwned", "https://haveibeenpwned.com", "数据泄露检查"},
		{"CrowdStrike", "https://www.crowdstrike.com", "端点安全"},
		{"Palo Alto Networks", "https://www.paloaltonetworks.com", "网络安全"},
		{"Fortinet", "https://www.fortinet.com", "网络安全"},
		{"Check Point", "https://www.checkpoint.com", "安全解决方案"},
		{"Sophos", "https://www.sophos.com", "企业安全"},
		{"Trend Micro", "https://www.trendmicro.com", "趋势科技"},
		{"Kaspersky", "https://www.kaspersky.com", "卡巴斯基安全"},
		{"Norton", "https://us.norton.com", "诺顿安全"},
		{"Bitdefender", "https://www.bitdefender.com", "比特梵德"},
		{"Malwarebytes", "https://www.malwarebytes.com", "恶意软件防护"},
		{"1Password", "https://1password.com", "密码管理器"},
		{"Bitwarden", "https://bitwarden.com", "开源密码管理"},
		{"LastPass", "https://www.lastpass.com", "密码管理器"},
		{"KeePass", "https://keepass.info", "开源密码管理"},
		{"Dashlane", "https://www.dashlane.com", "密码管理"},
		{"NordVPN", "https://nordvpn.com", "VPN服务"},
		{"ExpressVPN", "https://www.expressvpn.com", "VPN服务"},
		{"ProtonVPN", "https://protonvpn.com", "隐私VPN"},
		{"Mullvad VPN", "https://mullvad.net", "匿名VPN"},
		{"WireGuard", "https://www.wireguard.com", "VPN协议"},
		{"Burp Suite", "https://portswigger.net/burp", "Web安全测试"},
		{"Nmap", "https://nmap.org", "网络扫描工具"},
		{"Wireshark", "https://www.wireshark.org", "网络协议分析"},
		{"Metasploit", "https://www.metasploit.com", "渗透测试框架"},
		{"Kali Linux", "https://www.kali.org", "安全测试系统"},
		{"Parrot OS", "https://parrotlinux.org", "安全操作系统"},
		{"Snort", "https://www.snort.org", "入侵检测系统"},
		{"Suricata", "https://suricata.io", "网络安全监控"},
		{"OSSEC", "https://www.ossec.net", "主机入侵检测"},
		{"Wazuh", "https://wazuh.com", "安全监控平台"},
		{"奇安信", "https://www.qianxin.com", "网络安全企业"},
		{"360安全", "https://www.360.cn", "360安全"},
		{"深信服", "https://www.sangfor.com.cn", "深信服安全"},
		{"绿盟科技", "https://www.nsfocus.com.cn", "绿盟网络安全"},
		{"安恒信息", "https://www.dbappsecurity.com.cn", "安恒安全"},
		{"先知社区", "https://xz.aliyun.com", "安全技术社区"},
	}
}

func frontend() []S {
	return []S{
		{"React", "https://react.dev", "React前端框架"},
		{"Vue.js", "https://vuejs.org", "Vue前端框架"},
		{"Angular", "https://angular.io", "Angular框架"},
		{"Svelte", "https://svelte.dev", "Svelte编译框架"},
		{"Solid", "https://www.solidjs.com", "SolidJS反应式"},
		{"Qwik", "https://qwik.builder.io", "可恢复前端框架"},
		{"Preact", "https://preactjs.com", "轻量React替代"},
		{"Next.js", "https://nextjs.org", "React全栈框架"},
		{"Nuxt", "https://nuxt.com", "Vue全栈框架"},
		{"Remix", "https://remix.run", "React全栈框架"},
		{"Astro", "https://astro.build", "内容优先框架"},
		{"Gatsby", "https://www.gatsbyjs.com", "React静态站点"},
		{"SvelteKit", "https://kit.svelte.dev", "Svelte全栈框架"},
		{"Vite", "https://vitejs.dev", "前端构建工具"},
		{"Webpack", "https://webpack.js.org", "模块打包工具"},
		{"Rollup", "https://rollupjs.org", "ES模块打包"},
		{"esbuild", "https://esbuild.github.io", "极速JS打包"},
		{"Turbopack", "https://turbo.build/pack", "Rust打包工具"},
		{"Parcel", "https://parceljs.org", "零配置打包"},
		{"Bun", "https://bun.sh", "JS运行时与打包"},
		{"Tailwind CSS", "https://tailwindcss.com", "原子CSS框架"},
		{"Bootstrap", "https://getbootstrap.com", "Bootstrap框架"},
		{"Material UI", "https://mui.com", "React组件库"},
		{"Ant Design", "https://ant.design", "企业级UI组件"},
		{"Chakra UI", "https://chakra-ui.com", "React组件库"},
		{"Radix UI", "https://www.radix-ui.com", "无障碍组件"},
		{"shadcn/ui", "https://ui.shadcn.com", "可复制组件"},
		{"Headless UI", "https://headlessui.com", "无样式组件"},
		{"DaisyUI", "https://daisyui.com", "Tailwind组件"},
		{"Mantine", "https://mantine.dev", "React组件库"},
		{"Element Plus", "https://element-plus.org", "Vue3组件库"},
		{"Vuetify", "https://vuetifyjs.com", "Vue Material组件"},
		{"Naive UI", "https://www.naiveui.com", "Vue3组件库"},
		{"PrimeVue", "https://primevue.org", "Vue UI组件"},
		{"Storybook", "https://storybook.js.org", "组件开发工具"},
		{"TypeScript", "https://www.typescriptlang.org", "JavaScript超集"},
		{"MDN Web Docs", "https://developer.mozilla.org", "Web文档参考"},
		{"Can I Use", "https://caniuse.com", "浏览器兼容性"},
		{"CSS-Tricks", "https://css-tricks.com", "CSS技巧教程"},
		{"Smashing Magazine", "https://www.smashingmagazine.com", "Web开发杂志"},
		{"Frontend Masters", "https://frontendmasters.com", "前端视频教程"},
		{"CodePen", "https://codepen.io", "前端代码展示"},
		{"JSFiddle", "https://jsfiddle.net", "在线JS编辑"},
		{"StackBlitz", "https://stackblitz.com", "在线IDE"},
		{"CodeSandbox", "https://codesandbox.io", "在线开发环境"},
		{"Figma to Code", "https://www.figma.com/developers", "设计转代码"},
		{"Web.dev", "https://web.dev", "Google Web最佳实践"},
		{"Chrome DevTools", "https://developer.chrome.com/docs/devtools", "浏览器开发工具"},
		{"Lighthouse", "https://developer.chrome.com/docs/lighthouse", "网页性能审计"},
		{"Bundlephobia", "https://bundlephobia.com", "NPM包大小分析"},
		{"npm trends", "https://npmtrends.com", "NPM包对比"},
		{"State of JS", "https://stateofjs.com", "JS生态调查"},
	}
}

func backend() []S {
	return []S{
		{"Node.js", "https://nodejs.org", "JavaScript运行时"},
		{"Deno", "https://deno.com", "安全JS运行时"},
		{"Bun", "https://bun.sh", "快速JS运行时"},
		{"Express", "https://expressjs.com", "Node.js框架"},
		{"Fastify", "https://fastify.dev", "高性能Node框架"},
		{"NestJS", "https://nestjs.com", "企业级Node框架"},
		{"Koa", "https://koajs.com", "轻量Node框架"},
		{"Hono", "https://hono.dev", "超快Web框架"},
		{"Go", "https://go.dev", "Go语言官网"},
		{"Gin", "https://gin-gonic.com", "Go Web框架"},
		{"Echo", "https://echo.labstack.com", "Go Web框架"},
		{"Fiber", "https://gofiber.io", "Go Express风格"},
		{"Chi", "https://go-chi.io", "Go路由库"},
		{"Python", "https://www.python.org", "Python官网"},
		{"Django", "https://www.djangoproject.com", "Python全栈框架"},
		{"Flask", "https://flask.palletsprojects.com", "Python微框架"},
		{"FastAPI", "https://fastapi.tiangolo.com", "Python异步API"},
		{"Rust", "https://www.rust-lang.org", "Rust语言"},
		{"Actix Web", "https://actix.rs", "Rust Web框架"},
		{"Axum", "https://docs.rs/axum", "Rust异步Web"},
		{"Java", "https://www.java.com", "Java语言"},
		{"Spring Boot", "https://spring.io/projects/spring-boot", "Spring Boot框架"},
		{"Quarkus", "https://quarkus.io", "Java云原生框架"},
		{"Micronaut", "https://micronaut.io", "JVM微服务框架"},
		{"Ruby on Rails", "https://rubyonrails.org", "Ruby全栈框架"},
		{"Laravel", "https://laravel.com", "PHP框架"},
		{"Symfony", "https://symfony.com", "PHP企业框架"},
		{"ASP.NET", "https://dotnet.microsoft.com/apps/aspnet", ".NET Web框架"},
		{"gRPC", "https://grpc.io", "RPC框架"},
		{"GraphQL", "https://graphql.org", "API查询语言"},
		{"tRPC", "https://trpc.io", "类型安全API"},
		{"Swagger", "https://swagger.io", "API文档工具"},
		{"Postman", "https://www.postman.com", "API开发测试"},
		{"Insomnia", "https://insomnia.rest", "API客户端"},
		{"Hoppscotch", "https://hoppscotch.io", "开源API测试"},
		{"Bruno", "https://www.usebruno.com", "离线API客户端"},
		{"RabbitMQ", "https://www.rabbitmq.com", "消息队列"},
		{"Apache Kafka", "https://kafka.apache.org", "分布式消息"},
		{"NATS", "https://nats.io", "云原生消息"},
		{"ZeroMQ", "https://zeromq.org", "消息库"},
		{"Celery", "https://docs.celeryq.dev", "Python任务队列"},
		{"Bull", "https://optimalbits.github.io/bull", "Node.js任务队列"},
		{"Redis", "https://redis.io", "内存数据结构"},
		{"Memcached", "https://memcached.org", "分布式缓存"},
		{"Apache Thrift", "https://thrift.apache.org", "跨语言RPC"},
		{"Protocol Buffers", "https://protobuf.dev", "数据序列化"},
		{"JSON Schema", "https://json-schema.org", "JSON验证"},
		{"OpenAPI", "https://www.openapis.org", "API规范"},
		{"AsyncAPI", "https://www.asyncapi.com", "异步API规范"},
		{"Socket.IO", "https://socket.io", "实时通信"},
		{"WebSocket", "https://websocket.org", "WebSocket标准"},
		{"Prisma", "https://www.prisma.io", "Node.js ORM"},
	}
}

func mobileDev() []S {
	return []S{
		{"React Native", "https://reactnative.dev", "跨平台移动开发"},
		{"Flutter", "https://flutter.dev", "Google跨平台UI"},
		{"Expo", "https://expo.dev", "React Native工具"},
		{"Ionic", "https://ionicframework.com", "混合移动开发"},
		{"Capacitor", "https://capacitorjs.com", "跨平台运行时"},
		{"SwiftUI", "https://developer.apple.com/xcode/swiftui", "Apple声明式UI"},
		{"Swift", "https://swift.org", "Apple编程语言"},
		{"Kotlin", "https://kotlinlang.org", "Android开发语言"},
		{"Jetpack Compose", "https://developer.android.com/jetpack/compose", "Android声明式UI"},
		{"Apple Developer", "https://developer.apple.com", "Apple开发者"},
		{"Android Developers", "https://developer.android.com", "Android开发者"},
		{"Xcode", "https://developer.apple.com/xcode", "Apple IDE"},
		{"Android Studio", "https://developer.android.com/studio", "Android IDE"},
		{"TestFlight", "https://developer.apple.com/testflight", "iOS测试分发"},
		{"Firebase", "https://firebase.google.com", "移动后端服务"},
		{"App Store Connect", "https://appstoreconnect.apple.com", "iOS应用管理"},
		{"Google Play Console", "https://play.google.com/console", "Android应用管理"},
		{"OneSignal", "https://onesignal.com", "推送通知服务"},
		{"Pusher", "https://pusher.com", "实时通信API"},
		{"RevenueCat", "https://www.revenuecat.com", "应用内购管理"},
		{"Adapty", "https://adapty.io", "订阅分析"},
		{"Branch", "https://www.branch.io", "深度链接"},
		{"Adjust", "https://www.adjust.com", "移动归因分析"},
		{"AppsFlyer", "https://www.appsflyer.com", "移动归因"},
		{"Mixpanel", "https://mixpanel.com", "产品分析"},
		{"Amplitude", "https://amplitude.com", "产品分析平台"},
		{"Crashlytics", "https://firebase.google.com/products/crashlytics", "崩溃报告"},
		{"Bugsnag", "https://www.bugsnag.com", "错误监控"},
		{"Instabug", "https://instabug.com", "Bug报告SDK"},
		{"Fastlane", "https://fastlane.tools", "移动自动化工具"},
		{"Bitrise", "https://www.bitrise.io", "移动CI/CD"},
		{"Codemagic", "https://codemagic.io", "Flutter CI/CD"},
		{"AppCenter", "https://appcenter.ms", "微软移动DevOps"},
		{"Appetize", "https://appetize.io", "在线模拟器"},
		{"BrowserStack", "https://www.browserstack.com", "真机测试平台"},
		{"Sauce Labs", "https://saucelabs.com", "自动化测试云"},
		{"Detox", "https://wix.github.io/Detox", "RN E2E测试"},
		{"Appium", "https://appium.io", "移动自动化测试"},
		{"Maestro", "https://maestro.mobile.dev", "移动UI测试"},
		{"Tauri", "https://tauri.app", "跨平台桌面应用"},
		{"Electron", "https://www.electronjs.org", "桌面应用框架"},
		{"NativeScript", "https://nativescript.org", "原生移动开发"},
		{"Xamarin", "https://dotnet.microsoft.com/apps/xamarin", ".NET移动开发"},
		{"MAUI", "https://dotnet.microsoft.com/apps/maui", ".NET多平台"},
		{"uni-app", "https://uniapp.dcloud.net.cn", "跨平台开发"},
		{"Taro", "https://taro.jd.com", "京东多端框架"},
		{"微信小程序", "https://mp.weixin.qq.com", "微信小程序开发"},
		{"支付宝小程序", "https://open.alipay.com/develop/mini/introduce", "支付宝小程序"},
		{"抖音小程序", "https://developer.open-douyin.com", "抖音小程序"},
		{"HarmonyOS", "https://developer.harmonyos.com", "鸿蒙OS开发"},
		{"KMM", "https://kotlinlang.org/lp/multiplatform", "Kotlin多平台"},
		{"Compose Multiplatform", "https://www.jetbrains.com/lp/compose-multiplatform", "JetBrains跨平台"},
	}
}

func dataScience() []S {
	return []S{
		{"Jupyter", "https://jupyter.org", "交互式笔记本"},
		{"Google Colab", "https://colab.research.google.com", "免费GPU笔记本"},
		{"Kaggle", "https://www.kaggle.com", "数据科学竞赛"},
		{"Anaconda", "https://www.anaconda.com", "Python数据科学"},
		{"NumPy", "https://numpy.org", "Python数值计算"},
		{"Pandas", "https://pandas.pydata.org", "数据分析库"},
		{"Scikit-learn", "https://scikit-learn.org", "机器学习库"},
		{"TensorFlow", "https://www.tensorflow.org", "Google深度学习"},
		{"PyTorch", "https://pytorch.org", "Facebook深度学习"},
		{"Keras", "https://keras.io", "高级深度学习API"},
		{"JAX", "https://jax.readthedocs.io", "Google数值计算"},
		{"Hugging Face", "https://huggingface.co", "AI模型社区"},
		{"Weights & Biases", "https://wandb.ai", "ML实验追踪"},
		{"MLflow", "https://mlflow.org", "ML生命周期管理"},
		{"DVC", "https://dvc.org", "数据版本控制"},
		{"LabelStudio", "https://labelstud.io", "数据标注工具"},
		{"Prodigy", "https://prodi.gy", "AI数据标注"},
		{"Roboflow", "https://roboflow.com", "计算机视觉平台"},
		{"Apache Spark", "https://spark.apache.org", "大数据处理"},
		{"Apache Flink", "https://flink.apache.org", "流式计算"},
		{"Apache Airflow", "https://airflow.apache.org", "工作流编排"},
		{"Prefect", "https://www.prefect.io", "数据流编排"},
		{"Dagster", "https://dagster.io", "数据编排平台"},
		{"dbt", "https://www.getdbt.com", "数据转换工具"},
		{"Great Expectations", "https://greatexpectations.io", "数据质量验证"},
		{"Apache Superset", "https://superset.apache.org", "开源数据可视化"},
		{"Metabase", "https://www.metabase.com", "BI分析工具"},
		{"Redash", "https://redash.io", "数据可视化"},
		{"Tableau", "https://www.tableau.com", "商业智能"},
		{"Power BI", "https://powerbi.microsoft.com", "微软BI工具"},
		{"Looker", "https://looker.com", "Google数据分析"},
		{"Mode Analytics", "https://mode.com", "协作分析"},
		{"Plotly", "https://plotly.com", "交互式图表"},
		{"D3.js", "https://d3js.org", "数据驱动可视化"},
		{"Observable", "https://observablehq.com", "数据可视化笔记"},
		{"Streamlit", "https://streamlit.io", "Python数据应用"},
		{"Gradio", "https://www.gradio.app", "ML演示界面"},
		{"Panel", "https://panel.holoviz.org", "Python仪表板"},
		{"Dash", "https://dash.plotly.com", "Python Web分析"},
		{"OpenAI", "https://openai.com", "OpenAI人工智能"},
		{"Anthropic", "https://www.anthropic.com", "Claude AI"},
		{"Google DeepMind", "https://deepmind.google", "Google AI研究"},
		{"LangChain", "https://www.langchain.com", "LLM应用框架"},
		{"LlamaIndex", "https://www.llamaindex.ai", "LLM数据框架"},
		{"Ollama", "https://ollama.com", "本地运行LLM"},
		{"Replicate", "https://replicate.com", "AI模型API"},
		{"Together AI", "https://www.together.ai", "AI推理平台"},
		{"Groq", "https://groq.com", "AI推理芯片"},
		{"Papers With Code", "https://paperswithcode.com", "论文与代码"},
		{"ArXiv", "https://arxiv.org", "学术预印本"},
		{"Connected Papers", "https://www.connectedpapers.com", "论文关系图"},
		{"Semantic Scholar", "https://www.semanticscholar.org", "AI学术搜索"},
	}
}
