package main

func pets() []S {
	return []S{
		{"宠物之家", "https://www.mypethome.com", "宠物社区论坛"},
		{"波奇网", "https://www.boqii.com", "宠物用品电商"},
		{"爱宠网", "https://www.ichong123.com", "宠物知识分享"},
		{"有宠", "https://www.yc.cn", "宠物综合服务"},
		{"狗民网", "https://www.goumin.com", "狗狗社区"},
		{"猫扑", "https://www.mop.com", "猫咪爱好者"},
		{"E宠商城", "https://www.epet.com", "宠物用品商城"},
		{"宠物医生", "https://www.vetsky.com", "在线宠物问诊"},
		{"新瑞鹏宠物", "https://www.rpvets.com", "连锁宠物医院"},
		{"瑞派宠物", "https://www.repairvets.com", "宠物医疗连锁"},
		{"小红书宠物", "https://www.xiaohongshu.com/explore/pets", "宠物内容社区"},
		{"抖音宠物", "https://www.douyin.com/channel/300203", "宠物短视频"},
		{"Petfinder", "https://www.petfinder.com", "宠物领养平台"},
		{"Adopt-a-Pet", "https://www.adoptapet.com", "宠物收养"},
		{"ASPCA", "https://www.aspca.org", "美国防止虐待动物协会"},
		{"AKC", "https://www.akc.org", "美国养犬俱乐部"},
		{"The Spruce Pets", "https://www.thesprucepets.com", "宠物护理指南"},
		{"PetMD", "https://www.petmd.com", "宠物健康信息"},
		{"Rover", "https://www.rover.com", "宠物寄养遛狗"},
		{"Wag!", "https://wagwalking.com", "遛狗服务"},
		{"Chewy", "https://www.chewy.com", "宠物用品电商"},
		{"PetSmart", "https://www.petsmart.com", "宠物零售连锁"},
		{"Petco", "https://www.petco.com", "宠物超市"},
		{"BarkBox", "https://www.barkbox.com", "狗狗订阅盒"},
		{"Ollie", "https://www.myollie.com", "定制狗粮"},
		{"The Farmer's Dog", "https://www.thefarmersdog.com", "新鲜狗粮配送"},
		{"Trupanion", "https://www.trupanion.com", "宠物保险"},
		{"Healthy Paws", "https://www.healthypawspetinsurance.com", "宠物健康保险"},
		{"Lemonade Pet", "https://www.lemonade.com/pet", "宠物保险"},
		{"Furbo", "https://shopus.furbo.com", "宠物摄像头"},
		{"Whistle", "https://www.whistle.com", "宠物GPS追踪"},
		{"Fi", "https://tryfi.com", "智能狗项圈"},
		{"PetCube", "https://petcube.com", "宠物互动摄像头"},
		{"Catster", "https://www.catster.com", "猫咪爱好者社区"},
		{"Dogster", "https://www.dogster.com", "狗狗爱好者社区"},
		{"VetStreet", "https://www.vetstreet.com", "宠物健康护理"},
		{"Fear Free Pets", "https://fearfreepets.com", "减少宠物焦虑"},
		{"RSPCA", "https://www.rspca.org.uk", "英国防止虐待动物"},
		{"Battersea", "https://www.battersea.org.uk", "英国动物收容所"},
		{"DogTrust", "https://www.dogstrust.org.uk", "英国狗狗慈善"},
		{"Zooplus", "https://www.zooplus.com", "欧洲宠物用品"},
		{"Pets at Home", "https://www.petsathome.com", "英国宠物零售"},
		{"BirdLife", "https://www.birdlife.org", "鸟类保护"},
		{"World Wildlife Fund", "https://www.worldwildlife.org", "世界自然基金会"},
		{"National Geographic Animals", "https://www.nationalgeographic.com/animals", "国家地理动物"},
		{"Animal Planet", "https://www.animalplanet.com", "动物星球"},
		{"iNaturalist", "https://www.inaturalist.org", "自然观察社区"},
		{"eBird", "https://ebird.org", "鸟类观察记录"},
		{"Merlin Bird ID", "https://merlin.allaboutbirds.org", "鸟类识别"},
		{"PlantNet", "https://plantnet.org", "植物识别应用"},
		{"PictureThis", "https://www.picturethisai.com", "AI植物识别"},
		{"Seek by iNaturalist", "https://www.inaturalist.org/pages/seek_app", "物种识别"},
	}
}

func fashion() []S {
	return []S{
		{"ZARA", "https://www.zara.com", "ZARA时装"},
		{"H&M", "https://www.hm.com", "H&M快时尚"},
		{"UNIQLO", "https://www.uniqlo.com", "优衣库"},
		{"Nike", "https://www.nike.com", "Nike运动时尚"},
		{"Adidas", "https://www.adidas.com", "Adidas运动"},
		{"SHEIN", "https://www.shein.com", "跨境快时尚"},
		{"ASOS", "https://www.asos.com", "英国时尚电商"},
		{"Nordstrom", "https://www.nordstrom.com", "高端百货"},
		{"Net-a-Porter", "https://www.net-a-porter.com", "奢侈品电商"},
		{"Farfetch", "https://www.farfetch.com", "全球奢侈品平台"},
		{"SSENSE", "https://www.ssense.com", "设计师品牌电商"},
		{"Mytheresa", "https://www.mytheresa.com", "奢侈品电商"},
		{"MatchesFashion", "https://www.matchesfashion.com", "高端时尚"},
		{"Moda Operandi", "https://www.modaoperandi.com", "设计师时装预售"},
		{"Vestiaire Collective", "https://www.vestiairecollective.com", "二手奢侈品"},
		{"The RealReal", "https://www.therealreal.com", "奢侈品寄售"},
		{"Poshmark", "https://poshmark.com", "二手时尚交易"},
		{"ThredUp", "https://www.thredup.com", "二手时装"},
		{"Depop", "https://www.depop.com", "潮流二手交易"},
		{"StockX", "https://stockx.com", "球鞋潮流交易"},
		{"GOAT", "https://www.goat.com", "球鞋交易平台"},
		{"Lyst", "https://www.lyst.com", "时尚搜索引擎"},
		{"Vogue", "https://www.vogue.com", "时尚杂志"},
		{"Elle", "https://www.elle.com", "Elle时尚"},
		{"Harper's Bazaar", "https://www.harpersbazaar.com", "时尚芭莎"},
		{"GQ", "https://www.gq.com", "男士时尚"},
		{"Esquire", "https://www.esquire.com", "时尚先生"},
		{"WWD", "https://wwd.com", "时装日报"},
		{"Business of Fashion", "https://www.businessoffashion.com", "时尚商业"},
		{"Highsnobiety", "https://www.highsnobiety.com", "潮流文化"},
		{"Hypebeast", "https://hypebeast.com", "潮流媒体"},
		{"Complex", "https://www.complex.com", "潮流文化杂志"},
		{"Sephora", "https://www.sephora.com", "丝芙兰美妆"},
		{"Ulta Beauty", "https://www.ulta.com", "美妆零售"},
		{"Glossier", "https://www.glossier.com", "互联网美妆"},
		{"Fenty Beauty", "https://fentybeauty.com", "Rihanna美妆"},
		{"Charlotte Tilbury", "https://www.charlottetilbury.com", "英国美妆"},
		{"MAC Cosmetics", "https://www.maccosmetics.com", "MAC彩妆"},
		{"Estée Lauder", "https://www.esteelauder.com", "雅诗兰黛"},
		{"L'Oréal", "https://www.loreal.com", "欧莱雅集团"},
		{"天猫美妆", "https://beauty.tmall.com", "天猫美妆频道"},
		{"小红书美妆", "https://www.xiaohongshu.com/explore/beauty", "美妆种草"},
		{"美丽修行", "https://www.bevol.cn", "护肤品成分查询"},
		{"得物", "https://www.dewu.com", "潮流电商鉴定"},
		{"识货", "https://www.shihuo.cn", "运动潮流导购"},
		{"Lookpin", "https://www.lookpin.com", "时尚搭配分享"},
		{"穿衣助手", "https://www.chwear.com", "穿搭推荐"},
		{"蘑菇街", "https://www.mogujie.com", "女性时尚电商"},
		{"唯品会", "https://www.vip.com", "品牌特卖"},
		{"寺库", "https://www.secoo.com", "奢侈品电商"},
		{"妖精的口袋", "https://www.elfsack.com", "原创女装"},
		{"太平鸟", "https://www.peacebird.com.cn", "太平鸟时装"},
	}
}

func kids() []S {
	return []S{
		{"宝宝树", "https://www.babytree.com", "母婴育儿社区"},
		{"妈妈网", "https://www.mama.cn", "母婴知识平台"},
		{"亲宝宝", "https://www.qinbaobao.com", "育儿记录成长"},
		{"小豆苗", "https://www.xdoumiao.com", "疫苗接种提醒"},
		{"丁香妈妈", "https://mama.dxy.com", "科学育儿"},
		{"崔玉涛育学园", "https://www.yuexueyuan.com", "儿科医生育儿"},
		{"年糕妈妈", "https://www.niangao-mama.com", "母婴内容电商"},
		{"凯叔讲故事", "https://www.kaishustory.com", "儿童有声故事"},
		{"洪恩教育", "https://www.ihuman.com", "儿童教育APP"},
		{"小猿口算", "https://xiaoyuan.com", "口算练习"},
		{"作业帮口算", "https://www.zybang.com/ksapp", "口算批改"},
		{"宝宝巴士", "https://www.babybus.com", "儿童启蒙"},
		{"贝瓦儿歌", "https://www.beva.com", "儿童儿歌"},
		{"小伴龙", "https://www.xiaobanlong.com", "儿童早教"},
		{"蜜芽", "https://www.mia.com", "母婴特卖"},
		{"孩子王", "https://www.haiziwang.com", "母婴零售"},
		{"BabyCenter", "https://www.babycenter.com", "全球育儿资讯"},
		{"What to Expect", "https://www.whattoexpect.com", "孕期育儿指南"},
		{"Parents", "https://www.parents.com", "育儿杂志"},
		{"Bump", "https://www.thebump.com", "孕期育儿"},
		{"Motherly", "https://www.mother.ly", "现代母亲社区"},
		{"Babylist", "https://www.babylist.com", "新生儿礼物清单"},
		{"Carter's", "https://www.carters.com", "童装品牌"},
		{"Gymboree", "https://www.gymboree.com", "金宝贝早教"},
		{"Fisher-Price", "https://www.fisher-price.com", "费雪玩具"},
		{"LEGO", "https://www.lego.com", "乐高玩具"},
		{"Melissa & Doug", "https://www.melissaanddoug.com", "创意玩具"},
		{"PBS Kids", "https://pbskids.org", "PBS儿童教育"},
		{"National Geographic Kids", "https://kids.nationalgeographic.com", "国家地理少儿"},
		{"Sesame Street", "https://www.sesamestreet.org", "芝麻街教育"},
		{"Nick Jr.", "https://www.nickjr.com", "尼克少儿"},
		{"Disney Junior", "https://disneyjunior.disney.com", "迪士尼少儿"},
		{"ABCmouse", "https://www.abcmouse.com", "儿童英语学习"},
		{"Homer", "https://www.learnwithhomer.com", "儿童阅读学习"},
		{"Tynker", "https://www.tynker.com", "儿童编程教育"},
		{"Scratch", "https://scratch.mit.edu", "MIT少儿编程"},
		{"Code.org", "https://code.org", "编程教育普及"},
		{"Khan Academy Kids", "https://learn.khanacademy.org/khan-academy-kids", "可汗少儿教育"},
		{"Starfall", "https://www.starfall.com", "儿童阅读数学"},
		{"Coolmath Games", "https://www.coolmathgames.com", "趣味数学游戏"},
		{"Epic!", "https://www.getepic.com", "儿童数字图书馆"},
		{"Audible Kids", "https://www.audible.com/ep/kids", "儿童有声书"},
		{"Storyline Online", "https://storylineonline.net", "名人讲故事"},
		{"Highlights", "https://www.highlights.com", "儿童杂志"},
		{"Scholastic", "https://www.scholastic.com", "学乐出版教育"},
		{"巧虎", "https://www.qiaohu.com", "巧虎早教"},
		{"VIPKid", "https://www.vipkid.com", "少儿英语"},
		{"斑马AI", "https://www.banmaai.com", "AI少儿教育"},
		{"叽里呱啦", "https://www.jiliguala.com", "英语启蒙"},
		{"编程猫", "https://www.codemao.cn", "少儿编程平台"},
		{"核桃编程", "https://www.hetaobian.com", "少儿编程教育"},
		{"童程童美", "https://www.it61.cn", "少儿编程机器人"},
	}
}

func agriculture() []S {
	return []S{
		{"中国农业信息网", "https://www.agri.cn", "农业信息服务"},
		{"农业农村部", "https://www.moa.gov.cn", "农业政策信息"},
		{"中国农业网", "https://www.zgny.com.cn", "农业综合信息"},
		{"惠农网", "https://www.cnhnb.com", "农产品交易"},
		{"一亩田", "https://www.ymt.com", "农产品电商"},
		{"中国种子网", "https://www.seedchina.com.cn", "种业信息"},
		{"中国农药信息网", "https://www.chinapesticide.org.cn", "农药信息"},
		{"中国化肥网", "https://www.fert.cn", "化肥行业信息"},
		{"中国畜牧网", "https://www.chinafarming.com", "畜牧业信息"},
		{"中国渔业网", "https://www.cnfishing.com", "渔业信息"},
		{"中国茶网", "https://www.china-tea.org", "茶叶行业"},
		{"中国果品网", "https://www.chinafruits.cn", "水果行业信息"},
		{"中国蔬菜网", "https://www.vegnet.com.cn", "蔬菜行业"},
		{"猪易通", "https://www.zhue.com.cn", "生猪行情"},
		{"鸡病专业网", "https://www.jbzyw.com", "禽类养殖"},
		{"水产养殖网", "https://www.shuichan.cc", "水产养殖信息"},
		{"拼多多农货", "https://www.pinduoduo.com/subject/agriculture", "拼多多助农"},
		{"淘宝特色农货", "https://www.taobao.com/markets/nongye", "淘宝农产品"},
		{"京东农场", "https://farm.jd.com", "京东农业"},
		{"美菜网", "https://www.meicai.cn", "食材供应链"},
		{"农信互联", "https://www.nxin.com", "农业互联网"},
		{"大北农", "https://www.dbnsci.com", "农业科技企业"},
		{"新希望", "https://www.newhopegroup.com", "农牧企业"},
		{"USDA", "https://www.usda.gov", "美国农业部"},
		{"FAO", "https://www.fao.org", "联合国粮农组织"},
		{"IFPRI", "https://www.ifpri.org", "国际食物政策研究"},
		{"CIMMYT", "https://www.cimmyt.org", "国际玉米小麦中心"},
		{"IRRI", "https://www.irri.org", "国际水稻研究所"},
		{"FarmLogs", "https://www.farmlogs.com", "农场管理软件"},
		{"Granular", "https://granular.ag", "数字农业管理"},
		{"Climate FieldView", "https://climate.com", "农业气候数据"},
		{"John Deere", "https://www.deere.com", "农业机械"},
		{"CNH Industrial", "https://www.cnhindustrial.com", "农业工业设备"},
		{"AGCO", "https://www.agcocorp.com", "农业设备制造"},
		{"Trimble Agriculture", "https://agriculture.trimble.com", "精准农业"},
		{"Indigo Agriculture", "https://www.indigoag.com", "可持续农业"},
		{"Farmers Business Network", "https://www.fbn.com", "农民商业网络"},
		{"AgFunder", "https://agfundernews.com", "农业科技投资"},
		{"AgriWebb", "https://www.agriwebb.com", "牧场管理软件"},
		{"OnFarm", "https://www.onfarm.com", "智慧农业"},
		{"Plantix", "https://plantix.net", "植物病害AI诊断"},
		{"Cropio", "https://about.cropio.com", "卫星农业监测"},
		{"Arable", "https://www.arable.com", "农业物联网"},
		{"Agworld", "https://www.agworld.com", "农业管理平台"},
		{"FarmWise", "https://www.farmwise.io", "AI除草机器人"},
		{"Blue River Technology", "https://bluerivertechnology.com", "精准农业AI"},
		{"Plenty", "https://www.plenty.ag", "室内垂直农业"},
		{"AeroFarms", "https://www.aerofarms.com", "垂直农业"},
		{"Bowery Farming", "https://boweryfarming.com", "室内农场"},
		{"AppHarvest", "https://www.appharvest.com", "科技农业"},
		{"Apeel Sciences", "https://www.apeelsciences.com", "食物保鲜科技"},
		{"Impossible Foods", "https://impossiblefoods.com", "人造肉"},
		{"Beyond Meat", "https://www.beyondmeat.com", "植物肉"},
	}
}

func environment() []S {
	return []S{
		{"World Wildlife Fund", "https://www.worldwildlife.org", "世界自然基金会"},
		{"Greenpeace", "https://www.greenpeace.org", "绿色和平组织"},
		{"Sierra Club", "https://www.sierraclub.org", "美国环保组织"},
		{"NRDC", "https://www.nrdc.org", "自然资源保护"},
		{"WWF中国", "https://www.wwfchina.org", "世界自然基金会中国"},
		{"生态环境部", "https://www.mee.gov.cn", "中国环保部门"},
		{"中国环境网", "https://www.cenews.com.cn", "环境新闻"},
		{"绿色和平中国", "https://www.greenpeace.org.cn", "绿色和平中国"},
		{"自然之友", "https://www.fon.org.cn", "中国环保NGO"},
		{"阿拉善SEE", "https://www.see.org.cn", "环保公益"},
		{"蚂蚁森林", "https://www.antgroup.com/ecosystem/ant-forest", "蚂蚁公益"},
		{"腾讯公益", "https://gongyi.qq.com", "腾讯公益平台"},
		{"壹基金", "https://www.onefoundation.cn", "壹基金公益"},
		{"中国红十字会", "https://www.redcross.org.cn", "红十字会"},
		{"公益时报", "https://www.gongyishibao.com", "公益新闻"},
		{"UN Environment", "https://www.unep.org", "联合国环境署"},
		{"EPA", "https://www.epa.gov", "美国环保局"},
		{"IPCC", "https://www.ipcc.ch", "政府间气候变化"},
		{"Climate.gov", "https://www.climate.gov", "美国气候信息"},
		{"Carbon Brief", "https://www.carbonbrief.org", "气候变化分析"},
		{"Inside Climate News", "https://insideclimatenews.org", "气候新闻"},
		{"The Guardian Environment", "https://www.theguardian.com/environment", "卫报环境"},
		{"Mongabay", "https://news.mongabay.com", "热带雨林新闻"},
		{"TreeHugger", "https://www.treehugger.com", "绿色生活"},
		{"Grist", "https://grist.org", "环境新闻"},
		{"Earth.org", "https://earth.org", "环境新闻平台"},
		{"Climate Action Tracker", "https://climateactiontracker.org", "气候行动追踪"},
		{"Global Forest Watch", "https://www.globalforestwatch.org", "全球森林监测"},
		{"Ocean Conservancy", "https://oceanconservancy.org", "海洋保护"},
		{"Oceana", "https://oceana.org", "海洋保护组织"},
		{"Marine Conservation", "https://www.mcsuk.org", "海洋保护协会"},
		{"Surfrider Foundation", "https://www.surfrider.org", "海岸保护"},
		{"350.org", "https://350.org", "气候变化运动"},
		{"Extinction Rebellion", "https://extinctionrebellion.uk", "气候抗议运动"},
		{"Fridays for Future", "https://fridaysforfuture.org", "青年气候运动"},
		{"The Nature Conservancy", "https://www.nature.org", "自然保护协会"},
		{"Conservation International", "https://www.conservation.org", "国际保护"},
		{"WRI", "https://www.wri.org", "世界资源研究所"},
		{"IUCN", "https://www.iucn.org", "世界自然保护联盟"},
		{"Rainforest Alliance", "https://www.rainforest-alliance.org", "雨林联盟"},
		{"FSC", "https://fsc.org", "森林管理委员会"},
		{"Energy Star", "https://www.energystar.gov", "能源之星"},
		{"IRENA", "https://www.irena.org", "国际可再生能源"},
		{"Solar Energy Industries", "https://www.seia.org", "太阳能产业"},
		{"WindEurope", "https://windeurope.org", "欧洲风能协会"},
		{"BloombergNEF", "https://about.bnef.com", "新能源财经"},
		{"Clean Energy Council", "https://www.cleanenergycouncil.org.au", "清洁能源"},
		{"Circular Economy", "https://www.ellenmacarthurfoundation.org", "循环经济"},
		{"Ecosia", "https://www.ecosia.org", "种树搜索引擎"},
		{"One Tree Planted", "https://onetreeplanted.org", "植树公益"},
		{"TerraCycle", "https://www.terracycle.com", "回收再利用"},
		{"iFixit", "https://www.ifixit.com", "维修教程减少浪费"},
	}
}

func logistics() []S {
	return []S{
		{"顺丰速运", "https://www.sf-express.com", "顺丰快递"},
		{"中通快递", "https://www.zto.com", "中通快递"},
		{"圆通速递", "https://www.yto.net.cn", "圆通快递"},
		{"韵达快递", "https://www.yundaex.com", "韵达快递"},
		{"申通快递", "https://www.sto.cn", "申通快递"},
		{"百世快递", "https://www.800best.com", "百世快递"},
		{"极兔速递", "https://www.jtexpress.cn", "极兔快递"},
		{"德邦物流", "https://www.deppon.com", "德邦快递"},
		{"京东物流", "https://www.jdl.com", "京东物流"},
		{"菜鸟网络", "https://www.cainiao.com", "阿里物流平台"},
		{"邮政EMS", "https://www.ems.com.cn", "中国邮政速递"},
		{"中国邮政", "https://www.chinapost.com.cn", "中国邮政"},
		{"快递100", "https://www.kuaidi100.com", "快递查询服务"},
		{"17track", "https://www.17track.net", "全球包裹追踪"},
		{"FedEx", "https://www.fedex.com", "联邦快递"},
		{"UPS", "https://www.ups.com", "UPS快递"},
		{"DHL", "https://www.dhl.com", "DHL国际快递"},
		{"USPS", "https://www.usps.com", "美国邮政"},
		{"TNT", "https://www.tnt.com", "TNT快递"},
		{"DPD", "https://www.dpd.com", "DPD欧洲快递"},
		{"Royal Mail", "https://www.royalmail.com", "英国皇家邮政"},
		{"Canada Post", "https://www.canadapost-postescanada.ca", "加拿大邮政"},
		{"Australia Post", "https://auspost.com.au", "澳大利亚邮政"},
		{"Japan Post", "https://www.post.japanpost.jp", "日本邮政"},
		{"Yamato Transport", "https://www.kuronekoyamato.co.jp", "日本黑猫宅急便"},
		{"Sagawa Express", "https://www.sagawa-exp.co.jp", "佐川急便"},
		{"CJ Logistics", "https://www.cjlogistics.com", "韩国CJ物流"},
		{"Aramex", "https://www.aramex.com", "中东物流"},
		{"FleetComplete", "https://www.fleetcomplete.com", "车队管理"},
		{"Samsara", "https://www.samsara.com", "物联网车队管理"},
		{"Project44", "https://www.project44.com", "供应链可视化"},
		{"FourKites", "https://www.fourkites.com", "供应链追踪"},
		{"Flexport", "https://www.flexport.com", "数字货运代理"},
		{"Freightos", "https://www.freightos.com", "国际货运比价"},
		{"ShipBob", "https://www.shipbob.com", "电商仓储物流"},
		{"ShipStation", "https://www.shipstation.com", "订单发货管理"},
		{"Shippo", "https://goshippo.com", "发货API平台"},
		{"EasyPost", "https://www.easypost.com", "快递API服务"},
		{"AfterShip", "https://www.aftership.com", "包裹追踪API"},
		{"Parcels", "https://parcelsapp.com", "全球快递追踪"},
		{"PackageRadar", "https://www.packageradar.com", "包裹追踪"},
		{"Track24", "https://track24.net", "国际快递追踪"},
		{"TrackingMore", "https://www.trackingmore.com", "全球物流追踪"},
		{"满帮集团", "https://www.ymm56.com", "运满满货运"},
		{"货拉拉", "https://www.huolala.cn", "同城货运"},
		{"福佑卡车", "https://www.fuyoukache.com", "整车运输"},
		{"G7物联", "https://www.g7.com.cn", "物流物联网"},
		{"传化智联", "https://www.transfar.com", "智慧物流"},
		{"安能物流", "https://www.ane56.com", "零担快运"},
		{"壹米滴答", "https://www.yimidida.com", "综合物流"},
		{"中铁快运", "https://www.cre.cn", "铁路快运"},
		{"中远海运", "https://www.cosco.com", "海运物流"},
	}
}

func telecom() []S {
	return []S{
		{"中国移动", "https://www.10086.cn", "中国移动通信"},
		{"中国联通", "https://www.10010.com", "中国联通"},
		{"中国电信", "https://www.189.cn", "中国电信"},
		{"中国广电", "https://www.cbn.cn", "中国广电5G"},
		{"工信部", "https://www.miit.gov.cn", "工业和信息化部"},
		{"AT&T", "https://www.att.com", "AT&T通信"},
		{"Verizon", "https://www.verizon.com", "Verizon通信"},
		{"T-Mobile", "https://www.t-mobile.com", "T-Mobile通信"},
		{"Vodafone", "https://www.vodafone.com", "沃达丰通信"},
		{"Deutsche Telekom", "https://www.telekom.com", "德国电信"},
		{"Orange", "https://www.orange.com", "Orange法国电信"},
		{"BT Group", "https://www.bt.com", "英国电信"},
		{"Telefonica", "https://www.telefonica.com", "西班牙电信"},
		{"NTT", "https://www.ntt.com", "日本电信"},
		{"SoftBank", "https://www.softbank.jp", "软银通信"},
		{"SK Telecom", "https://www.sktelecom.com", "韩国SK电信"},
		{"KT Corp", "https://www.kt.com", "韩国电信"},
		{"Singtel", "https://www.singtel.com", "新加坡电信"},
		{"Telstra", "https://www.telstra.com.au", "澳洲电信"},
		{"Rogers", "https://www.rogers.com", "加拿大Rogers"},
		{"Huawei", "https://www.huawei.com", "华为通信"},
		{"ZTE", "https://www.zte.com.cn", "中兴通讯"},
		{"Ericsson", "https://www.ericsson.com", "爱立信"},
		{"Nokia Networks", "https://www.nokia.com", "诺基亚通信"},
		{"Samsung Networks", "https://www.samsung.com/global/business/networks", "三星网络"},
		{"Qualcomm", "https://www.qualcomm.com", "高通芯片"},
		{"MediaTek", "https://www.mediatek.com", "联发科技"},
		{"Cisco", "https://www.cisco.com", "思科网络"},
		{"Juniper Networks", "https://www.juniper.net", "Juniper网络"},
		{"Arista Networks", "https://www.arista.com", "数据中心网络"},
		{"Ubiquiti", "https://www.ui.com", "网络设备"},
		{"TP-Link", "https://www.tp-link.com", "TP-Link网络"},
		{"Netgear", "https://www.netgear.com", "网件路由器"},
		{"ASUS Networking", "https://www.asus.com/networking", "华硕网络"},
		{"Linksys", "https://www.linksys.com", "Linksys网络"},
		{"MikroTik", "https://mikrotik.com", "网络设备"},
		{"Cloudflare", "https://www.cloudflare.com", "CDN与安全"},
		{"Akamai", "https://www.akamai.com", "CDN服务"},
		{"Fastly", "https://www.fastly.com", "边缘云平台"},
		{"Twilio", "https://www.twilio.com", "通信API"},
		{"Vonage", "https://www.vonage.com", "通信API服务"},
		{"Bandwidth", "https://www.bandwidth.com", "通信平台"},
		{"Plivo", "https://www.plivo.com", "通信API"},
		{"MessageBird", "https://messagebird.com", "全渠道通信"},
		{"Speedtest", "https://www.speedtest.net", "网速测试"},
		{"Fast.com", "https://fast.com", "Netflix网速测试"},
		{"OpenSignal", "https://www.opensignal.com", "移动网络测速"},
		{"测速网", "https://www.speedtest.cn", "中国网速测试"},
		{"GSMA", "https://www.gsma.com", "全球移动通信协会"},
		{"3GPP", "https://www.3gpp.org", "通信标准组织"},
		{"IETF", "https://www.ietf.org", "互联网工程任务组"},
		{"IEEE 802", "https://www.ieee802.org", "网络标准"},
	}
}

func mapNav() []S {
	return []S{
		{"Google Maps", "https://maps.google.com", "Google地图"},
		{"Apple Maps", "https://maps.apple.com", "Apple地图"},
		{"高德地图", "https://www.amap.com", "高德地图导航"},
		{"百度地图", "https://map.baidu.com", "百度地图"},
		{"腾讯地图", "https://map.qq.com", "腾讯地图"},
		{"搜狗地图", "https://map.sogou.com", "搜狗地图"},
		{"Bing Maps", "https://www.bing.com/maps", "必应地图"},
		{"Waze", "https://www.waze.com", "社交导航应用"},
		{"Here Maps", "https://www.here.com", "Here地图"},
		{"MapBox", "https://www.mapbox.com", "地图开发平台"},
		{"OpenStreetMap", "https://www.openstreetmap.org", "开源地图"},
		{"Leaflet", "https://leafletjs.com", "开源地图JS库"},
		{"Mapillary", "https://www.mapillary.com", "街景图片平台"},
		{"Google Earth", "https://earth.google.com", "Google地球"},
		{"NASA Worldview", "https://worldview.earthdata.nasa.gov", "NASA卫星视图"},
		{"Sentinel Hub", "https://apps.sentinel-hub.com", "卫星遥感数据"},
		{"Planet", "https://www.planet.com", "卫星影像公司"},
		{"Maxar", "https://www.maxar.com", "卫星影像与分析"},
		{"TomTom", "https://www.tomtom.com", "导航地图服务"},
		{"Garmin", "https://www.garmin.com", "GPS导航设备"},
		{"凯立德", "https://www.kldzn.com", "凯立德导航"},
		{"四维图新", "https://www.navinfo.com", "导航地图数据"},
		{"What3words", "https://what3words.com", "三词定位系统"},
		{"GeoGebra Maps", "https://www.geogebra.org/m", "数学地理工具"},
		{"ArcGIS Online", "https://www.arcgis.com", "GIS云平台"},
		{"QGIS", "https://qgis.org", "开源GIS软件"},
		{"Carto", "https://carto.com", "位置智能平台"},
		{"Felt", "https://felt.com", "协作地图制作"},
		{"Strava Heatmap", "https://www.strava.com/heatmap", "运动热力图"},
		{"Komoot", "https://www.komoot.com", "户外路线规划"},
		{"AllTrails", "https://www.alltrails.com", "徒步路线"},
		{"Gaia GPS", "https://www.gaiagps.com", "户外GPS"},
		{"CalTopo", "https://caltopo.com", "地形图工具"},
		{"Windy", "https://www.windy.com", "风力天气地图"},
		{"MarineTraffic", "https://www.marinetraffic.com", "船舶追踪"},
		{"FlightRadar24", "https://www.flightradar24.com", "航班追踪"},
		{"Overpass Turbo", "https://overpass-turbo.eu", "OSM数据查询"},
		{"Geofabrik", "https://download.geofabrik.de", "OSM数据下载"},
		{"Natural Earth", "https://www.naturalearthdata.com", "公共地理数据"},
		{"USGS", "https://www.usgs.gov", "美国地质调查局"},
		{"Snazzy Maps", "https://snazzymaps.com", "Google地图样式"},
		{"MapTiler", "https://www.maptiler.com", "地图瓦片服务"},
		{"Thunderforest", "https://www.thunderforest.com", "地图瓦片"},
		{"Stamen Maps", "https://maps.stamen.com", "艺术风格地图"},
		{"Mapzen", "https://www.mapzen.com", "开放地图工具"},
		{"OsmAnd", "https://osmand.net", "离线地图应用"},
		{"Maps.me", "https://maps.me", "离线地图"},
		{"CityMapper", "https://citymapper.com", "城市交通导航"},
		{"Moovit", "https://moovitapp.com", "公共交通导航"},
		{"Transit", "https://transitapp.com", "公交地铁导航"},
		{"Rome2Rio", "https://www.rome2rio.com", "全球交通路线"},
		{"Google Street View", "https://www.google.com/streetview", "街景浏览"},
	}
}

func weather() []S {
	return []S{
		{"中国天气网", "https://www.weather.com.cn", "中国气象局天气"},
		{"墨迹天气", "https://www.moji.com", "墨迹天气预报"},
		{"彩云天气", "https://www.caiyunapp.com", "AI天气预报"},
		{"2345天气", "https://tianqi.2345.com", "天气预报查询"},
		{"天气通", "https://www.tqt.com", "天气预报应用"},
		{"和风天气", "https://www.qweather.com", "天气API服务"},
		{"Weather.com", "https://weather.com", "The Weather Channel"},
		{"AccuWeather", "https://www.accuweather.com", "精准天气预报"},
		{"Weather Underground", "https://www.wunderground.com", "个人气象站"},
		{"Dark Sky", "https://darksky.net", "分钟级天气"},
		{"OpenWeather", "https://openweathermap.org", "天气数据API"},
		{"WeatherAPI", "https://www.weatherapi.com", "天气API服务"},
		{"Windy", "https://www.windy.com", "风力天气可视化"},
		{"Ventusky", "https://www.ventusky.com", "天气地图可视化"},
		{"Meteoblue", "https://www.meteoblue.com", "天气预报"},
		{"Yr.no", "https://www.yr.no", "挪威气象服务"},
		{"Met Office", "https://www.metoffice.gov.uk", "英国气象局"},
		{"DWD", "https://www.dwd.de", "德国气象局"},
		{"Météo-France", "https://www.meteofrance.com", "法国气象局"},
		{"JMA", "https://www.jma.go.jp", "日本气象厅"},
		{"BoM", "https://www.bom.gov.au", "澳洲气象局"},
		{"Environment Canada Weather", "https://weather.gc.ca", "加拿大天气"},
		{"NOAA", "https://www.noaa.gov", "美国海洋大气局"},
		{"NWS", "https://www.weather.gov", "美国国家气象局"},
		{"ECMWF", "https://www.ecmwf.int", "欧洲中期天气预报"},
		{"Zoom Earth", "https://zoom.earth", "实时卫星天气"},
		{"Earth Nullschool", "https://earth.nullschool.net", "全球风流可视化"},
		{"AQI", "https://www.aqi.cn", "中国空气质量"},
		{"AQICN", "https://aqicn.org", "全球空气质量"},
		{"IQAir", "https://www.iqair.com", "空气质量地图"},
		{"BreezoMeter", "https://www.breezometer.com", "空气质量API"},
		{"Pollen.com", "https://www.pollen.com", "花粉预报"},
		{"UV Index", "https://www.epa.gov/sunsafety/uv-index-1", "紫外线指数"},
		{"Sunrise-Sunset", "https://sunrise-sunset.org", "日出日落时间"},
		{"TimeAndDate Weather", "https://www.timeanddate.com/weather", "全球天气"},
		{"WeatherBug", "https://www.weatherbug.com", "天气预警"},
		{"Storm Radar", "https://www.weatherbug.com/radar", "雷达风暴追踪"},
		{"MyRadar", "https://myradar.com", "天气雷达应用"},
		{"Radarscope", "https://www.radarscope.app", "专业雷达"},
		{"Earthquake USGS", "https://earthquake.usgs.gov", "地震监测"},
		{"中国地震台网", "https://www.ceic.ac.cn", "中国地震信息"},
		{"Tsunami.gov", "https://www.tsunami.gov", "海啸预警"},
		{"GDACS", "https://www.gdacs.org", "全球灾害预警"},
		{"ReliefWeb", "https://reliefweb.int", "灾害与人道主义"},
		{"Climate Reanalyzer", "https://climatereanalyzer.org", "气候数据分析"},
		{"WorldClim", "https://www.worldclim.org", "全球气候数据"},
		{"Severe Weather Europe", "https://www.severe-weather.eu", "欧洲极端天气"},
		{"Tropical Tidbits", "https://www.tropicaltidbits.com", "热带气象"},
		{"SpaceWeather", "https://spaceweather.com", "太空天气"},
		{"SolarHam", "https://www.solarham.net", "太阳活动监测"},
		{"Lightning Maps", "https://www.lightningmaps.org", "实时闪电地图"},
		{"Blitzortung", "https://www.blitzortung.org", "闪电追踪网络"},
	}
}

func forum() []S {
	return []S{
		{"Reddit", "https://www.reddit.com", "全球最大论坛"},
		{"Quora", "https://www.quora.com", "问答社区"},
		{"Stack Overflow", "https://stackoverflow.com", "开发者问答"},
		{"Stack Exchange", "https://stackexchange.com", "专业问答网络"},
		{"Discord", "https://discord.com", "社区聊天平台"},
		{"Slack Communities", "https://slack.com/community", "Slack社区"},
		{"知乎", "https://www.zhihu.com", "中文问答社区"},
		{"百度贴吧", "https://tieba.baidu.com", "百度贴吧"},
		{"豆瓣", "https://www.douban.com", "豆瓣社区"},
		{"虎扑", "https://www.hupu.com", "体育社区论坛"},
		{"小红书", "https://www.xiaohongshu.com", "生活分享社区"},
		{"NGA玩家社区", "https://bbs.nga.cn", "游戏综合社区"},
		{"V2EX", "https://www.v2ex.com", "创意工作者社区"},
		{"吾爱破解", "https://www.52pojie.cn", "技术论坛"},
		{"什么值得买", "https://www.smzdm.com", "消费决策社区"},
		{"水木社区", "https://www.newsmth.net", "清华水木BBS"},
		{"天涯社区", "https://www.tianya.cn", "天涯论坛"},
		{"凯迪社区", "https://www.cat898.com", "凯迪网络"},
		{"1024社区", "https://www.1024sj.com", "技术社区"},
		{"Ruby China", "https://ruby-china.org", "Ruby中文社区"},
		{"CNode", "https://cnodejs.org", "Node.js中文社区"},
		{"SegmentFault", "https://segmentfault.com", "开发者社区"},
		{"CSDN", "https://www.csdn.net", "开发者社区"},
		{"掘金", "https://juejin.cn", "开发者社区"},
		{"InfoQ", "https://www.infoq.cn", "技术资讯社区"},
		{"开源中国", "https://www.oschina.net", "开源技术社区"},
		{"博客园", "https://www.cnblogs.com", "开发者博客"},
		{"4chan", "https://www.4chan.org", "匿名图片论坛"},
		{"8kun", "https://8kun.top", "匿名论坛"},
		{"Hacker News", "https://news.ycombinator.com", "黑客新闻"},
		{"Lobsters", "https://lobste.rs", "技术链接聚合"},
		{"Tildes", "https://tildes.net", "高质量讨论"},
		{"Lemmy", "https://join-lemmy.org", "去中心化论坛"},
		{"Mastodon", "https://joinmastodon.org", "去中心化社交"},
		{"Discourse", "https://www.discourse.org", "现代论坛软件"},
		{"phpBB", "https://www.phpbb.com", "开源论坛程序"},
		{"Flarum", "https://flarum.org", "现代论坛软件"},
		{"XenForo", "https://xenforo.com", "论坛软件"},
		{"vBulletin", "https://www.vbulletin.com", "论坛系统"},
		{"Invision Community", "https://invisioncommunity.com", "社区软件"},
		{"Something Awful", "https://www.somethingawful.com", "幽默社区"},
		{"MetaFilter", "https://www.metafilter.com", "社区博客"},
		{"Slashdot", "https://slashdot.org", "科技新闻社区"},
		{"Ars Technica Forums", "https://arstechnica.com/civis", "科技论坛"},
		{"ResetEra", "https://www.resetera.com", "游戏讨论论坛"},
		{"NeoGAF", "https://www.neogaf.com", "游戏论坛"},
		{"GameFAQs", "https://gamefaqs.gamespot.com", "游戏攻略论坛"},
		{"Tom's Hardware Forum", "https://forums.tomshardware.com", "硬件论坛"},
		{"XDA Forums", "https://xdaforums.com", "移动开发论坛"},
		{"MacRumors Forums", "https://forums.macrumors.com", "Apple论坛"},
		{"Ubuntu Forums", "https://ubuntuforums.org", "Ubuntu论坛"},
		{"Arch Linux Forums", "https://bbs.archlinux.org", "Arch论坛"},
	}
}
