package main

func gameDev() []S {
	return []S{
		{"Unity", "https://unity.com", "Unity游戏引擎"},
		{"Unreal Engine", "https://www.unrealengine.com", "虚幻引擎"},
		{"Godot", "https://godotengine.org", "开源游戏引擎"},
		{"GameMaker", "https://gamemaker.io", "2D游戏引擎"},
		{"RPG Maker", "https://www.rpgmakerweb.com", "RPG制作工具"},
		{"Construct", "https://www.construct.net", "无代码游戏制作"},
		{"Defold", "https://defold.com", "轻量游戏引擎"},
		{"Cocos", "https://www.cocos.com", "Cocos游戏引擎"},
		{"Phaser", "https://phaser.io", "HTML5游戏框架"},
		{"PixiJS", "https://pixijs.com", "2D WebGL渲染"},
		{"Three.js", "https://threejs.org", "3D Web库"},
		{"Babylon.js", "https://www.babylonjs.com", "3D游戏引擎"},
		{"PlayCanvas", "https://playcanvas.com", "Web 3D引擎"},
		{"Roblox Studio", "https://www.roblox.com/create", "Roblox游戏创作"},
		{"Core", "https://www.coregames.com", "游戏创建平台"},
		{"LÖVE", "https://love2d.org", "Lua 2D游戏框架"},
		{"Monogame", "https://www.monogame.net", "C#游戏框架"},
		{"Raylib", "https://www.raylib.com", "C游戏编程库"},
		{"SDL", "https://www.libsdl.org", "多媒体开发库"},
		{"SFML", "https://www.sfml-dev.org", "多媒体库"},
		{"Bevy", "https://bevyengine.org", "Rust游戏引擎"},
		{"Amethyst", "https://amethyst.rs", "Rust游戏引擎"},
		{"Itch.io", "https://itch.io", "独立游戏平台"},
		{"Game Jolt", "https://gamejolt.com", "独立游戏社区"},
		{"Newgrounds", "https://www.newgrounds.com", "Flash游戏社区"},
		{"Gamasutra", "https://www.gamedeveloper.com", "游戏开发者资讯"},
		{"GDC Vault", "https://www.gdcvault.com", "游戏开发者大会"},
		{"GameDev.net", "https://www.gamedev.net", "游戏开发社区"},
		{"GameDev.tv", "https://www.gamedev.tv", "游戏开发课程"},
		{"Brackeys", "https://brackeys.com", "Unity教程"},
		{"Kenney", "https://kenney.nl", "免费游戏素材"},
		{"OpenGameArt", "https://opengameart.org", "开源游戏美术"},
		{"Mixamo", "https://www.mixamo.com", "3D角色动画"},
		{"Spine", "https://esotericsoftware.com", "2D骨骼动画"},
		{"Aseprite", "https://www.aseprite.org", "像素艺术工具"},
		{"Tiled", "https://www.mapeditor.org", "瓦片地图编辑"},
		{"LDtk", "https://ldtk.io", "关卡设计工具"},
		{"FMOD", "https://www.fmod.com", "游戏音频引擎"},
		{"Wwise", "https://www.audiokinetic.com/wwise", "交互式音频"},
		{"Photon", "https://www.photonengine.com", "多人游戏网络"},
		{"Mirror", "https://mirror-networking.com", "Unity网络库"},
		{"Nakama", "https://heroiclabs.com", "游戏服务器"},
		{"PlayFab", "https://playfab.com", "游戏后端服务"},
		{"GameAnalytics", "https://gameanalytics.com", "游戏分析"},
		{"Unity Analytics", "https://unity.com/products/analytics", "Unity分析"},
		{"IndieDB", "https://www.indiedb.com", "独立游戏数据库"},
		{"ModDB", "https://www.moddb.com", "游戏MOD社区"},
		{"Nexus Mods", "https://www.nexusmods.com", "游戏MOD下载"},
		{"CurseForge", "https://www.curseforge.com", "游戏MOD平台"},
		{"Steam Workshop", "https://steamcommunity.com/workshop", "Steam创意工坊"},
		{"IGDA", "https://igda.org", "国际游戏开发者协会"},
		{"游戏葡萄", "https://youxiputao.com", "游戏行业资讯"},
	}
}

func openSource() []S {
	return []S{
		{"GitHub", "https://github.com", "代码托管平台"},
		{"GitLab", "https://gitlab.com", "DevOps平台"},
		{"Bitbucket", "https://bitbucket.org", "Git代码托管"},
		{"Gitee", "https://gitee.com", "中国代码托管"},
		{"Codeberg", "https://codeberg.org", "非营利代码托管"},
		{"SourceForge", "https://sourceforge.net", "开源项目托管"},
		{"Launchpad", "https://launchpad.net", "Ubuntu代码托管"},
		{"Apache Foundation", "https://www.apache.org", "Apache基金会"},
		{"Linux Foundation", "https://www.linuxfoundation.org", "Linux基金会"},
		{"CNCF", "https://www.cncf.io", "云原生基金会"},
		{"Eclipse Foundation", "https://www.eclipse.org", "Eclipse基金会"},
		{"Free Software Foundation", "https://www.fsf.org", "自由软件基金会"},
		{"Open Source Initiative", "https://opensource.org", "开源倡议"},
		{"GitHub Trending", "https://github.com/trending", "GitHub热门项目"},
		{"GitHub Stars", "https://stars.github.com", "GitHub明星项目"},
		{"Awesome Lists", "https://github.com/sindresorhus/awesome", "资源精选列表"},
		{"HelloGitHub", "https://hellogithub.com", "中文开源推荐"},
		{"GitHubDaily", "https://github.com/GitHubDaily/GitHubDaily", "GitHub每日推荐"},
		{"Open Source Guides", "https://opensource.guide", "开源指南"},
		{"Choose a License", "https://choosealicense.com", "开源许可证选择"},
		{"SPDX", "https://spdx.dev", "软件包数据交换"},
		{"Fosstodon", "https://fosstodon.org", "开源社交"},
		{"FOSDEM", "https://fosdem.org", "欧洲开源大会"},
		{"All Things Open", "https://allthingsopen.org", "开源技术会议"},
		{"Open Collective", "https://opencollective.com", "开源资金管理"},
		{"GitHub Sponsors", "https://github.com/sponsors", "开源赞助"},
		{"Tidelift", "https://tidelift.com", "开源维护者收入"},
		{"Linux", "https://www.linux.org", "Linux操作系统"},
		{"Ubuntu", "https://ubuntu.com", "Ubuntu操作系统"},
		{"Fedora", "https://fedoraproject.org", "Fedora Linux"},
		{"Debian", "https://www.debian.org", "Debian操作系统"},
		{"Arch Linux", "https://archlinux.org", "Arch Linux"},
		{"NixOS", "https://nixos.org", "NixOS操作系统"},
		{"FreeBSD", "https://www.freebsd.org", "FreeBSD操作系统"},
		{"OpenBSD", "https://www.openbsd.org", "安全操作系统"},
		{"Alpine Linux", "https://www.alpinelinux.org", "轻量Linux"},
		{"DistroWatch", "https://distrowatch.com", "Linux发行版排名"},
		{"Homebrew", "https://brew.sh", "macOS包管理"},
		{"Chocolatey", "https://chocolatey.org", "Windows包管理"},
		{"Scoop", "https://scoop.sh", "Windows包管理"},
		{"Winget", "https://learn.microsoft.com/windows/package-manager", "Windows包管理"},
		{"npm", "https://www.npmjs.com", "Node.js包管理"},
		{"PyPI", "https://pypi.org", "Python包索引"},
		{"crates.io", "https://crates.io", "Rust包管理"},
		{"Maven Central", "https://search.maven.org", "Java依赖仓库"},
		{"NuGet", "https://www.nuget.org", ".NET包管理"},
		{"RubyGems", "https://rubygems.org", "Ruby包管理"},
		{"Packagist", "https://packagist.org", "PHP包管理"},
		{"pkg.go.dev", "https://pkg.go.dev", "Go包文档"},
		{"Flathub", "https://flathub.org", "Linux应用商店"},
		{"Snap Store", "https://snapcraft.io", "Ubuntu应用商店"},
		{"F-Droid", "https://f-droid.org", "Android开源应用"},
	}
}

func apiService() []S {
	return []S{
		{"RapidAPI", "https://rapidapi.com", "API市场"},
		{"Postman", "https://www.postman.com", "API开发平台"},
		{"Swagger", "https://swagger.io", "API设计文档"},
		{"OpenAPI", "https://www.openapis.org", "API规范标准"},
		{"Apigee", "https://cloud.google.com/apigee", "Google API管理"},
		{"Kong", "https://konghq.com", "API网关"},
		{"Tyk", "https://tyk.io", "开源API网关"},
		{"APISIX", "https://apisix.apache.org", "Apache API网关"},
		{"Gravitee", "https://www.gravitee.io", "API管理平台"},
		{"AWS API Gateway", "https://aws.amazon.com/api-gateway", "AWS API网关"},
		{"Twilio", "https://www.twilio.com", "通信API"},
		{"SendGrid", "https://sendgrid.com", "邮件API"},
		{"Stripe", "https://stripe.com", "支付API"},
		{"Plaid", "https://plaid.com", "金融API"},
		{"Mapbox", "https://www.mapbox.com", "地图API"},
		{"Algolia", "https://www.algolia.com", "搜索API"},
		{"Auth0", "https://auth0.com", "认证API"},
		{"Clerk", "https://clerk.com", "用户管理API"},
		{"Cloudinary", "https://cloudinary.com", "图片视频API"},
		{"Imgix", "https://imgix.com", "图片处理API"},
		{"Pusher", "https://pusher.com", "实时API"},
		{"Ably", "https://ably.com", "实时消息API"},
		{"Liveblocks", "https://liveblocks.io", "协作API"},
		{"OpenAI API", "https://platform.openai.com", "OpenAI API"},
		{"Anthropic API", "https://docs.anthropic.com", "Claude API"},
		{"Google AI API", "https://ai.google.dev", "Gemini API"},
		{"Replicate", "https://replicate.com", "AI模型API"},
		{"DeepL API", "https://www.deepl.com/pro-api", "翻译API"},
		{"Google Translate API", "https://cloud.google.com/translate", "翻译API"},
		{"Giphy API", "https://developers.giphy.com", "GIF API"},
		{"Unsplash API", "https://unsplash.com/developers", "图片API"},
		{"GitHub API", "https://docs.github.com/rest", "GitHub REST API"},
		{"Twitter API", "https://developer.twitter.com", "X/Twitter API"},
		{"Discord API", "https://discord.com/developers", "Discord API"},
		{"Slack API", "https://api.slack.com", "Slack API"},
		{"WhatsApp API", "https://business.whatsapp.com/products/platform-overview", "WhatsApp商业API"},
		{"WeChat API", "https://developers.weixin.qq.com", "微信开放平台"},
		{"YouTube API", "https://developers.google.com/youtube", "YouTube Data API"},
		{"Spotify API", "https://developer.spotify.com", "Spotify Web API"},
		{"NASA API", "https://api.nasa.gov", "NASA开放API"},
		{"公共API列表", "https://github.com/public-apis/public-apis", "公共API合集"},
		{"Any API", "https://any-api.com", "API文档搜索"},
		{"API List", "https://apilist.fun", "公共API列表"},
		{"MockAPI", "https://mockapi.io", "模拟API服务"},
		{"JSONPlaceholder", "https://jsonplaceholder.typicode.com", "测试REST API"},
		{"httpbin", "https://httpbin.org", "HTTP测试服务"},
		{"Reqres", "https://reqres.in", "测试API"},
		{"Apiary", "https://apiary.io", "API设计协作"},
		{"Stoplight", "https://stoplight.io", "API设计平台"},
		{"ReadMe", "https://readme.com", "API文档平台"},
		{"Mintlify", "https://mintlify.com", "文档即代码"},
		{"Redocly", "https://redocly.com", "API文档工具"},
	}
}

func marketing() []S {
	return []S{
		{"Google Ads", "https://ads.google.com", "Google广告平台"},
		{"Facebook Ads", "https://www.facebook.com/business/ads", "Meta广告"},
		{"Google Analytics", "https://analytics.google.com", "网站分析"},
		{"Google Search Console", "https://search.google.com/search-console", "搜索优化"},
		{"Google Tag Manager", "https://tagmanager.google.com", "标签管理"},
		{"HubSpot", "https://www.hubspot.com", "营销CRM平台"},
		{"Salesforce", "https://www.salesforce.com", "CRM平台"},
		{"Mailchimp", "https://mailchimp.com", "邮件营销"},
		{"Brevo", "https://www.brevo.com", "营销自动化"},
		{"ActiveCampaign", "https://www.activecampaign.com", "营销自动化"},
		{"SEMrush", "https://www.semrush.com", "SEO营销工具"},
		{"Ahrefs", "https://ahrefs.com", "SEO分析工具"},
		{"Moz", "https://moz.com", "SEO软件"},
		{"Ubersuggest", "https://neilpatel.com/ubersuggest", "关键词研究"},
		{"SimilarWeb", "https://www.similarweb.com", "网站流量分析"},
		{"Hotjar", "https://www.hotjar.com", "用户行为分析"},
		{"Heap", "https://heap.io", "数字分析"},
		{"Mixpanel", "https://mixpanel.com", "产品分析"},
		{"Amplitude", "https://amplitude.com", "产品分析"},
		{"Segment", "https://segment.com", "客户数据平台"},
		{"Optimizely", "https://www.optimizely.com", "A/B测试平台"},
		{"VWO", "https://vwo.com", "A/B测试"},
		{"Unbounce", "https://unbounce.com", "着陆页构建"},
		{"Leadpages", "https://www.leadpages.com", "着陆页创建"},
		{"Hootsuite", "https://www.hootsuite.com", "社交媒体管理"},
		{"Buffer", "https://buffer.com", "社交媒体发布"},
		{"Sprout Social", "https://sproutsocial.com", "社交媒体管理"},
		{"Later", "https://later.com", "社交媒体排程"},
		{"Canva", "https://www.canva.com", "设计营销素材"},
		{"Loom", "https://www.loom.com", "视频消息工具"},
		{"Vidyard", "https://www.vidyard.com", "视频营销"},
		{"Intercom", "https://www.intercom.com", "客户沟通平台"},
		{"Drift", "https://www.drift.com", "对话营销"},
		{"Zendesk", "https://www.zendesk.com", "客户服务平台"},
		{"Freshdesk", "https://www.freshdesk.com", "客服软件"},
		{"Crisp", "https://crisp.chat", "客户消息平台"},
		{"百度营销", "https://e.baidu.com", "百度推广"},
		{"巨量引擎", "https://www.oceanengine.com", "字节广告平台"},
		{"腾讯广告", "https://e.qq.com", "腾讯广告投放"},
		{"微博粉丝通", "https://tui.weibo.com", "微博营销"},
		{"知乎营销", "https://zhi.zhihu.com", "知乎效果广告"},
		{"小红书营销", "https://business.xiaohongshu.com", "小红书推广"},
		{"快手磁力引擎", "https://e.kuaishou.com", "快手广告"},
		{"新榜", "https://www.newrank.cn", "新媒体数据"},
		{"蝉妈妈", "https://www.chanmama.com", "抖音电商数据"},
		{"灰豚数据", "https://www.huitun.com", "直播电商数据"},
		{"飞瓜数据", "https://www.feigua.cn", "短视频数据"},
		{"西瓜数据", "https://data.xiguaji.com", "新媒体数据"},
		{"GrowingIO", "https://www.growingio.com", "增长分析"},
		{"神策数据", "https://www.sensorsdata.cn", "用户行为分析"},
		{"友盟", "https://www.umeng.com", "移动统计分析"},
		{"TalkingData", "https://www.talkingdata.com", "数据智能"},
	}
}

func freelance() []S {
	return []S{
		{"Upwork", "https://www.upwork.com", "自由职业平台"},
		{"Fiverr", "https://www.fiverr.com", "技能服务市场"},
		{"Freelancer", "https://www.freelancer.com", "自由职业招标"},
		{"Toptal", "https://www.toptal.com", "顶尖自由职业者"},
		{"99designs", "https://99designs.com", "设计外包"},
		{"PeoplePerHour", "https://www.peopleperhour.com", "自由职业平台"},
		{"Guru", "https://www.guru.com", "自由职业交易"},
		{"Contra", "https://contra.com", "独立工作者平台"},
		{"Malt", "https://www.malt.com", "欧洲自由职业"},
		{"YunoJuno", "https://www.yunojuno.com", "英国自由职业"},
		{"Reedsy", "https://reedsy.com", "出版自由职业"},
		{"Catalant", "https://www.catalant.com", "专业咨询市场"},
		{"Expert360", "https://expert360.com", "管理咨询"},
		{"A.Team", "https://www.a.team", "团队组建平台"},
		{"Braintrust", "https://www.usebraintrust.com", "去中心化人才"},
		{"Arc.dev", "https://arc.dev", "远程开发者"},
		{"Turing", "https://www.turing.com", "远程开发者配对"},
		{"Andela", "https://www.andela.com", "全球技术人才"},
		{"Lemon.io", "https://lemon.io", "审核开发者"},
		{"Gun.io", "https://gun.io", "精英自由开发者"},
		{"猪八戒网", "https://www.zbj.com", "中国外包平台"},
		{"一品威客", "https://www.epwk.com", "创意设计外包"},
		{"程序员客栈", "https://www.proginn.com", "开发者接单"},
		{"电鸭社区", "https://eleduck.com", "远程工作社区"},
		{"实现网", "https://shixian.com", "技术外包"},
		{"开源众包", "https://zb.oschina.net", "开源中国众包"},
		{"码市", "https://codemart.com", "软件众包"},
		{"Notion", "https://www.notion.so", "项目管理"},
		{"Trello", "https://trello.com", "看板管理"},
		{"Asana", "https://asana.com", "项目管理工具"},
		{"Monday.com", "https://monday.com", "工作管理平台"},
		{"ClickUp", "https://clickup.com", "生产力平台"},
		{"Linear", "https://linear.app", "项目管理工具"},
		{"Basecamp", "https://basecamp.com", "项目管理"},
		{"Toggl", "https://toggl.com", "时间追踪"},
		{"Harvest", "https://www.getharvest.com", "时间追踪计费"},
		{"Clockify", "https://clockify.me", "免费时间追踪"},
		{"FreshBooks", "https://www.freshbooks.com", "发票记账"},
		{"Wave", "https://www.waveapps.com", "免费发票记账"},
		{"Invoice Ninja", "https://invoiceninja.com", "开源发票"},
		{"Bonsai", "https://www.hellobonsai.com", "自由职业管理"},
		{"HoneyBook", "https://www.honeybook.com", "客户管理"},
		{"Dubsado", "https://www.dubsado.com", "业务管理"},
		{"AND.CO", "https://www.and.co", "自由职业工具"},
		{"Calendly", "https://calendly.com", "日程预约"},
		{"Cal.com", "https://cal.com", "开源日程预约"},
		{"Doodle", "https://doodle.com", "会议时间协调"},
		{"Zoom", "https://zoom.us", "视频会议"},
		{"Google Meet", "https://meet.google.com", "Google视频会议"},
		{"Loom", "https://www.loom.com", "异步视频消息"},
		{"Miro", "https://miro.com", "在线白板协作"},
		{"FigJam", "https://www.figma.com/figjam", "Figma白板"},
	}
}

func threeDAR() []S {
	return []S{
		{"Blender", "https://www.blender.org", "开源3D创作"},
		{"SketchUp", "https://www.sketchup.com", "3D建模软件"},
		{"AutoCAD", "https://www.autodesk.com/products/autocad", "CAD设计"},
		{"3ds Max", "https://www.autodesk.com/products/3ds-max", "3D动画建模"},
		{"Maya", "https://www.autodesk.com/products/maya", "3D动画"},
		{"Cinema 4D", "https://www.maxon.net/cinema-4d", "3D动画设计"},
		{"ZBrush", "https://www.maxon.net/zbrush", "数字雕刻"},
		{"Houdini", "https://www.sidefx.com", "程序化3D"},
		{"Substance 3D", "https://www.adobe.com/products/substance3d.html", "3D材质"},
		{"Rhino", "https://www.rhino3d.com", "工业设计建模"},
		{"SolidWorks", "https://www.solidworks.com", "机械CAD"},
		{"Fusion 360", "https://www.autodesk.com/products/fusion-360", "云端CAD"},
		{"FreeCAD", "https://www.freecad.org", "开源CAD"},
		{"OpenSCAD", "https://openscad.org", "程序化CAD"},
		{"Tinkercad", "https://www.tinkercad.com", "在线3D设计"},
		{"Sketchfab", "https://sketchfab.com", "3D模型分享"},
		{"Turbosquid", "https://www.turbosquid.com", "3D模型市场"},
		{"CGTrader", "https://www.cgtrader.com", "3D模型交易"},
		{"Free3D", "https://free3d.com", "免费3D模型"},
		{"Poly Haven", "https://polyhaven.com", "免费3D资产"},
		{"AmbientCG", "https://ambientcg.com", "免费PBR材质"},
		{"Quixel Megascans", "https://quixel.com/megascans", "扫描3D资产"},
		{"Mixamo", "https://www.mixamo.com", "3D角色动画"},
		{"Ready Player Me", "https://readyplayer.me", "3D虚拟形象"},
		{"ARKit", "https://developer.apple.com/augmented-reality", "Apple AR开发"},
		{"ARCore", "https://developers.google.com/ar", "Google AR开发"},
		{"Vuforia", "https://developer.vuforia.com", "AR SDK"},
		{"Niantic Lightship", "https://lightship.dev", "AR开发平台"},
		{"8th Wall", "https://www.8thwall.com", "Web AR平台"},
		{"Spark AR", "https://spark.meta.com", "Meta AR创作"},
		{"Snap Lens Studio", "https://ar.snap.com/lens-studio", "Snap AR"},
		{"WebXR", "https://immersiveweb.dev", "Web XR标准"},
		{"A-Frame", "https://aframe.io", "Web VR框架"},
		{"Meta Quest", "https://www.meta.com/quest", "Meta VR头显"},
		{"Apple Vision Pro", "https://developer.apple.com/visionos", "Apple空间计算"},
		{"Varjo", "https://varjo.com", "企业级XR"},
		{"Nvidia Omniverse", "https://www.nvidia.com/omniverse", "3D协作平台"},
		{"USD", "https://openusd.org", "通用场景描述"},
		{"glTF", "https://www.khronos.org/gltf", "3D传输格式"},
		{"Spline", "https://spline.design", "Web 3D设计"},
		{"Vectary", "https://www.vectary.com", "在线3D设计"},
		{"Womp", "https://womp.com", "3D设计工具"},
		{"Luma AI", "https://lumalabs.ai", "AI 3D重建"},
		{"Kaedim", "https://www.kaedim3d.com", "AI 3D生成"},
		{"Meshy", "https://www.meshy.ai", "AI 3D模型生成"},
		{"Point-E", "https://github.com/openai/point-e", "AI 3D点云"},
		{"Shap-E", "https://github.com/openai/shap-e", "AI 3D生成"},
		{"3D Printing Industry", "https://3dprintingindustry.com", "3D打印资讯"},
		{"Thingiverse", "https://www.thingiverse.com", "3D打印模型"},
		{"Printables", "https://www.printables.com", "3D打印社区"},
		{"Cults 3D", "https://cults3d.com", "3D打印模型市场"},
		{"MyMiniFactory", "https://www.myminifactory.com", "3D打印模型"},
	}
}

func noCode() []S {
	return []S{
		{"Bubble", "https://bubble.io", "无代码Web应用"},
		{"Webflow", "https://webflow.com", "可视化Web设计"},
		{"Airtable", "https://www.airtable.com", "智能数据表格"},
		{"Notion", "https://www.notion.so", "知识管理平台"},
		{"Zapier", "https://zapier.com", "自动化连接器"},
		{"Make", "https://www.make.com", "可视化自动化"},
		{"n8n", "https://n8n.io", "开源自动化"},
		{"IFTTT", "https://ifttt.com", "应用连接自动化"},
		{"Retool", "https://retool.com", "内部工具构建"},
		{"Appsmith", "https://www.appsmith.com", "开源内部工具"},
		{"Tooljet", "https://www.tooljet.com", "低代码内部工具"},
		{"Budibase", "https://budibase.com", "开源低代码"},
		{"Glide", "https://www.glideapps.com", "无代码移动应用"},
		{"Adalo", "https://www.adalo.com", "无代码App构建"},
		{"Thunkable", "https://thunkable.com", "可视化App开发"},
		{"FlutterFlow", "https://flutterflow.io", "可视化Flutter"},
		{"Bravo Studio", "https://www.bravostudio.app", "设计转App"},
		{"Softr", "https://www.softr.io", "Airtable转Web应用"},
		{"Stacker", "https://www.stackerhq.com", "数据库转应用"},
		{"Internal.io", "https://www.internal.io", "内部工具平台"},
		{"Coda", "https://coda.io", "文档与应用混合"},
		{"Fibery", "https://fibery.io", "工作管理平台"},
		{"Tally", "https://tally.so", "简洁表单构建"},
		{"Typeform", "https://www.typeform.com", "交互式表单"},
		{"Jotform", "https://www.jotform.com", "在线表单"},
		{"Google Forms", "https://docs.google.com/forms", "Google表单"},
		{"SurveyMonkey", "https://www.surveymonkey.com", "在线问卷"},
		{"Carrd", "https://carrd.co", "简洁落地页"},
		{"Typedream", "https://typedream.com", "无代码建站"},
		{"Dorik", "https://dorik.com", "网站构建器"},
		{"Framer", "https://www.framer.com", "设计驱动建站"},
		{"Wix", "https://www.wix.com", "可视化建站"},
		{"Squarespace", "https://www.squarespace.com", "精美建站"},
		{"Shopify", "https://www.shopify.com", "电商建站"},
		{"Gumroad", "https://gumroad.com", "数字产品销售"},
		{"Lemonsqueezy", "https://www.lemonsqueezy.com", "数字产品支付"},
		{"Memberstack", "https://www.memberstack.com", "会员系统"},
		{"Outseta", "https://www.outseta.com", "SaaS启动套件"},
		{"Bildr", "https://www.bildr.com", "高级无代码"},
		{"Xano", "https://www.xano.com", "无代码后端"},
		{"Directus", "https://directus.io", "开源数据平台"},
		{"Strapi", "https://strapi.io", "开源CMS"},
		{"Contentful", "https://www.contentful.com", "Headless CMS"},
		{"Sanity", "https://www.sanity.io", "结构化内容"},
		{"Prismic", "https://prismic.io", "Headless CMS"},
		{"Payload CMS", "https://payloadcms.com", "代码优先CMS"},
		{"WordPress", "https://wordpress.org", "开源CMS"},
		{"Ghost", "https://ghost.org", "发布平台"},
		{"简道云", "https://www.jiandaoyun.com", "零代码应用"},
		{"明道云", "https://www.mingdao.com", "企业低代码"},
		{"宜搭", "https://www.aliwork.com", "钉钉低代码"},
		{"微搭", "https://cloud.tencent.com/product/weda", "腾讯低代码"},
	}
}

func lifestyle() []S {
	return []S{
		{"美团", "https://www.meituan.com", "生活服务平台"},
		{"大众点评", "https://www.dianping.com", "生活服务点评"},
		{"58同城", "https://www.58.com", "生活信息服务"},
		{"闲鱼", "https://www.goofish.com", "二手交易平台"},
		{"转转", "https://www.zhuanzhuan.com", "二手交易"},
		{"多抓鱼", "https://www.duozhuayu.com", "二手书循环"},
		{"小红书", "https://www.xiaohongshu.com", "生活分享社区"},
		{"什么值得买", "https://www.smzdm.com", "消费决策"},
		{"返利网", "https://www.fanli.com", "购物返利"},
		{"慧慧网", "https://www.huihui.cn", "比价工具"},
		{"中国移动", "https://www.10086.cn", "手机话费充值"},
		{"国家电网", "https://www.95598.cn", "电费缴纳"},
		{"水务集团", "https://www.watergroup.cn", "水费缴纳"},
		{"燃气缴费", "https://www.cnoocgas.com", "燃气费缴纳"},
		{"交管12123", "https://gab.122.gov.cn", "交通违章处理"},
		{"铁路12306", "https://www.12306.cn", "火车票预订"},
		{"高德打车", "https://www.amap.com/taxi", "打车服务"},
		{"滴滴出行", "https://www.didiglobal.com", "网约车出行"},
		{"哈啰", "https://www.hellobike.com", "共享单车"},
		{"丰巢", "https://www.fcbox.com", "智能快递柜"},
		{"菜鸟驿站", "https://cainiao.com/station", "快递代收"},
		{"Groupon", "https://www.groupon.com", "团购折扣"},
		{"Yelp", "https://www.yelp.com", "商户点评"},
		{"Nextdoor", "https://nextdoor.com", "社区邻居"},
		{"TaskRabbit", "https://www.taskrabbit.com", "生活服务任务"},
		{"Thumbtack", "https://www.thumbtack.com", "本地服务"},
		{"Angi", "https://www.angi.com", "家居服务"},
		{"HomeAdvisor", "https://www.homeadvisor.com", "家居服务匹配"},
		{"Handy", "https://www.handy.com", "家政清洁"},
		{"Care.com", "https://www.care.com", "保姆护工"},
		{"Rover", "https://www.rover.com", "宠物照看"},
		{"ClassPass", "https://classpass.com", "健身课程订阅"},
		{"Mindbody", "https://www.mindbodyonline.com", "健身预约"},
		{"Eventbrite", "https://www.eventbrite.com", "活动售票"},
		{"Meetup", "https://www.meetup.com", "活动社交"},
		{"活动行", "https://www.huodongxing.com", "活动报名"},
		{"互动吧", "https://www.hdb.com", "活动管理"},
		{"豆瓣同城", "https://www.douban.com/location", "同城活动"},
		{"百度糯米", "https://nuomi.baidu.com", "百度团购"},
		{"口碑", "https://www.koubei.com", "阿里本地生活"},
		{"拼多多", "https://www.pinduoduo.com", "拼团电商"},
		{"唯品会", "https://www.vip.com", "品牌折扣"},
		{"当当网", "https://www.dangdang.com", "图书电商"},
		{"苏宁易购", "https://www.suning.com", "电器电商"},
		{"国美", "https://www.gome.com.cn", "家电零售"},
		{"名创优品", "https://www.miniso.com", "生活百货"},
		{"无印良品", "https://www.muji.com", "生活杂货"},
		{"网易严选", "https://you.163.com", "品质电商"},
		{"小米有品", "https://www.xiaomiyoupin.com", "小米精品电商"},
		{"京东到家", "https://www.jddj.com", "即时零售"},
		{"叮咚买菜", "https://www.100.me", "生鲜到家"},
		{"盒马", "https://www.freshhema.com", "新零售超市"},
	}
}

func reading() []S {
	return []S{
		{"Kindle", "https://www.amazon.com/kindle", "Kindle电子书"},
		{"Apple Books", "https://www.apple.com/apple-books", "Apple电子书"},
		{"Google Books", "https://books.google.com", "Google图书"},
		{"Goodreads", "https://www.goodreads.com", "读书社交社区"},
		{"Bookish", "https://www.bookish.com", "图书推荐"},
		{"StoryGraph", "https://www.thestorygraph.com", "读书追踪"},
		{"LibraryThing", "https://www.librarything.com", "图书分类社交"},
		{"Audible", "https://www.audible.com", "有声书平台"},
		{"Scribd", "https://www.scribd.com", "电子书订阅"},
		{"Libby", "https://www.overdrive.com/apps/libby", "图书馆借阅"},
		{"Kobo", "https://www.kobo.com", "Kobo电子书"},
		{"Barnes & Noble", "https://www.barnesandnoble.com", "美国书店"},
		{"Project Gutenberg", "https://www.gutenberg.org", "免费古典电子书"},
		{"Open Library", "https://openlibrary.org", "开放图书馆"},
		{"Internet Archive Books", "https://archive.org/details/texts", "互联网档案图书"},
		{"Standard Ebooks", "https://standardebooks.org", "精排公版电子书"},
		{"ManyBooks", "https://manybooks.net", "免费电子书"},
		{"Feedbooks", "https://www.feedbooks.com", "电子书商店"},
		{"Smashwords", "https://www.smashwords.com", "独立电子书"},
		{"豆瓣读书", "https://book.douban.com", "豆瓣图书评分"},
		{"微信读书", "https://weread.qq.com", "微信读书"},
		{"得到", "https://www.dedao.cn", "得到电子书"},
		{"掌阅", "https://www.zhangyue.com", "掌阅阅读"},
		{"QQ阅读", "https://book.qq.com", "QQ阅读"},
		{"京东读书", "https://e.jd.com", "京东电子书"},
		{"当当电子书", "https://e.dangdang.com", "当当电子书"},
		{"网易蜗牛读书", "https://du.163.com", "网易阅读"},
		{"多看阅读", "https://www.duokan.com", "小米阅读"},
		{"起点中文网", "https://www.qidian.com", "网络小说"},
		{"晋江文学城", "https://www.jjwxc.net", "女性文学"},
		{"纵横中文网", "https://www.zongheng.com", "网络文学"},
		{"番茄小说", "https://fanqienovel.com", "免费小说"},
		{"七猫小说", "https://www.qimao.com", "免费阅读"},
		{"书旗小说", "https://www.shuqi.com", "小说阅读"},
		{"飞卢小说", "https://www.faloo.com", "飞卢文学"},
		{"刺猬猫", "https://www.ciweimao.com", "二次元文学"},
		{"喜马拉雅", "https://www.ximalaya.com", "有声读物"},
		{"懒人听书", "https://www.lrts.me", "有声小说"},
		{"蜻蜓FM", "https://www.qingting.fm", "有声内容"},
		{"Medium", "https://medium.com", "英文阅读"},
		{"Pocket", "https://getpocket.com", "稍后阅读"},
		{"Instapaper", "https://www.instapaper.com", "文章收藏"},
		{"Raindrop.io", "https://raindrop.io", "书签管理"},
		{"Omnivore", "https://omnivore.app", "开源稍后读"},
		{"Readwise", "https://readwise.io", "阅读笔记回顾"},
		{"Feedly", "https://feedly.com", "RSS阅读器"},
		{"Inoreader", "https://www.inoreader.com", "RSS阅读"},
		{"NewsBlur", "https://newsblur.com", "RSS新闻阅读"},
		{"Miniflux", "https://miniflux.app", "极简RSS阅读"},
		{"FreshRSS", "https://freshrss.org", "开源RSS阅读"},
		{"NetNewsWire", "https://netnewswire.com", "macOS RSS"},
		{"Calibre", "https://calibre-ebook.com", "电子书管理"},
	}
}

func gaming() []S {
	return []S{
		{"Steam", "https://store.steampowered.com", "PC游戏平台"},
		{"Epic Games Store", "https://store.epicgames.com", "Epic游戏商店"},
		{"GOG", "https://www.gog.com", "DRM-Free游戏"},
		{"Xbox", "https://www.xbox.com", "微软游戏"},
		{"PlayStation", "https://www.playstation.com", "索尼游戏"},
		{"Nintendo", "https://www.nintendo.com", "任天堂"},
		{"EA Play", "https://www.ea.com/ea-play", "EA游戏订阅"},
		{"Ubisoft Store", "https://store.ubi.com", "育碧游戏"},
		{"Battle.net", "https://www.blizzard.com", "暴雪游戏"},
		{"Riot Games", "https://www.riotgames.com", "拳头游戏"},
		{"Roblox", "https://www.roblox.com", "Roblox游戏平台"},
		{"Minecraft", "https://www.minecraft.net", "我的世界"},
		{"Fortnite", "https://www.fortnite.com", "堡垒之夜"},
		{"League of Legends", "https://www.leagueoflegends.com", "英雄联盟"},
		{"Valorant", "https://playvalorant.com", "Valorant射击"},
		{"Genshin Impact", "https://genshin.hoyoverse.com", "原神"},
		{"Honkai Star Rail", "https://hsr.hoyoverse.com", "崩坏：星穹铁道"},
		{"Apex Legends", "https://www.ea.com/games/apex-legends", "Apex英雄"},
		{"DOTA 2", "https://www.dota2.com", "DOTA 2"},
		{"Counter-Strike", "https://www.counter-strike.net", "CS2反恐精英"},
		{"Twitch", "https://www.twitch.tv", "游戏直播平台"},
		{"YouTube Gaming", "https://www.youtube.com/gaming", "YouTube游戏"},
		{"斗鱼", "https://www.douyu.com", "游戏直播"},
		{"虎牙", "https://www.huya.com", "游戏直播"},
		{"Bilibili游戏", "https://game.bilibili.com", "B站游戏"},
		{"TapTap", "https://www.taptap.com", "游戏社区平台"},
		{"好游快爆", "https://www.3839.com", "手游社区"},
		{"4399", "https://www.4399.com", "小游戏平台"},
		{"网易游戏", "https://game.163.com", "网易游戏"},
		{"腾讯游戏", "https://game.qq.com", "腾讯游戏"},
		{"米哈游", "https://www.mihoyo.com", "米哈游官网"},
		{"IGN", "https://www.ign.com", "游戏评测媒体"},
		{"GameSpot", "https://www.gamespot.com", "游戏新闻评测"},
		{"Kotaku", "https://kotaku.com", "游戏文化"},
		{"Polygon", "https://www.polygon.com", "游戏新闻"},
		{"PC Gamer", "https://www.pcgamer.com", "PC游戏杂志"},
		{"Rock Paper Shotgun", "https://www.rockpapershotgun.com", "PC游戏"},
		{"Eurogamer", "https://www.eurogamer.net", "欧洲游戏媒体"},
		{"Destructoid", "https://www.destructoid.com", "游戏新闻"},
		{"GiantBomb", "https://www.giantbomb.com", "游戏视频社区"},
		{"Metacritic", "https://www.metacritic.com", "游戏评分聚合"},
		{"OpenCritic", "https://opencritic.com", "游戏评分"},
		{"HowLongToBeat", "https://howlongtobeat.com", "游戏时长查询"},
		{"ProtonDB", "https://www.protondb.com", "Linux游戏兼容"},
		{"PCSX2", "https://pcsx2.net", "PS2模拟器"},
		{"RetroArch", "https://www.retroarch.com", "复古游戏模拟"},
		{"Steam Deck", "https://www.steamdeck.com", "Steam掌机"},
		{"Xbox Game Pass", "https://www.xbox.com/xbox-game-pass", "Xbox游戏订阅"},
		{"PS Plus", "https://www.playstation.com/ps-plus", "PS游戏订阅"},
		{"Nintendo eShop", "https://www.nintendo.com/store", "任天堂商店"},
		{"Humble Bundle", "https://www.humblebundle.com", "游戏慈善包"},
		{"Fanatical", "https://www.fanatical.com", "游戏折扣"},
	}
}
