package main

func video() []S {
	return []S{
		{"YouTube", "https://www.youtube.com", "全球最大的视频分享网站"},
		{"Netflix", "https://www.netflix.com", "全球流媒体影视平台"},
		{"TikTok", "https://www.tiktok.com", "全球短视频平台"},
		{"Disney+", "https://www.disneyplus.com", "迪士尼流媒体服务"},
		{"Prime Video", "https://www.primevideo.com", "亚马逊视频流媒体"},
		{"Vimeo", "https://vimeo.com", "高质量视频托管平台"},
		{"HBO Max", "https://www.max.com", "HBO 流媒体服务"},
		{"Hulu", "https://www.hulu.com", "美国流媒体平台"},
		{"Peacock", "https://www.peacocktv.com", "NBC 环球流媒体"},
		{"Paramount+", "https://www.paramountplus.com", "派拉蒙流媒体"},
		{"Crunchyroll", "https://www.crunchyroll.com", "全球最大动漫流媒体"},
		{"Dailymotion", "https://www.dailymotion.com", "法国视频分享平台"},
		{"Rumble", "https://rumble.com", "自由言论视频平台"},
		{"Odysee", "https://odysee.com", "去中心化视频平台"},
		{"Tubi", "https://tubitv.com", "免费电影和电视流媒体"},
		{"Pluto TV", "https://pluto.tv", "免费电视流媒体"},
		{"Plex", "https://www.plex.tv", "个人媒体服务器与流媒体"},
		{"Apple TV+", "https://tv.apple.com", "Apple 原创节目与电影"},
		{"CuriosityStream", "https://curiositystream.com", "纪录片流媒体服务"},
		{"BritBox", "https://www.britbox.com", "英国电视流媒体"},
		{"Mubi", "https://mubi.com", "精选艺术电影流媒体"},
		{"Kanopy", "https://www.kanopy.com", "图书馆免费流媒体"},
		{"Criterion Channel", "https://www.criterionchannel.com", "经典艺术电影"},
		{"Bilibili", "https://www.bilibili.com", "哔哩哔哩弹幕视频网"},
		{"腾讯视频", "https://v.qq.com", "腾讯视频在线观看"},
		{"优酷", "https://www.youku.com", "优酷视频平台"},
		{"爱奇艺", "https://www.iqiyi.com", "爱奇艺在线视频"},
		{"芒果TV", "https://www.mgtv.com", "湖南卫视在线视频"},
		{"搜狐视频", "https://tv.sohu.com", "搜狐视频"},
		{"西瓜视频", "https://www.ixigua.com", "字节跳动视频平台"},
		{"好看视频", "https://haokan.baidu.com", "百度短视频平台"},
		{"咪咕视频", "https://www.miguvideo.com", "中国移动视频平台"},
		{"抖音", "https://www.douyin.com", "抖音短视频"},
		{"快手", "https://www.kuaishou.com", "快手短视频平台"},
		{"小红书", "https://www.xiaohongshu.com", "生活分享社区"},
		{"AcFun", "https://www.acfun.cn", "AcFun弹幕视频网"},
		{"梨视频", "https://www.pearvideo.com", "梨视频资讯平台"},
		{"微视", "https://weishi.qq.com", "腾讯短视频平台"},
		{"Niconico", "https://www.nicovideo.jp", "日本弹幕视频平台"},
		{"AbemaTV", "https://abema.tv", "日本网络电视"},
		{"TVer", "https://tver.jp", "日本电视回放"},
		{"Naver TV", "https://tv.naver.com", "韩国 Naver 视频"},
		{"Wavve", "https://www.wavve.com", "韩国视频流媒体"},
		{"TVING", "https://www.tving.com", "韩国 CJ ENM 流媒体"},
		{"Hotstar", "https://www.hotstar.com", "Indian streaming platform"},
		{"ZEE5", "https://www.zee5.com", "Indian OTT platform"},
		{"JioCinema", "https://www.jiocinema.com", "Jio streaming"},
		{"SonyLIV", "https://www.sonyliv.com", "Sony India streaming"},
		{"iQIYI International", "https://www.iq.com", "爱奇艺国际版"},
		{"Viki", "https://www.viki.com", "亚洲影视平台"},
		{"WeTV", "https://wetv.vip", "腾讯海外流媒体"},
		{"Shahid", "https://shahid.mbc.net", "阿拉伯流媒体"},
		{"Stan", "https://www.stan.com.au", "澳大利亚流媒体"},
		{"Canal+", "https://www.canalplus.com", "法国流媒体平台"},
		{"Viaplay", "https://viaplay.com", "北欧流媒体"},
		{"Vidio", "https://www.vidio.com", "印尼流媒体"},
		{"Catchplay+", "https://www.catchplay.com", "台湾电影流媒体"},
		{"Rakuten TV", "https://www.rakuten.tv", "乐天视频点播"},
		{"MeWatch", "https://www.mewatch.sg", "新加坡流媒体"},
		{"Roku Channel", "https://therokuchannel.roku.com", "Roku 免费流媒体"},
		{"Vudu", "https://www.vudu.com", "点播电影与电视"},
		{"VRV", "https://vrv.co", "动画和游戏频道"},
		{"Funimation", "https://www.funimation.com", "动漫流媒体"},
		{"DAZN", "https://www.dazn.com", "体育流媒体"},
		{"ESPN+", "https://plus.espn.com", "ESPN 体育流媒体"},
		{"Starz", "https://www.starz.com", "Starz 流媒体"},
		{"Showtime", "https://www.sho.com", "Showtime 流媒体"},
		{"AMC+", "https://www.amcplus.com", "AMC 流媒体"},
		{"Shudder", "https://www.shudder.com", "恐怖片流媒体"},
		{"BET+", "https://www.bet.com/betplus", "BET 流媒体"},
		{"Acorn TV", "https://acorn.tv", "英国剧集流媒体"},
		{"FilmStruck", "https://www.filmstruck.com", "经典电影流媒体"},
		{"Vudu Free", "https://www.vudu.com/content/movies/free", "Vudu 免费电影"},
		{"Popcornflix", "https://www.popcornflix.com", "免费电影流媒体"},
		{"Crackle", "https://www.crackle.com", "Sony 免费流媒体"},
		{"Xumo", "https://www.xumo.tv", "免费流媒体电视"},
		{"Sling TV", "https://www.sling.com", "在线电视直播"},
		{"FuboTV", "https://www.fubo.tv", "体育为主的流媒体"},
		{"Philo", "https://www.philo.com", "在线电视订阅"},
		{"YouTube TV", "https://tv.youtube.com", "YouTube 电视直播"},
		{"IPTV Smarters", "https://www.iptvsmarters.com", "IPTV 播放器"},
		{"Emby", "https://emby.media", "媒体服务器"},
		{"Jellyfin", "https://jellyfin.org", "开源媒体系统"},
		{"Kodi", "https://kodi.tv", "开源家庭影院"},
		{"Infuse", "https://firecore.com/infuse", "Apple 视频播放器"},
		{"VLC", "https://www.videolan.org", "开源跨平台播放器"},
		{"MX Player", "https://www.mxplayer.in", "印度视频平台"},
		{"Voot", "https://www.voot.com", "Viacom18 流媒体"},
		{"ManoramaMAX", "https://www.manoramamax.com", "Malayalam 流媒体"},
		{"Hoichoi", "https://www.hoichoi.tv", "Bengali 流媒体"},
		{"Aha", "https://www.aha.video", "Telugu 流媒体"},
		{"Sun NXT", "https://www.sunnxt.com", "South Indian 流媒体"},
		{"Lionsgate Play", "https://www.lionsgateplay.com", "Lionsgate 流媒体"},
		{"DocuBay", "https://www.docubay.com", "纪录片流媒体"},
		{"MDAG", "https://online.mdag.pl", "波兰电影节在线"},
		{"Filmin", "https://www.filmin.es", "西班牙独立电影流媒体"},
		{"Pantaflix", "https://www.pantaflix.com", "德国视频点播"},
		{"Joyn", "https://www.joyn.de", "德国免费流媒体"},
		{"Salto", "https://www.salto.fr", "法国联合流媒体"},
		{"RaiPlay", "https://www.raiplay.it", "意大利 RAI 流媒体"},
		{"Atresplayer", "https://www.atresplayer.com", "西班牙流媒体"},
		{"Globoplay", "https://globoplay.globo.com", "巴西 Globo 流媒体"},
		{"Blim", "https://www.blim.com", "墨西哥流媒体"},
		{"Claro Video", "https://www.clarovideo.com", "拉美流媒体"},
		{"ViuTV", "https://www.viu.com", "亚洲多地区流媒体"},
		{"iflix", "https://www.iflix.com", "东南亚流媒体"},
		{"HOOQ", "https://www.hooq.tv", "亚洲视频平台"},
		{"Irokotv", "https://irokotv.com", "非洲 Nollywood 流媒体"},
		{"Showmax", "https://www.showmax.com", "非洲流媒体"},
		{"DStv", "https://www.dstv.com", "南非卫星电视"},
		{"StarTimes", "https://www.startimestv.com", "非洲数字电视"},
		{"Okko", "https://okko.tv", "俄罗斯流媒体"},
		{"Kinopoisk", "https://www.kinopoisk.ru", "俄罗斯影视数据库"},
		{"ivi", "https://www.ivi.ru", "俄罗斯流媒体"},
		{"Amediateka", "https://www.amediateka.ru", "俄罗斯 HBO 合作平台"},
		{"Bilibili 漫画", "https://manga.bilibili.com", "B站漫画平台"},
		{"哔哩哔哩 HD", "https://www.hdslb.com", "哔哩哔哩高清"},
		{"PP视频", "https://www.pptvyun.com", "PPTV 聚力视频"},
		{"乐视视频", "https://www.le.com", "乐视视频平台"},
		{"风行网", "https://www.fun.tv", "风行视频"},
		{"百度视频", "https://v.baidu.com", "百度视频搜索"},
		{"56网", "https://www.56.com", "56视频分享"},
		{"六间房", "https://www.6.cn", "六间房直播"},
		{"土豆视频", "https://www.tudou.com", "土豆视频网"},
		{"1905电影网", "https://www.1905.com", "中国电影频道"},
		{"CCTV", "https://tv.cctv.com", "中央电视台"},
		{"央视网", "https://www.cctv.com", "中国网络电视台"},
		{"凤凰视频", "https://v.ifeng.com", "凤凰网视频"},
		{"新浪视频", "https://video.sina.com.cn", "新浪视频"},
		{"网易视频", "https://v.163.com", "网易视频频道"},
		{"看看新闻", "https://www.kankanews.com", "看看新闻Knews"},
		{"澎湃新闻视频", "https://www.thepaper.cn/video", "澎湃新闻视频"},
		{"秒拍", "https://www.miaopai.com", "秒拍短视频"},
		{"美拍", "https://www.meipai.com", "美图旗下短视频"},
		{"火山小视频", "https://www.huoshan.com", "字节跳动短视频"},
		{"皮皮虾", "https://www.pipix.com", "搞笑视频社区"},
		{"最右", "https://www.izuiyou.com", "搞笑内容社区"},
		{"波洞星球", "https://www.podon.com", "腾讯二次元内容"},
		{"CNTV", "https://www.cntv.cn", "中国网络电视台"},
		{"影视大全", "https://www.360kan.com", "360影视大全"},
		{"电影天堂", "https://www.dytt8.net", "电影天堂下载"},
		{"豆瓣电影", "https://movie.douban.com", "豆瓣电影评分"},
		{"猫眼电影", "https://www.maoyan.com", "猫眼电影票务"},
		{"淘票票", "https://www.taopiaopiao.com", "阿里电影票务"},
		{"时光网", "https://www.mtime.com", "时光网影视资讯"},
		{"IMDb", "https://www.imdb.com", "Internet Movie Database"},
		{"Rotten Tomatoes", "https://www.rottentomatoes.com", "电影评分网站"},
		{"Metacritic", "https://www.metacritic.com", "综合评分网站"},
		{"Letterboxd", "https://letterboxd.com", "电影社交日记"},
		{"TMDb", "https://www.themoviedb.org", "开放电影数据库"},
		{"Trakt", "https://trakt.tv", "影视追踪平台"},
		{"JustWatch", "https://www.justwatch.com", "流媒体搜索引擎"},
		{"Reelgood", "https://reelgood.com", "流媒体内容聚合"},
		{"TV Time", "https://www.tvtime.com", "剧集追踪应用"},
		{"MyAnimeList", "https://myanimelist.net", "动漫数据库与社区"},
		{"AniList", "https://anilist.co", "动漫追踪社区"},
		{"Kitsu", "https://kitsu.io", "动漫与漫画追踪"},
		{"Anime-Planet", "https://www.anime-planet.com", "动漫推荐平台"},
		{"9anime", "https://9anime.to", "免费动漫在线看"},
		{"AnimeFLV", "https://www3.animeflv.net", "西语动漫平台"},
		{"Anime News Network", "https://www.animenewsnetwork.com", "动漫新闻网"},
		{"短视频工场", "https://www.duanshipin.cc", "短视频行业资讯"},
		{"新片场", "https://www.xinpianchang.com", "创作人社区"},
		{"场库", "https://www.vmovier.com", "高品质短视频"},
		{"开眼", "https://www.kaiyanapp.com", "精选视频推荐"},
		{"Twitch Tracker", "https://twitchtracker.com", "Twitch 数据统计"},
		{"SullyGnome", "https://sullygnome.com", "Twitch 分析"},
		{"Stream Hatchet", "https://streamhatchet.com", "直播数据分析"},
		{"StreamElements", "https://streamelements.com", "直播工具平台"},
		{"Streamlabs", "https://streamlabs.com", "直播工具套件"},
		{"OBS Studio", "https://obsproject.com", "开源直播推流软件"},
		{"Restream", "https://restream.io", "多平台直播推流"},
		{"Kapwing", "https://www.kapwing.com", "在线视频编辑器"},
		{"Clipchamp", "https://clipchamp.com", "微软视频编辑器"},
		{"InVideo", "https://invideo.io", "在线视频制作"},
		{"Lumen5", "https://lumen5.com", "AI 视频创作"},
		{"Synthesia", "https://www.synthesia.io", "AI 视频生成"},
		{"HeyGen", "https://www.heygen.com", "AI 视频创作平台"},
		{"D-ID", "https://www.d-id.com", "AI 数字人视频"},
		{"Pictory", "https://pictory.ai", "AI 视频摘要"},
		{"Descript", "https://www.descript.com", "视频音频编辑"},
		{"DaVinci Resolve", "https://www.blackmagicdesign.com/products/davinciresolve", "专业视频编辑"},
		{"Final Cut Pro", "https://www.apple.com/final-cut-pro", "Apple 视频编辑"},
		{"Adobe Premiere", "https://www.adobe.com/products/premiere.html", "Adobe 视频编辑"},
		{"Filmora", "https://filmora.wondershare.com", "万兴视频编辑器"},
		{"CapCut", "https://www.capcut.com", "剪映国际版"},
		{"剪映", "https://www.capcut.cn", "字节跳动视频编辑"},
		{"必剪", "https://bcut.bilibili.cn", "B站视频编辑工具"},
	}
}

func live() []S {
	return []S{
		{"Twitch", "https://www.twitch.tv", "全球最大游戏直播平台"},
		{"YouTube Live", "https://www.youtube.com/live", "YouTube 直播"},
		{"Kick", "https://kick.com", "新兴直播平台"},
		{"Facebook Gaming", "https://www.facebook.com/gaming", "Facebook 游戏直播"},
		{"TikTok Live", "https://www.tiktok.com/live", "TikTok 直播"},
		{"Trovo", "https://trovo.live", "腾讯海外直播平台"},
		{"DLive", "https://dlive.tv", "区块链直播平台"},
		{"Afreeca TV", "https://www.afreecatv.com", "韩国直播平台"},
		{"Caffeine", "https://www.caffeine.tv", "社交广播平台"},
		{"Steam Broadcasting", "https://store.steampowered.com/broadcast", "Steam 游戏直播"},
		{"斗鱼直播", "https://www.douyu.com", "斗鱼游戏直播"},
		{"虎牙直播", "https://www.huya.com", "虎牙游戏直播"},
		{"Bilibili 直播", "https://live.bilibili.com", "B站直播"},
		{"抖音直播", "https://live.douyin.com", "抖音直播"},
		{"快手直播", "https://live.kuaishou.com", "快手直播"},
		{"YY直播", "https://www.yy.com", "YY语音直播平台"},
		{"花椒直播", "https://www.huajiao.com", "花椒直播"},
		{"企鹅电竞", "https://egame.qq.com", "腾讯电竞直播"},
		{"CC直播", "https://cc.163.com", "网易CC直播"},
		{"战旗直播", "https://www.zhanqi.tv", "战旗直播"},
		{"NOW直播", "https://now.qq.com", "腾讯NOW直播"},
		{"映客直播", "https://www.inke.cn", "映客直播"},
		{"酷狗直播", "https://fanxing.kugou.com", "酷狗繁星直播"},
		{"陌陌直播", "https://www.immomo.com", "陌陌社交直播"},
		{"一直播", "https://www.yizhibo.com", "一直播平台"},
		{"龙珠直播", "https://www.longzhu.com", "龙珠直播"},
		{"Nimo TV", "https://www.nimo.tv", "虎牙全球直播"},
		{"OPENREC", "https://www.openrec.tv", "日本游戏直播"},
		{"Mildom", "https://www.mildom.com", "日本游戏直播"},
		{"GoodGame", "https://goodgame.ru", "俄罗斯游戏直播"},
		{"Wasd.tv", "https://wasd.tv", "俄罗斯直播"},
		{"Booyah!", "https://booyah.live", "Garena 直播"},
		{"Nonolive", "https://www.nonolive.com", "东南亚直播"},
		{"Bigo Live", "https://www.bigo.tv", "全球社交直播"},
		{"LiveMe", "https://www.liveme.com", "社交直播平台"},
		{"StreamElements", "https://streamelements.com", "直播工具平台"},
		{"Streamlabs", "https://streamlabs.com", "直播工具套件"},
		{"Lightstream", "https://golightstream.com", "云端直播工具"},
		{"Restream", "https://restream.io", "多平台同步直播"},
		{"OBS Studio", "https://obsproject.com", "开源直播推流"},
		{"XSplit", "https://www.xsplit.com", "直播和录制软件"},
		{"Wirecast", "https://www.telestream.net/wirecast", "专业直播生产"},
		{"vMix", "https://www.vmix.com", "专业直播软件"},
		{"哔哩哔哩直播姬", "https://link.bilibili.com/p/center/index", "B站直播工具"},
		{"淘宝直播", "https://tblive.taobao.com", "淘宝电商直播"},
		{"抖音电商直播", "https://buyin.jinritemai.com", "抖音电商直播工具"},
		{"快手电商直播", "https://s.kwaixiaodian.com", "快手电商直播"},
		{"微信视频号直播", "https://channels.weixin.qq.com", "微信视频号直播"},
		{"小红书直播", "https://www.xiaohongshu.com/protocols/live", "小红书直播"},
		{"拼多多直播", "https://mms.pinduoduo.com", "拼多多电商直播"},
		{"看点直播", "https://kandian.qq.com", "腾讯看点直播"},
	}
}

func music() []S {
	return []S{
		{"Spotify", "https://open.spotify.com", "全球最大音乐流媒体"},
		{"Apple Music", "https://music.apple.com", "Apple 音乐流媒体"},
		{"YouTube Music", "https://music.youtube.com", "YouTube 音乐"},
		{"SoundCloud", "https://soundcloud.com", "音频分发平台"},
		{"Tidal", "https://tidal.com", "高保真音乐流媒体"},
		{"Deezer", "https://www.deezer.com", "法国音乐流媒体"},
		{"Amazon Music", "https://music.amazon.com", "亚马逊音乐"},
		{"Pandora", "https://www.pandora.com", "音乐发现平台"},
		{"iHeartRadio", "https://www.iheart.com", "免费音乐与电台"},
		{"Audiomack", "https://audiomack.com", "免费音乐流媒体"},
		{"Bandcamp", "https://bandcamp.com", "独立音乐平台"},
		{"Last.fm", "https://www.last.fm", "音乐追踪与推荐"},
		{"Genius", "https://genius.com", "歌词与音乐知识"},
		{"Discogs", "https://www.discogs.com", "音乐数据库与市场"},
		{"AllMusic", "https://www.allmusic.com", "音乐评论与推荐"},
		{"MusicBrainz", "https://musicbrainz.org", "开放音乐百科"},
		{"Shazam", "https://www.shazam.com", "音乐识别应用"},
		{"Mixcloud", "https://www.mixcloud.com", "DJ混音与电台"},
		{"Beatport", "https://www.beatport.com", "电子音乐商店"},
		{"Napster", "https://www.napster.com", "音乐流媒体"},
		{"Qobuz", "https://www.qobuz.com", "高解析度音乐"},
		{"网易云音乐", "https://music.163.com", "网易云音乐平台"},
		{"QQ音乐", "https://y.qq.com", "QQ音乐在线听歌"},
		{"酷狗音乐", "https://www.kugou.com", "酷狗音乐在线听"},
		{"酷我音乐", "https://www.kuwo.cn", "酷我音乐在线听"},
		{"咪咕音乐", "https://music.migu.cn", "移动咪咕音乐"},
		{"千千音乐", "https://music.taihe.com", "百度千千音乐"},
		{"5sing", "https://5sing.kugou.com", "原创音乐平台"},
		{"豆瓣FM", "https://fm.douban.com", "豆瓣电台"},
		{"荔枝FM", "https://www.lizhi.fm", "荔枝FM播客"},
		{"AWA", "https://awa.fm", "日本音乐流媒体"},
		{"LINE Music", "https://music.line.me", "LINE 音乐"},
		{"Melon", "https://www.melon.com", "韩国音乐流媒体"},
		{"Bugs", "https://music.bugs.co.kr", "韩国音乐平台"},
		{"Genie", "https://www.genie.co.kr", "韩国音乐流媒体"},
		{"FLO", "https://www.music-flo.com", "韩国SK音乐"},
		{"Gaana", "https://gaana.com", "印度音乐流媒体"},
		{"JioSaavn", "https://www.jiosaavn.com", "印度音乐流媒体"},
		{"Wynk Music", "https://wynk.in", "Airtel 音乐"},
		{"Anghami", "https://www.anghami.com", "阿拉伯音乐流媒体"},
		{"Boomplay", "https://www.boomplay.com", "非洲音乐流媒体"},
		{"Yandex Music", "https://music.yandex.com", "俄罗斯音乐"},
		{"KKBOX", "https://www.kkbox.com", "亚洲音乐流媒体"},
		{"Joox", "https://www.joox.com", "腾讯东南亚音乐"},
		{"Rate Your Music", "https://rateyourmusic.com", "音乐数据库社区"},
		{"Songkick", "https://www.songkick.com", "演唱会追踪"},
		{"Setlist.fm", "https://www.setlist.fm", "演唱会歌单数据库"},
		{"Juno", "https://www.juno.co.uk", "电子音乐下载"},
		{"Splice", "https://splice.com", "音乐制作采样"},
		{"Landr", "https://www.landr.com", "AI 音乐母带处理"},
		{"DistroKid", "https://distrokid.com", "独立音乐分发"},
		{"TuneCore", "https://www.tunecore.com", "音乐分发服务"},
		{"CD Baby", "https://cdbaby.com", "独立音乐分发"},
		{"Soundtrap", "https://www.soundtrap.com", "在线音乐制作"},
		{"BandLab", "https://www.bandlab.com", "社交音乐创作"},
		{"Ableton", "https://www.ableton.com", "专业音乐制作"},
		{"FL Studio", "https://www.image-line.com", "数字音频工作站"},
		{"Logic Pro", "https://www.apple.com/logic-pro", "Apple 音乐制作"},
		{"Audacity", "https://www.audacityteam.org", "开源音频编辑"},
		{"Musescore", "https://musescore.org", "开源乐谱编辑"},
		{"Hooktheory", "https://www.hooktheory.com", "音乐理论与和弦"},
		{"Chordify", "https://chordify.net", "歌曲和弦识别"},
		{"Ultimate Guitar", "https://www.ultimate-guitar.com", "吉他谱与和弦"},
		{"Songsterr", "https://www.songsterr.com", "吉他谱平台"},
	}
}
