package main

func ai() []S {
	return []S{
		{"ChatGPT", "https://chat.openai.com", "OpenAI AI 对话助手"},
		{"Claude", "https://claude.ai", "Anthropic AI 助手"},
		{"Gemini", "https://gemini.google.com", "Google AI 助手"},
		{"Perplexity", "https://www.perplexity.ai", "AI 搜索引擎"},
		{"Midjourney", "https://www.midjourney.com", "AI 图像生成"},
		{"Poe", "https://poe.com", "AI 聊天机器人聚合"},
		{"HuggingFace", "https://huggingface.co", "AI 模型中心"},
		{"Stable Diffusion", "https://stablediffusionweb.com", "AI 图像生成"},
		{"OpenAI", "https://openai.com", "OpenAI 官网"},
		{"Anthropic", "https://www.anthropic.com", "Claude AI 开发商"},
		{"Google DeepMind", "https://deepmind.google", "Google AI 研究"},
		{"Meta AI", "https://ai.meta.com", "Meta AI 研究"},
		{"Microsoft Copilot", "https://copilot.microsoft.com", "微软 AI 助手"},
		{"GitHub Copilot", "https://github.com/features/copilot", "AI 编程助手"},
		{"Cursor", "https://cursor.sh", "AI 代码编辑器"},
		{"Replit AI", "https://replit.com/ai", "AI 编程平台"},
		{"Codeium", "https://codeium.com", "免费 AI 编程助手"},
		{"Tabnine", "https://www.tabnine.com", "AI 代码补全"},
		{"Amazon CodeWhisperer", "https://aws.amazon.com/codewhisperer", "AWS AI 编程"},
		{"DALL-E", "https://labs.openai.com", "OpenAI 图像生成"},
		{"Leonardo AI", "https://leonardo.ai", "AI 图像生成"},
		{"Ideogram", "https://ideogram.ai", "AI 文字图像"},
		{"Adobe Firefly", "https://www.adobe.com/products/firefly.html", "Adobe AI 创意工具"},
		{"Runway", "https://runwayml.com", "AI 视频编辑"},
		{"Pika", "https://pika.art", "AI 视频生成"},
		{"Sora", "https://openai.com/sora", "OpenAI 视频生成"},
		{"Kling", "https://klingai.com", "快手 AI 视频生成"},
		{"ElevenLabs", "https://elevenlabs.io", "AI 语音合成"},
		{"Murf AI", "https://murf.ai", "AI 配音平台"},
		{"Descript", "https://www.descript.com", "AI 音视频编辑"},
		{"Otter.ai", "https://otter.ai", "AI 会议记录"},
		{"Jasper", "https://www.jasper.ai", "AI 营销文案"},
		{"Copy.ai", "https://www.copy.ai", "AI 文案生成"},
		{"Writesonic", "https://writesonic.com", "AI 写作工具"},
		{"Notion AI", "https://www.notion.so/product/ai", "Notion AI 助手"},
		{"Grammarly", "https://www.grammarly.com", "AI 语法检查"},
		{"QuillBot", "https://quillbot.com", "AI 改写工具"},
		{"DeepL", "https://www.deepl.com", "AI 翻译"},
		{"Replika", "https://replika.ai", "AI 伴侣"},
		{"Character.ai", "https://character.ai", "AI 角色对话"},
		{"Pi", "https://pi.ai", "Inflection AI 助手"},
		{"Cohere", "https://cohere.com", "企业 AI 平台"},
		{"Together AI", "https://www.together.ai", "开源 AI 平台"},
		{"Groq", "https://groq.com", "高速 AI 推理"},
		{"Mistral AI", "https://mistral.ai", "欧洲 AI 公司"},
		{"Stability AI", "https://stability.ai", "开源 AI 生成模型"},
		{"Civitai", "https://civitai.com", "AI 模型分享社区"},
		{"Replicate", "https://replicate.com", "云端运行 AI 模型"},
		{"Weights & Biases", "https://wandb.ai", "ML 实验追踪"},
		{"Lightning AI", "https://lightning.ai", "AI 开发平台"},
		{"Roboflow", "https://roboflow.com", "计算机视觉平台"},
		{"Scale AI", "https://scale.com", "AI 数据标注"},
		{"Labelbox", "https://labelbox.com", "数据标注平台"},
		{"DataRobot", "https://www.datarobot.com", "企业 AI 平台"},
		{"H2O.ai", "https://h2o.ai", "开源 AI/ML 平台"},
		{"Kaggle", "https://www.kaggle.com", "数据科学竞赛平台"},
		{"Papers with Code", "https://paperswithcode.com", "AI 论文与代码"},
		{"arXiv", "https://arxiv.org", "学术预印本平台"},
		{"Semantic Scholar", "https://www.semanticscholar.org", "AI 学术搜索"},
		{"Connected Papers", "https://www.connectedpapers.com", "论文关联图谱"},
		{"Lensa AI", "https://prisma-ai.com/lensa", "AI 头像生成"},
		{"PhotoRoom", "https://www.photoroom.com", "AI 背景移除"},
		{"Remove.bg", "https://www.remove.bg", "AI 背景移除"},
		{"Canva AI", "https://www.canva.com/ai-image-generator", "Canva AI 设计"},
		{"Beautiful.ai", "https://www.beautiful.ai", "AI 演示文稿"},
		{"Gamma", "https://gamma.app", "AI 演示文稿"},
		{"Tome", "https://tome.app", "AI 叙事工具"},
		{"Napkin AI", "https://www.napkin.ai", "AI 图表生成"},
		{"通义千问", "https://tongyi.aliyun.com", "阿里通义千问"},
		{"文心一言", "https://yiyan.baidu.com", "百度文心一言"},
		{"豆包", "https://www.doubao.com", "字节跳动 AI 助手"},
		{"Kimi", "https://kimi.moonshot.cn", "月之暗面 AI 助手"},
		{"智谱清言", "https://chatglm.cn", "智谱 AI 对话"},
		{"讯飞星火", "https://xinghuo.xfyun.cn", "科大讯飞 AI"},
		{"百川大模型", "https://www.baichuan-ai.com", "百川智能"},
		{"零一万物", "https://www.01.ai", "李开复 AI 公司"},
		{"MiniMax", "https://www.minimaxi.com", "MiniMax AI"},
		{"商汤日日新", "https://www.sensecore.cn", "商汤科技 AI"},
		{"昆仑万维", "https://www.kunlun.com", "天工 AI 大模型"},
		{"出门问问", "https://www.chumenwenwen.com", "序列猴子大模型"},
		{"阶跃星辰", "https://www.stepfun.com", "阶跃星辰 AI"},
		{"深度求索", "https://www.deepseek.com", "DeepSeek AI"},
		{"面壁智能", "https://modelbest.cn", "面壁智能大模型"},
		{"Coze", "https://www.coze.com", "字节跳动 AI Bot 平台"},
		{"Dify", "https://dify.ai", "开源 LLM 应用平台"},
		{"LangChain", "https://www.langchain.com", "LLM 应用开发框架"},
		{"LlamaIndex", "https://www.llamaindex.ai", "LLM 数据框架"},
		{"Vercel AI SDK", "https://sdk.vercel.ai", "Vercel AI 开发工具"},
		{"Ollama", "https://ollama.ai", "本地运行大模型"},
		{"LM Studio", "https://lmstudio.ai", "本地大模型GUI"},
		{"Jan", "https://jan.ai", "开源本地AI助手"},
		{"GPT4All", "https://gpt4all.io", "本地运行 LLM"},
		{"PrivateGPT", "https://privategpt.dev", "私有化 AI 对话"},
		{"Open WebUI", "https://openwebui.com", "自托管AI聊天界面"},
		{"FlowiseAI", "https://flowiseai.com", "LLM 流程构建器"},
		{"n8n", "https://n8n.io", "工作流自动化+AI"},
		{"Zapier AI", "https://zapier.com/ai", "Zapier AI 自动化"},
		{"Make", "https://www.make.com", "自动化平台+AI"},
		{"Bardeen", "https://www.bardeen.ai", "AI 工作流自动化"},
		{"Taskade", "https://www.taskade.com", "AI 协作工作空间"},
		{"Monica", "https://monica.im", "Chrome AI 助手插件"},
		{"Sider", "https://sider.ai", "浏览器 AI 侧栏"},
		{"MaxAI", "https://www.maxai.me", "AI 浏览器扩展"},
		{"Merlin", "https://www.getmerlin.in", "AI 浏览器助手"},
		{"ChatHub", "https://chathub.gg", "多AI聊天浏览器插件"},
		{"Perplexity Chrome", "https://chrome.google.com/webstore/detail/perplexity", "Perplexity 浏览器插件"},
		{"AI Studio", "https://aistudio.google.com", "Google AI Studio"},
		{"Vertex AI", "https://cloud.google.com/vertex-ai", "Google 企业 AI"},
		{"Azure OpenAI", "https://azure.microsoft.com/en-us/products/ai-services/openai-service", "微软 Azure AI"},
		{"AWS Bedrock", "https://aws.amazon.com/bedrock", "AWS AI 基础模型"},
		{"Pinecone", "https://www.pinecone.io", "向量数据库"},
		{"Weaviate", "https://weaviate.io", "开源向量搜索"},
		{"Qdrant", "https://qdrant.tech", "向量相似度搜索"},
		{"Chroma", "https://www.trychroma.com", "开源嵌入数据库"},
		{"Milvus", "https://milvus.io", "开源向量数据库"},
		{"Unstructured", "https://unstructured.io", "AI 数据预处理"},
	}
}

func news() []S {
	return []S{
		{"Google News", "https://news.google.com", "Google 新闻聚合"},
		{"BBC", "https://www.bbc.com", "英国广播公司"},
		{"CNN", "https://www.cnn.com", "有线电视新闻网"},
		{"Reuters", "https://www.reuters.com", "路透社国际新闻"},
		{"AP News", "https://apnews.com", "美联社"},
		{"Al Jazeera", "https://www.aljazeera.com", "半岛电视台"},
		{"The New York Times", "https://www.nytimes.com", "纽约时报"},
		{"The Washington Post", "https://www.washingtonpost.com", "华盛顿邮报"},
		{"The Guardian", "https://www.theguardian.com", "卫报"},
		{"Bloomberg", "https://www.bloomberg.com", "彭博社财经新闻"},
		{"Financial Times", "https://www.ft.com", "金融时报"},
		{"The Wall Street Journal", "https://www.wsj.com", "华尔街日报"},
		{"The Economist", "https://www.economist.com", "经济学人"},
		{"Forbes", "https://www.forbes.com", "福布斯商业杂志"},
		{"Time", "https://time.com", "时代周刊"},
		{"Newsweek", "https://www.newsweek.com", "新闻周刊"},
		{"NPR", "https://www.npr.org", "美国公共广播"},
		{"PBS", "https://www.pbs.org", "美国公共电视"},
		{"CBS News", "https://www.cbsnews.com", "CBS 新闻"},
		{"ABC News", "https://abcnews.go.com", "ABC 新闻"},
		{"NBC News", "https://www.nbcnews.com", "NBC 新闻"},
		{"Fox News", "https://www.foxnews.com", "Fox 新闻"},
		{"CNBC", "https://www.cnbc.com", "CNBC 财经新闻"},
		{"The Verge", "https://www.theverge.com", "科技媒体"},
		{"Wired", "https://www.wired.com", "科技与文化"},
		{"Ars Technica", "https://arstechnica.com", "科技新闻"},
		{"TechCrunch", "https://techcrunch.com", "创业与科技"},
		{"Engadget", "https://www.engadget.com", "消费电子新闻"},
		{"The Register", "https://www.theregister.com", "IT 新闻"},
		{"Hacker News", "https://news.ycombinator.com", "黑客新闻"},
		{"Slashdot", "https://slashdot.org", "技术新闻"},
		{"Drudge Report", "https://www.drudgereport.com", "新闻聚合"},
		{"Politico", "https://www.politico.com", "政策新闻"},
		{"Axios", "https://www.axios.com", "简明新闻"},
		{"The Hill", "https://thehill.com", "美国政策新闻"},
		{"Vox", "https://www.vox.com", "解释性新闻"},
		{"Vice", "https://www.vice.com", "青年文化与新闻"},
		{"Buzzfeed News", "https://www.buzzfeednews.com", "网络媒体"},
		{"Business Insider", "https://www.businessinsider.com", "商业新闻"},
		{"The Atlantic", "https://www.theatlantic.com", "文化与时事"},
		{"The New Yorker", "https://www.newyorker.com", "文化杂志"},
		{"Japan Times", "https://www.japantimes.co.jp", "日本英语新闻"},
		{"NHK World", "https://www3.nhk.or.jp/nhkworld", "日本 NHK 国际"},
		{"Yonhap News", "https://en.yna.co.kr", "韩联社英语"},
		{"The Straits Times", "https://www.straitstimes.com", "海峡时报"},
		{"South China Morning Post", "https://www.scmp.com", "南华早报"},
		{"India Today", "https://www.indiatoday.in", "印度新闻"},
		{"The Hindu", "https://www.thehindu.com", "印度英语报"},
		{"NDTV", "https://www.ndtv.com", "印度新闻电视"},
		{"Deutsche Welle", "https://www.dw.com", "德国之声"},
		{"France24", "https://www.france24.com", "法国24新闻"},
		{"RT", "https://www.rt.com", "今日俄罗斯"},
		{"TASS", "https://tass.com", "塔斯社"},
		{"Xinhua", "https://www.xinhuanet.com", "新华社"},
		{"知乎", "https://www.zhihu.com", "知乎社区"},
		{"今日头条", "https://www.toutiao.com", "今日头条资讯"},
		{"新浪新闻", "https://news.sina.com.cn", "新浪新闻"},
		{"网易新闻", "https://news.163.com", "网易新闻"},
		{"搜狐新闻", "https://news.sohu.com", "搜狐新闻"},
		{"腾讯新闻", "https://news.qq.com", "腾讯新闻"},
		{"凤凰网", "https://www.ifeng.com", "凤凰网新闻"},
		{"澎湃新闻", "https://www.thepaper.cn", "澎湃新闻"},
		{"界面新闻", "https://www.jiemian.com", "界面新闻"},
		{"36氪", "https://36kr.com", "科技创投媒体"},
		{"虎嗅", "https://www.huxiu.com", "商业与科技"},
		{"钛媒体", "https://www.tmtpost.com", "科技与财经"},
		{"品玩", "https://www.pingwest.com", "科技媒体"},
		{"极客公园", "https://www.geekpark.net", "创新者社区"},
		{"爱范儿", "https://www.ifanr.com", "科技消费媒体"},
		{"少数派", "https://sspai.com", "数字生活指南"},
		{"果壳", "https://www.guokr.com", "科技人文社区"},
		{"环球网", "https://www.huanqiu.com", "环球网新闻"},
		{"光明网", "https://www.gmw.cn", "光明日报"},
		{"央广网", "https://www.cnr.cn", "央广网"},
		{"中新网", "https://www.chinanews.com.cn", "中国新闻网"},
		{"人民网", "https://www.people.com.cn", "人民日报"},
		{"观察者网", "https://www.guancha.cn", "观察者网时事"},
		{"财新网", "https://www.caixin.com", "财新传媒"},
		{"第一财经", "https://www.yicai.com", "第一财经"},
		{"经济观察网", "https://www.eeo.com.cn", "经济观察报"},
		{"21世纪经济报道", "https://www.21jingji.com", "21经济报道"},
		{"每日经济新闻", "https://www.nbd.com.cn", "每经网"},
		{"华尔街见闻", "https://wallstreetcn.com", "全球财经资讯"},
		{"雪球", "https://xueqiu.com", "投资者社区"},
		{"东方财富网", "https://www.eastmoney.com", "东方财富"},
		{"同花顺", "https://www.10jqka.com.cn", "同花顺财经"},
		{"新浪财经", "https://finance.sina.com.cn", "新浪财经"},
		{"Flipboard", "https://flipboard.com", "个性化杂志"},
		{"Feedly", "https://feedly.com", "RSS 阅读器"},
		{"Inoreader", "https://www.inoreader.com", "RSS 订阅"},
		{"NewsBlur", "https://newsblur.com", "新闻阅读器"},
		{"The Conversation", "https://theconversation.com", "学术新闻"},
		{"Quartz", "https://qz.com", "全球商业新闻"},
		{"Rest of World", "https://restofworld.org", "新兴市场科技"},
		{"Protocol", "https://www.protocol.com", "科技行业新闻"},
		{"The Information", "https://www.theinformation.com", "深度科技新闻"},
		{"Semafor", "https://www.semafor.com", "全球新闻平台"},
		{"Punchbowl News", "https://punchbowl.news", "政策新闻"},
		{"ProPublica", "https://www.propublica.org", "调查性新闻"},
	}
}

func social() []S {
	return []S{
		{"X (Twitter)", "https://x.com", "社交媒体平台"},
		{"Reddit", "https://www.reddit.com", "社区讨论平台"},
		{"Discord", "https://discord.com", "聊天与社区平台"},
		{"Facebook", "https://www.facebook.com", "Meta 社交网络"},
		{"Instagram", "https://www.instagram.com", "图片与视频分享"},
		{"Telegram", "https://web.telegram.org", "加密即时通讯"},
		{"WhatsApp", "https://web.whatsapp.com", "WhatsApp 网页版"},
		{"微博", "https://weibo.com", "新浪微博"},
		{"微信公众平台", "https://mp.weixin.qq.com", "微信公众号"},
		{"LinkedIn", "https://www.linkedin.com", "职业社交网络"},
		{"Pinterest", "https://www.pinterest.com", "视觉灵感发现"},
		{"Snapchat", "https://www.snapchat.com", "阅后即焚社交"},
		{"Threads", "https://www.threads.net", "Meta 文字社交"},
		{"Bluesky", "https://bsky.app", "去中心化社交"},
		{"Mastodon", "https://mastodon.social", "联邦宇宙社交"},
		{"Tumblr", "https://www.tumblr.com", "博客与社交平台"},
		{"Quora", "https://www.quora.com", "知识问答平台"},
		{"VK", "https://vk.com", "俄罗斯社交网络"},
		{"Line", "https://line.me", "日本韩国即时通讯"},
		{"KakaoTalk", "https://www.kakaocorp.com/page/service/service/KakaoTalk", "韩国即时通讯"},
		{"WeChat Web", "https://web.wechat.com", "微信网页版"},
		{"QQ", "https://im.qq.com", "腾讯QQ"},
		{"豆瓣", "https://www.douban.com", "豆瓣社区"},
		{"人人网", "https://www.renren.com", "人人网社区"},
		{"天涯社区", "https://www.tianya.cn", "天涯论坛"},
		{"百度贴吧", "https://tieba.baidu.com", "百度贴吧社区"},
		{"网易LOFTER", "https://www.lofter.com", "网易轻博客"},
		{"即刻", "https://okjike.com", "即刻社区"},
		{"Soul", "https://www.soulapp.cn", "Soul 社交"},
		{"探探", "https://tantanapp.com", "探探社交"},
		{"陌陌", "https://www.immomo.com", "陌陌社交"},
		{"Clubhouse", "https://www.clubhouse.com", "语音社交"},
		{"Signal", "https://signal.org", "加密通讯"},
		{"Element", "https://element.io", "Matrix 客户端"},
		{"Slack", "https://slack.com", "团队协作通讯"},
		{"Microsoft Teams", "https://teams.microsoft.com", "微软团队协作"},
		{"Zoom", "https://zoom.us", "视频会议"},
		{"Google Meet", "https://meet.google.com", "Google 视频会议"},
		{"Skype", "https://www.skype.com", "Skype 网络通话"},
		{"飞书", "https://www.feishu.cn", "字节跳动飞书"},
		{"钉钉", "https://www.dingtalk.com", "阿里钉钉"},
		{"企业微信", "https://work.weixin.qq.com", "腾讯企业微信"},
		{"Lark", "https://www.larksuite.com", "飞书国际版"},
		{"Nextdoor", "https://nextdoor.com", "邻里社交"},
		{"Meetup", "https://www.meetup.com", "活动组织平台"},
		{"Eventbrite", "https://www.eventbrite.com", "活动售票平台"},
		{"Twitch Chat", "https://www.twitch.tv/directory", "Twitch 社区"},
		{"Amino", "https://aminoapps.com", "兴趣社区"},
		{"Hive Social", "https://www.hivesocial.app", "社交网络"},
		{"Cohost", "https://cohost.org", "博客社交平台"},
		{"Plurk", "https://www.plurk.com", "台湾社交平台"},
		{"Gab", "https://gab.com", "社交平台"},
		{"Parler", "https://parler.com", "社交平台"},
		{"Truth Social", "https://truthsocial.com", "社交平台"},
		{"BeReal", "https://bereal.com", "真实社交"},
		{"Lemon8", "https://www.lemon8-app.com", "字节旗下生活分享"},
		{"Xiaohongshu", "https://www.xiaohongshu.com", "小红书国际版"},
		{"Farcaster", "https://www.farcaster.xyz", "Web3 社交协议"},
		{"Lens Protocol", "https://www.lens.xyz", "去中心化社交图谱"},
		{"Nostr", "https://nostr.com", "去中心化社交协议"},
		{"XMPP", "https://xmpp.org", "开放即时通讯协议"},
		{"Matrix", "https://matrix.org", "开放通讯协议"},
		{"Jami", "https://jami.net", "开源去中心化通讯"},
		{"Session", "https://getsession.org", "匿名加密通讯"},
		{"Briar", "https://briarproject.org", "P2P 加密通讯"},
		{"Keybase", "https://keybase.io", "加密身份平台"},
		{"Wire", "https://wire.com", "端到端加密通讯"},
	}
}
