package main

// Batch 1 extension data: Education, Travel, Food, Health, Sports, Real Estate, Automotive

func educationEx() []S {
	return []S{
		{"Brilliant", "https://brilliant.org", "交互式数学科学学习"},
		{"Duolingo", "https://www.duolingo.com", "免费语言学习"},
		{"Memrise", "https://www.memrise.com", "记忆法语言学习"},
		{"Babbel", "https://www.babbel.com", "语言学习应用"},
		{"Busuu", "https://www.busuu.com", "社交语言学习"},
		{"Rosetta Stone", "https://www.rosettastone.com", "语言学习软件"},
		{"Lingoda", "https://www.lingoda.com", "在线语言课程"},
		{"italki", "https://www.italki.com", "一对一语言学习"},
		{"Preply", "https://preply.com", "在线家教平台"},
		{"Wyzant", "https://www.wyzant.com", "私人家教"},
		{"Chegg", "https://www.chegg.com", "学生学习助手"},
		{"Quizlet", "https://quizlet.com", "闪卡记忆学习"},
		{"Anki", "https://apps.ankiweb.net", "间隔重复记忆"},
		{"Notion", "https://www.notion.so", "笔记与知识管理"},
		{"Evernote", "https://evernote.com", "数字笔记本"},
		{"OneNote", "https://www.onenote.com", "微软笔记工具"},
		{"Obsidian", "https://obsidian.md", "知识图谱笔记"},
		{"Roam Research", "https://roamresearch.com", "双向链接笔记"},
		{"Logseq", "https://logseq.com", "开源大纲笔记"},
		{"RemNote", "https://www.remnote.com", "笔记+闪卡"},
		{"Skillshare", "https://www.skillshare.com", "创意课程平台"},
		{"MasterClass", "https://www.masterclass.com", "名师课程"},
		{"CreativeLive", "https://www.creativelive.com", "创意技能课程"},
		{"Domestika", "https://www.domestika.org", "创意社区课程"},
		{"Pluralsight", "https://www.pluralsight.com", "技术课程平台"},
		{"LinkedIn Learning", "https://www.linkedin.com/learning", "职业技能课程"},
		{"Treehouse", "https://teamtreehouse.com", "编程设计课程"},
		{"Codecademy", "https://www.codecademy.com", "交互式编程学习"},
		{"freeCodeCamp", "https://www.freecodecamp.org", "免费编程课程"},
		{"The Odin Project", "https://www.theodinproject.com", "全栈课程"},
		{"Exercism", "https://exercism.org", "编程练习平台"},
		{"LeetCode", "https://leetcode.com", "算法练习"},
		{"HackerRank", "https://www.hackerrank.com", "编程挑战"},
		{"Codewars", "https://www.codewars.com", "代码道场"},
		{"TopCoder", "https://www.topcoder.com", "编程竞赛"},
		{"DataCamp", "https://www.datacamp.com", "数据科学课程"},
		{"Kaggle Learn", "https://www.kaggle.com/learn", "数据科学教程"},
		{"Fast.ai", "https://www.fast.ai", "深度学习课程"},
		{"Stanford Online", "https://online.stanford.edu", "斯坦福在线课程"},
		{"MIT OpenCourseWare", "https://ocw.mit.edu", "MIT开放课程"},
		{"Harvard Online", "https://online-learning.harvard.edu", "哈佛在线课程"},
		{"Yale Open Courses", "https://oyc.yale.edu", "耶鲁开放课程"},
		{"Open Culture", "https://www.openculture.com", "免费在线课程聚合"},
		{"Academic Earth", "https://academicearth.org", "学术视频课程"},
		{"Class Central", "https://www.classcentral.com", "MOOC搜索引擎"},
		{"FutureLearn", "https://www.futurelearn.com", "英国在线课程"},
		{"Swayam", "https://swayam.gov.in", "印度在线教育"},
		{"K-MOOC", "https://www.kmooc.kr", "韩国在线课程"},
		{"JMOOC", "https://www.jmooc.jp", "日本在线课程"},
		{"OpenClassrooms", "https://openclassrooms.com", "法国在线课程"},
		{"Alison", "https://alison.com", "免费在线教育"},
		{"Saylor Academy", "https://www.saylor.org", "免费大学课程"},
		{"CK-12", "https://www.ck12.org", "K12教育平台"},
		{"OpenStax", "https://openstax.org", "开放教科书"},
		{"LibreTexts", "https://libretexts.org", "自由教材"},
		{"Project Gutenberg", "https://www.gutenberg.org", "免费电子书"},
		{"Bartleby", "https://www.bartleby.com", "学术资源"},
		{"SparkNotes", "https://www.sparknotes.com", "学习指南"},
		{"CliffsNotes", "https://www.cliffsnotes.com", "学习笔记"},
		{"GradeScope", "https://www.gradescope.com", "作业评分平台"},
		{"Turnitin", "https://www.turnitin.com", "论文查重"},
		{"Google Scholar", "https://scholar.google.com", "学术搜索"},
		{"Semantic Scholar", "https://www.semanticscholar.org", "AI学术搜索"},
		{"ResearchGate", "https://www.researchgate.net", "学术社交网络"},
		{"Academia.edu", "https://www.academia.edu", "学术论文分享"},
		{"JSTOR", "https://www.jstor.org", "学术期刊数据库"},
		{"PubMed", "https://pubmed.ncbi.nlm.nih.gov", "生物医学文献"},
		{"IEEE Xplore", "https://ieeexplore.ieee.org", "工程技术文献"},
		{"ACM Digital Library", "https://dl.acm.org", "计算机科学文献"},
		{"arXiv", "https://arxiv.org", "预印本论文"},
		{"SSRN", "https://www.ssrn.com", "社科论文"},
		{"中国知网", "https://www.cnki.net", "中文学术数据库"},
		{"万方数据", "https://www.wanfangdata.com.cn", "中文学术平台"},
		{"维普", "https://www.cqvip.com", "中文期刊数据库"},
		{"百度学术", "https://xueshu.baidu.com", "中文学术搜索"},
		{"学堂在线", "https://www.xuetangx.com", "清华MOOC平台"},
		{"中国大学MOOC", "https://www.icourse163.org", "网易MOOC平台"},
		{"超星学习通", "https://www.chaoxing.com", "高校学习平台"},
		{"智慧树", "https://www.zhihuishu.com", "在线教育平台"},
		{"腾讯课堂", "https://ke.qq.com", "腾讯在线教育"},
		{"网易公开课", "https://open.163.com", "公开课平台"},
		{"慕课网", "https://www.imooc.com", "IT技能学习"},
		{"极客时间", "https://time.geekbang.org", "IT专业课程"},
		{"掘金课程", "https://juejin.cn/course", "开发者课程"},
		{"51CTO学堂", "https://edu.51cto.com", "IT在线教育"},
		{"CSDN学院", "https://edu.csdn.net", "技术课程"},
		{"力扣中国", "https://leetcode.cn", "算法题库"},
		{"牛客网", "https://www.nowcoder.com", "IT笔试面试"},
		{"七月在线", "https://www.julyedu.com", "AI教育平台"},
		{"开课吧", "https://www.kaikeba.com", "数字人才教育"},
		{"Mathway", "https://www.mathway.com", "数学题解答"},
		{"Wolfram Alpha", "https://www.wolframalpha.com", "计算知识引擎"},
		{"Desmos", "https://www.desmos.com", "图形计算器"},
		{"GeoGebra", "https://www.geogebra.org", "数学工具"},
		{"Symbolab", "https://www.symbolab.com", "数学求解器"},
		{"Photomath", "https://photomath.com", "拍照解数学题"},
		{"Grammarly", "https://www.grammarly.com", "英语写作助手"},
		{"LanguageTool", "https://languagetool.org", "多语言语法检查"},
		{"Hemingway Editor", "https://hemingwayapp.com", "英文写作优化"},
		{"ProWritingAid", "https://prowritingaid.com", "写作分析工具"},
		{"Scribens", "https://www.scribens.com", "法语语法检查"},
		{"TED-Ed", "https://ed.ted.com", "TED教育视频"},
		{"CrashCourse", "https://thecrashcourse.com", "速成课视频"},
		{"3Blue1Brown", "https://www.3blue1brown.com", "数学可视化"},
		{"Kurzgesagt", "https://kurzgesagt.org", "科学动画"},
		{"Numberphile", "https://www.numberphile.com", "数学视频"},
		{"Veritasium", "https://www.veritasium.com", "科学实验视频"},
		{"Byju's", "https://byjus.com", "印度在线教育"},
		{"Unacademy", "https://unacademy.com", "印度教育平台"},
		{"Toppr", "https://www.toppr.com", "印度K12平台"},
		{"Vedantu", "https://www.vedantu.com", "印度在线辅导"},
		{"Kahoot", "https://kahoot.com", "游戏化学习"},
		{"Quizizz", "https://quizizz.com", "互动测验平台"},
		{"Nearpod", "https://nearpod.com", "交互式课堂"},
		{"Edmodo", "https://www.edmodo.com", "教育社交平台"},
		{"Schoology", "https://www.schoology.com", "学习管理系统"},
		{"Canvas LMS", "https://www.instructure.com/canvas", "学习管理平台"},
		{"Moodle", "https://moodle.org", "开源LMS"},
		{"Blackboard", "https://www.blackboard.com", "教育技术平台"},
		{"Google Classroom", "https://classroom.google.com", "谷歌课堂"},
		{"Microsoft Teams EDU", "https://www.microsoft.com/en-us/education/products/teams", "微软教育团队"},
	}
}

func travelEx() []S {
	return []S{
		{"Skyscanner", "https://www.skyscanner.com", "机票比价"},
		{"Kayak", "https://www.kayak.com", "旅行搜索"},
		{"Google Flights", "https://www.google.com/travel/flights", "谷歌航班"},
		{"Hopper", "https://www.hopper.com", "航班价格预测"},
		{"Momondo", "https://www.momondo.com", "机票比价"},
		{"Kiwi", "https://www.kiwi.com", "多段航线搜索"},
		{"Rome2Rio", "https://www.rome2rio.com", "多交通方式搜索"},
		{"Omio", "https://www.omio.com", "欧洲交通搜索"},
		{"Trainline", "https://www.thetrainline.com", "欧洲火车票"},
		{"FlixBus", "https://www.flixbus.com", "欧洲巴士"},
		{"Hostelworld", "https://www.hostelworld.com", "青旅预订"},
		{"Agoda", "https://www.agoda.com", "亚洲酒店预订"},
		{"Hotels.com", "https://www.hotels.com", "酒店预订"},
		{"Vrbo", "https://www.vrbo.com", "度假租房"},
		{"HomeAway", "https://www.homeaway.com", "度假屋租赁"},
		{"Homestay", "https://www.homestay.com", "寄宿家庭"},
		{"Couchsurfing", "https://www.couchsurfing.com", "沙发客"},
		{"HouseTrip", "https://www.housetrip.com", "欧洲度假屋"},
		{"TripAdvisor", "https://www.tripadvisor.com", "旅行点评"},
		{"Lonely Planet", "https://www.lonelyplanet.com", "旅行指南"},
		{"WikiTravel", "https://wikitravel.org", "旅行百科"},
		{"Wikivoyage", "https://www.wikivoyage.org", "旅行指南百科"},
		{"Culture Trip", "https://theculturetrip.com", "文化旅行"},
		{"Atlas Obscura", "https://www.atlasobscura.com", "奇特景点"},
		{"Roadtrippers", "https://roadtrippers.com", "公路旅行规划"},
		{"Wanderlog", "https://wanderlog.com", "行程规划"},
		{"TripIt", "https://www.tripit.com", "行程管理"},
		{"Sygic Travel", "https://travel.sygic.com", "旅行规划"},
		{"Google Maps Travel", "https://www.google.com/travel", "谷歌旅行"},
		{"Viator", "https://www.viator.com", "当地活动预订"},
		{"GetYourGuide", "https://www.getyourguide.com", "旅游活动预订"},
		{"Klook", "https://www.klook.com", "亚洲活动预订"},
		{"KKday", "https://www.kkday.com", "旅游体验预订"},
		{"Civitatis", "https://www.civitatis.com", "西班牙语活动预订"},
		{"Musement", "https://www.musement.com", "景点门票"},
		{"Tiqets", "https://www.tiqets.com", "博物馆门票"},
		{"Headout", "https://www.headout.com", "即时活动预订"},
		{"Rentalcars", "https://www.rentalcars.com", "租车比价"},
		{"Sixt", "https://www.sixt.com", "国际租车"},
		{"Europcar", "https://www.europcar.com", "欧洲租车"},
		{"Turo", "https://turo.com", "P2P租车"},
		{"BlaBlaCar", "https://www.blablacar.com", "拼车平台"},
		{"Uber", "https://www.uber.com", "网约车"},
		{"Lyft", "https://www.lyft.com", "美国网约车"},
		{"Grab", "https://www.grab.com", "东南亚出行"},
		{"Gojek", "https://www.gojek.com", "印尼超级应用"},
		{"去哪儿", "https://www.qunar.com", "中国旅行搜索"},
		{"同程旅行", "https://www.ly.com", "中国在线旅游"},
		{"途牛", "https://www.tuniu.com", "中国旅游平台"},
		{"驴妈妈", "https://www.lvmama.com", "中国景点门票"},
		{"穷游网", "https://www.qyer.com", "中国旅行社区"},
		{"马蜂窝", "https://www.mafengwo.cn", "旅行攻略社区"},
		{"小红书旅行", "https://www.xiaohongshu.com/explore/travel", "旅行笔记"},
		{"飞猪", "https://www.fliggy.com", "阿里旅行平台"},
		{"12306", "https://www.12306.cn", "中国铁路购票"},
		{"航旅纵横", "https://www.umetrip.com", "航班管家"},
		{"春秋航空", "https://www.ch.com", "廉价航空"},
		{"Nomad List", "https://nomadlist.com", "数字游民城市"},
		{"Remote Year", "https://www.remoteyear.com", "远程工作旅行"},
		{"WorldPackers", "https://www.worldpackers.com", "义工旅行"},
		{"Workaway", "https://www.workaway.info", "以工换食宿"},
		{"WWOOF", "https://wwoof.net", "有机农场义工"},
		{"Trusted Housesitters", "https://www.trustedhousesitters.com", "看房换住宿"},
		{"Seat61", "https://www.seat61.com", "火车旅行指南"},
		{"SeatGuru", "https://www.seatguru.com", "飞机座位指南"},
		{"LoungeBuddy", "https://www.loungebuddy.com", "机场贵宾厅"},
		{"Priority Pass", "https://www.prioritypass.com", "机场贵宾厅会员"},
		{"Pack Point", "https://www.packpnt.com", "行李清单工具"},
		{"XE Travel", "https://www.xe.com", "旅行汇率"},
		{"Wise Travel", "https://wise.com", "旅行换汇"},
		{"Revolut Travel", "https://www.revolut.com", "旅行支付卡"},
		{"SafetyWing", "https://safetywing.com", "数字游民保险"},
		{"World Nomads", "https://www.worldnomads.com", "旅行保险"},
		{"iVisa", "https://www.ivisa.com", "签证申请"},
		{"VisaHQ", "https://www.visahq.com", "签证服务"},
		{"Sherpa", "https://apply.joinsherpa.com", "旅行限制查询"},
		{"Japan Guide", "https://www.japan-guide.com", "日本旅行指南"},
		{"Visit Korea", "https://english.visitkorea.or.kr", "韩国旅游"},
		{"Thailand Tourism", "https://www.tourismthailand.org", "泰国旅游"},
		{"Visit Britain", "https://www.visitbritain.com", "英国旅游"},
		{"France Tourism", "https://www.france.fr", "法国旅游"},
		{"Visit Italy", "https://www.italia.it", "意大利旅游"},
		{"Germany Travel", "https://www.germany.travel", "德国旅游"},
		{"Visit Japan", "https://www.japan.travel", "日本旅游"},
		{"Australia Tourism", "https://www.australia.com", "澳大利亚旅游"},
		{"New Zealand Tourism", "https://www.newzealand.com", "新西兰旅游"},
		{"Canada Tourism", "https://www.destinationcanada.com", "加拿大旅游"},
		{"Visit Dubai", "https://www.visitdubai.com", "迪拜旅游"},
		{"Visit Singapore", "https://www.visitsingapore.com", "新加坡旅游"},
		{"Discover Hong Kong", "https://www.discoverhongkong.com", "香港旅游"},
		{"Travel China Guide", "https://www.travelchinaguide.com", "中国旅游指南"},
		{"Booking Holdings", "https://www.bookingholdings.com", "旅行集团"},
		{"Secret Escapes", "https://www.secretescapes.com", "豪华酒店折扣"},
		{"HotelTonight", "https://www.hoteltonight.com", "当晚酒店特价"},
		{"Trivago", "https://www.trivago.com", "酒店比价"},
		{"Priceline", "https://www.priceline.com", "旅行折扣"},
		{"CheapOair", "https://www.cheapoair.com", "廉价机票"},
		{"Scott's Cheap Flights", "https://scottscheapflights.com", "特价机票提醒"},
		{"Secret Flying", "https://www.secretflying.com", "错误票价提醒"},
		{"The Points Guy", "https://thepointsguy.com", "里程积分攻略"},
		{"FlyerTalk", "https://www.flyertalk.com", "飞客论坛"},
		{"AwardWallet", "https://awardwallet.com", "里程管理"},
		{"ExpertFlyer", "https://www.expertflyer.com", "航班信息"},
		{"Flightradar24", "https://www.flightradar24.com", "实时航班追踪"},
		{"FlightAware", "https://flightaware.com", "航班状态追踪"},
		{"SkyVector", "https://skyvector.com", "航空地图"},
		{"Google Earth", "https://earth.google.com", "虚拟地球"},
		{"Mapillary", "https://www.mapillary.com", "街景地图"},
		{"OpenStreetMap Travel", "https://www.openstreetmap.org", "开源旅行地图"},
		{"iOverlander", "https://www.ioverlander.com", "自驾露营地"},
		{"Park4Night", "https://park4night.com", "欧洲房车停靠"},
		{"Campendium", "https://www.campendium.com", "美国露营地"},
		{"Recreation.gov", "https://www.recreation.gov", "美国公园预订"},
		{"AllTrails", "https://www.alltrails.com", "徒步路线"},
		{"Komoot", "https://www.komoot.com", "户外路线规划"},
		{"Wikiloc", "https://www.wikiloc.com", "GPS路线分享"},
		{"Gaia GPS", "https://www.gaiagps.com", "户外GPS地图"},
		{"ViewRanger", "https://www.viewranger.com", "户外导航"},
		{"PeakVisor", "https://peakvisor.com", "山峰识别"},
		{"两步路", "https://www.2bulu.com", "中国户外路线"},
	}
}

func foodEx() []S {
	return []S{
		{"Yelp", "https://www.yelp.com", "餐厅点评"},
		{"Zomato", "https://www.zomato.com", "全球餐厅点评"},
		{"OpenTable", "https://www.opentable.com", "餐厅预订"},
		{"Resy", "https://resy.com", "高端餐厅预订"},
		{"TheFork", "https://www.thefork.com", "欧洲餐厅预订"},
		{"DoorDash", "https://www.doordash.com", "美国外卖"},
		{"Uber Eats", "https://www.ubereats.com", "Uber外卖"},
		{"Grubhub", "https://www.grubhub.com", "美国外卖平台"},
		{"Postmates", "https://postmates.com", "即时配送"},
		{"Deliveroo", "https://deliveroo.com", "英国外卖"},
		{"Just Eat", "https://www.just-eat.com", "欧洲外卖"},
		{"Foodpanda", "https://www.foodpanda.com", "亚洲外卖"},
		{"Swiggy", "https://www.swiggy.com", "印度外卖"},
		{"Rappi", "https://www.rappi.com", "拉美外卖"},
		{"iFood", "https://www.ifood.com.br", "巴西外卖"},
		{"饿了么", "https://www.ele.me", "中国外卖平台"},
		{"美团外卖", "https://waimai.meituan.com", "中国外卖"},
		{"大众点评", "https://www.dianping.com", "中国餐厅点评"},
		{"下厨房", "https://www.xiachufang.com", "中国菜谱社区"},
		{"豆果美食", "https://www.douguo.com", "中国美食平台"},
		{"日食记", "https://www.rishiji.com", "美食视频"},
		{"AllRecipes", "https://www.allrecipes.com", "菜谱大全"},
		{"Food Network", "https://www.foodnetwork.com", "美食电视"},
		{"Bon Appétit", "https://www.bonappetit.com", "美食杂志"},
		{"Epicurious", "https://www.epicurious.com", "美食菜谱"},
		{"Serious Eats", "https://www.seriouseats.com", "美食科学"},
		{"Taste of Home", "https://www.tasteofhome.com", "家常菜谱"},
		{"Simply Recipes", "https://www.simplyrecipes.com", "简易菜谱"},
		{"Delish", "https://www.delish.com", "美食灵感"},
		{"Tasty", "https://tasty.co", "BuzzFeed美食"},
		{"BBC Good Food", "https://www.bbcgoodfood.com", "BBC美食"},
		{"Jamie Oliver", "https://www.jamieoliver.com", "Jamie Oliver菜谱"},
		{"NYT Cooking", "https://cooking.nytimes.com", "纽约时报菜谱"},
		{"Food52", "https://food52.com", "美食社区"},
		{"Kitchn", "https://www.thekitchn.com", "厨房生活"},
		{"Cookpad", "https://cookpad.com", "全球菜谱分享"},
		{"Yummly", "https://www.yummly.com", "智能菜谱推荐"},
		{"Supercook", "https://www.supercook.com", "食材搜菜谱"},
		{"MyFitnessPal", "https://www.myfitnesspal.com", "卡路里追踪"},
		{"Cronometer", "https://cronometer.com", "营养追踪"},
		{"Eat This Much", "https://www.eatthismuch.com", "饮食计划"},
		{"Mealime", "https://www.mealime.com", "健康餐计划"},
		{"PlateJoy", "https://www.platejoy.com", "个性化饮食"},
		{"Spoonacular", "https://spoonacular.com", "食品API"},
		{"Edamam", "https://www.edamam.com", "营养分析API"},
		{"FatSecret", "https://www.fatsecret.com", "卡路里计数"},
		{"Noom", "https://www.noom.com", "减重教练"},
		{"Weight Watchers", "https://www.weightwatchers.com", "WW减重"},
		{"HelloFresh", "https://www.hellofresh.com", "食材配送"},
		{"Blue Apron", "https://www.blueapron.com", "食材配送"},
		{"Home Chef", "https://www.homechef.com", "家庭料理包"},
		{"Sunbasket", "https://sunbasket.com", "有机食材配送"},
		{"Freshly", "https://www.freshly.com", "即食餐配送"},
		{"Factor", "https://www.factor75.com", "健身餐配送"},
		{"Tovala", "https://www.tovala.com", "智能烤箱+餐食"},
		{"Instacart", "https://www.instacart.com", "生鲜配送"},
		{"FreshDirect", "https://www.freshdirect.com", "生鲜电商"},
		{"Thrive Market", "https://thrivemarket.com", "有机食品电商"},
		{"iHerb", "https://www.iherb.com", "保健品电商"},
		{"Wine.com", "https://www.wine.com", "葡萄酒电商"},
		{"Vivino", "https://www.vivino.com", "葡萄酒评分"},
		{"Untappd", "https://untappd.com", "精酿啤酒社区"},
		{"CellarTracker", "https://www.cellartracker.com", "酒窖管理"},
		{"Distiller", "https://distiller.com", "威士忌评分"},
		{"Michelin Guide", "https://guide.michelin.com", "米其林指南"},
		{"The World's 50 Best", "https://www.theworlds50best.com", "全球50最佳餐厅"},
		{"La Liste", "https://laliste.com", "全球餐厅排名"},
		{"TasteAtlas", "https://www.tasteatlas.com", "世界美食地图"},
		{"Eater", "https://www.eater.com", "美食新闻"},
		{"Infatuation", "https://www.theinfatuation.com", "餐厅推荐"},
		{"Punch", "https://punchdrink.com", "鸡尾酒杂志"},
		{"Cocktail Party", "https://www.cocktailpartyapp.com", "鸡尾酒配方"},
		{"Difford's Guide", "https://www.diffordsguide.com", "鸡尾酒百科"},
		{"ChefSteps", "https://www.chefsteps.com", "烹饪技巧"},
		{"America's Test Kitchen", "https://www.americastestkitchen.com", "厨房测试"},
		{"Cook's Illustrated", "https://www.cooksillustrated.com", "烹饪科学"},
		{"Milk Street", "https://www.177milkstreet.com", "全球烹饪"},
		{"King Arthur Baking", "https://www.kingarthurbaking.com", "烘焙配方"},
		{"Sally's Baking", "https://sallysbakingaddiction.com", "烘焙博客"},
		{"Preppy Kitchen", "https://preppykitchen.com", "甜点烘焙"},
		{"Maangchi", "https://www.maangchi.com", "韩国料理"},
		{"Just One Cookbook", "https://www.justonecookbook.com", "日本料理"},
		{"Woks of Life", "https://thewoksoflife.com", "中餐菜谱"},
		{"RecipeTin Eats", "https://www.recipetineats.com", "家常菜谱"},
		{"Budget Bytes", "https://www.budgetbytes.com", "省钱菜谱"},
		{"Minimalist Baker", "https://minimalistbaker.com", "简单素食"},
		{"Oh She Glows", "https://ohsheglows.com", "纯素菜谱"},
		{"Cookie and Kate", "https://cookieandkate.com", "素食博客"},
		{"Ambitious Kitchen", "https://www.ambitiouskitchen.com", "健康菜谱"},
		{"Half Baked Harvest", "https://www.halfbakedharvest.com", "美食博客"},
		{"Damn Delicious", "https://damndelicious.net", "快手菜谱"},
		{"Pinch of Yum", "https://pinchofyum.com", "美食摄影博客"},
		{"Love and Lemons", "https://www.loveandlemons.com", "素食菜谱"},
		{"Smitten Kitchen", "https://smittenkitchen.com", "纽约美食博客"},
		{"Pioneer Woman", "https://www.thepioneerwoman.com", "家常菜博客"},
		{"Gimme Some Oven", "https://www.gimmesomeoven.com", "简易菜谱"},
		{"Well Plated", "https://www.wellplated.com", "健康菜谱"},
		{"Cafe Delites", "https://cafedelites.com", "低卡菜谱"},
		{"Skinnytaste", "https://www.skinnytaste.com", "减脂菜谱"},
		{"Dished", "https://dailyhive.com/dished", "加拿大美食"},
		{"Eater London", "https://london.eater.com", "伦敦美食"},
		{"Time Out Food", "https://www.timeout.com/food-drink", "城市美食指南"},
		{"ChefGPT", "https://www.chefgpt.xyz", "AI菜谱生成"},
		{"Whisk", "https://whisk.com", "菜谱管理"},
		{"Paprika", "https://www.paprikaapp.com", "菜谱管理App"},
		{"CopyMeThat", "https://www.copymethat.com", "菜谱剪藏"},
		{"Pepperplate", "https://www.pepperplate.com", "菜谱整理"},
		{"Mealie", "https://mealie.io", "自托管菜谱"},
		{"Tandoor Recipes", "https://tandoor.dev", "开源菜谱管理"},
		{"Grocy", "https://grocy.info", "家庭食品管理"},
		{"AnyList", "https://www.anylist.com", "购物清单"},
		{"OurGroceries", "https://www.ourgroceries.com", "共享购物清单"},
		{"Mealboard", "https://www.mealboardapp.com", "膳食规划"},
		{"Plan to Eat", "https://www.plantoeat.com", "菜谱+购物规划"},
		{"Cookstr", "https://www.cookstr.com", "名厨菜谱"},
		{"Great British Chefs", "https://www.greatbritishchefs.com", "英国名厨"},
		{"Fine Dining Lovers", "https://www.finedininglovers.com", "高端美食"},
		{"Chowhound", "https://www.chowhound.com", "美食讨论"},
		{"Saveur", "https://www.saveur.com", "美食文化"},
		{"Tasting Table", "https://www.tastingtable.com", "美食新闻"},
	}
}

func healthEx() []S {
	return []S{
		{"Mayo Clinic", "https://www.mayoclinic.org", "医学百科"},
		{"Cleveland Clinic", "https://my.clevelandclinic.org", "健康资讯"},
		{"Johns Hopkins Medicine", "https://www.hopkinsmedicine.org", "医学信息"},
		{"Healthline", "https://www.healthline.com", "健康信息平台"},
		{"Medical News Today", "https://www.medicalnewstoday.com", "医学新闻"},
		{"Verywell Health", "https://www.verywellhealth.com", "健康知识"},
		{"Everyday Health", "https://www.everydayhealth.com", "日常健康"},
		{"Health.com", "https://www.health.com", "健康生活"},
		{"Drugs.com", "https://www.drugs.com", "药物信息"},
		{"RxList", "https://www.rxlist.com", "药物百科"},
		{"GoodRx", "https://www.goodrx.com", "药价比较"},
		{"Epocrates", "https://www.epocrates.com", "临床药物参考"},
		{"UpToDate", "https://www.uptodate.com", "临床决策支持"},
		{"Medscape", "https://www.medscape.com", "医学专业资讯"},
		{"PubMed Central", "https://www.ncbi.nlm.nih.gov/pmc", "生物医学文献"},
		{"ClinicalTrials", "https://clinicaltrials.gov", "临床试验注册"},
		{"Zocdoc", "https://www.zocdoc.com", "在线预约医生"},
		{"Practo", "https://www.practo.com", "印度医疗平台"},
		{"Doctor On Demand", "https://www.doctorondemand.com", "远程医疗"},
		{"Teladoc", "https://www.teladoc.com", "远程问诊"},
		{"Amwell", "https://amwell.com", "在线医疗"},
		{"MDLive", "https://www.mdlive.com", "远程医疗"},
		{"PlushCare", "https://plushcare.com", "在线医生"},
		{"K Health", "https://khealth.com", "AI健康助手"},
		{"Ada Health", "https://ada.com", "AI症状检查"},
		{"Babylon Health", "https://www.babylonhealth.com", "AI医疗"},
		{"Symptomate", "https://symptomate.com", "症状检查器"},
		{"Isabel", "https://symptomchecker.isabelhealthcare.com", "症状诊断"},
		{"好大夫在线", "https://www.haodf.com", "中国在线问诊"},
		{"丁香园", "https://www.dxy.cn", "中国医学社区"},
		{"微医", "https://www.guahao.com", "中国互联网医院"},
		{"春雨医生", "https://www.chunyuyisheng.com", "在线问诊"},
		{"平安好医生", "https://www.jk.cn", "在线医疗服务"},
		{"健康160", "https://www.91160.com", "预约挂号"},
		{"Fitbit", "https://www.fitbit.com", "健身追踪器"},
		{"Garmin Health", "https://www.garmin.com/health", "健康监测"},
		{"Apple Health", "https://www.apple.com/health", "苹果健康"},
		{"Samsung Health", "https://www.samsung.com/health", "三星健康"},
		{"Oura", "https://ouraring.com", "智能戒指"},
		{"Whoop", "https://www.whoop.com", "运动恢复追踪"},
		{"Withings", "https://www.withings.com", "智能健康设备"},
		{"Peloton", "https://www.onepeloton.com", "智能健身"},
		{"Calm", "https://www.calm.com", "冥想放松"},
		{"Headspace", "https://www.headspace.com", "冥想应用"},
		{"Insight Timer", "https://insighttimer.com", "冥想定时器"},
		{"Waking Up", "https://www.wakingup.com", "冥想课程"},
		{"Ten Percent Happier", "https://www.tenpercent.com", "冥想播客"},
		{"BetterHelp", "https://www.betterhelp.com", "在线心理咨询"},
		{"Talkspace", "https://www.talkspace.com", "在线心理治疗"},
		{"Cerebral", "https://getcerebral.com", "心理健康平台"},
		{"7 Cups", "https://www.7cups.com", "情绪支持"},
		{"Crisis Text Line", "https://www.crisistextline.org", "危机短信热线"},
		{"壹心理", "https://www.xinli001.com", "中国心理健康"},
		{"简单心理", "https://www.jiandanxinli.com", "心理咨询平台"},
		{"Strava", "https://www.strava.com", "运动社交"},
		{"Nike Training Club", "https://www.nike.com/ntc-app", "Nike训练"},
		{"Adidas Running", "https://www.adidas.com/running", "adidas跑步"},
		{"MapMyRun", "https://www.mapmyrun.com", "跑步追踪"},
		{"Runkeeper", "https://runkeeper.com", "跑步记录"},
		{"Couch to 5K", "https://www.c25k.com", "跑步入门"},
		{"Yoga With Adriene", "https://yogawithadriene.com", "瑜伽视频"},
		{"Down Dog", "https://www.downdogapp.com", "瑜伽App"},
		{"Alo Moves", "https://www.alomoves.com", "瑜伽健身课程"},
		{"Glo", "https://www.glo.com", "瑜伽冥想"},
		{"Blogilates", "https://www.blogilates.com", "健身博客"},
		{"DAREBEE", "https://darebee.com", "免费健身计划"},
		{"Bodybuilding.com", "https://www.bodybuilding.com", "健身资源"},
		{"Muscle & Fitness", "https://www.muscleandfitness.com", "健身杂志"},
		{"Men's Health", "https://www.menshealth.com", "男性健康"},
		{"Women's Health", "https://www.womenshealthmag.com", "女性健康"},
		{"Prevention", "https://www.prevention.com", "预防医学"},
		{"Self", "https://www.self.com", "健康生活"},
		{"Shape", "https://www.shape.com", "女性健身"},
		{"Runner's World", "https://www.runnersworld.com", "跑步世界"},
		{"Bicycling", "https://www.bicycling.com", "骑行杂志"},
		{"Outside", "https://www.outsideonline.com", "户外运动"},
		{"GQ Fitness", "https://www.gq.com/about/fitness", "男性健身"},
		{"WebMD", "https://www.webmd.com", "医学百科"},
		{"NHS", "https://www.nhs.uk", "英国国民健康服务"},
		{"WHO", "https://www.who.int", "世界卫生组织"},
		{"CDC", "https://www.cdc.gov", "美国疾控中心"},
		{"NIH", "https://www.nih.gov", "美国国立卫生研究院"},
		{"MedlinePlus", "https://medlineplus.gov", "医学图书馆"},
		{"Patient.info", "https://patient.info", "英国健康信息"},
		{"Merck Manual", "https://www.merckmanuals.com", "默克医学手册"},
		{"BMJ", "https://www.bmj.com", "英国医学期刊"},
		{"The Lancet", "https://www.thelancet.com", "柳叶刀"},
		{"NEJM", "https://www.nejm.org", "新英格兰医学"},
		{"JAMA", "https://jamanetwork.com", "美国医学会杂志"},
		{"Nature Medicine", "https://www.nature.com/nm", "自然医学"},
		{"Cochrane", "https://www.cochranelibrary.com", "循证医学"},
		{"Examine.com", "https://examine.com", "营养补剂研究"},
		{"Labdoor", "https://labdoor.com", "补剂质量评估"},
		{"ConsumerLab", "https://www.consumerlab.com", "保健品测评"},
		{"Nutritics", "https://www.nutritics.com", "营养分析软件"},
		{"Cronometer Pro", "https://cronometer.com/pro", "专业营养追踪"},
		{"Precision Nutrition", "https://www.precisionnutrition.com", "营养教练"},
		{"NASM", "https://www.nasm.org", "运动医学认证"},
		{"ACE Fitness", "https://www.acefitness.org", "健身教练认证"},
		{"ACSM", "https://www.acsm.org", "运动医学学会"},
		{"Human API", "https://www.humanapi.co", "健康数据API"},
		{"Validic", "https://validic.com", "健康数据平台"},
		{"23andMe", "https://www.23andme.com", "基因检测"},
		{"AncestryDNA", "https://www.ancestry.com/dna", "祖源基因检测"},
		{"Color Health", "https://www.color.com", "基因健康筛查"},
		{"Invitae", "https://www.invitae.com", "基因检测"},
		{"Tempus", "https://www.tempus.com", "精准医疗"},
		{"Foundation Medicine", "https://www.foundationmedicine.com", "肿瘤基因"},
		{"Ro", "https://ro.co", "在线健康服务"},
		{"Hims", "https://www.forhims.com", "男性健康"},
		{"Nurx", "https://www.nurx.com", "处方药配送"},
		{"Alto Pharmacy", "https://www.alto.com", "药房配送"},
		{"Capsule", "https://www.capsule.com", "智能药房"},
		{"Carbon Health", "https://carbonhealth.com", "混合医疗"},
		{"One Medical", "https://www.onemedical.com", "会员制诊所"},
		{"Forward", "https://goforward.com", "AI医疗诊所"},
		{"Parsley Health", "https://www.parsleyhealth.com", "功能医学"},
		{"Thirty Madison", "https://www.thirtymadison.com", "慢病管理"},
		{"Omada Health", "https://www.omadahealth.com", "数字慢病管理"},
		{"Livongo", "https://www.livongo.com", "慢病管理"},
		{"Nuvance Health", "https://www.nuvancehealth.org", "健康网络"},
		{"Keep", "https://www.gotokeep.com", "中国健身App"},
		{"薄荷健康", "https://www.boohee.com", "中国减脂平台"},
	}
}

func sportsEx() []S {
	return []S{
		{"BBC Sport", "https://www.bbc.com/sport", "BBC体育"},
		{"Sky Sports", "https://www.skysports.com", "Sky体育"},
		{"Bleacher Report", "https://bleacherreport.com", "体育新闻"},
		{"The Athletic", "https://theathletic.com", "深度体育报道"},
		{"Deadspin", "https://deadspin.com", "体育博客"},
		{"SB Nation", "https://www.sbnation.com", "体育社区"},
		{"CBS Sports", "https://www.cbssports.com", "CBS体育"},
		{"Fox Sports", "https://www.foxsports.com", "Fox体育"},
		{"NBC Sports", "https://www.nbcsports.com", "NBC体育"},
		{"Yahoo Sports", "https://sports.yahoo.com", "雅虎体育"},
		{"SI", "https://www.si.com", "体育画报"},
		{"Sporting News", "https://www.sportingnews.com", "体育新闻"},
		{"Goal.com", "https://www.goal.com", "足球新闻"},
		{"FourFourTwo", "https://www.fourfourtwo.com", "足球杂志"},
		{"WhoScored", "https://www.whoscored.com", "足球数据"},
		{"Transfermarkt", "https://www.transfermarkt.com", "足球转会市场"},
		{"SofaScore", "https://www.sofascore.com", "比分直播"},
		{"FlashScore", "https://www.flashscore.com", "实时比分"},
		{"LiveScore", "https://www.livescore.com", "即时比分"},
		{"365Scores", "https://www.365scores.com", "比分新闻"},
		{"FotMob", "https://www.fotmob.com", "足球实时数据"},
		{"NFL", "https://www.nfl.com", "美式橄榄球"},
		{"NBA", "https://www.nba.com", "美国篮球"},
		{"MLB", "https://www.mlb.com", "美国棒球"},
		{"NHL", "https://www.nhl.com", "北美冰球"},
		{"MLS", "https://www.mlssoccer.com", "美国足球大联盟"},
		{"Premier League", "https://www.premierleague.com", "英超联赛"},
		{"La Liga", "https://www.laliga.com", "西甲联赛"},
		{"Serie A", "https://www.legaseriea.it", "意甲联赛"},
		{"Bundesliga", "https://www.bundesliga.com", "德甲联赛"},
		{"Ligue 1", "https://www.ligue1.com", "法甲联赛"},
		{"UEFA", "https://www.uefa.com", "欧洲足联"},
		{"FIFA", "https://www.fifa.com", "国际足联"},
		{"Olympics", "https://olympics.com", "奥运会"},
		{"World Athletics", "https://worldathletics.org", "世界田径"},
		{"FIBA", "https://www.fiba.basketball", "国际篮联"},
		{"ITF Tennis", "https://www.itftennis.com", "国际网联"},
		{"ATP Tour", "https://www.atptour.com", "ATP网球"},
		{"WTA Tennis", "https://www.wtatennis.com", "WTA网球"},
		{"F1", "https://www.formula1.com", "一级方程式"},
		{"MotoGP", "https://www.motogp.com", "摩托GP"},
		{"NASCAR", "https://www.nascar.com", "纳斯卡赛车"},
		{"IndyCar", "https://www.indycar.com", "印地赛车"},
		{"WRC", "https://www.wrc.com", "世界拉力赛"},
		{"UFC", "https://www.ufc.com", "综合格斗"},
		{"WWE", "https://www.wwe.com", "世界摔角娱乐"},
		{"Boxing News", "https://www.boxingnewsonline.net", "拳击新闻"},
		{"Cricket", "https://www.icc-cricket.com", "国际板球"},
		{"ESPNcricinfo", "https://www.espncricinfo.com", "板球数据"},
		{"Rugby World", "https://www.rugbyworld.com", "橄榄球"},
		{"World Rugby", "https://www.world.rugby", "世界橄榄球"},
		{"PGA Tour", "https://www.pgatour.com", "PGA高尔夫"},
		{"Golf Digest", "https://www.golfdigest.com", "高尔夫杂志"},
		{"Cycling News", "https://www.cyclingnews.com", "自行车赛事"},
		{"Swimming World", "https://www.swimmingworldmagazine.com", "游泳世界"},
		{"FIS Ski", "https://www.fis-ski.com", "国际滑雪联合会"},
		{"World Surf League", "https://www.worldsurfleague.com", "世界冲浪联盟"},
		{"虎扑体育", "https://www.hupu.com", "中国体育社区"},
		{"懂球帝", "https://www.dongqiudi.com", "中国足球社区"},
		{"直播吧", "https://www.zhibo8.cc", "体育直播"},
		{"雪球体育", "https://xueqiu.com/sports", "体育投资"},
		{"PP体育", "https://www.ppsport.com", "体育直播"},
		{"新浪体育", "https://sports.sina.com.cn", "新浪体育"},
		{"腾讯体育", "https://sports.qq.com", "腾讯体育"},
		{"网易体育", "https://sports.163.com", "网易体育"},
		{"CBA", "https://www.cba.net.cn", "中国篮球"},
		{"中超联赛", "https://www.thecsl.cn", "中国足球"},
		{"StatMuse", "https://www.statmuse.com", "体育AI问答"},
		{"Basketball Reference", "https://www.basketball-reference.com", "篮球数据"},
		{"Baseball Reference", "https://www.baseball-reference.com", "棒球数据"},
		{"Pro Football Reference", "https://www.pro-football-reference.com", "橄榄球数据"},
		{"Hockey Reference", "https://www.hockey-reference.com", "冰球数据"},
		{"FBref", "https://fbref.com", "足球统计"},
		{"Understat", "https://understat.com", "足球预期进球"},
		{"DAZN", "https://www.dazn.com", "体育流媒体"},
		{"FuboTV", "https://www.fubo.tv", "体育直播电视"},
		{"Sling TV Sports", "https://www.sling.com", "体育流媒体"},
		{"FloSports", "https://www.flosports.tv", "小众体育直播"},
		{"Bally Sports", "https://www.ballysports.com", "区域体育"},
		{"TUDN", "https://www.tudn.com", "西语体育"},
		{"beIN Sports", "https://www.beinsports.com", "中东体育"},
		{"Kayo Sports", "https://kayosports.com.au", "澳洲体育直播"},
		{"Hotstar Sports", "https://www.hotstar.com/in/sports", "印度体育"},
		{"Fantasy Premier League", "https://fantasy.premierleague.com", "英超梦幻足球"},
		{"Yahoo Fantasy", "https://sports.yahoo.com/fantasy", "雅虎梦幻体育"},
		{"DraftKings", "https://www.draftkings.com", "每日梦幻体育"},
		{"FanDuel", "https://www.fanduel.com", "梦幻体育"},
		{"Sleeper", "https://sleeper.com", "梦幻体育社交"},
		{"FantasyPros", "https://www.fantasypros.com", "梦幻体育建议"},
		{"RotoWire", "https://www.rotowire.com", "梦幻体育数据"},
		{"NumberFire", "https://www.numberfire.com", "体育分析"},
		{"Odds Shark", "https://www.oddsshark.com", "赔率分析"},
		{"Action Network", "https://www.actionnetwork.com", "体育博彩分析"},
		{"The Ringer", "https://www.theringer.com", "体育文化"},
		{"Defector", "https://defector.com", "体育媒体"},
		{"TrainingPeaks", "https://www.trainingpeaks.com", "运动训练平台"},
		{"Today's Plan", "https://www.todaysplan.com.au", "运动计划"},
		{"Final Surge", "https://www.finalsurge.com", "训练日志"},
		{"Garmin Connect", "https://connect.garmin.com", "Garmin运动"},
		{"Polar Flow", "https://flow.polar.com", "Polar运动"},
		{"COROS", "https://www.coros.com", "运动手表"},
		{"Suunto App", "https://www.suunto.com/suunto-app", "Suunto运动"},
		{"Zwift", "https://www.zwift.com", "虚拟骑行跑步"},
		{"Wahoo Fitness", "https://www.wahoofitness.com", "骑行训练"},
		{"Rouvy", "https://rouvy.com", "虚拟骑行"},
		{"TrainerRoad", "https://www.trainerroad.com", "骑行训练计划"},
		{"Xert", "https://www.xertonline.com", "AI骑行训练"},
		{"Intervals.icu", "https://intervals.icu", "运动分析"},
		{"Stryd", "https://www.stryd.com", "跑步功率计"},
		{"RunningAhead", "https://www.runningahead.com", "跑步日志"},
		{"SmashRun", "https://smashrun.com", "跑步数据"},
		{"Athlinks", "https://www.athlinks.com", "比赛成绩"},
		{"UltraSignup", "https://ultrasignup.com", "超马报名"},
		{"MarathonGuide", "https://www.marathonguide.com", "马拉松指南"},
		{"Parkrun", "https://www.parkrun.com", "公园跑"},
		{"MySwimPro", "https://myswimpro.com", "游泳训练"},
		{"SwimSwam", "https://swimswam.com", "游泳新闻"},
		{"Climbing Magazine", "https://www.climbing.com", "攀岩杂志"},
		{"Mountain Project", "https://www.mountainproject.com", "攀岩路线"},
	}
}

func realEstateEx() []S {
	return []S{
		{"Redfin", "https://www.redfin.com", "美国房产"},
		{"Realtor.com", "https://www.realtor.com", "美国房源"},
		{"Trulia", "https://www.trulia.com", "美国租售房"},
		{"Apartments.com", "https://www.apartments.com", "美国公寓"},
		{"Rent.com", "https://www.rent.com", "美国租房"},
		{"HotPads", "https://hotpads.com", "地图租房"},
		{"Compass", "https://www.compass.com", "美国房产经纪"},
		{"Opendoor", "https://www.opendoor.com", "即时买卖房"},
		{"Offerpad", "https://www.offerpad.com", "快速卖房"},
		{"Knock", "https://www.knock.com", "先买后卖"},
		{"HomeLight", "https://www.homelight.com", "找房产经纪"},
		{"Homesnap", "https://www.homesnap.com", "房产搜索"},
		{"LoopNet", "https://www.loopnet.com", "商业地产"},
		{"CoStar", "https://www.costar.com", "商业地产数据"},
		{"CREXi", "https://www.crexi.com", "商业地产交易"},
		{"Roofstock", "https://www.roofstock.com", "投资房产"},
		{"Fundrise", "https://fundrise.com", "房地产众筹"},
		{"RealtyMogul", "https://www.realtymogul.com", "房地产投资"},
		{"CrowdStreet", "https://www.crowdstreet.com", "房地产众筹"},
		{"Arrived Homes", "https://arrived.com", "分散式房产投资"},
		{"PropertyShark", "https://www.propertyshark.com", "房产数据"},
		{"ATTOM Data", "https://www.attomdata.com", "房产大数据"},
		{"CoreLogic", "https://www.corelogic.com", "房产分析"},
		{"Rightmove", "https://www.rightmove.co.uk", "英国房产"},
		{"Zoopla", "https://www.zoopla.co.uk", "英国房源"},
		{"OnTheMarket", "https://www.onthemarket.com", "英国房产"},
		{"Idealista", "https://www.idealista.com", "西班牙房产"},
		{"Immobilienscout24", "https://www.immobilienscout24.de", "德国房产"},
		{"SeLoger", "https://www.seloger.com", "法国房产"},
		{"Immoweb", "https://www.immoweb.be", "比利时房产"},
		{"Funda", "https://www.funda.nl", "荷兰房产"},
		{"REA Group", "https://www.rea-group.com", "澳洲房产集团"},
		{"Domain", "https://www.domain.com.au", "澳洲房产"},
		{"PropertyGuru", "https://www.propertyguru.com", "东南亚房产"},
		{"99.co", "https://www.99.co", "新加坡房产"},
		{"Housing.com", "https://housing.com", "印度房产"},
		{"MagicBricks", "https://www.magicbricks.com", "印度房源"},
		{"NoBroker", "https://www.nobroker.in", "印度免中介"},
		{"贝壳找房", "https://www.ke.com", "中国房产平台"},
		{"链家", "https://www.lianjia.com", "中国房产中介"},
		{"安居客", "https://www.anjuke.com", "中国房产信息"},
		{"58同城房产", "https://www.58.com/chuzu", "中国租房"},
		{"房天下", "https://www.fang.com", "中国房产门户"},
		{"搜房网", "https://www.soufun.com", "中国房产"},
		{"我爱我家", "https://www.5i5j.com", "中国房产中介"},
		{"自如", "https://www.ziroom.com", "中国长租公寓"},
		{"蛋壳公寓", "https://www.danke.com", "中国长租"},
		{"Houzz", "https://www.houzz.com", "家居设计"},
		{"Architectural Digest", "https://www.architecturaldigest.com", "建筑设计杂志"},
		{"Dwell", "https://www.dwell.com", "现代家居"},
		{"Dezeen", "https://www.dezeen.com", "建筑设计"},
		{"ArchDaily", "https://www.archdaily.com", "建筑日报"},
		{"Apartment Therapy", "https://www.apartmenttherapy.com", "家居生活"},
		{"The Spruce", "https://www.thespruce.com", "家居装修"},
		{"Bob Vila", "https://www.bobvila.com", "家居改造"},
		{"This Old House", "https://www.thisoldhouse.com", "老房翻新"},
		{"Family Handyman", "https://www.familyhandyman.com", "DIY家装"},
		{"IKEA", "https://www.ikea.com", "宜家家居"},
		{"Wayfair", "https://www.wayfair.com", "家居电商"},
		{"West Elm", "https://www.westelm.com", "现代家具"},
		{"CB2", "https://www.cb2.com", "现代家居"},
		{"Article", "https://www.article.com", "在线家具"},
		{"Joybird", "https://joybird.com", "定制家具"},
		{"Interior Define", "https://www.interiordefine.com", "定制沙发"},
		{"Havenly", "https://www.havenly.com", "在线室内设计"},
		{"Modsy", "https://www.modsy.com", "3D室内设计"},
		{"Roomstyler", "https://roomstyler.com", "3D房间设计"},
		{"Planner 5D", "https://planner5d.com", "房屋设计"},
		{"Floorplanner", "https://floorplanner.com", "平面图设计"},
		{"RoomSketcher", "https://www.roomsketcher.com", "房间规划"},
		{"SketchUp", "https://www.sketchup.com", "3D建模"},
		{"Sweet Home 3D", "https://www.sweethome3d.com", "免费家居设计"},
		{"HomeByMe", "https://home.by.me", "3D家居设计"},
		{"Pinterest Home", "https://www.pinterest.com/home-decor", "家居灵感"},
		{"Hunker", "https://www.hunker.com", "家居生活方式"},
		{"Emily Henderson", "https://stylebyemilyhenderson.com", "室内设计博客"},
		{"House Beautiful", "https://www.housebeautiful.com", "家居杂志"},
		{"Elle Decor", "https://www.elledecor.com", "家居装饰"},
		{"Better Homes & Gardens", "https://www.bhg.com", "家居花园"},
		{"Country Living", "https://www.countryliving.com", "乡村生活"},
		{"Real Simple", "https://www.realsimple.com", "简约生活"},
		{"Remodelista", "https://www.remodelista.com", "家居改造灵感"},
		{"Gardenista", "https://www.gardenista.com", "花园设计"},
		{"Home Depot", "https://www.homedepot.com", "家居建材"},
		{"Lowe's", "https://www.lowes.com", "家居建材"},
		{"Menards", "https://www.menards.com", "家居建材"},
		{"BuildDirect", "https://www.builddirect.com", "建材直销"},
		{"Floor & Decor", "https://www.flooranddecor.com", "地板装饰"},
		{"Tile Bar", "https://www.tilebar.com", "瓷砖商店"},
		{"Build.com", "https://www.build.com", "家居五金"},
		{"居然之家", "https://www.easyhome.com.cn", "中国家居卖场"},
		{"红星美凯龙", "https://www.macalline.com", "中国家居"},
		{"土巴兔", "https://www.to8to.com", "中国装修平台"},
		{"齐家网", "https://www.jia.com", "中国家装"},
		{"好好住", "https://www.haohaozhu.com", "家居社区"},
		{"住小帮", "https://www.zhuxiaobang.com", "家居装修"},
		{"Airbnb Plus", "https://www.airbnb.com/plus", "精选房源"},
		{"Sonder", "https://www.sonder.com", "品牌公寓"},
		{"Stay Alfred", "https://stayalfred.com", "短租公寓"},
		{"Vacasa", "https://www.vacasa.com", "度假房管理"},
		{"TurnKey", "https://www.turnkeyvr.com", "度假租赁"},
		{"Evolve", "https://www.evolve.com", "度假房管理"},
		{"Mashvisor", "https://www.mashvisor.com", "投资分析"},
		{"BiggerPockets", "https://www.biggerpockets.com", "房产投资社区"},
		{"Reonomy", "https://www.reonomy.com", "商业地产AI"},
		{"DealMachine", "https://www.dealmachine.com", "房产投资工具"},
		{"PropStream", "https://www.propstream.com", "房产数据平台"},
		{"Buildium", "https://www.buildium.com", "物业管理"},
		{"AppFolio", "https://www.appfolio.com", "物业管理软件"},
		{"RentManager", "https://www.rentmanager.com", "租赁管理"},
		{"Cozy", "https://www.cozy.co", "在线收租"},
		{"Avail", "https://www.avail.co", "房东工具"},
		{"Propy", "https://propy.com", "区块链房产"},
		{"Matterport", "https://matterport.com", "3D房产扫描"},
		{"Zillow 3D Home", "https://www.zillow.com/z/3d-home", "3D看房"},
		{"EasyKnock", "https://www.easyknock.com", "售后回租"},
		{"Divvy Homes", "https://www.divvyhomes.com", "先租后买"},
		{"Landed", "https://www.landed.com", "首付援助"},
		{"Point", "https://point.com", "房屋净值投资"},
		{"Unison", "https://www.unison.com", "共享房屋升值"},
		{"LendingTree", "https://www.lendingtree.com", "贷款比价"},
		{"Better Mortgage", "https://better.com", "在线房贷"},
		{"Rocket Mortgage", "https://www.rocketmortgage.com", "快速房贷"},
	}
}

func automotiveEx() []S {
	return []S{
		{"Car and Driver", "https://www.caranddriver.com", "汽车测评"},
		{"Motor Trend", "https://www.motortrend.com", "汽车趋势"},
		{"Top Gear", "https://www.topgear.com", "BBC汽车节目"},
		{"Jalopnik", "https://jalopnik.com", "汽车博客"},
		{"The Drive", "https://www.thedrive.com", "汽车新闻"},
		{"Road & Track", "https://www.roadandtrack.com", "赛车公路"},
		{"Autocar", "https://www.autocar.co.uk", "英国汽车杂志"},
		{"What Car", "https://www.whatcar.com", "汽车选购"},
		{"Auto Express", "https://www.autoexpress.co.uk", "英国汽车新闻"},
		{"Carwow", "https://www.carwow.co.uk", "汽车比价视频"},
		{"Edmunds", "https://www.edmunds.com", "汽车定价"},
		{"KBB", "https://www.kbb.com", "蓝皮书估价"},
		{"TrueCar", "https://www.truecar.com", "透明车价"},
		{"Cars.com", "https://www.cars.com", "美国买车"},
		{"AutoTrader", "https://www.autotrader.com", "二手车交易"},
		{"CarGurus", "https://www.cargurus.com", "车价分析"},
		{"Vroom", "https://www.vroom.com", "在线买车"},
		{"Carvana", "https://www.carvana.com", "在线二手车"},
		{"Shift", "https://shift.com", "二手车平台"},
		{"Tred", "https://www.tred.com", "P2P卖车"},
		{"Bring a Trailer", "https://bringatrailer.com", "经典车拍卖"},
		{"Hemmings", "https://www.hemmings.com", "经典车市场"},
		{"Copart", "https://www.copart.com", "事故车拍卖"},
		{"IAAI", "https://www.iaai.com", "保险车拍卖"},
		{"CarMax", "https://www.carmax.com", "二手车连锁"},
		{"Tesla", "https://www.tesla.com", "特斯拉"},
		{"Rivian", "https://rivian.com", "电动皮卡"},
		{"Lucid Motors", "https://www.lucidmotors.com", "豪华电动车"},
		{"Polestar", "https://www.polestar.com", "电动汽车"},
		{"NIO", "https://www.nio.com", "蔚来汽车"},
		{"XPeng", "https://www.xpeng.com", "小鹏汽车"},
		{"Li Auto", "https://www.lixiang.com", "理想汽车"},
		{"BYD", "https://www.byd.com", "比亚迪"},
		{"Geely", "https://www.geely.com", "吉利汽车"},
		{"Great Wall", "https://www.gwm.com.cn", "长城汽车"},
		{"ZEEKR", "https://www.zeekr.com", "极氪汽车"},
		{"Hyundai", "https://www.hyundai.com", "现代汽车"},
		{"Toyota", "https://www.toyota.com", "丰田汽车"},
		{"Honda", "https://www.honda.com", "本田汽车"},
		{"BMW", "https://www.bmw.com", "宝马汽车"},
		{"Mercedes-Benz", "https://www.mercedes-benz.com", "梅赛德斯-奔驰"},
		{"Audi", "https://www.audi.com", "奥迪汽车"},
		{"Volkswagen", "https://www.volkswagen.com", "大众汽车"},
		{"Ford", "https://www.ford.com", "福特汽车"},
		{"Chevrolet", "https://www.chevrolet.com", "雪佛兰"},
		{"Porsche", "https://www.porsche.com", "保时捷"},
		{"Volvo", "https://www.volvocars.com", "沃尔沃汽车"},
		{"Mazda", "https://www.mazda.com", "马自达"},
		{"Subaru", "https://www.subaru.com", "斯巴鲁"},
		{"Kia", "https://www.kia.com", "起亚汽车"},
		{"Nissan", "https://www.nissan.com", "日产汽车"},
		{"Lexus", "https://www.lexus.com", "雷克萨斯"},
		{"Jeep", "https://www.jeep.com", "Jeep越野"},
		{"Land Rover", "https://www.landrover.com", "路虎"},
		{"Ferrari", "https://www.ferrari.com", "法拉利"},
		{"Lamborghini", "https://www.lamborghini.com", "兰博基尼"},
		{"McLaren", "https://www.mclaren.com", "迈凯伦"},
		{"Bugatti", "https://www.bugatti.com", "布加迪"},
		{"Rolls-Royce", "https://www.rolls-roycemotorcars.com", "劳斯莱斯"},
		{"Bentley", "https://www.bentleymotors.com", "宾利"},
		{"Maserati", "https://www.maserati.com", "玛莎拉蒂"},
		{"Aston Martin", "https://www.astonmartin.com", "阿斯顿马丁"},
		{"PlugShare", "https://www.plugshare.com", "充电桩地图"},
		{"ChargePoint", "https://www.chargepoint.com", "充电网络"},
		{"Electrify America", "https://www.electrifyamerica.com", "美国充电网络"},
		{"EVgo", "https://www.evgo.com", "快充网络"},
		{"IONITY", "https://ionity.eu", "欧洲充电网络"},
		{"特来电", "https://www.teld.cn", "中国充电桩"},
		{"星星充电", "https://www.wbstar.com", "中国充电网络"},
		{"国家电网充电", "https://www.evs.sgcc.com.cn", "国网充电"},
		{"InsideEVs", "https://insideevs.com", "电动车新闻"},
		{"Electrek", "https://electrek.co", "电动交通新闻"},
		{"CleanTechnica", "https://cleantechnica.com", "清洁能源"},
		{"Green Car Reports", "https://www.greencarreports.com", "绿色汽车"},
		{"EV Specifications", "https://www.evspecifications.com", "电动车参数"},
		{"汽车之家", "https://www.autohome.com.cn", "中国汽车门户"},
		{"易车网", "https://www.yiche.com", "中国汽车平台"},
		{"太平洋汽车", "https://www.pcauto.com.cn", "汽车资讯"},
		{"爱卡汽车", "https://www.xcar.com.cn", "汽车论坛"},
		{"懂车帝", "https://www.dongchedi.com", "汽车短视频"},
		{"瓜子二手车", "https://www.guazi.com", "二手车C2C"},
		{"优信二手车", "https://www.xin.com", "二手车B2C"},
		{"人人车", "https://www.renrenche.com", "二手车平台"},
		{"天天拍车", "https://www.ttpai.cn", "卖车拍卖"},
		{"途虎养车", "https://www.tuhu.cn", "汽车养护"},
		{"RepairPal", "https://repairpal.com", "维修估价"},
		{"AutoZone", "https://www.autozone.com", "汽车零件"},
		{"O'Reilly Auto", "https://www.oreillyauto.com", "汽车配件"},
		{"RockAuto", "https://www.rockauto.com", "在线汽车零件"},
		{"Tire Rack", "https://www.tirerack.com", "轮胎商店"},
		{"CarFax", "https://www.carfax.com", "车辆历史报告"},
		{"AutoCheck", "https://www.autocheck.com", "车辆检查"},
		{"AAA", "https://www.aaa.com", "美国汽车协会"},
		{"RAC", "https://www.rac.co.uk", "英国汽车服务"},
		{"ADAC", "https://www.adac.de", "德国汽车俱乐部"},
		{"Waymo", "https://waymo.com", "自动驾驶"},
		{"Cruise", "https://getcruise.com", "自动驾驶出行"},
		{"Argo AI", "https://www.argo.ai", "自动驾驶技术"},
		{"Mobileye", "https://www.mobileye.com", "ADAS技术"},
		{"TuSimple", "https://www.tusimple.com", "自动驾驶卡车"},
		{"Aurora", "https://aurora.tech", "自动驾驶平台"},
		{"Motional", "https://motional.com", "自动驾驶"},
		{"Nuro", "https://www.nuro.ai", "无人配送车"},
		{"驾校一点通", "https://www.jxedt.com", "中国驾考学习"},
		{"驾考宝典", "https://www.jiakaobaodian.com", "驾考题库"},
		{"Hagerty", "https://www.hagerty.com", "经典车保险"},
		{"Jerry", "https://getjerry.com", "AI车险比价"},
		{"The Zebra", "https://www.thezebra.com", "车险比较"},
		{"Lemonade Car", "https://www.lemonade.com/car", "车险"},
		{"Metromile", "https://www.metromile.com", "按里程计费保险"},
		{"Root Insurance", "https://www.joinroot.com", "驾驶行为保险"},
		{"Turo", "https://turo.com", "P2P租车平台"},
		{"Getaround", "https://www.getaround.com", "共享租车"},
		{"Zipcar", "https://www.zipcar.com", "共享汽车"},
		{"GoFun出行", "https://www.gofunev.com", "共享汽车"},
		{"SpotHero", "https://spothero.com", "停车预订"},
		{"ParkMobile", "https://parkmobile.io", "移动停车"},
		{"ETCP", "https://www.etcp.cn", "中国智慧停车"},
	}
}
