package main

// Boost data for categories that need more sites to reach 10,000 total.
// These functions are called via merge() in data.go.

func searchEngineBoost() []S {
	return []S{
		{"Ecosia", "https://www.ecosia.org", "种树搜索引擎"},
		{"Qwant", "https://www.qwant.com", "法国隐私搜索"},
		{"Startpage", "https://www.startpage.com", "匿名谷歌搜索"},
		{"Dogpile", "https://www.dogpile.com", "元搜索引擎"},
		{"Swisscows", "https://swisscows.com", "瑞士隐私搜索"},
		{"Mojeek", "https://www.mojeek.com", "英国独立搜索"},
		{"Searx", "https://searx.space", "开源元搜索"},
		{"SearXNG", "https://searxng.org", "SearX新版分支"},
		{"Kagi", "https://kagi.com", "付费高质量搜索"},
		{"Wolfram Alpha", "https://www.wolframalpha.com", "计算型搜索引擎"},
		{"Ask.com", "https://www.ask.com", "问答搜索引擎"},
		{"Lycos", "https://www.lycos.com", "老牌搜索引擎"},
		{"WebCrawler", "https://www.webcrawler.com", "元搜索引擎"},
		{"MetaGer", "https://metager.org", "德国元搜索"},
		{"Marginalia Search", "https://search.marginalia.nu", "独立小站搜索"},
		{"Presearch", "https://presearch.com", "去中心化搜索"},
		{"Search Encrypt", "https://www.searchencrypt.com", "隐私搜索"},
		{"Oscobo", "https://www.oscobo.com", "英国隐私搜索"},
		{"Peekier", "https://peekier.com", "可视化搜索"},
		{"Exalead", "https://www.exalead.com", "达索搜索引擎"},
		{"ZapMeta", "https://www.zapmeta.com", "元搜索聚合"},
		{"InfoSpace", "https://www.infospace.com", "元搜索平台"},
		{"SearchScene", "https://www.searchscene.com", "慈善搜索引擎"},
		{"Yandex", "https://yandex.com", "俄罗斯搜索引擎"},
		{"Naver", "https://www.naver.com", "韩国搜索引擎"},
		{"Daum", "https://www.daum.net", "韩国门户搜索"},
		{"Cốc Cốc", "https://coccoc.com", "越南搜索引擎"},
		{"Seznam", "https://www.seznam.cz", "捷克搜索引擎"},
		{"Baidu学术", "https://xueshu.baidu.com", "学术论文搜索"},
		{"Goo", "https://www.goo.ne.jp", "日本搜索引擎"},
		{"Sogou", "https://www.sogou.com", "搜狗搜索"},
		{"360搜索", "https://www.so.com", "360搜索引擎"},
		{"神马搜索", "https://m.sm.cn", "移动搜索引擎"},
		{"头条搜索", "https://so.toutiao.com", "今日头条搜索"},
		{"微信搜一搜", "https://weixin.sogou.com", "微信内容搜索"},
		{"多吉搜索", "https://www.dogedoge.com", "中文隐私搜索"},
		{"秘塔搜索", "https://metaso.cn", "AI搜索引擎"},
		{"天工AI搜索", "https://www.tiangong.cn", "AI搜索引擎"},
		{"夸克搜索", "https://quark.sm.cn", "智能搜索引擎"},
		{"Bing", "https://www.bing.com", "微软搜索引擎"},
		{"DuckDuckGo", "https://duckduckgo.com", "隐私搜索引擎"},
		{"Google", "https://www.google.com", "全球最大搜索"},
		{"Brave Search", "https://search.brave.com", "独立隐私搜索"},
		{"You.com", "https://you.com", "AI搜索引擎"},
		{"Phind", "https://www.phind.com", "开发者AI搜索"},
		{"Consensus", "https://consensus.app", "学术AI搜索"},
		{"Elicit", "https://elicit.org", "研究AI搜索"},
		{"iAsk.Ai", "https://iask.ai", "AI问答搜索"},
		{"Andi", "https://andisearch.com", "对话式搜索"},
		{"Google Lens", "https://lens.google.com", "图片搜索识别"},
		{"TinEye", "https://tineye.com", "反向图片搜索"},
		{"PimEyes", "https://pimeyes.com", "人脸搜索引擎"},
		{"Yandex Images", "https://yandex.com/images", "Yandex图片搜索"},
		{"Shodan", "https://www.shodan.io", "物联网搜索引擎"},
		{"Censys", "https://censys.io", "互联网设备搜索"},
		{"ZoomEye", "https://www.zoomeye.org", "网络空间搜索"},
		{"FOFA", "https://fofa.info", "网络资产搜索"},
		{"Hunter.how", "https://hunter.how", "网络空间引擎"},
		{"PublicWWW", "https://publicwww.com", "源代码搜索"},
		{"NerdyData", "https://www.nerdydata.com", "网站代码搜索"},
		{"BuiltWith", "https://builtwith.com", "网站技术栈搜索"},
		{"Wappalyzer", "https://www.wappalyzer.com", "网站技术检测"},
		{"Pipl", "https://pipl.com", "人物搜索引擎"},
		{"Spokeo", "https://www.spokeo.com", "人物信息搜索"},
		{"Namechk", "https://namechk.com", "用户名搜索"},
		{"HaveIBeenPwned", "https://haveibeenpwned.com", "数据泄露搜索"},
		{"SearchCode", "https://searchcode.com", "源码搜索引擎"},
		{"Sourcegraph", "https://sourcegraph.com", "代码搜索平台"},
		{"grep.app", "https://grep.app", "Git仓库搜索"},
		{"Libraries.io", "https://libraries.io", "开源库搜索"},
	}
}

func emailBoost() []S {
	return []S{
		{"Gmail", "https://mail.google.com", "谷歌邮箱"},
		{"Outlook", "https://outlook.live.com", "微软邮箱"},
		{"Yahoo Mail", "https://mail.yahoo.com", "雅虎邮箱"},
		{"iCloud Mail", "https://www.icloud.com/mail", "苹果邮箱"},
		{"Zoho Mail", "https://www.zoho.com/mail", "企业邮箱"},
		{"ProtonMail", "https://proton.me/mail", "加密邮箱"},
		{"Tutanota", "https://tuta.com", "端到端加密邮箱"},
		{"FastMail", "https://www.fastmail.com", "快速邮箱服务"},
		{"Hey", "https://www.hey.com", "重新定义邮箱"},
		{"Spike", "https://www.spikenow.com", "对话式邮箱"},
		{"Mailspring", "https://getmailspring.com", "开源邮件客户端"},
		{"eM Client", "https://www.emclient.com", "Windows邮件客户端"},
		{"Posteo", "https://posteo.de", "德国绿色邮箱"},
		{"Kolab Now", "https://kolabnow.com", "瑞士安全邮箱"},
		{"QQ邮箱", "https://mail.qq.com", "QQ邮箱服务"},
		{"网易邮箱", "https://mail.163.com", "网易163邮箱"},
		{"新浪邮箱", "https://mail.sina.com.cn", "新浪邮箱"},
		{"139邮箱", "https://mail.10086.cn", "移动139邮箱"},
		{"阿里邮箱", "https://mail.aliyun.com", "阿里云邮箱"},
		{"腾讯企业邮", "https://exmail.qq.com", "腾讯企业邮箱"},
		{"网易企业邮", "https://ym.163.com", "网易企业邮箱"},
		{"263企业邮", "https://www.263.net", "263企业邮箱"},
		{"Coremail", "https://www.coremail.cn", "邮件系统厂商"},
		{"Mailgun", "https://www.mailgun.com", "邮件发送API"},
		{"SendGrid", "https://sendgrid.com", "邮件发送平台"},
		{"Mailjet", "https://www.mailjet.com", "邮件营销发送"},
		{"Postmark", "https://postmarkapp.com", "事务邮件服务"},
		{"Amazon SES", "https://aws.amazon.com/ses", "AWS邮件服务"},
		{"SparkPost", "https://www.sparkpost.com", "邮件传递平台"},
		{"Mailchimp", "https://mailchimp.com", "邮件营销平台"},
		{"ConvertKit", "https://convertkit.com", "创作者邮件"},
		{"Sendinblue", "https://www.sendinblue.com", "邮件营销工具"},
		{"Campaign Monitor", "https://www.campaignmonitor.com", "邮件营销服务"},
		{"MailerLite", "https://www.mailerlite.com", "邮件营销"},
		{"Buttondown", "https://buttondown.email", "极简邮件通讯"},
		{"Revue", "https://www.getrevue.co", "Twitter通讯"},
		{"Beehiiv", "https://www.beehiiv.com", "通讯平台"},
		{"Ghost Newsletter", "https://ghost.org/newsletter", "Ghost通讯"},
		{"Substack", "https://substack.com", "付费邮件通讯"},
		{"Mailnesia", "https://mailnesia.com", "临时邮箱"},
		{"Guerrilla Mail", "https://www.guerrillamail.com", "临时匿名邮箱"},
		{"10 Minute Mail", "https://10minutemail.com", "十分钟邮箱"},
		{"Temp Mail", "https://temp-mail.org", "一次性邮箱"},
		{"ThrowAwayMail", "https://www.throwawaymail.com", "临时邮箱服务"},
		{"Mailtrap", "https://mailtrap.io", "邮件测试工具"},
		{"Litmus", "https://www.litmus.com", "邮件测试优化"},
		{"Email on Acid", "https://www.emailonacid.com", "邮件渲染测试"},
		{"Mail Tester", "https://www.mail-tester.com", "邮件评分测试"},
		{"MX Toolbox", "https://mxtoolbox.com", "邮件诊断工具"},
		{"DKIM Validator", "https://dkimvalidator.com", "DKIM验证工具"},
		{"Superhuman", "https://superhuman.com", "高效邮件客户端"},
		{"Airmail", "https://airmailapp.com", "Mac邮件客户端"},
		{"Newton Mail", "https://newtonhq.com", "跨平台邮件"},
		{"Canary Mail", "https://canarymail.io", "AI邮件客户端"},
		{"Spark", "https://sparkmailapp.com", "智能邮件客户端"},
		{"BlueMail", "https://bluemail.me", "多平台邮件"},
		{"FairEmail", "https://email.faircode.eu", "安卓隐私邮件"},
		{"K-9 Mail", "https://k9mail.app", "安卓开源邮件"},
		{"Thunderbird", "https://www.thunderbird.net", "Mozilla邮件"},
		{"Betterbird", "https://www.betterbird.eu", "Thunderbird增强"},
		{"Evolution", "https://wiki.gnome.org/Apps/Evolution", "GNOME邮件"},
		{"Claws Mail", "https://www.claws-mail.org", "轻量邮件客户端"},
		{"Mutt", "https://www.mutt.org", "终端邮件客户端"},
		{"NeoMutt", "https://neomutt.org", "Mutt增强版"},
		{"Alpine", "https://alpineapp.email", "终端邮件程序"},
		{"Mailpile", "https://www.mailpile.is", "自托管Webmail"},
		{"Modoboa", "https://modoboa.org", "邮件托管平台"},
		{"iRedMail", "https://www.iredmail.org", "邮件服务器方案"},
		{"Zimbra", "https://www.zimbra.com", "企业邮件协作"},
		{"Horde Webmail", "https://www.horde.org", "开源Webmail"},
	}
}

func financeBoost() []S {
	return []S{
		{"Yahoo Finance", "https://finance.yahoo.com", "雅虎财经"},
		{"Google Finance", "https://www.google.com/finance", "谷歌财经"},
		{"Bloomberg", "https://www.bloomberg.com", "彭博财经"},
		{"Reuters", "https://www.reuters.com", "路透社财经"},
		{"CNBC", "https://www.cnbc.com", "CNBC财经频道"},
		{"MarketWatch", "https://www.marketwatch.com", "市场观察"},
		{"Seeking Alpha", "https://seekingalpha.com", "投资分析平台"},
		{"Investopedia", "https://www.investopedia.com", "投资百科"},
		{"TradingView", "https://www.tradingview.com", "图表交易平台"},
		{"StockX", "https://stockx.com", "潮品交易平台"},
		{"Robinhood", "https://robinhood.com", "免佣金交易"},
		{"Webull", "https://www.webull.com", "智能交易平台"},
		{"Interactive Brokers", "https://www.interactivebrokers.com", "盈透证券"},
		{"Charles Schwab", "https://www.schwab.com", "嘉信理财"},
		{"Fidelity", "https://www.fidelity.com", "富达投资"},
		{"Vanguard", "https://www.vanguard.com", "先锋集团"},
		{"TD Ameritrade", "https://www.tdameritrade.com", "德美利证券"},
		{"东方财富", "https://www.eastmoney.com", "中国财经门户"},
		{"同花顺", "https://www.10jqka.com.cn", "股票行情软件"},
		{"雪球", "https://xueqiu.com", "投资者社区"},
		{"和讯网", "https://www.hexun.com", "财经资讯平台"},
		{"新浪财经", "https://finance.sina.com.cn", "新浪财经频道"},
		{"腾讯财经", "https://finance.qq.com", "腾讯财经"},
		{"网易财经", "https://money.163.com", "网易财经"},
		{"第一财经", "https://www.yicai.com", "专业财经媒体"},
		{"财联社", "https://www.cls.cn", "财经资讯"},
		{"华尔街见闻", "https://wallstreetcn.com", "全球金融资讯"},
		{"36氪Finance", "https://36kr.com/information/finance", "创投财经"},
		{"巨潮资讯", "https://www.cninfo.com.cn", "上市公司公告"},
		{"天天基金", "https://fund.eastmoney.com", "基金交易平台"},
		{"蚂蚁财富", "https://www.antfortune.com", "蚂蚁集团理财"},
		{"陆金所", "https://www.lufax.com", "综合理财平台"},
		{"理杏仁", "https://www.lixinger.com", "投资数据工具"},
		{"萝卜投研", "https://robo.datayes.com", "智能投研平台"},
		{"Wind金融终端", "https://www.wind.com.cn", "金融数据终端"},
		{"Choice数据", "https://choice.eastmoney.com", "金融数据平台"},
		{"Tushare", "https://tushare.pro", "Python金融数据"},
		{"AKShare", "https://akshare.akfamily.xyz", "开源金融数据"},
		{"JoinQuant", "https://www.joinquant.com", "聚宽量化平台"},
		{"RiceQuant", "https://www.ricequant.com", "米筐量化平台"},
		{"优矿", "https://uqer.datayes.com", "通联量化平台"},
		{"BigQuant", "https://bigquant.com", "AI量化平台"},
		{"掘金量化", "https://www.myquant.cn", "量化交易平台"},
		{"NerdWallet", "https://www.nerdwallet.com", "个人理财比较"},
		{"Credit Karma", "https://www.creditkarma.com", "免费信用评分"},
		{"Mint", "https://mint.intuit.com", "个人财务管理"},
		{"Personal Capital", "https://www.personalcapital.com", "财富管理"},
		{"YNAB", "https://www.ynab.com", "预算管理工具"},
		{"GoodBudget", "https://goodbudget.com", "信封预算法"},
		{"EveryDollar", "https://www.everydollar.com", "零基预算"},
		{"PocketGuard", "https://pocketguard.com", "支出追踪"},
		{"Honeydue", "https://www.honeydue.com", "情侣财务管理"},
		{"随手记", "https://www.sui.com", "记账理财应用"},
		{"挖财", "https://www.wacai.com", "记账工具"},
		{"鲨鱼记账", "https://www.shayujizhang.com", "简洁记账"},
		{"网商银行", "https://www.mybank.cn", "蚂蚁网商银行"},
		{"微众银行", "https://www.webank.com", "腾讯微众银行"},
		{"京东金融", "https://jr.jd.com", "京东金融服务"},
		{"度小满金融", "https://www.duxiaoman.com", "百度金融服务"},
		{"PayPal", "https://www.paypal.com", "全球支付平台"},
		{"Stripe", "https://stripe.com", "在线支付处理"},
		{"Square", "https://squareup.com", "商户支付方案"},
		{"Adyen", "https://www.adyen.com", "全球支付平台"},
		{"Klarna", "https://www.klarna.com", "先买后付"},
		{"Afterpay", "https://www.afterpay.com", "分期付款服务"},
		{"Revolut", "https://www.revolut.com", "数字银行"},
		{"N26", "https://n26.com", "欧洲数字银行"},
		{"Monzo", "https://monzo.com", "英国数字银行"},
		{"Chime", "https://www.chime.com", "美国数字银行"},
		{"Wise", "https://wise.com", "国际汇款"},
	}
}

func jobBoost() []S {
	return []S{
		{"LinkedIn Jobs", "https://www.linkedin.com/jobs", "LinkedIn求职"},
		{"Indeed", "https://www.indeed.com", "全球求职搜索"},
		{"Glassdoor", "https://www.glassdoor.com", "公司评价求职"},
		{"ZipRecruiter", "https://www.ziprecruiter.com", "AI匹配求职"},
		{"Monster", "https://www.monster.com", "老牌求职网站"},
		{"CareerBuilder", "https://www.careerbuilder.com", "求职招聘平台"},
		{"Dice", "https://www.dice.com", "科技岗位招聘"},
		{"AngelList", "https://angel.co", "创业公司工作"},
		{"Hired", "https://hired.com", "科技人才匹配"},
		{"Triplebyte", "https://triplebyte.com", "工程师评估招聘"},
		{"Underdog.io", "https://underdog.io", "创业公司求职"},
		{"The Muse", "https://www.themuse.com", "职业发展平台"},
		{"Ladders", "https://www.theladders.com", "高薪求职"},
		{"Snagajob", "https://www.snagajob.com", "小时工求职"},
		{"Remote OK", "https://remoteok.com", "远程工作列表"},
		{"We Work Remotely", "https://weworkremotely.com", "远程招聘"},
		{"FlexJobs", "https://www.flexjobs.com", "灵活工作"},
		{"Working Nomads", "https://www.workingnomads.com", "远程工作"},
		{"Remotive", "https://remotive.com", "远程工作招聘"},
		{"Himalayas", "https://himalayas.app", "远程工作平台"},
		{"JustRemote", "https://justremote.co", "远程岗位聚合"},
		{"Pangian", "https://pangian.com", "远程工作社区"},
		{"Wellfound", "https://wellfound.com", "创业求职平台"},
		{"Built In", "https://builtin.com", "科技岗位"},
		{"Crunchboard", "https://www.crunchboard.com", "TechCrunch招聘"},
		{"GitHub Jobs", "https://jobs.github.com", "开发者岗位"},
		{"HackerRank Jobs", "https://www.hackerrank.com/jobs", "编程挑战招聘"},
		{"LeetCode Jobs", "https://leetcode.com/jobs", "LeetCode招聘"},
		{"BOSS直聘", "https://www.zhipin.com", "直聊招聘平台"},
		{"前程无忧", "https://www.51job.com", "综合招聘平台"},
		{"智联招聘", "https://www.zhaopin.com", "综合招聘网站"},
		{"猎聘", "https://www.liepin.com", "中高端招聘"},
		{"拉勾", "https://www.lagou.com", "互联网招聘"},
		{"实习僧", "https://www.shixiseng.com", "实习招聘平台"},
		{"应届生求职网", "https://www.yingjiesheng.com", "校园招聘"},
		{"大街网", "https://www.dajie.com", "职业社交招聘"},
		{"猎云网招聘", "https://www.lieyunwang.com", "创业公司招聘"},
		{"牛客网", "https://www.nowcoder.com", "IT求职笔试"},
		{"赛码网", "https://www.acmcoder.com", "在线笔试平台"},
		{"Hacker News Hiring", "https://hnhiring.com", "HN招聘帖"},
		{"Jobserve", "https://www.jobserve.com", "IT合同工作"},
		{"Totaljobs", "https://www.totaljobs.com", "英国求职"},
		{"Reed", "https://www.reed.co.uk", "英国招聘网站"},
		{"Seek", "https://www.seek.com.au", "澳洲求职"},
		{"Naukri", "https://www.naukri.com", "印度招聘平台"},
		{"JobStreet", "https://www.jobstreet.com", "东南亚招聘"},
		{"Bayt", "https://www.bayt.com", "中东招聘平台"},
		{"StepStone", "https://www.stepstone.de", "德国招聘网站"},
		{"InfoJobs", "https://www.infojobs.net", "西班牙招聘"},
		{"Hays", "https://www.hays.com", "全球人才招聘"},
		{"Robert Half", "https://www.roberthalf.com", "专业人才招聘"},
		{"Michael Page", "https://www.michaelpage.com", "全球招聘顾问"},
		{"Randstad", "https://www.randstad.com", "人力资源服务"},
		{"Adecco", "https://www.adecco.com", "人力资源方案"},
		{"ManpowerGroup", "https://www.manpowergroup.com", "人力资源公司"},
		{"Kforce", "https://www.kforce.com", "IT人才方案"},
		{"Robert Walters", "https://www.robertwalters.com", "专业招聘"},
		{"Hudson", "https://www.hudson.com", "人才管理方案"},
		{"Kelly Services", "https://www.kellyservices.com", "人才服务"},
		{"Workday", "https://www.workday.com", "HR管理平台"},
		{"Greenhouse", "https://www.greenhouse.com", "招聘管理系统"},
		{"Lever", "https://www.lever.co", "招聘软件"},
		{"Workable", "https://www.workable.com", "招聘管理工具"},
		{"BambooHR", "https://www.bamboohr.com", "HR软件"},
		{"Gusto", "https://gusto.com", "薪酬HR平台"},
		{"ADP", "https://www.adp.com", "人力资源管理"},
		{"Paychex", "https://www.paychex.com", "薪资HR服务"},
		{"Rippling", "https://www.rippling.com", "员工管理平台"},
		{"Deel", "https://www.deel.com", "全球远程HR"},
		{"Oyster HR", "https://www.oysterhr.com", "全球雇佣"},
	}
}

func liveBoost() []S {
	return []S{
		{"TikTok Live", "https://www.tiktok.com/live", "TikTok直播"},
		{"Instagram Live", "https://www.instagram.com", "Instagram直播"},
		{"Facebook Live", "https://www.facebook.com/live", "Facebook直播"},
		{"Kick", "https://kick.com", "新兴直播平台"},
		{"Rumble", "https://rumble.com", "视频直播平台"},
		{"DLive", "https://dlive.tv", "区块链直播"},
		{"Trovo", "https://trovo.live", "腾讯海外直播"},
		{"Caffeine", "https://www.caffeine.tv", "社交直播"},
		{"StreamYard", "https://streamyard.com", "浏览器直播工具"},
		{"Restream", "https://restream.io", "多平台直播"},
		{"Streamlabs", "https://streamlabs.com", "直播工具套件"},
		{"OBS Studio", "https://obsproject.com", "开源直播软件"},
		{"XSplit", "https://www.xsplit.com", "直播录制工具"},
		{"Prism Live Studio", "https://prismlive.com", "移动直播工具"},
		{"花椒直播", "https://www.huajiao.com", "社交直播平台"},
		{"映客直播", "https://www.inke.cn", "泛娱乐直播"},
		{"NOW直播", "https://now.qq.com", "腾讯直播平台"},
		{"酷狗直播", "https://fanxing.kugou.com", "音乐直播"},
		{"CC直播", "https://cc.163.com", "网易游戏直播"},
		{"企鹅电竞", "https://egame.qq.com", "腾讯电竞直播"},
		{"快手直播", "https://live.kuaishou.com", "快手直播"},
		{"淘宝直播", "https://taobaolive.taobao.com", "电商直播"},
		{"京东直播", "https://live.jd.com", "京东直播"},
		{"抖音直播", "https://live.douyin.com", "抖音直播"},
		{"微信视频号直播", "https://channels.weixin.qq.com", "微信直播"},
		{"小红书直播", "https://www.xiaohongshu.com/protocols/live", "小红书直播"},
		{"Niconico", "https://live.nicovideo.jp", "日本弹幕直播"},
		{"SHOWROOM", "https://www.showroom-live.com", "日本偶像直播"},
		{"17LIVE", "https://17.live", "亚洲直播平台"},
		{"BIGO LIVE", "https://www.bigo.tv", "全球直播平台"},
	}
}

func socialBoost() []S {
	return []S{
		{"Threads", "https://www.threads.net", "Meta文字社交"},
		{"BlueSky", "https://bsky.app", "去中心化社交"},
		{"Mastodon", "https://joinmastodon.org", "开源社交网络"},
		{"Lemmy", "https://join-lemmy.org", "开源Reddit替代"},
		{"Pixelfed", "https://pixelfed.org", "开源图片社交"},
		{"Diaspora", "https://diasporafoundation.org", "去中心化社交"},
		{"Cohost", "https://cohost.org", "博客社交平台"},
		{"Hive Social", "https://www.hivesocial.app", "新兴社交平台"},
		{"T2 Social", "https://t2.social", "Twitter替代"},
		{"Post.news", "https://post.news", "新闻社交平台"},
		{"Minds", "https://www.minds.com", "自由社交平台"},
		{"MeWe", "https://mewe.com", "隐私社交网络"},
		{"Parler", "https://parler.com", "自由言论社交"},
		{"Truth Social", "https://truthsocial.com", "社交媒体平台"},
		{"Gab", "https://gab.com", "自由言论社交"},
		{"Clubhouse", "https://www.clubhouse.com", "音频社交平台"},
		{"BeReal", "https://bereal.com", "真实社交应用"},
		{"Lemon8", "https://www.lemon8-app.com", "生活方式社交"},
		{"即刻", "https://www.okjike.com", "兴趣社交平台"},
		{"绿洲", "https://www.weibo.com/oasis", "微博绿洲"},
		{"Soul", "https://www.soulapp.cn", "社交元宇宙"},
		{"Ablo", "https://www.ablo.live", "全球社交翻译"},
		{"Tandem", "https://www.tandem.net", "语言交换社交"},
		{"HelloTalk", "https://www.hellotalk.com", "语言学习社交"},
		{"Strava", "https://www.strava.com", "运动社交平台"},
		{"Letterboxd", "https://letterboxd.com", "电影社交平台"},
		{"Untappd", "https://untappd.com", "啤酒社交平台"},
		{"Vivino", "https://www.vivino.com", "红酒社交评分"},
		{"Nextdoor", "https://nextdoor.com", "邻居社交网络"},
		{"Polywork", "https://www.polywork.com", "专业社交网络"},
	}
}

func musicBoost() []S {
	return []S{
		{"Tidal", "https://tidal.com", "HiFi音乐流媒体"},
		{"Deezer", "https://www.deezer.com", "法国音乐平台"},
		{"Amazon Music", "https://music.amazon.com", "亚马逊音乐"},
		{"Pandora", "https://www.pandora.com", "个性化电台"},
		{"iHeartRadio", "https://www.iheart.com", "网络电台"},
		{"TuneIn", "https://tunein.com", "全球广播电台"},
		{"Last.fm", "https://www.last.fm", "音乐记录推荐"},
		{"Genius", "https://genius.com", "歌词解读平台"},
		{"Musixmatch", "https://www.musixmatch.com", "歌词数据库"},
		{"AZLyrics", "https://www.azlyrics.com", "歌词网站"},
		{"Rate Your Music", "https://rateyourmusic.com", "音乐评分社区"},
		{"Album of the Year", "https://www.albumoftheyear.org", "专辑评分汇总"},
		{"Pitchfork", "https://pitchfork.com", "独立音乐媒体"},
		{"NME", "https://www.nme.com", "英国音乐媒体"},
		{"Rolling Stone", "https://www.rollingstone.com", "滚石音乐杂志"},
		{"Stereogum", "https://www.stereogum.com", "独立音乐博客"},
		{"Consequence of Sound", "https://consequence.net", "音乐娱乐媒体"},
		{"Discogs", "https://www.discogs.com", "音乐数据库市场"},
		{"MusicBrainz", "https://musicbrainz.org", "开放音乐数据库"},
		{"AllMusic", "https://www.allmusic.com", "音乐百科指南"},
		{"Setlist.fm", "https://www.setlist.fm", "演出曲目数据库"},
		{"Songkick", "https://www.songkick.com", "演唱会追踪"},
		{"Bandsintown", "https://www.bandsintown.com", "现场演出追踪"},
		{"DistroKid", "https://distrokid.com", "音乐分发平台"},
		{"TuneCore", "https://www.tunecore.com", "数字音乐发行"},
		{"CD Baby", "https://cdbaby.com", "独立音乐发行"},
		{"Landr", "https://www.landr.com", "AI母带处理"},
		{"Splice", "https://splice.com", "音乐制作素材"},
		{"Loopmasters", "https://www.loopmasters.com", "采样音色库"},
		{"Native Instruments", "https://www.native-instruments.com", "音乐制作工具"},
	}
}

func shoppingBoost() []S {
	return []S{
		{"Temu", "https://www.temu.com", "拼多多海外版"},
		{"Shein", "https://www.shein.com", "快时尚电商"},
		{"Wish", "https://www.wish.com", "折扣购物平台"},
		{"AliExpress", "https://www.aliexpress.com", "阿里速卖通"},
		{"DHgate", "https://www.dhgate.com", "敦煌网跨境电商"},
		{"Mercari", "https://www.mercari.com", "二手交易平台"},
		{"Poshmark", "https://poshmark.com", "时尚二手交易"},
		{"Depop", "https://www.depop.com", "年轻人二手时尚"},
		{"ThredUp", "https://www.thredup.com", "二手时尚电商"},
		{"StockX", "https://stockx.com", "球鞋潮品交易"},
		{"GOAT", "https://www.goat.com", "球鞋认证交易"},
		{"Grailed", "https://www.grailed.com", "男士奢侈二手"},
		{"Vestiaire", "https://www.vestiairecollective.com", "奢侈品二手"},
		{"The RealReal", "https://www.therealreal.com", "奢侈品寄售"},
		{"Zappos", "https://www.zappos.com", "鞋类电商"},
		{"ASOS", "https://www.asos.com", "英国时尚电商"},
		{"Zara", "https://www.zara.com", "快时尚品牌"},
		{"H&M", "https://www.hm.com", "瑞典快时尚"},
		{"Uniqlo", "https://www.uniqlo.com", "优衣库"},
		{"Nike", "https://www.nike.com", "耐克官网"},
		{"Adidas", "https://www.adidas.com", "阿迪达斯官网"},
		{"Etsy", "https://www.etsy.com", "手工艺品市场"},
		{"Wayfair", "https://www.wayfair.com", "家居电商"},
		{"Overstock", "https://www.overstock.com", "折扣家居"},
		{"Best Buy", "https://www.bestbuy.com", "电子产品零售"},
		{"Newegg", "https://www.newegg.com", "电脑配件电商"},
		{"B&H Photo", "https://www.bhphotovideo.com", "摄影器材"},
		{"iHerb", "https://www.iherb.com", "保健品电商"},
		{"Costco Online", "https://www.costco.com", "会员仓储购物"},
		{"Walmart", "https://www.walmart.com", "沃尔玛购物"},
	}
}
