package main

// Batch 5 extension data: Hosting, Database, DevOps, Security, Frontend, Backend, Mobile Dev

func hostingEx() []S {
	return []S{
		{"GoDaddy", "https://www.godaddy.com", "域名注册"},
		{"Namecheap", "https://www.namecheap.com", "域名注册"},
		{"Google Domains", "https://domains.google", "谷歌域名"},
		{"Cloudflare Registrar", "https://www.cloudflare.com/products/registrar", "域名注册"},
		{"Hover", "https://www.hover.com", "域名注册"},
		{"Porkbun", "https://porkbun.com", "便宜域名"},
		{"Gandi", "https://www.gandi.net", "域名主机"},
		{"Name.com", "https://www.name.com", "域名注册"},
		{"Dynadot", "https://www.dynadot.com", "域名注册"},
		{"Epik", "https://www.epik.com", "域名市场"},
		{"Sedo", "https://sedo.com", "域名交易"},
		{"Afternic", "https://www.afternic.com", "域名交易"},
		{"Dan.com", "https://dan.com", "域名交易"},
		{"Domainr", "https://domainr.com", "域名搜索"},
		{"万网", "https://wanwang.aliyun.com", "中国域名注册"},
		{"DNSPod", "https://www.dnspod.cn", "DNS服务"},
		{"新网", "https://www.xinnet.com", "中国域名主机"},
		{"西部数码", "https://www.west.cn", "域名主机"},
		{"易名", "https://www.ename.com", "域名交易"},
		{"Bluehost", "https://www.bluehost.com", "主机托管"},
		{"HostGator", "https://www.hostgator.com", "主机托管"},
		{"DreamHost", "https://www.dreamhost.com", "主机托管"},
		{"SiteGround", "https://www.siteground.com", "WordPress主机"},
		{"A2 Hosting", "https://www.a2hosting.com", "高速主机"},
		{"InMotion", "https://www.inmotionhosting.com", "主机托管"},
		{"Hostinger", "https://www.hostinger.com", "便宜主机"},
		{"InterServer", "https://www.interserver.net", "主机服务"},
		{"Liquid Web", "https://www.liquidweb.com", "托管主机"},
		{"WP Engine", "https://wpengine.com", "WordPress专用"},
		{"Kinsta", "https://kinsta.com", "高性能WordPress"},
		{"Flywheel", "https://getflywheel.com", "WordPress托管"},
		{"Cloudways", "https://www.cloudways.com", "管理云主机"},
		{"RunCloud", "https://runcloud.io", "服务器管理"},
		{"ServerPilot", "https://serverpilot.io", "PHP托管"},
		{"GridPane", "https://gridpane.com", "WordPress托管"},
		{"SpinupWP", "https://spinupwp.com", "WordPress服务器"},
		{"Plesk", "https://www.plesk.com", "服务器面板"},
		{"cPanel", "https://cpanel.net", "主机面板"},
		{"DirectAdmin", "https://www.directadmin.com", "主机面板"},
		{"CyberPanel", "https://cyberpanel.net", "LiteSpeed面板"},
		{"HestiaCP", "https://hestiacp.com", "开源面板"},
		{"宝塔", "https://www.bt.cn", "中国服务器面板"},
		{"1Panel", "https://1panel.cn", "开源面板"},
		{"WordPress", "https://wordpress.org", "WordPress"},
		{"Squarespace", "https://www.squarespace.com", "建站平台"},
		{"Wix", "https://www.wix.com", "可视化建站"},
		{"Weebly", "https://www.weebly.com", "简易建站"},
		{"Webflow", "https://webflow.com", "可视化Web开发"},
		{"Framer", "https://www.framer.com", "设计建站"},
		{"Carrd", "https://carrd.co", "单页网站"},
		{"Strikingly", "https://www.strikingly.com", "建站工具"},
		{"Ghost Pro", "https://ghost.org/pricing", "Ghost托管"},
		{"Shopify", "https://www.shopify.com", "电商建站"},
		{"BigCommerce", "https://www.bigcommerce.com", "电商平台"},
		{"WooCommerce", "https://woocommerce.com", "WordPress电商"},
		{"Magento", "https://business.adobe.com/products/magento", "开源电商"},
		{"PrestaShop", "https://www.prestashop.com", "电商系统"},
		{"OpenCart", "https://www.opencart.com", "开源电商"},
		{"Gatsby Cloud", "https://www.gatsbyjs.com/cloud", "Gatsby部署"},
		{"Storyblok", "https://www.storyblok.com", "无头CMS"},
		{"Contentful", "https://www.contentful.com", "无头CMS"},
		{"Strapi", "https://strapi.io", "开源无头CMS"},
		{"Sanity", "https://www.sanity.io", "结构化CMS"},
		{"Prismic", "https://prismic.io", "无头CMS"},
		{"DatoCMS", "https://www.datocms.com", "无头CMS"},
		{"Hygraph", "https://hygraph.com", "GraphQL CMS"},
		{"Butter CMS", "https://buttercms.com", "无头CMS"},
		{"Directus", "https://directus.io", "开源数据平台"},
		{"KeystoneJS", "https://keystonejs.com", "开源CMS"},
		{"PayloadCMS", "https://payloadcms.com", "TypeScript CMS"},
		{"WordPress.com", "https://wordpress.com", "托管WordPress"},
		{"Blogger", "https://www.blogger.com", "谷歌博客"},
		{"Tumblr", "https://www.tumblr.com", "轻博客"},
		{"Hashnode", "https://hashnode.com", "开发者博客"},
		{"Hugo", "https://gohugo.io", "静态网站生成"},
		{"Jekyll", "https://jekyllrb.com", "静态博客"},
		{"Hexo", "https://hexo.io", "博客框架"},
		{"Eleventy", "https://www.11ty.dev", "静态网站"},
		{"Astro", "https://astro.build", "内容优先框架"},
		{"Zola", "https://www.getzola.org", "Rust静态生成"},
		{"Pelican", "https://getpelican.com", "Python静态生成"},
		{"GitHub Pages", "https://pages.github.com", "免费静态托管"},
		{"GitLab Pages", "https://docs.gitlab.com/ee/user/project/pages", "GitLab静态"},
		{"Surge", "https://surge.sh", "静态部署"},
		{"Tiiny Host", "https://tiiny.host", "静态托管"},
		{"Neocities", "https://neocities.org", "免费网站托管"},
		{"Glitch", "https://glitch.com", "在线代码"},
		{"Replit", "https://replit.com", "在线IDE"},
		{"CodeSandbox", "https://codesandbox.io", "在线开发环境"},
		{"StackBlitz", "https://stackblitz.com", "WebContainer"},
		{"Codepen", "https://codepen.io", "前端代码演示"},
		{"JSFiddle", "https://jsfiddle.net", "JS代码片段"},
		{"SSL.com", "https://www.ssl.com", "SSL证书"},
		{"Let's Encrypt", "https://letsencrypt.org", "免费SSL"},
		{"ZeroSSL", "https://zerossl.com", "免费SSL证书"},
		{"DigiCert", "https://www.digicert.com", "SSL证书"},
		{"Comodo SSL", "https://comodosslstore.com", "SSL证书"},
		{"SSL For Free", "https://www.sslforfree.com", "免费SSL"},
		{"Pingdom", "https://www.pingdom.com", "网站监控"},
		{"UptimeRobot", "https://uptimerobot.com", "正常运行监控"},
		{"StatusCake", "https://www.statuscake.com", "网站监控"},
	}
}

func databaseEx() []S {
	return []S{
		{"PostgreSQL", "https://www.postgresql.org", "PostgreSQL"},
		{"MySQL", "https://www.mysql.com", "MySQL"},
		{"MariaDB", "https://mariadb.org", "MariaDB"},
		{"SQLite", "https://www.sqlite.org", "SQLite"},
		{"SQL Server", "https://www.microsoft.com/en-us/sql-server", "SQL Server"},
		{"Oracle Database", "https://www.oracle.com/database", "Oracle数据库"},
		{"MongoDB", "https://www.mongodb.com", "文档数据库"},
		{"Redis", "https://redis.io", "缓存数据库"},
		{"Cassandra", "https://cassandra.apache.org", "分布式数据库"},
		{"ScyllaDB", "https://www.scylladb.com", "高性能NoSQL"},
		{"CouchDB", "https://couchdb.apache.org", "文档数据库"},
		{"RethinkDB", "https://rethinkdb.com", "实时数据库"},
		{"Neo4j", "https://neo4j.com", "图数据库"},
		{"ArangoDB", "https://www.arangodb.com", "多模型数据库"},
		{"DGraph", "https://dgraph.io", "分布式图数据库"},
		{"InfluxDB", "https://www.influxdata.com", "时序数据库"},
		{"TimescaleDB", "https://www.timescale.com", "时序PostgreSQL"},
		{"QuestDB", "https://questdb.io", "高性能时序"},
		{"ClickHouse", "https://clickhouse.com", "列式分析数据库"},
		{"Apache Druid", "https://druid.apache.org", "实时分析"},
		{"DuckDB", "https://duckdb.org", "分析型数据库"},
		{"Snowflake", "https://www.snowflake.com", "云数据仓库"},
		{"Databricks", "https://www.databricks.com", "数据+AI"},
		{"BigQuery", "https://cloud.google.com/bigquery", "谷歌数据仓库"},
		{"Redshift", "https://aws.amazon.com/redshift", "AWS数据仓库"},
		{"Synapse", "https://azure.microsoft.com/en-us/products/synapse-analytics", "Azure分析"},
		{"SingleStore", "https://www.singlestore.com", "实时数据库"},
		{"TiDB", "https://www.pingcap.com", "分布式SQL"},
		{"CockroachDB", "https://www.cockroachlabs.com", "分布式SQL"},
		{"YugabyteDB", "https://www.yugabyte.com", "分布式PostgreSQL"},
		{"Vitess", "https://vitess.io", "MySQL分片"},
		{"Citus", "https://www.citusdata.com", "分布式PostgreSQL"},
		{"FaunaDB", "https://fauna.com", "Serverless数据库"},
		{"Supabase", "https://supabase.com", "Firebase替代"},
		{"Firebase Firestore", "https://firebase.google.com/products/firestore", "NoSQL云"},
		{"DynamoDB", "https://aws.amazon.com/dynamodb", "AWS NoSQL"},
		{"Cosmos DB", "https://azure.microsoft.com/en-us/products/cosmos-db", "Azure多模型"},
		{"Cloud Spanner", "https://cloud.google.com/spanner", "全球分布式"},
		{"PlanetScale", "https://planetscale.com", "MySQL云"},
		{"Neon", "https://neon.tech", "Serverless Postgres"},
		{"Turso", "https://turso.tech", "边缘SQLite"},
		{"Xata", "https://xata.io", "Serverless数据库"},
		{"Convex", "https://www.convex.dev", "实时后端数据"},
		{"EdgeDB", "https://www.edgedb.com", "图关系型数据库"},
		{"SurrealDB", "https://surrealdb.com", "多模型数据库"},
		{"Apache HBase", "https://hbase.apache.org", "Hadoop数据库"},
		{"Apache Hive", "https://hive.apache.org", "数据仓库"},
		{"Apache Spark SQL", "https://spark.apache.org/sql", "Spark SQL"},
		{"Presto", "https://prestodb.io", "分布式SQL"},
		{"Trino", "https://trino.io", "联合查询"},
		{"Apache Flink", "https://flink.apache.org", "流处理"},
		{"Apache Kafka", "https://kafka.apache.org", "流平台"},
		{"RabbitMQ", "https://www.rabbitmq.com", "消息队列"},
		{"NATS", "https://nats.io", "消息系统"},
		{"Pulsar", "https://pulsar.apache.org", "消息流"},
		{"Memcached", "https://memcached.org", "内存缓存"},
		{"Valkey", "https://valkey.io", "Redis分叉"},
		{"KeyDB", "https://docs.keydb.dev", "多线程Redis"},
		{"DragonflyDB", "https://www.dragonflydb.io", "高性能缓存"},
		{"Milvus", "https://milvus.io", "向量数据库"},
		{"Pinecone", "https://www.pinecone.io", "向量数据库"},
		{"Weaviate", "https://weaviate.io", "向量搜索"},
		{"Qdrant", "https://qdrant.tech", "向量搜索引擎"},
		{"Chroma", "https://www.trychroma.com", "AI向量数据库"},
		{"LanceDB", "https://lancedb.com", "AI向量存储"},
		{"Elasticsearch", "https://www.elastic.co", "搜索引擎"},
		{"OpenSearch", "https://opensearch.org", "开源搜索"},
		{"Solr", "https://solr.apache.org", "搜索平台"},
		{"Meilisearch", "https://www.meilisearch.com", "搜索引擎"},
		{"Typesense", "https://typesense.org", "搜索引擎"},
		{"Algolia", "https://www.algolia.com", "搜索API"},
		{"Zinc Search", "https://zincsearch.com", "轻量搜索"},
		{"DBeaver", "https://dbeaver.io", "数据库IDE"},
		{"DataGrip", "https://www.jetbrains.com/datagrip", "JetBrains数据库"},
		{"TablePlus", "https://tableplus.com", "数据库GUI"},
		{"Beekeeper Studio", "https://www.beekeeperstudio.io", "SQL编辑器"},
		{"DbVisualizer", "https://www.dbvis.com", "数据库工具"},
		{"Adminer", "https://www.adminer.org", "轻量数据库管理"},
		{"phpMyAdmin", "https://www.phpmyadmin.net", "MySQL管理"},
		{"pgAdmin", "https://www.pgadmin.org", "PostgreSQL管理"},
		{"Prisma", "https://www.prisma.io", "Node.js ORM"},
		{"Drizzle", "https://orm.drizzle.team", "TypeScript ORM"},
		{"Sequelize", "https://sequelize.org", "Node ORM"},
		{"TypeORM", "https://typeorm.io", "TypeScript ORM"},
		{"SQLAlchemy", "https://www.sqlalchemy.org", "Python ORM"},
		{"Django ORM", "https://www.djangoproject.com", "Django ORM"},
		{"GORM", "https://gorm.io", "Go ORM"},
		{"Ent", "https://entgo.io", "Go实体框架"},
		{"Flyway", "https://flywaydb.org", "数据库迁移"},
		{"Liquibase", "https://www.liquibase.com", "数据库变更管理"},
		{"Atlas", "https://atlasgo.io", "数据库Schema管理"},
		{"DB-Engines", "https://db-engines.com", "数据库排名"},
		{"SQLBolt", "https://sqlbolt.com", "学SQL"},
		{"SQLZoo", "https://sqlzoo.net", "SQL练习"},
		{"Mode SQL", "https://mode.com/sql-tutorial", "SQL教程"},
		{"Use the Index Luke", "https://use-the-index-luke.com", "SQL索引"},
		{"DBdiagram", "https://dbdiagram.io", "数据库设计"},
		{"DrawSQL", "https://drawsql.app", "SQL可视化"},
		{"ERDPlus", "https://erdplus.com", "ER图工具"},
		{"Navicat", "https://www.navicat.com", "数据库管理"},
		{"Toad", "https://www.quest.com/toad", "数据库开发"},
	}
}

func devopsEx() []S {
	return []S{
		{"Docker", "https://www.docker.com", "容器平台"},
		{"Kubernetes", "https://kubernetes.io", "容器编排"},
		{"Podman", "https://podman.io", "无守护进程容器"},
		{"containerd", "https://containerd.io", "容器运行时"},
		{"CRI-O", "https://cri-o.io", "K8s容器运行时"},
		{"Rancher", "https://www.rancher.com", "K8s管理"},
		{"OpenShift", "https://www.redhat.com/en/technologies/cloud-computing/openshift", "红帽K8s"},
		{"Portainer", "https://www.portainer.io", "容器管理"},
		{"K3s", "https://k3s.io", "轻量K8s"},
		{"MicroK8s", "https://microk8s.io", "最小K8s"},
		{"Kind", "https://kind.sigs.k8s.io", "Docker里的K8s"},
		{"Minikube", "https://minikube.sigs.k8s.io", "本地K8s"},
		{"Helm", "https://helm.sh", "K8s包管理"},
		{"Kustomize", "https://kustomize.io", "K8s配置"},
		{"ArgoCD", "https://argo-cd.readthedocs.io", "GitOps CD"},
		{"Flux", "https://fluxcd.io", "GitOps工具"},
		{"Jenkins", "https://www.jenkins.io", "CI/CD"},
		{"GitLab CI", "https://about.gitlab.com/stages-devops-lifecycle/continuous-integration", "GitLab CI"},
		{"GitHub Actions", "https://github.com/features/actions", "GitHub CI"},
		{"CircleCI", "https://circleci.com", "CI/CD平台"},
		{"Travis CI", "https://www.travis-ci.com", "CI服务"},
		{"Buildkite", "https://buildkite.com", "CI/CD"},
		{"Drone CI", "https://www.drone.io", "容器CI"},
		{"TeamCity", "https://www.jetbrains.com/teamcity", "JetBrains CI"},
		{"Bamboo", "https://www.atlassian.com/software/bamboo", "Atlassian CI"},
		{"Tekton", "https://tekton.dev", "云原生CI/CD"},
		{"Spinnaker", "https://spinnaker.io", "多云CD"},
		{"Harness", "https://harness.io", "软件交付"},
		{"Terraform", "https://www.terraform.io", "基础设施即代码"},
		{"Ansible", "https://www.ansible.com", "自动化运维"},
		{"Puppet", "https://puppet.com", "配置管理"},
		{"Chef", "https://www.chef.io", "自动化基础设施"},
		{"SaltStack", "https://saltproject.io", "基础设施自动化"},
		{"Pulumi", "https://www.pulumi.com", "代码基础设施"},
		{"CDK", "https://aws.amazon.com/cdk", "AWS CDK"},
		{"Crossplane", "https://www.crossplane.io", "云原生基础设施"},
		{"Prometheus", "https://prometheus.io", "监控告警"},
		{"Grafana", "https://grafana.com", "可视化监控"},
		{"Zabbix", "https://www.zabbix.com", "监控系统"},
		{"Nagios", "https://www.nagios.org", "网络监控"},
		{"Icinga", "https://icinga.com", "监控框架"},
		{"Datadog", "https://www.datadoghq.com", "云监控"},
		{"New Relic", "https://newrelic.com", "可观测性"},
		{"Dynatrace", "https://www.dynatrace.com", "AI监控"},
		{"Jaeger", "https://www.jaegertracing.io", "分布式追踪"},
		{"Zipkin", "https://zipkin.io", "分布式追踪"},
		{"OpenTelemetry", "https://opentelemetry.io", "可观测性框架"},
		{"ELK Stack", "https://www.elastic.co/what-is/elk-stack", "日志分析"},
		{"Loki", "https://grafana.com/oss/loki", "日志聚合"},
		{"Fluentd", "https://www.fluentd.org", "日志收集"},
		{"Fluent Bit", "https://fluentbit.io", "轻量日志"},
		{"Vector", "https://vector.dev", "数据管道"},
		{"Logstash", "https://www.elastic.co/logstash", "数据处理"},
		{"Sentry", "https://sentry.io", "错误追踪"},
		{"Rollbar", "https://rollbar.com", "错误监控"},
		{"Honeycomb", "https://www.honeycomb.io", "可观测性"},
		{"Lightstep", "https://lightstep.com", "可观测性"},
		{"HashiCorp Vault", "https://www.vaultproject.io", "密钥管理"},
		{"HashiCorp Consul", "https://www.consul.io", "服务发现"},
		{"HashiCorp Nomad", "https://www.nomadproject.io", "工作负载编排"},
		{"HashiCorp Packer", "https://www.packer.io", "镜像构建"},
		{"HashiCorp Vagrant", "https://www.vagrantup.com", "开发环境"},
		{"Nginx", "https://nginx.org", "Web服务器"},
		{"Caddy", "https://caddyserver.com", "自动HTTPS服务器"},
		{"Apache HTTPD", "https://httpd.apache.org", "Apache服务器"},
		{"Traefik", "https://traefik.io", "边缘路由"},
		{"Envoy", "https://www.envoyproxy.io", "服务代理"},
		{"Istio", "https://istio.io", "服务网格"},
		{"Linkerd", "https://linkerd.io", "服务网格"},
		{"Cilium", "https://cilium.io", "eBPF网络"},
		{"Calico", "https://www.tigera.io/project-calico", "K8s网络"},
		{"Tailscale", "https://tailscale.com", "VPN网格"},
		{"WireGuard", "https://www.wireguard.com", "现代VPN"},
		{"Teleport", "https://goteleport.com", "安全访问"},
		{"Boundary", "https://www.boundaryproject.io", "安全远程访问"},
		{"Velero", "https://velero.io", "K8s备份"},
		{"Longhorn", "https://longhorn.io", "K8s存储"},
		{"Rook", "https://rook.io", "K8s存储编排"},
		{"Cert Manager", "https://cert-manager.io", "K8s证书"},
		{"External DNS", "https://github.com/kubernetes-sigs/external-dns", "K8s DNS"},
		{"Keda", "https://keda.sh", "K8s事件驱动自动缩放"},
		{"Knative", "https://knative.dev", "K8s无服务器"},
		{"OpenFaaS", "https://www.openfaas.com", "无服务器函数"},
		{"Kubecost", "https://www.kubecost.com", "K8s成本"},
		{"K9s", "https://k9scli.io", "K8s终端UI"},
		{"Lens", "https://k8slens.dev", "K8s IDE"},
		{"Octant", "https://octant.dev", "K8s Web UI"},
		{"DevOps Roadmap", "https://roadmap.sh/devops", "DevOps学习路线"},
		{"KataCoda", "https://www.katacoda.com", "交互式学习"},
		{"KillerCoda", "https://killercoda.com", "K8s练习"},
		{"Play with Docker", "https://labs.play-with-docker.com", "Docker游乐场"},
		{"Play with K8s", "https://labs.play-with-k8s.com", "K8s游乐场"},
		{"CNCF", "https://www.cncf.io", "云原生基金会"},
		{"CNCF Landscape", "https://landscape.cncf.io", "云原生全景"},
		{"12 Factor App", "https://12factor.net", "十二要素应用"},
		{"SRE Book", "https://sre.google/sre-book/table-of-contents", "SRE手册"},
		{"DevOps Weekly", "https://www.devopsweekly.com", "DevOps周刊"},
		{"SRE Weekly", "https://sreweekly.com", "SRE周刊"},
	}
}

func securityEx() []S {
	return []S{
		{"OWASP", "https://owasp.org", "Web安全项目"},
		{"NIST", "https://www.nist.gov/cybersecurity", "安全标准"},
		{"CVE", "https://cve.mitre.org", "漏洞编号"},
		{"NVD", "https://nvd.nist.gov", "漏洞数据库"},
		{"Exploit-DB", "https://www.exploit-db.com", "漏洞利用数据库"},
		{"Shodan", "https://www.shodan.io", "IoT搜索引擎"},
		{"Censys", "https://censys.io", "互联网扫描"},
		{"ZoomEye", "https://www.zoomeye.org", "网络空间搜索"},
		{"VirusTotal", "https://www.virustotal.com", "恶意软件检测"},
		{"Any.run", "https://any.run", "恶意软件沙箱"},
		{"Hybrid Analysis", "https://www.hybrid-analysis.com", "恶意软件分析"},
		{"URLScan", "https://urlscan.io", "URL分析"},
		{"Have I Been Pwned", "https://haveibeenpwned.com", "账号泄露查询"},
		{"SecurityTrails", "https://securitytrails.com", "DNS历史"},
		{"Snyk", "https://snyk.io", "开发者安全"},
		{"SonarQube", "https://www.sonarsource.com/products/sonarqube", "代码质量"},
		{"Checkmarx", "https://checkmarx.com", "应用安全"},
		{"Veracode", "https://www.veracode.com", "应用安全"},
		{"Fortify", "https://www.microfocus.com/en-us/cyberres/application-security", "安全测试"},
		{"Qualys", "https://www.qualys.com", "漏洞管理"},
		{"Tenable", "https://www.tenable.com", "网络安全"},
		{"Rapid7", "https://www.rapid7.com", "安全分析"},
		{"CrowdStrike", "https://www.crowdstrike.com", "终端安全"},
		{"SentinelOne", "https://www.sentinelone.com", "AI安全"},
		{"Carbon Black", "https://www.vmware.com/products/carbon-black-cloud.html", "终端保护"},
		{"Malwarebytes", "https://www.malwarebytes.com", "反恶意软件"},
		{"Kaspersky", "https://www.kaspersky.com", "安全软件"},
		{"Norton", "https://us.norton.com", "安全软件"},
		{"Bitdefender", "https://www.bitdefender.com", "安全软件"},
		{"ESET", "https://www.eset.com", "安全软件"},
		{"Avast", "https://www.avast.com", "免费安全"},
		{"Wireshark", "https://www.wireshark.org", "网络协议分析"},
		{"Nmap", "https://nmap.org", "网络扫描"},
		{"Metasploit", "https://www.metasploit.com", "渗透测试"},
		{"Burp Suite", "https://portswigger.net/burp", "Web安全测试"},
		{"ZAP", "https://www.zaproxy.org", "OWASP安全扫描"},
		{"Nuclei", "https://nuclei.projectdiscovery.io", "漏洞扫描"},
		{"Nikto", "https://cirt.net/Nikto2", "Web服务器扫描"},
		{"SQLMap", "https://sqlmap.org", "SQL注入工具"},
		{"Acunetix", "https://www.acunetix.com", "Web漏洞扫描"},
		{"Kali Linux", "https://www.kali.org", "渗透测试系统"},
		{"Parrot OS", "https://parrotsec.org", "安全系统"},
		{"Black Arch", "https://blackarch.org", "安全工具集"},
		{"HackTheBox", "https://www.hackthebox.com", "渗透练习"},
		{"TryHackMe", "https://tryhackme.com", "安全学习"},
		{"OverTheWire", "https://overthewire.org", "安全挑战"},
		{"PicoCTF", "https://picoctf.org", "CTF入门"},
		{"CTFtime", "https://ctftime.org", "CTF赛事"},
		{"Hack The Box Academy", "https://academy.hackthebox.com", "安全教育"},
		{"SANS", "https://www.sans.org", "安全培训"},
		{"Offensive Security", "https://www.offensive-security.com", "OSCP认证"},
		{"ISC2", "https://www.isc2.org", "CISSP认证"},
		{"CompTIA Security+", "https://www.comptia.org/certifications/security", "安全认证"},
		{"Krebs on Security", "https://krebsonsecurity.com", "安全新闻"},
		{"The Hacker News", "https://thehackernews.com", "安全新闻"},
		{"Bleeping Computer", "https://www.bleepingcomputer.com", "安全新闻"},
		{"Dark Reading", "https://www.darkreading.com", "安全资讯"},
		{"SecurityWeek", "https://www.securityweek.com", "安全周刊"},
		{"Threatpost", "https://threatpost.com", "威胁情报"},
		{"SC Magazine", "https://www.scmagazine.com", "安全杂志"},
		{"CSO Online", "https://www.csoonline.com", "安全领导"},
		{"FreeBuf", "https://www.freebuf.com", "中国安全资讯"},
		{"安全客", "https://www.anquanke.com", "中国安全"},
		{"先知社区", "https://xz.aliyun.com", "阿里安全社区"},
		{"看雪", "https://www.pediy.com", "中国安全论坛"},
		{"SecWiki", "https://www.sec-wiki.com", "安全百科"},
		{"1Password", "https://1password.com", "密码管理"},
		{"Bitwarden", "https://bitwarden.com", "开源密码管理"},
		{"LastPass", "https://www.lastpass.com", "密码管理"},
		{"Dashlane", "https://www.dashlane.com", "密码管理"},
		{"KeePass", "https://keepass.info", "密码管理器"},
		{"NordPass", "https://nordpass.com", "密码管理"},
		{"NordVPN", "https://nordvpn.com", "VPN服务"},
		{"ExpressVPN", "https://www.expressvpn.com", "VPN服务"},
		{"Surfshark", "https://surfshark.com", "VPN服务"},
		{"ProtonVPN", "https://protonvpn.com", "隐私VPN"},
		{"Mullvad", "https://mullvad.net", "隐私VPN"},
		{"Tor Project", "https://www.torproject.org", "匿名网络"},
		{"Tails", "https://tails.boum.org", "隐私系统"},
		{"Whonix", "https://www.whonix.org", "匿名系统"},
		{"Signal", "https://signal.org", "加密通信"},
		{"ProtonMail", "https://proton.me/mail", "加密邮箱"},
		{"Tutanota", "https://tutanota.com", "加密邮箱"},
		{"Matrix", "https://matrix.org", "加密通信协议"},
		{"Keybase", "https://keybase.io", "加密身份"},
		{"Let's Encrypt", "https://letsencrypt.org", "免费TLS"},
		{"Cloudflare SSL", "https://www.cloudflare.com/ssl", "SSL服务"},
		{"SSL Labs", "https://www.ssllabs.com/ssltest", "SSL测试"},
		{"Observatory", "https://observatory.mozilla.org", "安全评估"},
		{"Security Headers", "https://securityheaders.com", "HTTP安全头"},
		{"CSP Evaluator", "https://csp-evaluator.withgoogle.com", "CSP检查"},
		{"Dependabot", "https://github.com/dependabot", "依赖安全"},
		{"Renovate", "https://www.mend.io/renovate", "依赖更新"},
		{"Socket.dev", "https://socket.dev", "供应链安全"},
		{"StepSecurity", "https://www.stepsecurity.io", "CI/CD安全"},
		{"GitGuardian", "https://www.gitguardian.com", "密钥泄露检测"},
		{"TruffleHog", "https://trufflesecurity.com/trufflehog", "密钥扫描"},
		{"Gitleaks", "https://gitleaks.io", "Git密钥扫描"},
		{"Trivy", "https://aquasecurity.github.io/trivy", "容器安全扫描"},
		{"Falco", "https://falco.org", "运行时安全"},
		{"Aqua Security", "https://www.aquasec.com", "云原生安全"},
	}
}

func frontendEx() []S {
	return []S{
		{"React", "https://react.dev", "React框架"},
		{"Vue.js", "https://vuejs.org", "Vue框架"},
		{"Angular", "https://angular.io", "Angular框架"},
		{"Svelte", "https://svelte.dev", "Svelte框架"},
		{"Solid.js", "https://www.solidjs.com", "Solid框架"},
		{"Preact", "https://preactjs.com", "轻量React替代"},
		{"Lit", "https://lit.dev", "Web Components"},
		{"Alpine.js", "https://alpinejs.dev", "轻量JS框架"},
		{"HTMX", "https://htmx.org", "HTML扩展"},
		{"Qwik", "https://qwik.builder.io", "即时加载框架"},
		{"Next.js", "https://nextjs.org", "React全栈框架"},
		{"Nuxt.js", "https://nuxt.com", "Vue全栈框架"},
		{"SvelteKit", "https://kit.svelte.dev", "Svelte框架"},
		{"Remix", "https://remix.run", "React全栈"},
		{"Astro", "https://astro.build", "内容优先框架"},
		{"Gatsby", "https://www.gatsbyjs.com", "静态网站"},
		{"Eleventy", "https://www.11ty.dev", "静态网站生成"},
		{"Vite", "https://vitejs.dev", "前端构建工具"},
		{"Webpack", "https://webpack.js.org", "模块打包"},
		{"Rollup", "https://rollupjs.org", "JS打包"},
		{"esbuild", "https://esbuild.github.io", "极速打包"},
		{"SWC", "https://swc.rs", "Rust编译器"},
		{"Turbopack", "https://turbo.build/pack", "Vercel打包"},
		{"Bun", "https://bun.sh", "JS运行时"},
		{"Deno", "https://deno.land", "安全JS运行时"},
		{"TypeScript", "https://www.typescriptlang.org", "TypeScript"},
		{"Tailwind CSS", "https://tailwindcss.com", "实用CSS"},
		{"Bootstrap", "https://getbootstrap.com", "CSS框架"},
		{"Material UI", "https://mui.com", "React组件库"},
		{"Ant Design", "https://ant.design", "企业UI库"},
		{"Chakra UI", "https://chakra-ui.com", "React UI"},
		{"Radix UI", "https://www.radix-ui.com", "无样式组件"},
		{"Shadcn UI", "https://ui.shadcn.com", "可复制组件"},
		{"Headless UI", "https://headlessui.com", "无样式UI"},
		{"DaisyUI", "https://daisyui.com", "Tailwind组件"},
		{"Mantine", "https://mantine.dev", "React组件"},
		{"Element Plus", "https://element-plus.org", "Vue3组件库"},
		{"Vuetify", "https://vuetifyjs.com", "Vue Material"},
		{"Naive UI", "https://www.naiveui.com", "Vue3组件"},
		{"PrimeVue", "https://primevue.org", "Vue组件"},
		{"Storybook", "https://storybook.js.org", "UI组件开发"},
		{"Chromatic", "https://www.chromatic.com", "视觉测试"},
		{"Cypress", "https://www.cypress.io", "E2E测试"},
		{"Playwright", "https://playwright.dev", "浏览器测试"},
		{"Jest", "https://jestjs.io", "JS测试框架"},
		{"Vitest", "https://vitest.dev", "Vite测试"},
		{"Testing Library", "https://testing-library.com", "测试工具"},
		{"Puppeteer", "https://pptr.dev", "无头浏览器"},
		{"Selenium", "https://www.selenium.dev", "浏览器自动化"},
		{"Framer Motion", "https://www.framer.com/motion", "React动画"},
		{"GSAP", "https://gsap.com", "Web动画"},
		{"Three.js", "https://threejs.org", "3D Web"},
		{"D3.js", "https://d3js.org", "数据可视化"},
		{"Chart.js", "https://www.chartjs.org", "图表库"},
		{"ECharts", "https://echarts.apache.org", "Apache图表"},
		{"Recharts", "https://recharts.org", "React图表"},
		{"Lottie", "https://airbnb.io/lottie", "动效库"},
		{"Rive", "https://rive.app", "交互动画"},
		{"Anime.js", "https://animejs.com", "JS动画"},
		{"React Spring", "https://www.react-spring.dev", "React物理动画"},
		{"Redux", "https://redux.js.org", "状态管理"},
		{"Zustand", "https://zustand-demo.pmnd.rs", "轻量状态"},
		{"Jotai", "https://jotai.org", "原子状态"},
		{"Recoil", "https://recoiljs.org", "React状态"},
		{"Pinia", "https://pinia.vuejs.org", "Vue状态"},
		{"MobX", "https://mobx.js.org", "响应式状态"},
		{"XState", "https://xstate.js.org", "状态机"},
		{"TanStack Query", "https://tanstack.com/query", "数据获取"},
		{"SWR", "https://swr.vercel.app", "React数据获取"},
		{"Apollo Client", "https://www.apollographql.com/docs/react", "GraphQL客户端"},
		{"URQL", "https://formidable.com/open-source/urql", "GraphQL客户端"},
		{"Zod", "https://zod.dev", "TypeScript验证"},
		{"React Hook Form", "https://react-hook-form.com", "React表单"},
		{"Formik", "https://formik.org", "React表单"},
		{"Can I Use", "https://caniuse.com", "浏览器兼容性"},
		{"MDN", "https://developer.mozilla.org", "Web文档"},
		{"CSS-Tricks", "https://css-tricks.com", "CSS技巧"},
		{"Smashing Magazine", "https://www.smashingmagazine.com", "前端杂志"},
		{"Frontend Masters", "https://frontendmasters.com", "前端课程"},
		{"Frontend Roadmap", "https://roadmap.sh/frontend", "前端学习路线"},
		{"State of JS", "https://stateofjs.com", "JS调查"},
		{"State of CSS", "https://stateofcss.com", "CSS调查"},
		{"Web.dev", "https://web.dev", "谷歌Web最佳实践"},
		{"PageSpeed Insights", "https://pagespeed.web.dev", "性能分析"},
		{"Lighthouse", "https://developer.chrome.com/docs/lighthouse", "Web审计"},
		{"WebPageTest", "https://www.webpagetest.org", "性能测试"},
		{"Bundlephobia", "https://bundlephobia.com", "包体积分析"},
		{"npm trends", "https://npmtrends.com", "npm包趋势"},
		{"BestofJS", "https://bestofjs.org", "JS项目排名"},
		{"JavaScriptWeekly", "https://javascriptweekly.com", "JS周刊"},
		{"CSS Weekly", "https://css-weekly.com", "CSS周刊"},
		{"React Newsletter", "https://reactnewsletter.com", "React周刊"},
		{"Vue Newsletter", "https://news.vuejs.org", "Vue新闻"},
		{"Svelte Society", "https://sveltesociety.dev", "Svelte社区"},
		{"Angular Blog", "https://blog.angular.io", "Angular博客"},
		{"Vercel Blog", "https://vercel.com/blog", "Vercel博客"},
		{"Next.js Conf", "https://nextjs.org/conf", "Next.js大会"},
	}
}

func backendEx() []S {
	return []S{
		{"Node.js", "https://nodejs.org", "Node.js"},
		{"Express.js", "https://expressjs.com", "Node框架"},
		{"Fastify", "https://www.fastify.io", "高性能Node"},
		{"NestJS", "https://nestjs.com", "Node企业框架"},
		{"Koa", "https://koajs.com", "Node框架"},
		{"Hono", "https://hono.dev", "边缘Web框架"},
		{"Go", "https://go.dev", "Go语言"},
		{"Gin", "https://gin-gonic.com", "Go Web框架"},
		{"Echo", "https://echo.labstack.com", "Go框架"},
		{"Fiber", "https://gofiber.io", "Go框架"},
		{"Chi", "https://go-chi.io", "Go路由"},
		{"Rust", "https://www.rust-lang.org", "Rust语言"},
		{"Actix", "https://actix.rs", "Rust Web框架"},
		{"Axum", "https://github.com/tokio-rs/axum", "Rust框架"},
		{"Rocket", "https://rocket.rs", "Rust Web"},
		{"Python", "https://www.python.org", "Python语言"},
		{"Django", "https://www.djangoproject.com", "Python Web框架"},
		{"Flask", "https://flask.palletsprojects.com", "Python微框架"},
		{"FastAPI", "https://fastapi.tiangolo.com", "Python高性能API"},
		{"Starlette", "https://www.starlette.io", "ASGI框架"},
		{"Java", "https://www.java.com", "Java语言"},
		{"Spring Boot", "https://spring.io/projects/spring-boot", "Spring Boot"},
		{"Spring Framework", "https://spring.io/projects/spring-framework", "Spring框架"},
		{"Quarkus", "https://quarkus.io", "Java云原生"},
		{"Micronaut", "https://micronaut.io", "JVM微服务"},
		{"Vert.x", "https://vertx.io", "反应式JVM"},
		{"Kotlin", "https://kotlinlang.org", "Kotlin语言"},
		{"Ktor", "https://ktor.io", "Kotlin框架"},
		{"Ruby", "https://www.ruby-lang.org", "Ruby语言"},
		{"Rails", "https://rubyonrails.org", "Ruby on Rails"},
		{"Sinatra", "https://sinatrarb.com", "Ruby微框架"},
		{"Hanami", "https://hanamirb.org", "Ruby Web"},
		{"PHP", "https://www.php.net", "PHP语言"},
		{"Laravel", "https://laravel.com", "PHP框架"},
		{"Symfony", "https://symfony.com", "PHP企业框架"},
		{"CodeIgniter", "https://codeigniter.com", "PHP轻量框架"},
		{"Slim", "https://www.slimframework.com", "PHP微框架"},
		{"C#", "https://dotnet.microsoft.com/languages/csharp", "C#语言"},
		{".NET", "https://dotnet.microsoft.com", ".NET平台"},
		{"ASP.NET Core", "https://dotnet.microsoft.com/apps/aspnet", "ASP.NET"},
		{"Elixir", "https://elixir-lang.org", "Elixir语言"},
		{"Phoenix", "https://www.phoenixframework.org", "Elixir Web"},
		{"Scala", "https://www.scala-lang.org", "Scala语言"},
		{"Play Framework", "https://www.playframework.com", "Scala/Java Web"},
		{"Akka", "https://akka.io", "Actor模型"},
		{"GraphQL", "https://graphql.org", "GraphQL规范"},
		{"Apollo Server", "https://www.apollographql.com", "GraphQL服务器"},
		{"Hasura", "https://hasura.io", "即时GraphQL"},
		{"PostGraphile", "https://www.graphile.org/postgraphile", "PostgreSQL GraphQL"},
		{"gRPC", "https://grpc.io", "RPC框架"},
		{"tRPC", "https://trpc.io", "TypeScript RPC"},
		{"Protobuf", "https://protobuf.dev", "协议缓冲"},
		{"REST API Tutorial", "https://restfulapi.net", "REST教程"},
		{"Swagger", "https://swagger.io", "API文档"},
		{"OpenAPI", "https://www.openapis.org", "API规范"},
		{"Postman", "https://www.postman.com", "API开发"},
		{"Insomnia", "https://insomnia.rest", "API客户端"},
		{"Hoppscotch", "https://hoppscotch.io", "开源API工具"},
		{"Bruno", "https://www.usebruno.com", "API客户端"},
		{"RapidAPI", "https://rapidapi.com", "API市场"},
		{"Kong", "https://konghq.com", "API网关"},
		{"APISIX", "https://apisix.apache.org", "API网关"},
		{"Tyk", "https://tyk.io", "API管理"},
		{"WSO2", "https://wso2.com", "集成平台"},
		{"MuleSoft", "https://www.mulesoft.com", "API管理"},
		{"Apigee", "https://cloud.google.com/apigee", "API管理"},
		{"Celery", "https://docs.celeryq.dev", "Python任务队列"},
		{"Sidekiq", "https://sidekiq.org", "Ruby后台任务"},
		{"BullMQ", "https://bullmq.io", "Node任务队列"},
		{"Temporal", "https://temporal.io", "工作流引擎"},
		{"Apache Airflow", "https://airflow.apache.org", "工作流调度"},
		{"Prefect", "https://www.prefect.io", "数据工作流"},
		{"Dagster", "https://dagster.io", "数据编排"},
		{"Mage.ai", "https://www.mage.ai", "数据管道"},
		{"n8n", "https://n8n.io", "工作流自动化"},
		{"Zapier", "https://zapier.com", "自动化集成"},
		{"Make", "https://www.make.com", "自动化平台"},
		{"Windmill", "https://www.windmill.dev", "开源自动化"},
		{"Backend Roadmap", "https://roadmap.sh/backend", "后端学习路线"},
		{"System Design Primer", "https://github.com/donnemartin/system-design-primer", "系统设计"},
		{"High Scalability", "https://highscalability.com", "高可扩展性"},
		{"Martin Fowler", "https://martinfowler.com", "软件架构"},
		{"InfoQ", "https://www.infoq.com", "软件开发资讯"},
		{"DZone", "https://dzone.com", "开发者社区"},
		{"ByteByteGo", "https://bytebytego.com", "系统设计"},
		{"Dev.to Backend", "https://dev.to/t/backend", "后端文章"},
		{"Go Weekly", "https://golangweekly.com", "Go周刊"},
		{"Ruby Weekly", "https://rubyweekly.com", "Ruby周刊"},
		{"Python Weekly", "https://www.pythonweekly.com", "Python周刊"},
		{"Java Weekly", "https://www.baeldung.com/java-weekly-review", "Java周报"},
		{"PHP Weekly", "https://www.phpweekly.com", "PHP周刊"},
		{"Rust Weekly", "https://this-week-in-rust.org", "Rust周刊"},
		{"Elixir Weekly", "https://elixirweekly.net", "Elixir周刊"},
		{"Backend Engineer Path", "https://roadmap.sh/backend", "后端路线"},
		{"Microservices.io", "https://microservices.io", "微服务模式"},
		{"Event Sourcing", "https://www.eventstore.com", "事件溯源"},
		{"CQRS Pattern", "https://docs.microsoft.com/en-us/azure/architecture/patterns/cqrs", "CQRS模式"},
	}
}

func mobileDevEx() []S {
	return []S{
		{"React Native", "https://reactnative.dev", "React Native"},
		{"Expo", "https://expo.dev", "React Native工具"},
		{"Flutter", "https://flutter.dev", "Flutter框架"},
		{"Dart", "https://dart.dev", "Dart语言"},
		{"Swift", "https://swift.org", "Swift语言"},
		{"SwiftUI", "https://developer.apple.com/xcode/swiftui", "SwiftUI"},
		{"Kotlin Multiplatform", "https://kotlinlang.org/lp/multiplatform", "KMP跨平台"},
		{"Jetpack Compose", "https://developer.android.com/jetpack/compose", "Compose UI"},
		{"Capacitor", "https://capacitorjs.com", "混合应用"},
		{"Ionic", "https://ionicframework.com", "混合应用框架"},
		{"Xamarin", "https://dotnet.microsoft.com/apps/xamarin", "C#跨平台"},
		{"MAUI", "https://dotnet.microsoft.com/apps/maui", ".NET跨平台"},
		{"Tauri", "https://tauri.app", "桌面应用"},
		{"Electron", "https://www.electronjs.org", "桌面应用"},
		{"NativeScript", "https://nativescript.org", "原生跨平台"},
		{"Apple Developer", "https://developer.apple.com", "苹果开发者"},
		{"WWDC", "https://developer.apple.com/wwdc", "苹果开发者大会"},
		{"App Store Connect", "https://appstoreconnect.apple.com", "iOS应用管理"},
		{"TestFlight", "https://developer.apple.com/testflight", "iOS测试分发"},
		{"Android Developers", "https://developer.android.com", "安卓开发者"},
		{"Google Play Console", "https://play.google.com/console", "安卓应用管理"},
		{"Material Design", "https://m3.material.io", "Material设计"},
		{"Human Interface Guidelines", "https://developer.apple.com/design/human-interface-guidelines", "苹果设计指南"},
		{"Firebase", "https://firebase.google.com", "移动后端"},
		{"Realm", "https://realm.io", "移动数据库"},
		{"Fastlane", "https://fastlane.tools", "移动自动化"},
		{"Bitrise", "https://www.bitrise.io", "移动CI/CD"},
		{"Codemagic", "https://codemagic.io", "Flutter CI/CD"},
		{"AppCenter", "https://appcenter.ms", "微软移动DevOps"},
		{"CodePush", "https://microsoft.github.io/code-push", "热更新"},
		{"Sentry Mobile", "https://sentry.io/for/mobile", "移动错误追踪"},
		{"Bugsnag", "https://www.bugsnag.com", "错误监控"},
		{"Instabug", "https://instabug.com", "用户反馈"},
		{"Firebase Crashlytics", "https://firebase.google.com/products/crashlytics", "崩溃报告"},
		{"Amplitude Mobile", "https://amplitude.com/mobile-analytics", "移动分析"},
		{"Adjust", "https://www.adjust.com", "移动归因"},
		{"AppsFlyer", "https://www.appsflyer.com", "移动归因"},
		{"Branch", "https://branch.io", "深度链接"},
		{"OneSignal", "https://onesignal.com", "推送通知"},
		{"Pushwoosh", "https://www.pushwoosh.com", "推送服务"},
		{"RevenueCat", "https://www.revenuecat.com", "订阅管理"},
		{"Qonversion", "https://qonversion.io", "订阅分析"},
		{"Adapty", "https://adapty.io", "应用内购买"},
		{"Lottie Mobile", "https://airbnb.io/lottie", "移动动画"},
		{"Rive Mobile", "https://rive.app", "交互动画"},
		{"Detox", "https://wix.github.io/Detox", "RN E2E测试"},
		{"Appium", "https://appium.io", "移动测试"},
		{"XCTest", "https://developer.apple.com/documentation/xctest", "iOS测试"},
		{"Espresso", "https://developer.android.com/training/testing/espresso", "安卓UI测试"},
		{"Maestro", "https://maestro.mobile.dev", "移动UI测试"},
		{"Flipper", "https://fbflipper.com", "移动调试"},
		{"Reactotron", "https://github.com/infinitered/reactotron", "RN调试"},
		{"App Store Optimization", "https://www.appannie.com", "ASO优化"},
		{"Sensor Tower", "https://sensortower.com", "应用分析"},
		{"App Annie", "https://www.data.ai", "应用数据"},
		{"42matters", "https://42matters.com", "应用市场数据"},
		{"AppFollow", "https://appfollow.io", "应用评价管理"},
		{"图鸟UI", "https://www.tuniao.com", "小程序组件"},
		{"uni-app", "https://uniapp.dcloud.net.cn", "跨平台框架"},
		{"Taro", "https://taro.jd.com", "多端开发"},
		{"微信小程序", "https://developers.weixin.qq.com/miniprogram", "小程序开发"},
		{"支付宝小程序", "https://mini.open.alipay.com", "支付宝小程序"},
		{"抖音小程序", "https://developer.open-douyin.com/docs/resource/zh-CN/mini-app/develop/guide/start/overview", "抖音开发"},
		{"HarmonyOS", "https://developer.harmonyos.com", "鸿蒙开发"},
		{"ArkUI", "https://developer.harmonyos.com/cn/docs/documentation/doc-guides-V3/arkui-overview-0000001532577181-V3", "鸿蒙UI"},
		{"CocoaPods", "https://cocoapods.org", "iOS包管理"},
		{"Swift Package Manager", "https://www.swift.org/package-manager", "Swift包管理"},
		{"Gradle", "https://gradle.org", "构建工具"},
		{"Maven Central", "https://search.maven.org", "Java包仓库"},
		{"pub.dev", "https://pub.dev", "Dart包仓库"},
		{"npm React Native", "https://www.npmjs.com/search?q=react-native", "RN包"},
		{"Mobile Dev Roadmap", "https://roadmap.sh/android", "移动开发路线"},
		{"iOS Dev Roadmap", "https://roadmap.sh/ios", "iOS学习路线"},
		{"Android Weekly", "https://androidweekly.net", "安卓周刊"},
		{"iOS Dev Weekly", "https://iosdevweekly.com", "iOS周刊"},
		{"Flutter Weekly", "https://flutterweekly.net", "Flutter周刊"},
		{"React Native Newsletter", "https://reactnative.cc", "RN周刊"},
		{"Ray Wenderlich", "https://www.kodeco.com", "移动教程"},
		{"Hacking with Swift", "https://www.hackingwithswift.com", "Swift教程"},
		{"Android Authority Dev", "https://www.androidauthority.com/develop", "安卓开发"},
		{"Flutter Gems", "https://fluttergems.dev", "Flutter包推荐"},
		{"Awesome React Native", "https://github.com/jondot/awesome-react-native", "RN资源"},
		{"Awesome Flutter", "https://github.com/Solido/awesome-flutter", "Flutter资源"},
		{"Swift by Sundell", "https://www.swiftbysundell.com", "Swift博客"},
		{"Objc.io", "https://www.objc.io", "iOS进阶"},
		{"ProAndroidDev", "https://proandroiddev.com", "安卓进阶"},
		{"The Flutter Way", "https://www.youtube.com/c/TheFlutterWay", "Flutter视频"},
		{"Flutter Mapp", "https://fluttermapp.com", "Flutter地图"},
		{"Codemagic Blog", "https://blog.codemagic.io", "移动CI博客"},
		{"Mobile Dev Memo", "https://mobiledevmemo.com", "移动营销"},
		{"App Business Podcast", "https://appbusinesspodcast.com", "应用商业"},
		{"Fragmented Podcast", "https://fragmentedpodcast.com", "安卓播客"},
		{"Swift over Coffee", "https://anchor.fm/swiftovercoffee", "Swift播客"},
		{"Flutter Podcast", "https://flutterpodcast.com", "Flutter播客"},
		{"NSHipster", "https://nshipster.com", "iOS开发"},
		{"Big Nerd Ranch", "https://bignerdranch.com", "移动培训"},
		{"Kodeco", "https://www.kodeco.com", "移动开发教程"},
	}
}
