package main

func job() []S {
	return []S{
		{"LinkedIn", "https://www.linkedin.com", "职业社交求职"},
		{"Indeed", "https://www.indeed.com", "全球招聘搜索"},
		{"Glassdoor", "https://www.glassdoor.com", "公司评价与招聘"},
		{"Monster", "https://www.monster.com", "美国招聘网站"},
		{"ZipRecruiter", "https://www.ziprecruiter.com", "AI招聘匹配"},
		{"CareerBuilder", "https://www.careerbuilder.com", "招聘平台"},
		{"Dice", "https://www.dice.com", "科技人才招聘"},
		{"AngelList", "https://angel.co", "初创公司招聘"},
		{"Wellfound", "https://wellfound.com", "创业公司工作"},
		{"We Work Remotely", "https://weworkremotely.com", "远程工作招聘"},
		{"Remote.co", "https://remote.co", "远程岗位"},
		{"FlexJobs", "https://www.flexjobs.com", "弹性工作搜索"},
		{"Remotive", "https://remotive.com", "远程工作板"},
		{"Working Nomads", "https://www.workingnomads.com", "数字游民工作"},
		{"Toptal", "https://www.toptal.com", "顶尖自由职业者"},
		{"Upwork", "https://www.upwork.com", "自由职业平台"},
		{"Freelancer", "https://www.freelancer.com", "自由职业招标"},
		{"Fiverr", "https://www.fiverr.com", "技能服务市场"},
		{"99designs", "https://99designs.com", "设计外包平台"},
		{"Hired", "https://hired.com", "科技人才市场"},
		{"Triplebyte", "https://triplebyte.com", "工程师评估招聘"},
		{"Lever", "https://www.lever.co", "招聘管理系统"},
		{"Greenhouse", "https://www.greenhouse.com", "招聘软件"},
		{"Workday", "https://www.workday.com", "人力资源管理"},
		{"BambooHR", "https://www.bamboohr.com", "HR软件"},
		{"前程无忧", "https://www.51job.com", "前程无忧招聘"},
		{"智联招聘", "https://www.zhaopin.com", "智联招聘"},
		{"Boss直聘", "https://www.zhipin.com", "Boss直聘"},
		{"猎聘", "https://www.liepin.com", "猎聘中高端招聘"},
		{"拉勾网", "https://www.lagou.com", "互联网招聘"},
		{"脉脉", "https://maimai.cn", "职场社交平台"},
		{"牛客网", "https://www.nowcoder.com", "IT面试刷题"},
		{"实习僧", "https://www.shixiseng.com", "实习生招聘"},
		{"应届生求职网", "https://www.yingjiesheng.com", "校园招聘"},
		{"大街网", "https://www.dajie.com", "大学生招聘"},
		{"中华英才网", "https://www.chinahr.com", "综合招聘"},
		{"赶集网", "https://www.ganji.com", "生活信息招聘"},
		{"58同城", "https://www.58.com", "58同城招聘"},
		{"猎云网", "https://www.lieyunwang.com", "创投与招聘"},
		{"电鸭社区", "https://eleduck.com", "远程工作社区"},
		{"Reed", "https://www.reed.co.uk", "英国招聘网站"},
		{"Seek", "https://www.seek.com.au", "澳洲招聘"},
		{"Naukri", "https://www.naukri.com", "印度招聘平台"},
		{"Saramin", "https://www.saramin.co.kr", "韩国招聘"},
		{"Rikunabi", "https://next.rikunabi.com", "日本招聘"},
		{"Hays", "https://www.hays.com", "国际猎头"},
		{"Robert Half", "https://www.roberthalf.com", "专业人才招聘"},
		{"Michael Page", "https://www.michaelpage.com", "高端招聘"},
		{"Randstad", "https://www.randstad.com", "全球人力资源"},
		{"Adecco", "https://www.adecco.com", "人才解决方案"},
	}
}

func government() []S {
	return []S{
		{"中国政府网", "https://www.gov.cn", "中国政府门户"},
		{"国务院", "https://www.gov.cn/guowuyuan", "国务院信息"},
		{"国家税务总局", "https://www.chinatax.gov.cn", "税务服务"},
		{"人力资源社会保障部", "https://www.mohrss.gov.cn", "社保查询"},
		{"住房公积金", "https://gjj.beijing.gov.cn", "公积金查询"},
		{"交管12123", "https://gab.122.gov.cn", "交通管理服务"},
		{"个人所得税", "https://etax.chinatax.gov.cn", "个税服务"},
		{"国家企业信用", "https://www.gsxt.gov.cn", "企业信用查询"},
		{"天眼查", "https://www.tianyancha.com", "企业信息查询"},
		{"企查查", "https://www.qcc.com", "企业信息平台"},
		{"爱企查", "https://aiqicha.baidu.com", "百度企业查询"},
		{"信用中国", "https://www.creditchina.gov.cn", "社会信用信息"},
		{"中国裁判文书网", "https://wenshu.court.gov.cn", "裁判文书公开"},
		{"中国执行信息公开网", "https://zxgk.court.gov.cn", "法院执行信息"},
		{"国家知识产权局", "https://www.cnipa.gov.cn", "专利商标查询"},
		{"中国专利公布公告", "https://epub.cnipa.gov.cn", "专利信息"},
		{"学信网", "https://www.chsi.com.cn", "学历查询认证"},
		{"中国人事考试网", "https://www.cpta.com.cn", "职业资格考试"},
		{"全国社保查询", "https://si.12333.gov.cn", "社保查询服务"},
		{"医保服务", "https://fuwu.nhsa.gov.cn", "医保查询"},
		{"出入境管理", "https://s.nia.gov.cn", "出入境服务"},
		{"USA.gov", "https://www.usa.gov", "美国政府门户"},
		{"Gov.uk", "https://www.gov.uk", "英国政府门户"},
		{"Service-Public.fr", "https://www.service-public.fr", "法国公共服务"},
		{"Canada.ca", "https://www.canada.ca", "加拿大政府"},
		{"Australia.gov.au", "https://www.australia.gov.au", "澳大利亚政府"},
		{"e-Gov", "https://www.e-gov.go.jp", "日本电子政务"},
		{"Gov.sg", "https://www.gov.sg", "新加坡政府"},
		{"Data.gov", "https://data.gov", "美国政府开放数据"},
		{"Data.gov.uk", "https://data.gov.uk", "英国开放数据"},
		{"European Union", "https://europa.eu", "欧盟门户"},
		{"United Nations", "https://www.un.org", "联合国官网"},
		{"World Bank", "https://www.worldbank.org", "世界银行"},
		{"IMF", "https://www.imf.org", "国际货币基金组织"},
		{"WTO", "https://www.wto.org", "世界贸易组织"},
		{"OECD", "https://www.oecd.org", "经合组织"},
		{"IRS", "https://www.irs.gov", "美国国税局"},
		{"NHS", "https://www.nhs.uk", "英国国民医疗"},
		{"FEMA", "https://www.fema.gov", "美国应急管理"},
		{"NASA", "https://www.nasa.gov", "美国宇航局"},
		{"ESA", "https://www.esa.int", "欧洲航天局"},
		{"中国气象局", "https://www.cma.gov.cn", "中国气象"},
		{"水利部", "https://www.mwr.gov.cn", "水利信息"},
		{"生态环境部", "https://www.mee.gov.cn", "环保信息"},
		{"国家统计局", "https://www.stats.gov.cn", "统计数据"},
		{"海关总署", "https://www.customs.gov.cn", "海关服务"},
		{"国家邮政局", "https://www.spb.gov.cn", "邮政管理"},
		{"市场监管总局", "https://www.samr.gov.cn", "市场监管"},
		{"粤省事", "https://www.gdzwfw.gov.cn", "广东政务服务"},
		{"浙里办", "https://www.zjzwfw.gov.cn", "浙江政务服务"},
	}
}

func photography() []S {
	return []S{
		{"Unsplash", "https://unsplash.com", "免费高质量图片"},
		{"Pexels", "https://www.pexels.com", "免费图片视频"},
		{"Pixabay", "https://pixabay.com", "免费图片素材"},
		{"Flickr", "https://www.flickr.com", "图片分享社区"},
		{"500px", "https://500px.com", "高品质摄影社区"},
		{"SmugMug", "https://www.smugmug.com", "摄影师作品展示"},
		{"Getty Images", "https://www.gettyimages.com", "商业图片库"},
		{"Shutterstock", "https://www.shutterstock.com", "图片素材库"},
		{"Adobe Stock", "https://stock.adobe.com", "Adobe图片库"},
		{"iStock", "https://www.istockphoto.com", "图片素材"},
		{"Alamy", "https://www.alamy.com", "图片素材市场"},
		{"Dreamstime", "https://www.dreamstime.com", "图片库"},
		{"123RF", "https://www.123rf.com", "图片素材下载"},
		{"Depositphotos", "https://depositphotos.com", "图片视频素材"},
		{"StockSnap", "https://stocksnap.io", "免费CC0图片"},
		{"Burst", "https://burst.shopify.com", "Shopify免费图片"},
		{"Reshot", "https://www.reshot.com", "免费图标和图片"},
		{"Kaboompics", "https://kaboompics.com", "免费生活图片"},
		{"Life of Pix", "https://www.lifeofpix.com", "免费高分辨率"},
		{"Gratisography", "https://gratisography.com", "创意免费图片"},
		{"Picjumbo", "https://picjumbo.com", "免费图片素材"},
		{"ISO Republic", "https://isorepublic.com", "免费CC0图片"},
		{"Foodiesfeed", "https://www.foodiesfeed.com", "免费美食图片"},
		{"图虫", "https://tuchong.com", "中国摄影社区"},
		{"摄影世界", "https://www.photoworld.com.cn", "摄影杂志"},
		{"蜂鸟网", "https://www.fengniao.com", "中国影像门户"},
		{"色影无忌", "https://www.xitek.com", "摄影器材社区"},
		{"中关村摄影", "https://dcdv.zol.com.cn", "摄影器材评测"},
		{"POCO摄影", "https://www.poco.cn", "摄影作品分享"},
		{"视觉中国", "https://www.vcg.com", "商业图片版权"},
		{"东方IC", "https://www.dfic.cn", "图片新闻"},
		{"全景网", "https://www.quanjing.com", "全景图片库"},
		{"昵图网", "https://www.nipic.com", "图片素材网"},
		{"千图网", "https://www.58pic.com", "设计素材下载"},
		{"摄图网", "https://699pic.com", "正版图片素材"},
		{"DPReview", "https://www.dpreview.com", "数码相机评测"},
		{"PetaPixel", "https://petapixel.com", "摄影新闻"},
		{"Fstoppers", "https://fstoppers.com", "摄影教程社区"},
		{"Digital Photography Review", "https://www.dpreview.com", "相机评测"},
		{"Lightroom", "https://www.adobe.com/products/photoshop-lightroom.html", "Adobe照片编辑"},
		{"Capture One", "https://www.captureone.com", "专业RAW处理"},
		{"DxO", "https://www.dxo.com", "相机评分与软件"},
		{"Snapseed", "https://snapseed.online", "Google照片编辑"},
		{"VSCO", "https://vsco.co", "照片滤镜编辑"},
		{"Darkroom", "https://darkroom.co", "Apple照片编辑"},
		{"RawTherapee", "https://rawtherapee.com", "开源RAW编辑"},
		{"darktable", "https://www.darktable.org", "开源照片处理"},
		{"GIMP", "https://www.gimp.org", "开源图像编辑"},
		{"Photopea", "https://www.photopea.com", "在线PS替代"},
		{"Canva", "https://www.canva.com", "在线设计工具"},
	}
}

func anime() []S {
	return []S{
		{"MyAnimeList", "https://myanimelist.net", "动漫数据库社区"},
		{"AniList", "https://anilist.co", "动漫追踪社区"},
		{"Crunchyroll", "https://www.crunchyroll.com", "全球动漫流媒体"},
		{"Funimation", "https://www.funimation.com", "北美动漫"},
		{"Bilibili", "https://www.bilibili.com", "B站动漫视频"},
		{"AcFun", "https://www.acfun.cn", "A站弹幕视频"},
		{"Niconico", "https://www.nicovideo.jp", "日本弹幕视频"},
		{"Anime-Planet", "https://www.anime-planet.com", "动漫推荐"},
		{"Kitsu", "https://kitsu.io", "动漫漫画追踪"},
		{"AnimeFLV", "https://www3.animeflv.net", "西语动漫"},
		{"9anime", "https://9anime.to", "免费动漫在线"},
		{"Anime News Network", "https://www.animenewsnetwork.com", "动漫新闻"},
		{"Pixiv", "https://www.pixiv.net", "日本插画社区"},
		{"DeviantArt", "https://www.deviantart.com", "艺术创作社区"},
		{"ArtStation", "https://www.artstation.com", "专业艺术作品"},
		{"Danbooru", "https://danbooru.donmai.us", "动漫图片标签库"},
		{"Gelbooru", "https://gelbooru.com", "动漫图库"},
		{"Zerochan", "https://www.zerochan.net", "动漫壁纸图库"},
		{"Wallhaven Anime", "https://wallhaven.cc/search?categories=010", "动漫壁纸"},
		{"Manga Plus", "https://mangaplus.shueisha.co.jp", "集英社官方漫画"},
		{"MangaDex", "https://mangadex.org", "漫画阅读平台"},
		{"Webtoon", "https://www.webtoons.com", "网络漫画平台"},
		{"Tapas", "https://tapas.io", "网络漫画与小说"},
		{"腾讯动漫", "https://ac.qq.com", "腾讯动漫平台"},
		{"快看漫画", "https://www.kuaikanmanhua.com", "快看漫画"},
		{"有妖气", "https://www.u17.com", "有妖气漫画"},
		{"哔哩哔哩漫画", "https://manga.bilibili.com", "B站漫画"},
		{"漫画岛", "https://www.manhuadao.com", "漫画阅读"},
		{"动漫之家", "https://www.idmzj.com", "动漫之家"},
		{"半次元", "https://bcy.net", "二次元创作"},
		{"Lofter", "https://www.lofter.com", "同人创作"},
		{"Comico", "https://www.comico.jp", "日本网络漫画"},
		{"Piccoma", "https://piccoma.com", "日韩漫画"},
		{"Kakao Webtoon", "https://webtoon.kakao.com", "韩国网络漫画"},
		{"Naver Webtoon", "https://comic.naver.com", "韩国Naver漫画"},
		{"ComicWalker", "https://comic-walker.com", "角川漫画"},
		{"ShonenJump+", "https://shonenjumpplus.com", "少年Jump+"},
		{"Bookwalker", "https://bookwalker.jp", "日本电子书漫画"},
		{"ComiXology", "https://www.comixology.com", "美漫数字平台"},
		{"Marvel", "https://www.marvel.com", "漫威官网"},
		{"DC Comics", "https://www.dc.com", "DC漫画"},
		{"Dark Horse", "https://www.darkhorse.com", "黑马漫画"},
		{"Image Comics", "https://imagecomics.com", "Image漫画"},
		{"VIZ Media", "https://www.viz.com", "日漫英语发行"},
		{"Yen Press", "https://yenpress.com", "轻小说漫画发行"},
		{"Amiami", "https://www.amiami.com", "动漫手办商店"},
		{"Good Smile Company", "https://www.goodsmile.info", "手办制造商"},
		{"Kotobukiya", "https://www.kotobukiya.co.jp", "寿屋手办"},
		{"Tokyo Otaku Mode", "https://otakumode.com", "二次元商品"},
		{"Animate", "https://www.animate.co.jp", "日本动漫店"},
	}
}

func cryptocurrency() []S {
	return []S{
		{"CoinMarketCap", "https://coinmarketcap.com", "加密货币市值排名"},
		{"CoinGecko", "https://www.coingecko.com", "加密货币数据"},
		{"Binance", "https://www.binance.com", "全球加密交易所"},
		{"Coinbase", "https://www.coinbase.com", "美国加密交易所"},
		{"Kraken", "https://www.kraken.com", "加密货币交易"},
		{"OKX", "https://www.okx.com", "加密货币交易所"},
		{"Bybit", "https://www.bybit.com", "加密衍生品交易"},
		{"KuCoin", "https://www.kucoin.com", "加密交易所"},
		{"Gate.io", "https://www.gate.io", "加密交易平台"},
		{"Bitfinex", "https://www.bitfinex.com", "加密交易所"},
		{"Gemini", "https://www.gemini.com", "合规加密交易"},
		{"Crypto.com", "https://crypto.com", "加密金融平台"},
		{"Uniswap", "https://app.uniswap.org", "去中心化交易"},
		{"PancakeSwap", "https://pancakeswap.finance", "BSC去中心化交易"},
		{"Aave", "https://aave.com", "DeFi借贷协议"},
		{"Compound", "https://compound.finance", "DeFi利率协议"},
		{"MakerDAO", "https://makerdao.com", "DAI稳定币协议"},
		{"Lido", "https://lido.fi", "流动性质押"},
		{"OpenSea", "https://opensea.io", "NFT交易市场"},
		{"Blur", "https://blur.io", "NFT交易平台"},
		{"Magic Eden", "https://magiceden.io", "多链NFT市场"},
		{"Rarible", "https://rarible.com", "NFT创建交易"},
		{"Ethereum", "https://ethereum.org", "以太坊官网"},
		{"Solana", "https://solana.com", "Solana区块链"},
		{"Polygon", "https://polygon.technology", "Polygon L2"},
		{"Avalanche", "https://www.avax.network", "Avalanche区块链"},
		{"Cosmos", "https://cosmos.network", "Cosmos生态"},
		{"Polkadot", "https://polkadot.network", "Polkadot跨链"},
		{"Cardano", "https://cardano.org", "Cardano区块链"},
		{"Arbitrum", "https://arbitrum.io", "以太坊L2扩展"},
		{"Optimism", "https://www.optimism.io", "以太坊L2"},
		{"Base", "https://base.org", "Coinbase L2"},
		{"MetaMask", "https://metamask.io", "加密钱包"},
		{"Phantom", "https://phantom.app", "Solana钱包"},
		{"Ledger", "https://www.ledger.com", "硬件钱包"},
		{"Trezor", "https://trezor.io", "硬件钱包"},
		{"Trust Wallet", "https://trustwallet.com", "多链钱包"},
		{"Rainbow", "https://rainbow.me", "以太坊钱包"},
		{"Etherscan", "https://etherscan.io", "以太坊区块浏览器"},
		{"Solscan", "https://solscan.io", "Solana区块浏览器"},
		{"BscScan", "https://bscscan.com", "BSC区块浏览器"},
		{"DeFi Llama", "https://defillama.com", "DeFi数据聚合"},
		{"Dune Analytics", "https://dune.com", "链上数据分析"},
		{"Nansen", "https://www.nansen.ai", "区块链分析平台"},
		{"Messari", "https://messari.io", "加密研究平台"},
		{"The Block", "https://www.theblock.co", "加密新闻"},
		{"CoinDesk", "https://www.coindesk.com", "加密货币新闻"},
		{"Decrypt", "https://decrypt.co", "Web3新闻"},
		{"Bankless", "https://www.bankless.com", "DeFi教育"},
		{"Mirror.xyz", "https://mirror.xyz", "Web3写作平台"},
	}
}

func science() []S {
	return []S{
		{"Nature", "https://www.nature.com", "自然杂志"},
		{"Science", "https://www.science.org", "科学杂志"},
		{"Cell", "https://www.cell.com", "细胞杂志"},
		{"The Lancet", "https://www.thelancet.com", "柳叶刀医学"},
		{"PNAS", "https://www.pnas.org", "美国国家科学院院刊"},
		{"arXiv", "https://arxiv.org", "学术预印本"},
		{"PubMed", "https://pubmed.ncbi.nlm.nih.gov", "生物医学文献"},
		{"Google Scholar", "https://scholar.google.com", "学术搜索"},
		{"Semantic Scholar", "https://www.semanticscholar.org", "AI学术搜索"},
		{"ResearchGate", "https://www.researchgate.net", "学术社交网络"},
		{"Academia.edu", "https://www.academia.edu", "学术论文分享"},
		{"JSTOR", "https://www.jstor.org", "学术期刊数据库"},
		{"Springer", "https://www.springer.com", "学术出版"},
		{"Elsevier", "https://www.elsevier.com", "学术出版商"},
		{"Wiley", "https://www.wiley.com", "科学出版"},
		{"IEEE", "https://www.ieee.org", "电气电子工程"},
		{"ACM", "https://www.acm.org", "计算机协会"},
		{"AAAS", "https://www.aaas.org", "美国科学促进会"},
		{"Royal Society", "https://royalsociety.org", "英国皇家学会"},
		{"CNRS", "https://www.cnrs.fr", "法国国家科研中心"},
		{"Max Planck", "https://www.mpg.de", "马克斯普朗克学会"},
		{"CERN", "https://home.cern", "欧洲核子研究中心"},
		{"NASA", "https://www.nasa.gov", "美国宇航局"},
		{"ESA", "https://www.esa.int", "欧洲航天局"},
		{"SpaceX", "https://www.spacex.com", "SpaceX太空探索"},
		{"National Geographic", "https://www.nationalgeographic.com", "国家地理"},
		{"Smithsonian", "https://www.si.edu", "史密森学会"},
		{"New Scientist", "https://www.newscientist.com", "新科学家"},
		{"Scientific American", "https://www.scientificamerican.com", "科学美国人"},
		{"Quanta Magazine", "https://www.quantamagazine.org", "数学与物理前沿"},
		{"ScienceDaily", "https://www.sciencedaily.com", "科学新闻聚合"},
		{"Phys.org", "https://phys.org", "物理与科技新闻"},
		{"Live Science", "https://www.livescience.com", "科学新闻"},
		{"Science News", "https://www.sciencenews.org", "科学新闻报道"},
		{"中国知网", "https://www.cnki.net", "中国学术论文数据库"},
		{"万方数据", "https://www.wanfangdata.com.cn", "万方数据库"},
		{"维普", "https://www.cqvip.com", "维普期刊数据库"},
		{"中国科学院", "https://www.cas.cn", "中科院官网"},
		{"科学网", "https://www.sciencenet.cn", "科学网博客"},
		{"果壳", "https://www.guokr.com", "科技人文社区"},
		{"知乎科学", "https://www.zhihu.com/topic/19554298", "知乎科学话题"},
		{"中国科学报", "https://www.sciencenet.cn/sbck", "科学报纸"},
		{"Wolfram MathWorld", "https://mathworld.wolfram.com", "数学百科"},
		{"Khan Academy", "https://www.khanacademy.org", "免费教育"},
		{"MIT Technology Review", "https://www.technologyreview.com", "MIT科技评论"},
		{"Wired Science", "https://www.wired.com/category/science", "Wired科学"},
		{"Aeon", "https://aeon.co", "科学与哲学"},
		{"Edge", "https://www.edge.org", "前沿科学讨论"},
		{"Nautilus", "https://nautil.us", "科学文化杂志"},
		{"Atlas Obscura", "https://www.atlasobscura.com", "探索奇妙世界"},
	}
}

func writing() []S {
	return []S{
		{"Medium", "https://medium.com", "内容发布平台"},
		{"Substack", "https://substack.com", "Newsletter平台"},
		{"WordPress", "https://wordpress.com", "博客与网站"},
		{"Ghost", "https://ghost.org", "专业发布平台"},
		{"Hashnode", "https://hashnode.com", "开发者博客"},
		{"Dev.to", "https://dev.to", "开发者社区"},
		{"Wattpad", "https://www.wattpad.com", "在线写作社区"},
		{"Archive of Our Own", "https://archiveofourown.org", "同人小说"},
		{"FanFiction.net", "https://www.fanfiction.net", "粉丝小说"},
		{"Royal Road", "https://www.royalroad.com", "网络小说"},
		{"Scribophile", "https://www.scribophile.com", "写作社区"},
		{"Reedsy", "https://reedsy.com", "出版与写作工具"},
		{"Grammarly", "https://www.grammarly.com", "AI语法检查"},
		{"ProWritingAid", "https://prowritingaid.com", "写作助手"},
		{"Hemingway Editor", "https://hemingwayapp.com", "写作可读性"},
		{"Scrivener", "https://www.literatureandlatte.com/scrivener", "长篇写作工具"},
		{"Ulysses", "https://ulysses.app", "Markdown写作"},
		{"iA Writer", "https://ia.net/writer", "专注写作"},
		{"Bear", "https://bear.app", "笔记与写作"},
		{"Notion", "https://www.notion.so", "知识管理写作"},
		{"Obsidian", "https://obsidian.md", "知识图谱笔记"},
		{"Roam Research", "https://roamresearch.com", "网状笔记"},
		{"Logseq", "https://logseq.com", "双向链接笔记"},
		{"Craft", "https://www.craft.do", "文档笔记"},
		{"Dropbox Paper", "https://www.dropbox.com/paper", "协作文档"},
		{"Google Docs", "https://docs.google.com", "在线文档"},
		{"Overleaf", "https://www.overleaf.com", "在线LaTeX编辑"},
		{"HackMD", "https://hackmd.io", "协作Markdown"},
		{"简书", "https://www.jianshu.com", "中文写作社区"},
		{"豆瓣阅读", "https://read.douban.com", "豆瓣电子书"},
		{"起点中文网", "https://www.qidian.com", "网络小说平台"},
		{"晋江文学城", "https://www.jjwxc.net", "女性文学平台"},
		{"番茄小说", "https://fanqienovel.com", "免费小说阅读"},
		{"七猫小说", "https://www.qimao.com", "免费小说"},
		{"纵横中文网", "https://www.zongheng.com", "网络文学"},
		{"17K小说网", "https://www.17k.com", "网络小说"},
		{"语雀", "https://www.yuque.com", "知识库文档"},
		{"飞书文档", "https://docs.feishu.cn", "飞书文档协作"},
		{"石墨文档", "https://shimo.im", "在线协作文档"},
		{"腾讯文档", "https://docs.qq.com", "腾讯在线文档"},
		{"秀米", "https://xiumi.us", "微信排版工具"},
		{"135编辑器", "https://www.135editor.com", "微信图文编辑"},
		{"壹伴", "https://yiban.io", "公众号编辑助手"},
		{"新榜", "https://www.newrank.cn", "内容产业服务"},
		{"西瓜数据", "https://data.xiguaji.com", "新媒体数据"},
		{"Leanpub", "https://leanpub.com", "自出版平台"},
		{"Gumroad", "https://gumroad.com", "数字产品销售"},
		{"Amazon KDP", "https://kdp.amazon.com", "亚马逊自出版"},
		{"Draft2Digital", "https://www.draft2digital.com", "电子书分发"},
		{"IngramSpark", "https://www.ingramspark.com", "图书印刷分发"},
	}
}

func podcast() []S {
	return []S{
		{"Spotify Podcasts", "https://open.spotify.com/genre/podcasts-page", "Spotify播客"},
		{"Apple Podcasts", "https://podcasts.apple.com", "Apple播客"},
		{"Google Podcasts", "https://podcasts.google.com", "Google播客"},
		{"Pocket Casts", "https://www.pocketcasts.com", "播客应用"},
		{"Overcast", "https://overcast.fm", "iOS播客应用"},
		{"Castro", "https://castro.fm", "播客管理应用"},
		{"Podcast Addict", "https://podcastaddict.com", "Android播客"},
		{"Podbean", "https://www.podbean.com", "播客托管平台"},
		{"Buzzsprout", "https://www.buzzsprout.com", "播客托管"},
		{"Anchor", "https://anchor.fm", "Spotify播客工具"},
		{"Transistor", "https://transistor.fm", "播客托管"},
		{"Captivate", "https://www.captivate.fm", "播客托管"},
		{"Simplecast", "https://simplecast.com", "播客分析托管"},
		{"Libsyn", "https://libsyn.com", "播客发行平台"},
		{"SoundCloud", "https://soundcloud.com", "音频分发"},
		{"Castbox", "https://castbox.fm", "播客发现平台"},
		{"Stitcher", "https://www.stitcher.com", "播客与广播"},
		{"TuneIn", "https://tunein.com", "网络广播电台"},
		{"iHeartRadio", "https://www.iheart.com", "广播与播客"},
		{"Audible", "https://www.audible.com", "有声书平台"},
		{"Audiobooks.com", "https://www.audiobooks.com", "有声书"},
		{"Blinkist", "https://www.blinkist.com", "书籍摘要"},
		{"喜马拉雅", "https://www.ximalaya.com", "有声内容平台"},
		{"荔枝FM", "https://www.lizhi.fm", "荔枝播客"},
		{"蜻蜓FM", "https://www.qingting.fm", "蜻蜓FM播客"},
		{"小宇宙", "https://www.xiaoyuzhoufm.com", "播客应用"},
		{"得到", "https://www.dedao.cn", "知识平台"},
		{"樊登读书", "https://www.fandengdushu.com", "读书平台"},
		{"凤凰FM", "https://diantai.ifeng.com", "凤凰广播"},
		{"央广云听", "https://www.radio.cn", "央广播客"},
		{"网易云音乐播客", "https://music.163.com/podcast", "网易播客"},
		{"皮艇", "https://www.piyingit.com", "语音内容"},
		{"Descript", "https://www.descript.com", "播客编辑工具"},
		{"Riverside", "https://riverside.fm", "远程播客录制"},
		{"Zencastr", "https://zencastr.com", "播客录制工具"},
		{"SquadCast", "https://squadcast.fm", "远程录音"},
		{"Cleanfeed", "https://cleanfeed.net", "在线录音"},
		{"Audacity", "https://www.audacityteam.org", "开源音频编辑"},
		{"Adobe Podcast", "https://podcast.adobe.com", "Adobe播客工具"},
		{"Alitu", "https://alitu.com", "播客制作工具"},
		{"Headliner", "https://www.headliner.app", "播客视频剪辑"},
		{"Opus Clip", "https://www.opus.pro", "AI剪辑播客"},
		{"Podchaser", "https://www.podchaser.com", "播客数据库"},
		{"Listen Notes", "https://www.listennotes.com", "播客搜索引擎"},
		{"Chartable", "https://chartable.com", "播客分析"},
		{"Podtrac", "https://analytics.podtrac.com", "播客流量统计"},
		{"RSS.com", "https://rss.com", "播客RSS托管"},
		{"Podcast Index", "https://podcastindex.org", "开放播客索引"},
		{"Goodpods", "https://goodpods.com", "播客社交推荐"},
		{"Podyssey", "https://podyssey.fm", "播客发现"},
	}
}

func startup() []S {
	return []S{
		{"Y Combinator", "https://www.ycombinator.com", "顶级创业孵化器"},
		{"TechCrunch", "https://techcrunch.com", "创业科技新闻"},
		{"Product Hunt", "https://www.producthunt.com", "新产品发现"},
		{"AngelList", "https://angel.co", "创业投资平台"},
		{"Crunchbase", "https://www.crunchbase.com", "创业公司数据库"},
		{"PitchBook", "https://pitchbook.com", "私募股权数据"},
		{"CB Insights", "https://www.cbinsights.com", "创投研究"},
		{"Startup Grind", "https://www.startupgrind.com", "创业者社区"},
		{"Indie Hackers", "https://www.indiehackers.com", "独立开发者社区"},
		{"Hacker News", "https://news.ycombinator.com", "黑客新闻"},
		{"Kickstarter", "https://www.kickstarter.com", "众筹平台"},
		{"Indiegogo", "https://www.indiegogo.com", "众筹平台"},
		{"GoFundMe", "https://www.gofundme.com", "筹款平台"},
		{"Patreon", "https://www.patreon.com", "创作者赞助"},
		{"Open Collective", "https://opencollective.com", "开源资金管理"},
		{"GitHub Sponsors", "https://github.com/sponsors", "开源赞助"},
		{"Buy Me a Coffee", "https://www.buymeacoffee.com", "创作者打赏"},
		{"Ko-fi", "https://ko-fi.com", "创作者支持"},
		{"Gumroad", "https://gumroad.com", "数字产品销售"},
		{"Stripe Atlas", "https://stripe.com/atlas", "创业公司注册"},
		{"Clerky", "https://www.clerky.com", "创业法律文件"},
		{"Firstbase", "https://www.firstbase.io", "公司注册服务"},
		{"36氪", "https://36kr.com", "科技创投媒体"},
		{"虎嗅", "https://www.huxiu.com", "商业科技资讯"},
		{"钛媒体", "https://www.tmtpost.com", "科技创新媒体"},
		{"品玩", "https://www.pingwest.com", "科技媒体"},
		{"极客公园", "https://www.geekpark.net", "创新者社区"},
		{"IT桔子", "https://www.itjuzi.com", "创投数据库"},
		{"投资界", "https://www.pedaily.cn", "PE/VC资讯"},
		{"创业邦", "https://www.cyzone.cn", "创业服务平台"},
		{"猎云网", "https://www.lieyunwang.com", "创投新闻"},
		{"铅笔道", "https://www.pencilnews.cn", "创业者报道"},
		{"Sequoia Capital", "https://www.sequoiacap.com", "红杉资本"},
		{"Andreessen Horowitz", "https://a16z.com", "a16z风投"},
		{"Accel", "https://www.accel.com", "全球风投"},
		{"Benchmark", "https://www.benchmark.com", "风险投资"},
		{"Greylock", "https://greylock.com", "风险投资"},
		{"Lightspeed", "https://lsvp.com", "光速创投"},
		{"GGV Capital", "https://www.ggvc.com", "纪源资本"},
		{"IDG Capital", "https://www.idgcapital.com", "IDG资本"},
		{"高瓴资本", "https://www.hillhousecap.com", "高瓴资本"},
		{"红杉中国", "https://www.sequoiacap.com/china", "红杉中国"},
		{"经纬创投", "https://www.matrixpartners.com.cn", "经纬创投"},
		{"真格基金", "https://www.zhenfund.com", "真格基金"},
		{"源码资本", "https://www.sourcecodecap.com", "源码资本"},
		{"Notion for Startups", "https://www.notion.so/startups", "创业工具"},
		{"Stripe Press", "https://press.stripe.com", "创业思想出版"},
		{"First Round Review", "https://review.firstround.com", "创业经验"},
		{"Lenny's Newsletter", "https://www.lennysnewsletter.com", "产品增长"},
		{"The Hustle", "https://thehustle.co", "商业新闻"},
	}
}

func legal() []S {
	return []S{
		{"中国裁判文书网", "https://wenshu.court.gov.cn", "裁判文书公开"},
		{"北大法宝", "https://www.pkulaw.com", "法律数据库"},
		{"威科先行", "https://law.wkinfo.com.cn", "法律信息平台"},
		{"法信", "https://www.faxin.cn", "法律知识服务"},
		{"无讼", "https://www.itslaw.com", "法律检索平台"},
		{"Alpha法律智能", "https://alphalawyer.cn", "AI法律研究"},
		{"天同诉讼圈", "https://www.tiantonglaw.com", "诉讼律所"},
		{"中国法律服务网", "https://www.12348.gov.cn", "公共法律服务"},
		{"国家法律法规数据库", "https://flk.npc.gov.cn", "法律法规查询"},
		{"律师黄页", "https://lvshi.baidu.com", "找律师服务"},
		{"法大大", "https://www.fadada.com", "电子合同签署"},
		{"上上签", "https://www.bestsign.cn", "电子签名"},
		{"e签宝", "https://www.esign.cn", "电子签名平台"},
		{"合同家", "https://www.hetongfamily.com", "合同模板"},
		{"LexisNexis", "https://www.lexisnexis.com", "法律信息数据库"},
		{"Westlaw", "https://www.westlaw.com", "法律研究平台"},
		{"Bloomberg Law", "https://www.bloomberglaw.com", "法律资讯服务"},
		{"Casetext", "https://casetext.com", "AI法律研究"},
		{"Fastcase", "https://www.fastcase.com", "法律研究"},
		{"Google Scholar Legal", "https://scholar.google.com/scholar?hl=en&as_sdt=2006", "法律判例搜索"},
		{"Cornell Law", "https://www.law.cornell.edu", "法律信息研究所"},
		{"Justia", "https://www.justia.com", "美国法律信息"},
		{"FindLaw", "https://www.findlaw.com", "法律信息"},
		{"Avvo", "https://www.avvo.com", "律师评价寻找"},
		{"LegalZoom", "https://www.legalzoom.com", "在线法律服务"},
		{"Rocket Lawyer", "https://www.rocketlawyer.com", "在线法律服务"},
		{"DocuSign", "https://www.docusign.com", "电子签名"},
		{"HelloSign", "https://www.hellosign.com", "Dropbox电子签名"},
		{"PandaDoc", "https://www.pandadoc.com", "文档与电子签名"},
		{"Ironclad", "https://ironcladapp.com", "合同生命周期管理"},
		{"ContractPodAi", "https://contractpodai.com", "AI合同管理"},
		{"Kira Systems", "https://www.kirasystems.com", "AI合同分析"},
		{"Luminance", "https://www.luminance.com", "AI法律平台"},
		{"Harvey AI", "https://www.harvey.ai", "AI法律助手"},
		{"EUR-Lex", "https://eur-lex.europa.eu", "欧盟法律数据库"},
		{"WIPO", "https://www.wipo.int", "世界知识产权组织"},
		{"USPTO", "https://www.uspto.gov", "美国专利商标局"},
		{"EPO", "https://www.epo.org", "欧洲专利局"},
		{"Google Patents", "https://patents.google.com", "专利搜索"},
		{"Espacenet", "https://worldwide.espacenet.com", "全球专利搜索"},
		{"国家知识产权局", "https://www.cnipa.gov.cn", "中国专利商标"},
		{"佰腾专利", "https://www.baiten.cn", "专利检索分析"},
		{"SooPAT", "https://www.soopat.com", "专利搜索"},
		{"权大师", "https://www.quandashi.com", "知识产权服务"},
		{"八戒知识产权", "https://ipr.zbj.com", "知识产权服务"},
		{"知果果", "https://www.zhiguoguo.com", "商标注册"},
		{"Creative Commons", "https://creativecommons.org", "知识共享许可"},
		{"DMCA", "https://www.dmca.com", "数字版权保护"},
		{"Internet Archive Legal", "https://archive.org/legal", "互联网档案法律"},
		{"EFF", "https://www.eff.org", "电子前沿基金会"},
	}
}
