package main

func videoEx() []S {
	return []S{
		{"Vimeo", "https://vimeo.com", "高品质视频社区"},
		{"Dailymotion", "https://www.dailymotion.com", "法国视频平台"},
		{"Rumble", "https://rumble.com", "视频分享平台"},
		{"Odysee", "https://odysee.com", "去中心化视频"},
		{"PeerTube", "https://joinpeertube.org", "联邦化视频"},
		{"TED Talks", "https://www.ted.com/talks", "TED演讲"},
		{"CuriosityStream", "https://curiositystream.com", "纪录片流媒体"},
		{"Nebula", "https://nebula.tv", "创作者视频平台"},
		{"Tubi", "https://tubitv.com", "免费视频流媒体"},
		{"Pluto TV", "https://pluto.tv", "免费电视流媒体"},
		{"Kanopy", "https://www.kanopy.com", "图书馆流媒体"},
		{"MUBI", "https://mubi.com", "艺术电影"},
		{"Criterion Channel", "https://www.criterionchannel.com", "经典电影"},
		{"Crackle", "https://www.crackle.com", "免费流媒体"},
		{"Peacock", "https://www.peacocktv.com", "NBC流媒体"},
		{"Paramount+", "https://www.paramountplus.com", "派拉蒙流媒体"},
		{"AMC+", "https://www.amcplus.com", "AMC流媒体"},
		{"Discovery+", "https://www.discoveryplus.com", "探索频道流媒体"},
		{"Viki", "https://www.viki.com", "亚洲影视字幕"},
		{"AsianCrush", "https://www.asiancrush.com", "亚洲电影"},
		{"Vudu", "https://www.vudu.com", "数字视频商店"},
		{"Google Play Movies", "https://play.google.com/store/movies", "Google影视"},
		{"Letterboxd", "https://letterboxd.com", "电影日记社交"},
		{"JustWatch", "https://www.justwatch.com", "流媒体搜索引擎"},
		{"IMDb", "https://www.imdb.com", "电影数据库"},
		{"Rotten Tomatoes", "https://www.rottentomatoes.com", "烂番茄影评"},
		{"Metacritic", "https://www.metacritic.com", "影评聚合"},
		{"TMDb", "https://www.themoviedb.org", "电影数据库"},
		{"Trakt", "https://trakt.tv", "影视追踪"},
		{"豆瓣电影", "https://movie.douban.com", "豆瓣电影评分"},
		{"猫眼电影", "https://www.maoyan.com", "猫眼票房数据"},
		{"淘票票", "https://www.taopiaopiao.com", "电影购票"},
		{"时光网", "https://www.mtime.com", "电影资讯"},
		{"电影天堂", "https://www.dytt89.com", "电影资源"},
		{"人人影视", "https://yyets.dmesg.app", "字幕与影视"},
		{"字幕组", "https://www.zimuxia.cn", "字幕下载"},
		{"射手网", "https://assrt.net", "字幕搜索"},
		{"搜狐视频", "https://tv.sohu.com", "搜狐视频"},
		{"芒果TV国际", "https://www.mgtv.com", "芒果TV"},
		{"CCTV", "https://tv.cctv.com", "央视网"},
		{"风行视频", "https://www.fun.tv", "风行视频"},
		{"乐视视频", "https://www.le.com", "乐视网"},
		{"1905电影网", "https://www.1905.com", "中国电影"},
		{"Vidio", "https://www.vidio.com", "印尼视频平台"},
		{"Hotstar", "https://www.hotstar.com", "印度流媒体"},
		{"ZEE5", "https://www.zee5.com", "印度流媒体"},
		{"iQIYI Intl", "https://www.iq.com", "爱奇艺国际版"},
		{"WeTV", "https://wetv.vip", "腾讯视频海外"},
		{"VIU", "https://www.viu.com", "亚洲流媒体"},
		{"Shahid", "https://shahid.mbc.net", "中东流媒体"},
		{"DAZN", "https://www.dazn.com", "体育流媒体"},
		{"Plex", "https://www.plex.tv", "媒体服务器"},
		{"Jellyfin", "https://jellyfin.org", "开源媒体服务器"},
		{"Emby", "https://emby.media", "媒体服务器"},
		{"Kodi", "https://kodi.tv", "开源媒体中心"},
		{"Infuse", "https://firecore.com/infuse", "Apple视频播放"},
		{"VLC", "https://www.videolan.org/vlc", "开源视频播放器"},
		{"mpv", "https://mpv.io", "极简视频播放"},
		{"HandBrake", "https://handbrake.fr", "视频转码工具"},
		{"FFmpeg", "https://ffmpeg.org", "视频处理工具"},
		{"OBS Studio", "https://obsproject.com", "直播录屏软件"},
		{"Streamlabs", "https://streamlabs.com", "直播工具套件"},
		{"Restream", "https://restream.io", "多平台直播推流"},
		{"DaVinci Resolve", "https://www.blackmagicdesign.com/products/davinciresolve", "专业视频剪辑"},
		{"Final Cut Pro", "https://www.apple.com/final-cut-pro", "Apple视频剪辑"},
		{"Adobe Premiere", "https://www.adobe.com/products/premiere.html", "Adobe视频剪辑"},
		{"CapCut", "https://www.capcut.com", "剪映国际版"},
		{"剪映", "https://www.capcut.cn", "字节视频剪辑"},
		{"必剪", "https://bcut.bilibili.cn", "B站视频剪辑"},
		{"万兴喵影", "https://www.wondershare.cn/products-solutions/filmora-video-editor.html", "视频编辑"},
		{"Clipchamp", "https://clipchamp.com", "微软视频编辑"},
		{"Canva Video", "https://www.canva.com/video-editor", "Canva视频编辑"},
		{"Lumen5", "https://lumen5.com", "AI视频创建"},
		{"InVideo", "https://invideo.io", "在线视频制作"},
		{"Animoto", "https://animoto.com", "视频幻灯片"},
		{"Biteable", "https://biteable.com", "视频制作工具"},
		{"Descript", "https://www.descript.com", "视频编辑与转写"},
		{"Runway", "https://runwayml.com", "AI视频生成"},
		{"Synthesia", "https://www.synthesia.io", "AI数字人视频"},
		{"HeyGen", "https://www.heygen.com", "AI视频生成"},
		{"Pictory", "https://pictory.ai", "AI视频总结"},
		{"Kapwing", "https://www.kapwing.com", "在线视频编辑"},
		{"Veed.io", "https://www.veed.io", "在线视频编辑"},
		{"FlexClip", "https://www.flexclip.com", "在线视频制作"},
		{"Clipfly", "https://www.clipfly.ai", "AI视频工具"},
		{"Opus Clip", "https://www.opus.pro", "AI短视频剪辑"},
		{"Vidnoz", "https://www.vidnoz.com", "AI视频工具"},
		{"Elai", "https://elai.io", "AI视频演示"},
		{"Colossyan", "https://www.colossyan.com", "AI培训视频"},
		{"Fliki", "https://fliki.ai", "文字转视频"},
		{"Steve.AI", "https://www.steve.ai", "AI动画视频"},
		{"Powtoon", "https://www.powtoon.com", "动画演示视频"},
		{"Vyond", "https://www.vyond.com", "商务动画视频"},
		{"Toonly", "https://www.toonly.com", "卡通动画制作"},
		{"Moovly", "https://www.moovly.com", "视频制作平台"},
		{"Renderforest", "https://www.renderforest.com", "视频动画品牌"},
		{"Promo.com", "https://promo.com", "营销视频制作"},
		{"Wistia", "https://wistia.com", "商业视频托管"},
		{"Brightcove", "https://www.brightcove.com", "企业视频平台"},
		{"Kaltura", "https://corp.kaltura.com", "视频管理平台"},
		{"Cloudflare Stream", "https://www.cloudflare.com/products/cloudflare-stream", "视频流服务"},
		{"Mux", "https://www.mux.com", "视频API平台"},
		{"api.video", "https://api.video", "视频API服务"},
		{"Vidyard", "https://www.vidyard.com", "视频营销分析"},
		{"Loom", "https://www.loom.com", "异步视频录制"},
		{"Soapbox", "https://wistia.com/soapbox", "快速视频录制"},
		{"Screencast-O-Matic", "https://screencast-o-matic.com", "屏幕录制"},
		{"Camtasia", "https://www.techsmith.com/video-editor.html", "屏幕录制与编辑"},
		{"ScreenPal", "https://screenpal.com", "屏幕录制分享"},
	}
}

func liveEx() []S {
	return []S{
		{"Kick", "https://kick.com", "游戏直播平台"},
		{"Caffeine", "https://www.caffeine.tv", "社交直播"},
		{"Trovo", "https://trovo.live", "游戏直播平台"},
		{"DLive", "https://dlive.tv", "区块链直播"},
		{"Nimo TV", "https://www.nimo.tv", "游戏直播"},
		{"Booyah", "https://booyah.live", "游戏直播平台"},
		{"Bigo Live", "https://www.bigo.tv", "全球直播社交"},
		{"17LIVE", "https://17.live", "亚洲直播平台"},
		{"Uplive", "https://www.uplive.com", "全球互动直播"},
		{"LiveMe", "https://www.liveme.com", "直播社交"},
		{"Periscope", "https://www.periscope.tv", "Twitter直播"},
		{"Instagram Live", "https://www.instagram.com", "Instagram直播"},
		{"TikTok Live", "https://www.tiktok.com/live", "抖音国际直播"},
		{"YouTube Live", "https://www.youtube.com/live", "YouTube直播"},
		{"Facebook Live", "https://www.facebook.com/formedia/solutions/facebook-live", "Facebook直播"},
		{"LinkedIn Live", "https://www.linkedin.com/help/linkedin/answer/100224", "LinkedIn直播"},
		{"NOW直播", "https://now.qq.com", "腾讯NOW直播"},
		{"一直播", "https://www.yizhibo.com", "一下科技直播"},
		{"花椒直播", "https://www.huajiao.com", "花椒直播"},
		{"映客直播", "https://www.inke.cn", "映客直播"},
		{"酷狗直播", "https://fanxing.kugou.com", "酷狗繁星直播"},
		{"网易CC直播", "https://cc.163.com", "网易CC"},
		{"YY直播", "https://www.yy.com", "YY直播平台"},
		{"企鹅电竞", "https://egame.qq.com", "腾讯电竞直播"},
		{"战旗直播", "https://www.zhanqi.tv", "游戏直播"},
		{"龙珠直播", "https://www.longzhu.com", "游戏直播"},
		{"陌陌直播", "https://www.immomo.com", "陌陌直播"},
		{"探探直播", "https://www.tantanapp.com", "社交直播"},
		{"抖音直播", "https://www.douyin.com/live", "抖音直播"},
		{"快手直播", "https://live.kuaishou.com", "快手直播"},
		{"淘宝直播", "https://taobaolive.taobao.com", "电商直播"},
		{"京东直播", "https://lives.jd.com", "京东直播"},
		{"拼多多直播", "https://mobile.yangkeduo.com", "拼多多直播"},
		{"小红书直播", "https://www.xiaohongshu.com/protocols/live", "小红书直播"},
		{"微信视频号直播", "https://channels.weixin.qq.com", "微信直播"},
		{"Streamyard", "https://streamyard.com", "浏览器直播工具"},
		{"StreamElements", "https://streamelements.com", "直播管理工具"},
		{"Riverside", "https://riverside.fm", "远程录制直播"},
		{"Ecamm Live", "https://www.ecamm.com/mac/ecammlive", "Mac直播工具"},
		{"vMix", "https://www.vmix.com", "专业直播软件"},
		{"Wirecast", "https://www.telestream.net/wirecast", "直播编码软件"},
		{"XSplit", "https://www.xsplit.com", "直播录屏"},
		{"Lightstream", "https://golightstream.com", "云端直播"},
		{"Twitch Studio", "https://www.twitch.tv/broadcast/studio", "Twitch直播工具"},
		{"Be.Live", "https://be.live", "浏览器直播"},
		{"Crowdcast", "https://www.crowdcast.io", "网络研讨直播"},
		{"Hopin", "https://hopin.com", "虚拟活动直播"},
		{"Zoom Webinar", "https://zoom.us/webinar", "网络研讨会"},
		{"Airmeet", "https://www.airmeet.com", "虚拟活动平台"},
		{"Remo", "https://remo.co", "虚拟社交活动"},
		{"Gather", "https://www.gather.town", "虚拟空间"},
		{"Spatial", "https://www.spatial.io", "3D虚拟活动"},
		{"Wonder", "https://www.wonder.me", "虚拟社交"},
		{"Run The World", "https://www.runtheworld.today", "虚拟活动"},
		{"Dacast", "https://www.dacast.com", "视频直播平台"},
		{"Castr", "https://castr.io", "多平台推流"},
		{"Ant Media", "https://antmedia.io", "直播服务器"},
		{"Wowza", "https://www.wowza.com", "流媒体引擎"},
		{"Mux Live", "https://www.mux.com/live-streaming", "直播API"},
		{"Livepeer", "https://livepeer.org", "去中心化直播"},
	}
}

func aiEx() []S {
	return []S{
		{"Perplexity", "https://www.perplexity.ai", "AI搜索引擎"},
		{"Poe", "https://poe.com", "多AI模型聚合"},
		{"Character.AI", "https://character.ai", "AI角色对话"},
		{"Inflection Pi", "https://pi.ai", "个人AI助手"},
		{"Google Bard", "https://bard.google.com", "Google AI对话"},
		{"Cohere", "https://cohere.com", "企业AI平台"},
		{"AI21 Labs", "https://www.ai21.com", "语言AI模型"},
		{"Mistral AI", "https://mistral.ai", "开源AI模型"},
		{"xAI Grok", "https://grok.x.ai", "xAI对话"},
		{"DeepSeek", "https://www.deepseek.com", "深度求索AI"},
		{"百川智能", "https://www.baichuan-ai.com", "百川大模型"},
		{"智谱AI", "https://www.zhipuai.cn", "智谱ChatGLM"},
		{"讯飞星火", "https://xinghuo.xfyun.cn", "讯飞AI大模型"},
		{"通义千问", "https://qianwen.aliyun.com", "阿里AI对话"},
		{"文心一言", "https://yiyan.baidu.com", "百度AI对话"},
		{"Kimi", "https://kimi.moonshot.cn", "月之暗面AI"},
		{"腾讯混元", "https://hunyuan.tencent.com", "腾讯AI大模型"},
		{"MiniMax", "https://www.minimaxi.com", "MiniMax AI"},
		{"零一万物", "https://www.01.ai", "李开复AI"},
		{"Stability AI", "https://stability.ai", "Stable Diffusion"},
		{"Midjourney", "https://www.midjourney.com", "AI图像生成"},
		{"DALL-E", "https://openai.com/dall-e-3", "OpenAI图像生成"},
		{"Leonardo AI", "https://leonardo.ai", "AI图像生成"},
		{"Ideogram", "https://ideogram.ai", "AI文字图像"},
		{"Adobe Firefly", "https://firefly.adobe.com", "Adobe AI创作"},
		{"Canva AI", "https://www.canva.com/ai-image-generator", "Canva AI图像"},
		{"Civitai", "https://civitai.com", "AI模型社区"},
		{"Playground AI", "https://playgroundai.com", "AI图像编辑"},
		{"Clipdrop", "https://clipdrop.co", "AI图像工具"},
		{"Remove.bg", "https://www.remove.bg", "AI去背景"},
		{"Photoroom", "https://www.photoroom.com", "AI图片编辑"},
		{"ElevenLabs", "https://elevenlabs.io", "AI语音合成"},
		{"Murf AI", "https://murf.ai", "AI配音"},
		{"Play.ht", "https://play.ht", "AI语音生成"},
		{"Resemble AI", "https://www.resemble.ai", "AI语音克隆"},
		{"Descript", "https://www.descript.com", "AI视频编辑"},
		{"Runway", "https://runwayml.com", "AI视频生成"},
		{"Pika", "https://pika.art", "AI视频创作"},
		{"Suno", "https://suno.com", "AI音乐生成"},
		{"Udio", "https://www.udio.com", "AI音乐创作"},
		{"AIVA", "https://www.aiva.ai", "AI作曲"},
		{"Soundraw", "https://soundraw.io", "AI音乐生成"},
		{"Cursor", "https://cursor.sh", "AI代码编辑器"},
		{"GitHub Copilot", "https://github.com/features/copilot", "AI编程助手"},
		{"Tabnine", "https://www.tabnine.com", "AI代码补全"},
		{"Codeium", "https://codeium.com", "免费AI编程"},
		{"Replit AI", "https://replit.com/ai", "AI开发环境"},
		{"Sourcegraph Cody", "https://sourcegraph.com/cody", "AI代码助手"},
		{"Amazon CodeWhisperer", "https://aws.amazon.com/codewhisperer", "AWS AI编程"},
		{"Devin", "https://www.cognition-labs.com/devin", "AI软件工程师"},
		{"Jasper", "https://www.jasper.ai", "AI营销写作"},
		{"Copy.ai", "https://www.copy.ai", "AI文案工具"},
		{"Writesonic", "https://writesonic.com", "AI写作助手"},
		{"Rytr", "https://rytr.me", "AI写作工具"},
		{"Wordtune", "https://www.wordtune.com", "AI文字润色"},
		{"QuillBot", "https://quillbot.com", "AI改写工具"},
		{"Notion AI", "https://www.notion.so/product/ai", "Notion AI助手"},
		{"Tome", "https://tome.app", "AI演示文稿"},
		{"Beautiful.ai", "https://www.beautiful.ai", "AI PPT制作"},
		{"Gamma", "https://gamma.app", "AI演示文稿"},
		{"SlidesAI", "https://www.slidesai.io", "AI幻灯片"},
		{"Otter.ai", "https://otter.ai", "AI会议转写"},
		{"Fireflies.ai", "https://fireflies.ai", "AI会议记录"},
		{"tl;dv", "https://tldv.io", "AI会议总结"},
		{"Mem", "https://get.mem.ai", "AI笔记"},
		{"Cogram", "https://www.cogram.com", "AI会议助手"},
		{"Zapier AI", "https://zapier.com/ai", "AI自动化"},
		{"Bardeen", "https://www.bardeen.ai", "AI工作流"},
		{"Relevance AI", "https://relevanceai.com", "AI工作流平台"},
		{"Voiceflow", "https://www.voiceflow.com", "AI对话设计"},
		{"Botpress", "https://botpress.com", "开源聊天机器人"},
		{"Stack AI", "https://www.stack-ai.com", "AI应用构建"},
		{"Flowise", "https://flowiseai.com", "AI流程构建"},
		{"Dify", "https://dify.ai", "LLM应用平台"},
		{"Coze", "https://www.coze.com", "字节AI Bot平台"},
		{"AI Model Hub", "https://www.modelscope.cn", "魔搭AI模型社区"},
		{"百度飞桨", "https://www.paddlepaddle.org.cn", "百度深度学习"},
		{"旷视", "https://www.megvii.com", "旷视科技"},
		{"商汤", "https://www.sensetime.com", "商汤科技AI"},
		{"依图", "https://www.yitutech.com", "依图AI"},
		{"云从科技", "https://www.cloudwalk.com", "云从AI"},
		{"科大讯飞", "https://www.iflytek.com", "语音AI"},
		{"思必驰", "https://www.aispeech.com", "对话式AI"},
		{"出门问问", "https://www.chumenwenwen.com", "AI语音交互"},
		{"达观数据", "https://www.datagrand.com", "NLP AI"},
		{"第四范式", "https://www.4paradigm.com", "企业AI"},
		{"竹间智能", "https://www.emotibot.com", "情感AI"},
		{"小冰", "https://www.xiaoice.com", "小冰AI框架"},
		{"Nvidia AI", "https://www.nvidia.com/en-us/ai", "Nvidia AI平台"},
		{"Intel AI", "https://www.intel.com/content/www/us/en/artificial-intelligence/overview.html", "Intel AI"},
		{"AMD AI", "https://www.amd.com/en/solutions/ai.html", "AMD AI解决方案"},
		{"Cerebras", "https://www.cerebras.net", "AI芯片"},
		{"SambaNova", "https://sambanova.ai", "AI计算平台"},
		{"Graphcore", "https://www.graphcore.ai", "IPU AI芯片"},
		{"Habana Labs", "https://habana.ai", "Intel AI芯片"},
		{"Weights & Biases", "https://wandb.ai", "ML实验追踪"},
		{"Neptune.ai", "https://neptune.ai", "ML实验管理"},
		{"ClearML", "https://clear.ml", "ML运维平台"},
		{"Determined AI", "https://www.determined.ai", "ML训练平台"},
		{"Modal", "https://modal.com", "云端AI计算"},
		{"Banana.dev", "https://www.banana.dev", "AI推理托管"},
		{"Baseten", "https://www.baseten.co", "ML模型部署"},
		{"BentoML", "https://www.bentoml.com", "AI模型服务"},
		{"Seldon", "https://www.seldon.io", "ML部署平台"},
		{"Valohai", "https://valohai.com", "ML流水线"},
		{"Paperspace", "https://www.paperspace.com", "GPU云计算"},
		{"Lambda", "https://lambdalabs.com", "GPU云服务"},
		{"CoreWeave", "https://www.coreweave.com", "GPU云计算"},
		{"RunPod", "https://www.runpod.io", "GPU云部署"},
		{"Vast.ai", "https://vast.ai", "GPU租赁市场"},
	}
}

func newsEx() []S {
	return []S{
		{"Al Jazeera", "https://www.aljazeera.com", "半岛电视台"},
		{"France 24", "https://www.france24.com", "法国24新闻"},
		{"Deutsche Welle", "https://www.dw.com", "德国之声"},
		{"NHK World", "https://www3.nhk.or.jp/nhkworld", "日本NHK国际"},
		{"RT", "https://www.rt.com", "今日俄罗斯"},
		{"TASS", "https://tass.com", "塔斯社"},
		{"Yonhap", "https://en.yna.co.kr", "韩联社"},
		{"Kyodo News", "https://english.kyodonews.net", "共同社"},
		{"Xinhua", "https://www.xinhuanet.com", "新华社"},
		{"People's Daily", "https://en.people.cn", "人民日报英文"},
		{"Nikkei Asia", "https://asia.nikkei.com", "日经亚洲"},
		{"South China Morning Post", "https://www.scmp.com", "南华早报"},
		{"The Diplomat", "https://thediplomat.com", "亚太外交"},
		{"Channel NewsAsia", "https://www.channelnewsasia.com", "亚洲新闻"},
		{"The Straits Times", "https://www.straitstimes.com", "海峡时报"},
		{"The Hindu", "https://www.thehindu.com", "印度日报"},
		{"Times of India", "https://timesofindia.indiatimes.com", "印度时报"},
		{"NDTV", "https://www.ndtv.com", "印度新闻"},
		{"ABC News AU", "https://www.abc.net.au/news", "澳大利亚新闻"},
		{"Stuff NZ", "https://www.stuff.co.nz", "新西兰新闻"},
		{"The Local", "https://www.thelocal.com", "欧洲本地新闻"},
		{"EUobserver", "https://euobserver.com", "欧盟新闻"},
		{"Euronews", "https://www.euronews.com", "欧洲新闻"},
		{"Politico EU", "https://www.politico.eu", "欧洲政策新闻"},
		{"Axios", "https://www.axios.com", "美国商业新闻"},
		{"The Hill", "https://thehill.com", "美国政策新闻"},
		{"Vox", "https://www.vox.com", "解释性新闻"},
		{"Slate", "https://slate.com", "评论与分析"},
		{"The Intercept", "https://theintercept.com", "调查新闻"},
		{"ProPublica", "https://www.propublica.org", "公益调查新闻"},
		{"The Daily Beast", "https://www.thedailybeast.com", "新闻评论"},
		{"Quartz", "https://qz.com", "商业新闻"},
		{"Rest of World", "https://restofworld.org", "全球科技新闻"},
		{"The Information", "https://www.theinformation.com", "科技商业新闻"},
		{"Semafor", "https://www.semafor.com", "全球新闻"},
		{"Punchbowl News", "https://punchbowl.news", "政策新闻"},
		{"404 Media", "https://www.404media.co", "科技调查"},
		{"Substack News", "https://substack.com/discover/category/news", "独立新闻"},
		{"AllSides", "https://www.allsides.com", "多角度新闻"},
		{"Ground News", "https://ground.news", "新闻偏见检测"},
		{"Flipboard", "https://flipboard.com", "新闻聚合"},
		{"SmartNews", "https://www.smartnews.com", "智能新闻"},
		{"Google News", "https://news.google.com", "Google新闻聚合"},
		{"Apple News", "https://www.apple.com/apple-news", "Apple新闻"},
		{"Microsoft News", "https://www.msn.com/news", "微软新闻"},
		{"Yahoo News", "https://news.yahoo.com", "雅虎新闻"},
		{"观察者网", "https://www.guancha.cn", "观察者网"},
		{"界面新闻", "https://www.jiemian.com", "界面新闻"},
		{"澎湃新闻", "https://www.thepaper.cn", "澎湃新闻"},
		{"新京报", "https://www.bjnews.com.cn", "新京报"},
		{"南方周末", "https://www.infzm.com", "南方周末"},
		{"中国新闻周刊", "https://www.chinanewsweek.com.cn", "新闻周刊"},
		{"三联生活周刊", "https://www.lifeweek.com.cn", "生活周刊"},
		{"经济观察报", "https://www.eeo.com.cn", "经济观察"},
		{"中国经营报", "https://www.cb.com.cn", "商业报道"},
		{"21世纪经济报道", "https://www.21jingji.com", "财经新闻"},
		{"每日经济新闻", "https://www.nbd.com.cn", "财经新闻"},
		{"中国日报", "https://www.chinadaily.com.cn", "中国日报"},
		{"环球时报", "https://www.globaltimes.cn", "环球时报英文"},
		{"北京日报", "https://www.bjd.com.cn", "北京日报"},
		{"新民晚报", "https://www.xinmin.cn", "上海新闻"},
		{"羊城晚报", "https://www.ycwb.com", "广州新闻"},
		{"封面新闻", "https://www.thecover.cn", "封面新闻"},
		{"红星新闻", "https://www.cdsb.com", "红星新闻"},
		{"极目新闻", "https://www.ctdsb.net", "楚天都市报"},
		{"上游新闻", "https://www.cqcb.com", "重庆新闻"},
		{"正观新闻", "https://www.zzwb.cn", "郑州新闻"},
		{"潮新闻", "https://tidenews.com.cn", "浙江新闻"},
		{"九派新闻", "https://www.jiupainews.com", "九派新闻"},
		{"海报新闻", "https://www.dzwww.com", "山东新闻"},
	}
}

func socialEx() []S {
	return []S{
		{"Threads", "https://www.threads.net", "Meta文字社交"},
		{"Bluesky", "https://bsky.app", "去中心化社交"},
		{"Mastodon", "https://joinmastodon.org", "联邦化社交"},
		{"Nostr", "https://nostr.com", "去中心化协议"},
		{"Hive Social", "https://www.hivesocial.app", "Hive社交"},
		{"Lemon8", "https://www.lemon8-app.com", "生活方式分享"},
		{"BeReal", "https://bereal.com", "真实瞬间分享"},
		{"Clubhouse", "https://www.clubhouse.com", "语音社交"},
		{"Damus", "https://damus.io", "去中心化社交"},
		{"Lemmy", "https://join-lemmy.org", "联邦化论坛"},
		{"Pixelfed", "https://pixelfed.org", "去中心化图片"},
		{"BookWyrm", "https://joinbookwyrm.com", "联邦化读书"},
		{"Matrix", "https://matrix.org", "去中心化通信"},
		{"Signal", "https://signal.org", "加密即时通信"},
		{"Telegram", "https://telegram.org", "Telegram通信"},
		{"WhatsApp", "https://www.whatsapp.com", "WhatsApp通信"},
		{"Line", "https://line.me", "Line日本通信"},
		{"KakaoTalk", "https://www.kakaocorp.com/page/service/service/KakaoTalk", "韩国聊天"},
		{"Viber", "https://www.viber.com", "Viber通信"},
		{"Skype", "https://www.skype.com", "Skype视频通话"},
		{"Zoom", "https://zoom.us", "视频会议"},
		{"Teams", "https://www.microsoft.com/microsoft-teams", "微软团队"},
		{"Slack", "https://slack.com", "团队协作"},
		{"Discord", "https://discord.com", "社区聊天"},
		{"微信", "https://weixin.qq.com", "微信社交"},
		{"QQ", "https://im.qq.com", "QQ即时通信"},
		{"微博", "https://weibo.com", "新浪微博"},
		{"抖音", "https://www.douyin.com", "短视频社交"},
		{"快手", "https://www.kuaishou.com", "快手短视频"},
		{"小红书", "https://www.xiaohongshu.com", "种草社区"},
		{"知乎", "https://www.zhihu.com", "知识问答"},
		{"豆瓣", "https://www.douban.com", "兴趣社区"},
		{"即刻", "https://www.okjike.com", "年轻人社区"},
		{"Soul", "https://www.soulapp.cn", "灵魂社交"},
		{"Aloha", "https://www.aloha-app.com", "社交应用"},
		{"陌陌", "https://www.immomo.com", "社交平台"},
		{"探探", "https://www.tantanapp.com", "社交匹配"},
		{"Bumble", "https://bumble.com", "约会社交"},
		{"Tinder", "https://tinder.com", "Tinder社交"},
		{"Hinge", "https://hinge.co", "约会应用"},
		{"OkCupid", "https://www.okcupid.com", "约会平台"},
		{"Badoo", "https://badoo.com", "全球社交约会"},
		{"Coffee Meets Bagel", "https://coffeemeetsbagel.com", "约会应用"},
		{"Happn", "https://www.happn.com", "位置社交"},
		{"MeetMe", "https://www.meetme.com", "社交发现"},
		{"Nextdoor", "https://nextdoor.com", "社区邻居"},
		{"Meetup", "https://www.meetup.com", "线下活动社交"},
		{"Facebook Groups", "https://www.facebook.com/groups", "Facebook群组"},
		{"Reddit", "https://www.reddit.com", "社区论坛"},
		{"Tumblr", "https://www.tumblr.com", "博客社交"},
		{"Amino", "https://aminoapps.com", "兴趣社区"},
		{"Lofter", "https://www.lofter.com", "兴趣创作"},
		{"DeviantArt", "https://www.deviantart.com", "创意艺术社区"},
		{"ArtStation", "https://www.artstation.com", "专业创作社区"},
		{"Behance", "https://www.behance.net", "创意展示社区"},
		{"Dribbble", "https://dribbble.com", "设计师社交"},
		{"500px", "https://500px.com", "摄影师社交"},
		{"Flickr", "https://www.flickr.com", "图片分享"},
		{"VSCO", "https://vsco.co", "摄影社交"},
		{"Strava", "https://www.strava.com", "运动社交"},
	}
}

func developerEx() []S {
	return []S{
		{"VS Code", "https://code.visualstudio.com", "微软代码编辑器"},
		{"JetBrains", "https://www.jetbrains.com", "IDE开发工具"},
		{"Neovim", "https://neovim.io", "现代Vim"},
		{"Zed", "https://zed.dev", "高性能编辑器"},
		{"Replit", "https://replit.com", "在线IDE"},
		{"Gitpod", "https://www.gitpod.io", "云端开发环境"},
		{"GitHub Codespaces", "https://github.com/features/codespaces", "GitHub云IDE"},
		{"AWS Cloud9", "https://aws.amazon.com/cloud9", "AWS云IDE"},
		{"Glitch", "https://glitch.com", "在线Web开发"},
		{"Observable", "https://observablehq.com", "数据可视化笔记"},
		{"CodePen", "https://codepen.io", "前端代码展示"},
		{"JSFiddle", "https://jsfiddle.net", "在线JS编辑"},
		{"StackBlitz", "https://stackblitz.com", "WebContainer IDE"},
		{"CodeSandbox", "https://codesandbox.io", "在线开发"},
		{"LeetCode", "https://leetcode.com", "算法刷题"},
		{"LeetCode中文", "https://leetcode.cn", "力扣中文"},
		{"HackerRank", "https://www.hackerrank.com", "编程挑战"},
		{"Codeforces", "https://codeforces.com", "编程竞赛"},
		{"TopCoder", "https://www.topcoder.com", "编程比赛"},
		{"AtCoder", "https://atcoder.jp", "日本编程竞赛"},
		{"Codewars", "https://www.codewars.com", "编程练习"},
		{"Exercism", "https://exercism.org", "编程学习"},
		{"Project Euler", "https://projecteuler.net", "数学编程挑战"},
		{"Advent of Code", "https://adventofcode.com", "年度编程挑战"},
		{"洛谷", "https://www.luogu.com.cn", "中文编程训练"},
		{"牛客竞赛", "https://ac.nowcoder.com", "编程竞赛平台"},
		{"Figma", "https://www.figma.com", "设计协作工具"},
		{"Linear", "https://linear.app", "项目管理"},
		{"Jira", "https://www.atlassian.com/software/jira", "项目管理"},
		{"Notion", "https://www.notion.so", "知识管理"},
		{"Confluence", "https://www.atlassian.com/software/confluence", "团队文档"},
		{"GitKraken", "https://www.gitkraken.com", "Git可视化"},
		{"Tower", "https://www.git-tower.com", "Git客户端"},
		{"Sourcetree", "https://www.sourcetreeapp.com", "Git GUI"},
		{"Fork", "https://git-fork.com", "Git客户端"},
		{"Warp", "https://www.warp.dev", "现代终端"},
		{"iTerm2", "https://iterm2.com", "macOS终端"},
		{"Windows Terminal", "https://github.com/microsoft/terminal", "Windows终端"},
		{"Alacritty", "https://alacritty.org", "GPU加速终端"},
		{"Hyper", "https://hyper.is", "Electron终端"},
		{"Oh My Zsh", "https://ohmyz.sh", "Zsh框架"},
		{"Starship", "https://starship.rs", "终端提示符"},
		{"tmux", "https://github.com/tmux/tmux", "终端复用器"},
		{"Regex101", "https://regex101.com", "正则表达式测试"},
		{"JSON Formatter", "https://jsonformatter.org", "JSON格式化"},
		{"JWT.io", "https://jwt.io", "JWT调试器"},
		{"cURL Converter", "https://curlconverter.com", "cURL转代码"},
		{"Carbon", "https://carbon.now.sh", "代码截图"},
		{"Ray.so", "https://ray.so", "代码美化截图"},
		{"Excalidraw", "https://excalidraw.com", "手绘风格白板"},
		{"Draw.io", "https://app.diagrams.net", "流程图工具"},
		{"Eraser.io", "https://www.eraser.io", "技术图表"},
		{"Mermaid", "https://mermaid.js.org", "文本图表"},
		{"PlantUML", "https://plantuml.com", "UML图表"},
		{"Lucidchart", "https://www.lucidchart.com", "在线图表"},
		{"Whimsical", "https://whimsical.com", "流程图思维导图"},
		{"DockerHub", "https://hub.docker.com", "容器镜像仓库"},
		{"npm", "https://www.npmjs.com", "Node包管理"},
		{"PyPI", "https://pypi.org", "Python包索引"},
		{"crates.io", "https://crates.io", "Rust包管理"},
	}
}

func shoppingEx() []S {
	return []S{
		{"Walmart", "https://www.walmart.com", "沃尔玛商城"},
		{"Target", "https://www.target.com", "Target零售"},
		{"Best Buy", "https://www.bestbuy.com", "电子产品零售"},
		{"Costco", "https://www.costco.com", "Costco会员店"},
		{"Etsy", "https://www.etsy.com", "手工艺品市场"},
		{"Wish", "https://www.wish.com", "Wish低价电商"},
		{"Temu", "https://www.temu.com", "拼多多海外版"},
		{"AliExpress", "https://www.aliexpress.com", "速卖通跨境"},
		{"Rakuten", "https://www.rakuten.com", "乐天市场"},
		{"Mercado Libre", "https://www.mercadolibre.com", "拉美电商"},
		{"Flipkart", "https://www.flipkart.com", "印度电商"},
		{"Shopee", "https://shopee.com", "东南亚电商"},
		{"Lazada", "https://www.lazada.com", "东南亚电商"},
		{"Tokopedia", "https://www.tokopedia.com", "印尼电商"},
		{"Bukalapak", "https://www.bukalapak.com", "印尼电商"},
		{"Coupang", "https://www.coupang.com", "韩国电商"},
		{"Zalando", "https://www.zalando.com", "欧洲时尚电商"},
		{"OTTO", "https://www.otto.de", "德国电商"},
		{"Cdiscount", "https://www.cdiscount.com", "法国电商"},
		{"John Lewis", "https://www.johnlewis.com", "英国百货"},
		{"Argos", "https://www.argos.co.uk", "英国零售"},
		{"ASOS", "https://www.asos.com", "英国时尚电商"},
		{"Wayfair", "https://www.wayfair.com", "家居电商"},
		{"Overstock", "https://www.overstock.com", "折扣百货"},
		{"Newegg", "https://www.newegg.com", "电脑硬件电商"},
		{"B&H Photo", "https://www.bhphotovideo.com", "摄影器材"},
		{"Adorama", "https://www.adorama.com", "摄影电子"},
		{"REI", "https://www.rei.com", "户外用品"},
		{"Lululemon", "https://www.lululemon.com", "运动服饰"},
		{"Under Armour", "https://www.underarmour.com", "运动品牌"},
		{"天猫", "https://www.tmall.com", "天猫商城"},
		{"淘宝", "https://www.taobao.com", "淘宝网"},
		{"京东", "https://www.jd.com", "京东商城"},
		{"拼多多", "https://www.pinduoduo.com", "拼多多"},
		{"唯品会", "https://www.vip.com", "品牌特卖"},
		{"苏宁易购", "https://www.suning.com", "苏宁电器"},
		{"国美", "https://www.gome.com.cn", "国美电器"},
		{"当当网", "https://www.dangdang.com", "图书电商"},
		{"1号店", "https://www.yhd.com", "沃尔玛中国"},
		{"网易严选", "https://you.163.com", "品质电商"},
		{"小米有品", "https://www.xiaomiyoupin.com", "小米电商"},
		{"得物", "https://www.dewu.com", "潮流电商"},
		{"考拉海购", "https://www.kaola.com", "跨境电商"},
		{"蘑菇街", "https://www.mogujie.com", "女性电商"},
		{"Honey", "https://www.joinhoney.com", "优惠券插件"},
		{"Rakuten Rewards", "https://www.rakuten.com", "购物返现"},
		{"RetailMeNot", "https://www.retailmenot.com", "优惠券网站"},
		{"Slickdeals", "https://slickdeals.net", "折扣信息"},
		{"DealNews", "https://www.dealnews.com", "交易新闻"},
		{"CamelCamelCamel", "https://camelcamelcamel.com", "Amazon价格追踪"},
		{"Keepa", "https://keepa.com", "Amazon价格历史"},
		{"PriceGrabber", "https://www.pricegrabber.com", "比价网站"},
		{"Google Shopping", "https://shopping.google.com", "Google购物"},
		{"Shopify", "https://www.shopify.com", "电商建站"},
		{"BigCommerce", "https://www.bigcommerce.com", "电商平台"},
		{"WooCommerce", "https://woocommerce.com", "WordPress电商"},
		{"Magento", "https://business.adobe.com/products/magento/magento-commerce.html", "Adobe电商"},
		{"PrestaShop", "https://www.prestashop.com", "开源电商"},
		{"OpenCart", "https://www.opencart.com", "开源购物车"},
		{"Saleor", "https://saleor.io", "无头电商"},
	}
}

func musicEx() []S {
	return []S{
		{"Deezer", "https://www.deezer.com", "Deezer音乐"},
		{"Tidal", "https://tidal.com", "HiFi音乐流媒体"},
		{"Qobuz", "https://www.qobuz.com", "Hi-Res音乐"},
		{"Amazon Music", "https://music.amazon.com", "亚马逊音乐"},
		{"YouTube Music", "https://music.youtube.com", "YouTube音乐"},
		{"Pandora", "https://www.pandora.com", "音乐广播"},
		{"iHeartRadio", "https://www.iheart.com", "广播音乐"},
		{"TuneIn", "https://tunein.com", "全球广播"},
		{"Last.fm", "https://www.last.fm", "音乐追踪社交"},
		{"Rate Your Music", "https://rateyourmusic.com", "音乐评分数据库"},
		{"Discogs", "https://www.discogs.com", "唱片数据库市场"},
		{"MusicBrainz", "https://musicbrainz.org", "音乐元数据"},
		{"Genius", "https://genius.com", "歌词与注释"},
		{"Musixmatch", "https://www.musixmatch.com", "全球歌词平台"},
		{"AZLyrics", "https://www.azlyrics.com", "歌词搜索"},
		{"Songsterr", "https://www.songsterr.com", "吉他谱"},
		{"Ultimate Guitar", "https://www.ultimate-guitar.com", "吉他谱社区"},
		{"Chordify", "https://chordify.net", "自动和弦识别"},
		{"Flat.io", "https://flat.io", "在线乐谱编辑"},
		{"MuseScore", "https://musescore.org", "开源乐谱软件"},
		{"Noteflight", "https://www.noteflight.com", "在线乐谱"},
		{"BandLab", "https://www.bandlab.com", "在线音乐制作"},
		{"Splice", "https://splice.com", "音乐制作样本"},
		{"Landr", "https://www.landr.com", "AI母带处理"},
		{"DistroKid", "https://distrokid.com", "音乐分发"},
		{"TuneCore", "https://www.tunecore.com", "音乐发行"},
		{"CD Baby", "https://cdbaby.com", "独立音乐发行"},
		{"Amuse", "https://www.amuse.io", "免费音乐分发"},
		{"AWAL", "https://www.awal.com", "独立音乐发行"},
		{"Ableton", "https://www.ableton.com", "Ableton Live"},
		{"FL Studio", "https://www.image-line.com", "FL Studio DAW"},
		{"Logic Pro", "https://www.apple.com/logic-pro", "Apple DAW"},
		{"Cubase", "https://www.steinberg.net/cubase", "Steinberg DAW"},
		{"Pro Tools", "https://www.avid.com/pro-tools", "专业音频工作站"},
		{"Reaper", "https://www.reaper.fm", "平价DAW"},
		{"GarageBand", "https://www.apple.com/garageband", "Apple免费DAW"},
		{"Bitwig", "https://www.bitwig.com", "现代DAW"},
		{"Reason", "https://www.reasonstudios.com", "虚拟机架DAW"},
		{"Ardour", "https://ardour.org", "开源DAW"},
		{"LMMS", "https://lmms.io", "开源音乐制作"},
		{"Audacity", "https://www.audacityteam.org", "开源音频编辑"},
		{"iZotope", "https://www.izotope.com", "音频插件"},
		{"Native Instruments", "https://www.native-instruments.com", "音乐软硬件"},
		{"Waves", "https://www.waves.com", "音频插件"},
		{"FabFilter", "https://www.fabfilter.com", "音频效果插件"},
		{"Arturia", "https://www.arturia.com", "音乐软硬件"},
		{"Roland", "https://www.roland.com", "电子乐器"},
		{"Yamaha Music", "https://www.yamaha.com/en/products/musical_instruments", "雅马哈乐器"},
		{"Fender", "https://www.fender.com", "吉他品牌"},
		{"Gibson", "https://www.gibson.com", "吉他品牌"},
		{"Sweetwater", "https://www.sweetwater.com", "音乐设备商店"},
		{"Thomann", "https://www.thomann.de", "欧洲音乐设备"},
		{"酷我音乐", "https://www.kuwo.cn", "酷我音乐"},
		{"虾米音乐", "https://www.xiami.com", "虾米音乐"},
		{"5sing", "https://5sing.kugou.com", "原创音乐"},
		{"街声", "https://streetvoice.com", "独立音乐"},
		{"落网", "https://www.luoo.net", "独立音乐推荐"},
		{"豆瓣音乐", "https://music.douban.com", "音乐评分"},
		{"Echo回声", "https://www.app-echo.com", "弹幕音乐"},
		{"MOO音乐", "https://music.moo.qq.com", "腾讯品质音乐"},
	}
}

func toolsEx() []S {
	return []S{
		{"Raycast", "https://www.raycast.com", "macOS效率启动器"},
		{"Alfred", "https://www.alfredapp.com", "macOS效率工具"},
		{"Keyboard Maestro", "https://www.keyboardmaestro.com", "macOS自动化"},
		{"BetterTouchTool", "https://folivora.ai", "macOS触控增强"},
		{"Karabiner", "https://karabiner-elements.pqrs.org", "macOS键盘映射"},
		{"Rectangle", "https://rectangleapp.com", "macOS窗口管理"},
		{"Magnet", "https://magnet.crowdcafe.com", "macOS窗口管理"},
		{"CleanMyMac", "https://macpaw.com/cleanmymac", "Mac清理工具"},
		{"Bartender", "https://www.macbartender.com", "菜单栏管理"},
		{"iStat Menus", "https://bjango.com/mac/istatmenus", "系统监控"},
		{"PowerToys", "https://learn.microsoft.com/windows/powertoys", "Windows增强"},
		{"Everything", "https://www.voidtools.com", "Windows文件搜索"},
		{"Ditto", "https://ditto-cp.sourceforge.io", "剪贴板管理"},
		{"AutoHotkey", "https://www.autohotkey.com", "Windows自动化"},
		{"ShareX", "https://getsharex.com", "截图录屏上传"},
		{"Snagit", "https://www.techsmith.com/screen-capture.html", "截图编辑"},
		{"Greenshot", "https://getgreenshot.org", "截图工具"},
		{"Flameshot", "https://flameshot.org", "Linux截图"},
		{"Obsidian", "https://obsidian.md", "知识图谱笔记"},
		{"Logseq", "https://logseq.com", "双向链接笔记"},
		{"Roam Research", "https://roamresearch.com", "网状笔记"},
		{"Joplin", "https://joplinapp.org", "开源笔记"},
		{"Standard Notes", "https://standardnotes.com", "加密笔记"},
		{"Simplenote", "https://simplenote.com", "简洁笔记"},
		{"Typora", "https://typora.io", "Markdown编辑器"},
		{"Bear", "https://bear.app", "Apple笔记"},
		{"GoodNotes", "https://www.goodnotes.com", "手写笔记"},
		{"Notability", "https://notability.com", "iPad手写笔记"},
		{"Evernote", "https://evernote.com", "笔记应用"},
		{"OneNote", "https://www.onenote.com", "微软笔记"},
		{"Apple Notes", "https://www.icloud.com/notes", "Apple备忘录"},
		{"Google Keep", "https://keep.google.com", "Google便签"},
		{"Todoist", "https://todoist.com", "任务管理"},
		{"TickTick", "https://ticktick.com", "滴答清单"},
		{"Things", "https://culturedcode.com/things", "Apple任务管理"},
		{"OmniFocus", "https://www.omnigroup.com/omnifocus", "GTD任务管理"},
		{"Fantastical", "https://flexibits.com/fantastical", "日历应用"},
		{"Calendly", "https://calendly.com", "日程预约"},
		{"Cal.com", "https://cal.com", "开源预约"},
		{"Clockwise", "https://www.getclockwise.com", "AI日历优化"},
		{"1Password", "https://1password.com", "密码管理"},
		{"Bitwarden", "https://bitwarden.com", "开源密码管理"},
		{"NordPass", "https://nordpass.com", "密码管理"},
		{"Dropbox", "https://www.dropbox.com", "文件同步"},
		{"Google Drive", "https://drive.google.com", "云存储"},
		{"OneDrive", "https://onedrive.live.com", "微软云存储"},
		{"iCloud", "https://www.icloud.com", "Apple云存储"},
		{"Box", "https://www.box.com", "企业云存储"},
		{"pCloud", "https://www.pcloud.com", "安全云存储"},
		{"Mega", "https://mega.io", "加密云存储"},
		{"Sync.com", "https://www.sync.com", "加密同步"},
		{"Tresorit", "https://tresorit.com", "端到端加密存储"},
		{"坚果云", "https://www.jianguoyun.com", "中国云同步"},
		{"百度网盘", "https://pan.baidu.com", "百度云存储"},
		{"阿里云盘", "https://www.aliyundrive.com", "阿里云盘"},
		{"天翼云盘", "https://cloud.189.cn", "电信云盘"},
		{"夸克网盘", "https://pan.quark.cn", "夸克网盘"},
		{"115网盘", "https://115.com", "115云存储"},
		{"Grammarly", "https://www.grammarly.com", "英语写作助手"},
		{"DeepL", "https://www.deepl.com", "AI翻译"},
	}
}

func designEx() []S {
	return []S{
		{"Sketch", "https://www.sketch.com", "macOS设计工具"},
		{"Adobe XD", "https://www.adobe.com/products/xd.html", "UI/UX设计"},
		{"InVision", "https://www.invisionapp.com", "设计协作"},
		{"Zeplin", "https://zeplin.io", "设计交付"},
		{"Abstract", "https://www.abstract.com", "设计版本控制"},
		{"Marvel", "https://marvelapp.com", "原型设计工具"},
		{"ProtoPie", "https://www.protopie.io", "交互原型"},
		{"Principle", "https://principleformac.com", "macOS动画原型"},
		{"Origami Studio", "https://origami.design", "Meta原型工具"},
		{"Framer", "https://www.framer.com", "交互设计建站"},
		{"Axure", "https://www.axure.com", "原型线框图"},
		{"Balsamiq", "https://balsamiq.com", "线框图工具"},
		{"Mockplus", "https://www.mockplus.com", "原型设计"},
		{"Moqups", "https://moqups.com", "在线线框图"},
		{"Lunacy", "https://icons8.com/lunacy", "免费设计软件"},
		{"Penpot", "https://penpot.app", "开源设计工具"},
		{"Photoshop", "https://www.adobe.com/products/photoshop.html", "Adobe图像编辑"},
		{"Illustrator", "https://www.adobe.com/products/illustrator.html", "矢量设计"},
		{"After Effects", "https://www.adobe.com/products/aftereffects.html", "动效设计"},
		{"InDesign", "https://www.adobe.com/products/indesign.html", "排版设计"},
		{"Affinity Designer", "https://affinity.serif.com/designer", "矢量设计"},
		{"Affinity Photo", "https://affinity.serif.com/photo", "图像编辑"},
		{"Affinity Publisher", "https://affinity.serif.com/publisher", "排版设计"},
		{"Procreate", "https://procreate.com", "iPad绘画"},
		{"Clip Studio Paint", "https://www.clipstudio.net", "漫画绘画"},
		{"Krita", "https://krita.org", "开源绘画"},
		{"Pixelmator Pro", "https://www.pixelmator.com/pro", "macOS图像编辑"},
		{"GIMP", "https://www.gimp.org", "开源图像编辑"},
		{"Inkscape", "https://inkscape.org", "开源矢量设计"},
		{"Vectornator", "https://www.vectornator.io", "矢量设计"},
		{"Colorhunt", "https://colorhunt.co", "配色方案"},
		{"Coolors", "https://coolors.co", "配色生成器"},
		{"Adobe Color", "https://color.adobe.com", "Adobe配色"},
		{"Paletton", "https://paletton.com", "配色工具"},
		{"Muzli Colors", "https://colors.muz.li", "AI配色"},
		{"Google Fonts", "https://fonts.google.com", "免费字体"},
		{"Adobe Fonts", "https://fonts.adobe.com", "Adobe字体库"},
		{"Font Squirrel", "https://www.fontsquirrel.com", "免费字体"},
		{"DaFont", "https://www.dafont.com", "免费字体下载"},
		{"Fontshare", "https://www.fontshare.com", "免费质量字体"},
		{"Type Scale", "https://typescale.com", "字体比例工具"},
		{"Fontjoy", "https://fontjoy.com", "AI字体配对"},
		{"Icons8", "https://icons8.com", "图标插画素材"},
		{"Flaticon", "https://www.flaticon.com", "矢量图标"},
		{"Heroicons", "https://heroicons.com", "Tailwind图标"},
		{"Lucide", "https://lucide.dev", "开源图标"},
		{"Phosphor Icons", "https://phosphoricons.com", "灵活图标"},
		{"Feather Icons", "https://feathericons.com", "简洁图标"},
		{"Material Icons", "https://fonts.google.com/icons", "Google图标"},
		{"Font Awesome", "https://fontawesome.com", "图标字体"},
		{"Simple Icons", "https://simpleicons.org", "品牌SVG图标"},
		{"SVG Repo", "https://www.svgrepo.com", "SVG图标库"},
		{"unDraw", "https://undraw.co", "开源插画"},
		{"Humaaans", "https://www.humaaans.com", "人物插画库"},
		{"Blush", "https://blush.design", "插画创建"},
		{"Lottiefiles", "https://lottiefiles.com", "Lottie动画"},
		{"Rive", "https://rive.app", "交互动画设计"},
		{"Jitter", "https://jitter.video", "动效设计"},
		{"Mobbin", "https://mobbin.com", "移动UI参考"},
		{"UI8", "https://ui8.net", "UI设计资源"},
	}
}
