package main

// Batch 4 extension data: Logistics, Telecom, MapNav, Weather, Forum, Wiki, CloudService

func logisticsEx() []S {
	return []S{
		{"FedEx", "https://www.fedex.com", "联邦快递"},
		{"UPS", "https://www.ups.com", "UPS快递"},
		{"DHL", "https://www.dhl.com", "DHL快递"},
		{"USPS", "https://www.usps.com", "美国邮政"},
		{"Royal Mail", "https://www.royalmail.com", "英国皇家邮政"},
		{"La Poste", "https://www.laposte.fr", "法国邮政"},
		{"Deutsche Post", "https://www.deutschepost.de", "德国邮政"},
		{"Japan Post", "https://www.post.japanpost.jp", "日本邮政"},
		{"Australia Post", "https://auspost.com.au", "澳大利亚邮政"},
		{"Canada Post", "https://www.canadapost-postescanada.ca", "加拿大邮政"},
		{"Maersk", "https://www.maersk.com", "马士基航运"},
		{"MSC", "https://www.msc.com", "地中海航运"},
		{"CMA CGM", "https://www.cma-cgm.com", "达飞海运"},
		{"COSCO", "https://www.cosco.com", "中远海运"},
		{"Evergreen", "https://www.evergreen-line.com", "长荣海运"},
		{"Flexport", "https://www.flexport.com", "数字货运代理"},
		{"Freightos", "https://www.freightos.com", "货运比价"},
		{"FreightPOP", "https://www.freightpop.com", "货运管理"},
		{"Shippo", "https://goshippo.com", "发货API"},
		{"EasyPost", "https://www.easypost.com", "物流API"},
		{"ShipStation", "https://www.shipstation.com", "发货管理"},
		{"ShipBob", "https://www.shipbob.com", "电商物流"},
		{"Deliverr", "https://deliverr.com", "快速配送"},
		{"ShipHero", "https://shiphero.com", "仓储管理"},
		{"Extensiv", "https://www.extensiv.com", "仓储软件"},
		{"SkuVault", "https://www.skuvault.com", "库存管理"},
		{"NetSuite WMS", "https://www.netsuite.com/portal/products/erp/warehouse-fulfillment.shtml", "仓储管理"},
		{"Manhattan Associates", "https://www.manh.com", "供应链软件"},
		{"Blue Yonder", "https://blueyonder.com", "供应链AI"},
		{"Kinaxis", "https://www.kinaxis.com", "供应链规划"},
		{"o9 Solutions", "https://o9solutions.com", "AI供应链"},
		{"E2open", "https://www.e2open.com", "供应链平台"},
		{"Coupa", "https://www.coupa.com", "采购管理"},
		{"SAP Supply Chain", "https://www.sap.com/products/scm.html", "SAP供应链"},
		{"Oracle SCM", "https://www.oracle.com/scm", "Oracle供应链"},
		{"Project44", "https://www.project44.com", "物流可视化"},
		{"FourKites", "https://www.fourkites.com", "供应链可视化"},
		{"Transplace", "https://www.transplace.com", "运输管理"},
		{"Uber Freight", "https://www.uberfreight.com", "Uber货运"},
		{"Convoy", "https://convoy.com", "数字货运"},
		{"Loadsmart", "https://loadsmart.com", "AI货运"},
		{"Samsara", "https://www.samsara.com", "车队管理"},
		{"KeepTruckin", "https://keeptruckin.com", "车队安全"},
		{"Geotab", "https://www.geotab.com", "远程信息处理"},
		{"Trimble Transportation", "https://transportation.trimble.com", "运输技术"},
		{"Descartes", "https://www.descartes.com", "物流技术"},
		{"顺丰速运", "https://www.sf-express.com", "中国快递"},
		{"中通快递", "https://www.zto.com", "中通"},
		{"圆通速递", "https://www.yto.net.cn", "圆通"},
		{"韵达快递", "https://www.yundaex.com", "韵达"},
		{"申通快递", "https://www.sto.cn", "申通"},
		{"百世快递", "https://www.800best.com", "百世"},
		{"极兔速递", "https://www.jtexpress.com", "极兔"},
		{"德邦快递", "https://www.deppon.com", "德邦"},
		{"京东物流", "https://www.jdl.com", "京东物流"},
		{"菜鸟网络", "https://www.cainiao.com", "菜鸟物流"},
		{"满帮集团", "https://www.ymm56.com", "货运匹配"},
		{"货拉拉", "https://www.huolala.cn", "同城货运"},
		{"快狗打车", "https://www.kuaigou.com", "同城配送"},
		{"达达快送", "https://www.imdada.cn", "即时配送"},
		{"闪送", "https://www.ishansong.com", "同城闪送"},
		{"跨越速运", "https://www.ky-express.com", "快运物流"},
		{"安能物流", "https://www.ane56.com", "零担快运"},
		{"壹米滴答", "https://www.yimidida.com", "快运网络"},
		{"17TRACK", "https://www.17track.net", "全球包裹追踪"},
		{"AfterShip", "https://www.aftership.com", "物流追踪"},
		{"TrackingMore", "https://www.trackingmore.com", "包裹追踪"},
		{"ParcelMonitor", "https://www.parcelmonitor.com", "包裹监控"},
		{"快递100", "https://www.kuaidi100.com", "中国快递查询"},
		{"快递鸟", "https://www.kdniao.com", "快递API"},
		{"Shopify Shipping", "https://www.shopify.com/shipping", "电商发货"},
		{"Pirate Ship", "https://www.pirateship.com", "折扣邮费"},
		{"Stamps.com", "https://www.stamps.com", "在线邮资"},
		{"Endicia", "https://www.endicia.com", "邮资解决方案"},
		{"PostGrid", "https://www.postgrid.com", "地址验证"},
		{"Lob", "https://www.lob.com", "邮件API"},
		{"Route", "https://route.com", "包裹保护"},
		{"Narvar", "https://corp.narvar.com", "售后体验"},
		{"ParcelLab", "https://parcellab.com", "物流体验"},
		{"Bringg", "https://www.bringg.com", "配送管理"},
		{"Onfleet", "https://onfleet.com", "最后一公里"},
		{"Routific", "https://routific.com", "路线优化"},
		{"OptimoRoute", "https://optimoroute.com", "路线规划"},
		{"Circuit", "https://getcircuit.com", "送货路线"},
		{"Lalamove", "https://www.lalamove.com", "即时配送"},
		{"GoGoVan", "https://www.gogovan.com", "货运平台"},
		{"Ninja Van", "https://www.ninjavan.co", "东南亚快递"},
		{"J&T Express", "https://www.jet.co.id", "东南亚快递"},
		{"Aramex", "https://www.aramex.com", "中东快递"},
		{"Yodel", "https://www.yodel.co.uk", "英国快递"},
		{"Hermes", "https://www.evri.com", "英国快递"},
		{"GLS", "https://gls-group.com", "欧洲包裹"},
		{"DPD", "https://www.dpd.com", "欧洲快递"},
		{"Chronopost", "https://www.chronopost.fr", "法国快递"},
		{"PostNord", "https://www.postnord.com", "北欧邮政"},
		{"Correos", "https://www.correos.es", "西班牙邮政"},
		{"Poste Italiane", "https://www.poste.it", "意大利邮政"},
		{"Swiss Post", "https://www.post.ch", "瑞士邮政"},
		{"YunExpress", "https://www.yunexpress.com", "云途物流"},
		{"CNE Express", "https://www.cne.com", "递四方"},
		{"4PX Express", "https://www.4px.com", "递四方快递"},
	}
}

func telecomEx() []S {
	return []S{
		{"AT&T", "https://www.att.com", "美国电信"},
		{"Verizon", "https://www.verizon.com", "美国电信"},
		{"T-Mobile", "https://www.t-mobile.com", "美国电信"},
		{"Comcast", "https://www.xfinity.com", "美国宽带"},
		{"Charter", "https://www.spectrum.com", "美国有线"},
		{"Vodafone", "https://www.vodafone.com", "沃达丰"},
		{"Deutsche Telekom", "https://www.telekom.com", "德国电信"},
		{"Orange", "https://www.orange.com", "法国电信"},
		{"Telefonica", "https://www.telefonica.com", "西班牙电信"},
		{"BT", "https://www.bt.com", "英国电信"},
		{"NTT", "https://www.ntt.com", "日本电信"},
		{"SK Telecom", "https://www.sktelecom.com", "韩国电信"},
		{"KT Corporation", "https://www.kt.com", "韩国KT"},
		{"Singtel", "https://www.singtel.com", "新加坡电信"},
		{"Telstra", "https://www.telstra.com.au", "澳洲电信"},
		{"Rogers", "https://www.rogers.com", "加拿大电信"},
		{"Bell Canada", "https://www.bell.ca", "加拿大Bell"},
		{"Reliance Jio", "https://www.jio.com", "印度Jio"},
		{"Airtel", "https://www.airtel.in", "印度Airtel"},
		{"Etisalat", "https://www.etisalat.ae", "阿联酋电信"},
		{"STC", "https://www.stc.com.sa", "沙特电信"},
		{"MTN", "https://www.mtn.com", "非洲电信"},
		{"America Movil", "https://www.americamovil.com", "拉美电信"},
		{"中国移动", "https://www.10086.cn", "中国移动"},
		{"中国联通", "https://www.chinaunicom.com.cn", "中国联通"},
		{"中国电信", "https://www.chinatelecom.com.cn", "中国电信"},
		{"中国广电", "https://www.cbn.cn", "中国广电"},
		{"中国铁塔", "https://www.china-tower.com", "铁塔公司"},
		{"华为", "https://www.huawei.com", "华为通信"},
		{"中兴", "https://www.zte.com.cn", "中兴通讯"},
		{"Ericsson", "https://www.ericsson.com", "爱立信"},
		{"Nokia", "https://www.nokia.com", "诺基亚"},
		{"Samsung Networks", "https://www.samsung.com/global/business/networks", "三星网络"},
		{"Qualcomm", "https://www.qualcomm.com", "高通"},
		{"MediaTek", "https://www.mediatek.com", "联发科"},
		{"Intel Networking", "https://www.intel.com/networking", "英特尔网络"},
		{"Cisco", "https://www.cisco.com", "思科"},
		{"Juniper Networks", "https://www.juniper.net", "瞻博网络"},
		{"Arista Networks", "https://www.arista.com", "Arista网络"},
		{"Palo Alto Networks", "https://www.paloaltonetworks.com", "网络安全"},
		{"Fortinet", "https://www.fortinet.com", "网络安全"},
		{"F5 Networks", "https://www.f5.com", "应用交付"},
		{"Ubiquiti", "https://www.ui.com", "网络设备"},
		{"TP-Link", "https://www.tp-link.com", "路由器"},
		{"Netgear", "https://www.netgear.com", "网络设备"},
		{"ASUS Networking", "https://www.asus.com/networking", "华硕网络"},
		{"Linksys", "https://www.linksys.com", "路由器"},
		{"Eero", "https://eero.com", "Mesh路由"},
		{"Google Nest WiFi", "https://store.google.com/category/google_wifi", "谷歌WiFi"},
		{"Starlink", "https://www.starlink.com", "卫星互联网"},
		{"OneWeb", "https://oneweb.net", "卫星通信"},
		{"Amazon Kuiper", "https://www.aboutamazon.com/what-we-do/devices-services/project-kuiper", "亚马逊卫星"},
		{"Iridium", "https://www.iridium.com", "卫星通信"},
		{"Inmarsat", "https://www.inmarsat.com", "海事卫星"},
		{"Twilio", "https://www.twilio.com", "通信API"},
		{"Vonage", "https://www.vonage.com", "通信平台"},
		{"Bandwidth", "https://www.bandwidth.com", "通信API"},
		{"Plivo", "https://www.plivo.com", "云通信"},
		{"MessageBird", "https://messagebird.com", "全渠道通信"},
		{"Sinch", "https://www.sinch.com", "云通信"},
		{"Infobip", "https://www.infobip.com", "全渠道平台"},
		{"Telnyx", "https://telnyx.com", "通信API"},
		{"RingCentral", "https://www.ringcentral.com", "云通信"},
		{"Zoom Phone", "https://zoom.us/phone", "云电话"},
		{"Microsoft Teams", "https://www.microsoft.com/en-us/microsoft-teams", "协作通信"},
		{"Google Voice", "https://voice.google.com", "谷歌语音"},
		{"Grasshopper", "https://grasshopper.com", "虚拟电话"},
		{"OpenPhone", "https://www.openphone.com", "商务电话"},
		{"Dialpad", "https://www.dialpad.com", "AI通信"},
		{"8x8", "https://www.8x8.com", "云通信"},
		{"Nextiva", "https://www.nextiva.com", "商务通信"},
		{"Ooma", "https://www.ooma.com", "商务电话"},
		{"Speedtest", "https://www.speedtest.net", "网速测试"},
		{"Fast.com", "https://fast.com", "Netflix网速"},
		{"Broadband Map", "https://broadbandmap.fcc.gov", "宽带地图"},
		{"OpenSignal", "https://www.opensignal.com", "网络信号"},
		{"RootMetrics", "https://rootmetrics.com", "网络测评"},
		{"GSMA", "https://www.gsma.com", "全球移动通信"},
		{"3GPP", "https://www.3gpp.org", "通信标准"},
		{"ETSI", "https://www.etsi.org", "欧洲通信标准"},
		{"ITU", "https://www.itu.int", "国际电信联盟"},
		{"IETF", "https://www.ietf.org", "互联网工程"},
		{"Wi-Fi Alliance", "https://www.wi-fi.org", "WiFi联盟"},
		{"Bluetooth SIG", "https://www.bluetooth.com", "蓝牙标准"},
		{"LoRa Alliance", "https://lora-alliance.org", "LoRa物联网"},
		{"5G Americas", "https://www.5gamericas.org", "5G美洲"},
		{"NGMN", "https://www.ngmn.org", "下一代移动网络"},
		{"O-RAN Alliance", "https://www.o-ran.org", "开放无线接入"},
		{"Light Reading", "https://www.lightreading.com", "电信新闻"},
		{"Fierce Telecom", "https://www.fiercetelecom.com", "电信资讯"},
		{"Telecoms.com", "https://telecoms.com", "电信行业"},
		{"Total Telecom", "https://www.totaltele.com", "全球电信"},
		{"RCR Wireless", "https://www.rcrwireless.com", "无线新闻"},
		{"SDxCentral", "https://www.sdxcentral.com", "网络虚拟化"},
		{"Packet Pushers", "https://packetpushers.net", "网络播客"},
		{"Network World", "https://www.networkworld.com", "网络世界"},
		{"TeleGeography", "https://www.telegeography.com", "电信地理"},
		{"Submarine Cable Map", "https://www.submarinecablemap.com", "海底电缆"},
		{"PeeringDB", "https://www.peeringdb.com", "互联对等数据"},
		{"RIPE NCC", "https://www.ripe.net", "欧洲IP资源"},
		{"ARIN", "https://www.arin.net", "美洲IP资源"},
		{"APNIC", "https://www.apnic.net", "亚太IP资源"},
	}
}

func mapNavEx() []S {
	return []S{
		{"Google Maps", "https://maps.google.com", "谷歌地图"},
		{"Apple Maps", "https://maps.apple.com", "苹果地图"},
		{"Bing Maps", "https://www.bing.com/maps", "必应地图"},
		{"Waze", "https://www.waze.com", "众包导航"},
		{"HERE Maps", "https://www.here.com", "HERE地图"},
		{"TomTom", "https://www.tomtom.com", "TomTom导航"},
		{"Garmin Maps", "https://www.garmin.com/maps", "佳明地图"},
		{"Mapbox", "https://www.mapbox.com", "地图开发平台"},
		{"OpenStreetMap", "https://www.openstreetmap.org", "开源地图"},
		{"Leaflet", "https://leafletjs.com", "地图JS库"},
		{"MapLibre", "https://maplibre.org", "开源地图库"},
		{"Deck.gl", "https://deck.gl", "大规模可视化"},
		{"Kepler.gl", "https://kepler.gl", "地理数据可视化"},
		{"CARTO", "https://carto.com", "位置智能"},
		{"Mapillary", "https://www.mapillary.com", "街景众包"},
		{"Google Earth", "https://earth.google.com", "谷歌地球"},
		{"NASA Worldview", "https://worldview.earthdata.nasa.gov", "卫星图"},
		{"Sentinel Hub", "https://www.sentinel-hub.com", "卫星数据"},
		{"Planet Labs", "https://www.planet.com", "地球影像"},
		{"Maxar", "https://www.maxar.com", "卫星图像"},
		{"ArcGIS", "https://www.arcgis.com", "GIS平台"},
		{"QGIS", "https://qgis.org", "开源GIS"},
		{"GIS Cloud", "https://www.giscloud.com", "云GIS"},
		{"Felt", "https://felt.com", "协作地图"},
		{"Scribble Maps", "https://www.scribblemaps.com", "自定义地图"},
		{"BatchGeo", "https://batchgeo.com", "批量地理编码"},
		{"Geocodio", "https://www.geocod.io", "地理编码API"},
		{"LocationIQ", "https://locationiq.com", "位置API"},
		{"Nominatim", "https://nominatim.org", "开源地理编码"},
		{"Photon", "https://photon.komoot.io", "开源地理搜索"},
		{"百度地图", "https://map.baidu.com", "百度地图"},
		{"高德地图", "https://www.amap.com", "高德地图"},
		{"腾讯地图", "https://map.qq.com", "腾讯地图"},
		{"搜狗地图", "https://map.sogou.com", "搜狗地图"},
		{"北斗导航", "https://www.beidou.gov.cn", "北斗卫星导航"},
		{"图吧导航", "https://www.mapbar.com", "图吧地图"},
		{"凯立德", "https://www.careland.com.cn", "凯立德导航"},
		{"Naver Map", "https://map.naver.com", "韩国Naver地图"},
		{"Kakao Map", "https://map.kakao.com", "韩国Kakao地图"},
		{"Yahoo地図", "https://map.yahoo.co.jp", "日本雅虎地图"},
		{"Yandex Maps", "https://yandex.com/maps", "俄罗斯地图"},
		{"2GIS", "https://2gis.com", "俄罗斯城市地图"},
		{"Citymapper", "https://citymapper.com", "城市出行"},
		{"Moovit", "https://moovitapp.com", "公交导航"},
		{"Transit App", "https://transitapp.com", "公交应用"},
		{"Rome2Rio", "https://www.rome2rio.com", "多模式导航"},
		{"AllTrails", "https://www.alltrails.com", "徒步路线"},
		{"Komoot", "https://www.komoot.com", "户外路线"},
		{"Strava Routes", "https://www.strava.com/routes", "运动路线"},
		{"Organic Maps", "https://organicmaps.app", "离线地图"},
		{"OsmAnd", "https://osmand.net", "离线导航"},
		{"Maps.me", "https://maps.me", "离线地图"},
		{"Sygic", "https://www.sygic.com", "GPS导航"},
		{"CoPilot", "https://copilotgps.com", "导航应用"},
		{"Navmii", "https://www.navmii.com", "免费导航"},
		{"What3words", "https://what3words.com", "三词地址"},
		{"Plus Codes", "https://maps.google.com/pluscodes", "加号代码"},
		{"Geohash", "https://geohash.org", "地理哈希"},
		{"GeoJSON.io", "https://geojson.io", "GeoJSON编辑"},
		{"Overpass Turbo", "https://overpass-turbo.eu", "OSM查询"},
		{"MapRoulette", "https://maproulette.org", "OSM贡献"},
		{"TeachOSM", "https://teachosm.org", "OSM教学"},
		{"HOT", "https://www.hotosm.org", "人道主义OSM"},
		{"Mapbox Studio", "https://studio.mapbox.com", "地图设计"},
		{"Stamen Maps", "https://maps.stamen.com", "地图设计"},
		{"Snazzy Maps", "https://snazzymaps.com", "谷歌地图样式"},
		{"Natural Earth", "https://www.naturalearthdata.com", "自然地图数据"},
		{"OpenTopoMap", "https://opentopomap.org", "开源地形图"},
		{"OpenSeaMap", "https://www.openseamap.org", "开源海图"},
		{"OpenRailwayMap", "https://www.openrailwaymap.org", "开源铁路图"},
		{"OpenCycleMap", "https://www.opencyclemap.org", "骑行地图"},
		{"Marine Traffic", "https://www.marinetraffic.com", "船舶追踪"},
		{"VesselFinder", "https://www.vesselfinder.com", "船舶定位"},
		{"FlightRadar24", "https://www.flightradar24.com", "航班追踪"},
		{"FlightAware", "https://flightaware.com", "航班追踪"},
		{"ADS-B Exchange", "https://www.adsbexchange.com", "航空数据"},
		{"PlaneFinder", "https://planefinder.net", "飞机追踪"},
		{"ISS Tracker", "https://www.esa.int/Science_Exploration/Human_and_Robotic_Exploration/International_Space_Station/Where_is_the_International_Space_Station", "空间站追踪"},
		{"N2YO", "https://www.n2yo.com", "卫星追踪"},
		{"Windy Maps", "https://www.windy.com", "风力地图"},
		{"Earth Nullschool", "https://earth.nullschool.net", "全球风力可视化"},
		{"Light Pollution Map", "https://www.lightpollutionmap.info", "光污染地图"},
		{"Noise Map", "https://noise.euenv.info", "噪音地图"},
		{"TimeZoneDB", "https://timezonedb.com", "时区数据"},
		{"WorldTimeServer", "https://www.worldtimeserver.com", "世界时间"},
		{"SunCalc", "https://www.suncalc.org", "日照计算"},
		{"Shade Map", "https://shademap.app", "阴影地图"},
		{"Mapzen", "https://www.mapzen.com", "地图服务"},
		{"Pelias", "https://github.com/pelias/pelias", "开源地理编码"},
		{"Valhalla", "https://github.com/valhalla/valhalla", "开源路线引擎"},
		{"OSRM", "https://project-osrm.org", "开源路线"},
		{"GraphHopper", "https://www.graphhopper.com", "路线引擎"},
		{"OpenRouteService", "https://openrouteservice.org", "开源路线服务"},
		{"Routino", "https://www.routino.org", "路线规划"},
		{"Overture Maps", "https://overturemaps.org", "开放地图数据"},
		{"Protomaps", "https://protomaps.com", "轻量地图"},
		{"Tangram", "https://github.com/tangrams/tangram", "WebGL地图"},
		{"CesiumJS", "https://cesium.com/cesiumjs", "3D地球"},
		{"Globe.GL", "https://globe.gl", "3D地球可视化"},
		{"Maptiler", "https://www.maptiler.com", "地图服务"},
	}
}

func weatherEx() []S {
	return []S{
		{"Weather.com", "https://weather.com", "天气频道"},
		{"AccuWeather", "https://www.accuweather.com", "精准天气"},
		{"Weather Underground", "https://www.wunderground.com", "天气地下"},
		{"Dark Sky", "https://darksky.net", "超局部天气"},
		{"OpenWeather", "https://openweathermap.org", "天气API"},
		{"WeatherAPI", "https://www.weatherapi.com", "天气数据API"},
		{"Tomorrow.io", "https://www.tomorrow.io", "天气智能"},
		{"Climacell", "https://www.tomorrow.io", "微气象"},
		{"Weatherbit", "https://www.weatherbit.io", "天气API"},
		{"Visual Crossing", "https://www.visualcrossing.com", "天气数据"},
		{"Meteoblue", "https://www.meteoblue.com", "全球天气"},
		{"Meteostat", "https://meteostat.net", "天气统计"},
		{"Windy", "https://www.windy.com", "风力天气"},
		{"Ventusky", "https://www.ventusky.com", "天气地图"},
		{"Zoom Earth", "https://zoom.earth", "卫星天气"},
		{"Earth Nullschool", "https://earth.nullschool.net", "地球风力"},
		{"NOAA", "https://www.noaa.gov", "美国海洋大气局"},
		{"National Weather Service", "https://www.weather.gov", "美国气象局"},
		{"Met Office", "https://www.metoffice.gov.uk", "英国气象局"},
		{"Météo-France", "https://www.meteofrance.com", "法国气象"},
		{"DWD", "https://www.dwd.de", "德国气象"},
		{"JMA", "https://www.jma.go.jp", "日本气象厅"},
		{"BOM", "https://www.bom.gov.au", "澳洲气象"},
		{"Environment Canada", "https://weather.gc.ca", "加拿大天气"},
		{"KMA", "https://www.kma.go.kr", "韩国气象"},
		{"IMD", "https://mausam.imd.gov.in", "印度气象"},
		{"中国气象网", "https://www.weather.com.cn", "中国天气"},
		{"中国天气", "https://www.weather.com.cn", "中央气象台"},
		{"墨迹天气", "https://www.moji.com", "墨迹天气"},
		{"彩云天气", "https://www.caiyunapp.com", "彩云天气"},
		{"和风天气", "https://www.qweather.com", "和风天气API"},
		{"Severe Weather Europe", "https://www.severe-weather.eu", "恶劣天气"},
		{"Tropical Tidbits", "https://www.tropicaltidbits.com", "热带天气"},
		{"Hurricane Tracker", "https://www.nhc.noaa.gov", "飓风追踪"},
		{"Earthquake USGS", "https://earthquake.usgs.gov", "地震监测"},
		{"Volcano Discovery", "https://www.volcanodiscovery.com", "火山发现"},
		{"Tornado HQ", "https://www.tornadohq.com", "龙卷风追踪"},
		{"Lightning Maps", "https://www.lightningmaps.org", "闪电地图"},
		{"Blitzortung", "https://www.blitzortung.org", "雷电追踪"},
		{"RainViewer", "https://www.rainviewer.com", "雨量雷达"},
		{"MyRadar", "https://www.acurite.com/myradar", "天气雷达"},
		{"Radarscope", "https://www.radarscope.app", "专业雷达"},
		{"AirNow", "https://www.airnow.gov", "美国空气质量"},
		{"IQAir", "https://www.iqair.com", "全球空气质量"},
		{"BreezoMeter", "https://www.breezometer.com", "空气质量"},
		{"AQICN", "https://aqicn.org", "全球空气指数"},
		{"PurpleAir", "https://www.purpleair.com", "空气质量传感器"},
		{"Pollen.com", "https://www.pollen.com", "花粉预报"},
		{"UV Index", "https://www.epa.gov/sunsafety/uv-index-1", "紫外线指数"},
		{"Surfline", "https://www.surfline.com", "冲浪天气"},
		{"Magicseaweed", "https://magicseaweed.com", "海浪预报"},
		{"Windguru", "https://www.windguru.cz", "风力预报"},
		{"iKitesurf", "https://www.ikitesurf.com", "风筝冲浪天气"},
		{"Snowforecast", "https://www.snow-forecast.com", "滑雪天气"},
		{"OnTheSnow", "https://www.onthesnow.com", "雪况报告"},
		{"Mountain Forecast", "https://www.mountain-forecast.com", "山区天气"},
		{"Yr.no", "https://www.yr.no", "挪威天气"},
		{"Foreca", "https://www.foreca.com", "芬兰天气"},
		{"SMHI", "https://www.smhi.se", "瑞典气象"},
		{"Ilmatieteen Laitos", "https://www.ilmatieteenlaitos.fi", "芬兰气象"},
		{"TimeandDate Weather", "https://www.timeanddate.com/weather", "世界天气"},
		{"Wetter.com", "https://www.wetter.com", "德国天气"},
		{"Eltiempo", "https://www.eltiempo.es", "西班牙天气"},
		{"Il Meteo", "https://www.ilmeteo.it", "意大利天气"},
		{"Lameteo", "https://www.lameteo.org", "法国天气"},
		{"Clearoutside", "https://clearoutside.com", "天文天气"},
		{"Astrospheric", "https://www.astrospheric.com", "天文观测天气"},
		{"SatelliteWX", "https://www.goes.noaa.gov", "卫星天气"},
		{"EarthCam", "https://www.earthcam.com", "全球实时摄像"},
		{"WorldCam", "https://worldcam.eu", "世界摄像头"},
		{"Skyline Webcams", "https://www.skylinewebcams.com", "天际线摄像"},
		{"Airport Webcams", "https://airportwebcams.net", "机场摄像"},
		{"Weatherspark", "https://weatherspark.com", "气候对比"},
		{"Climate Data", "https://en.climate-data.org", "气候数据"},
		{"WorldClim", "https://www.worldclim.org", "全球气候"},
		{"Berkeley Earth", "https://berkeleyearth.org", "气温数据"},
		{"ECMWF", "https://www.ecmwf.int", "欧洲气象中心"},
		{"GFS Model", "https://www.tropicaltidbits.com/analysis/models/?model=gfs", "GFS模型"},
		{"EURO Model", "https://www.tropicaltidbits.com/analysis/models/?model=ecmwf", "欧洲模型"},
		{"Pivotal Weather", "https://www.pivotalweather.com", "天气模型"},
		{"WeatherModels", "https://weathermodels.com", "天气模型"},
		{"Ambient Weather", "https://ambientweather.com", "家庭气象站"},
		{"Davis Instruments", "https://www.davisinstruments.com", "气象仪器"},
		{"Netatmo", "https://www.netatmo.com", "智能气象站"},
		{"Tempest Weather", "https://weatherflow.com/tempest-weather-system", "个人气象站"},
		{"WeatherXM", "https://weatherxm.com", "去中心化气象"},
		{"Climate Reanalyzer", "https://climatereanalyzer.org", "气候分析"},
		{"Carbon Tracker", "https://carbontracker.org", "碳排放追踪"},
		{"Global Forest Watch", "https://www.globalforestwatch.org", "森林监测"},
		{"Drought Monitor", "https://droughtmonitor.unl.edu", "干旱监测"},
		{"Fire Information", "https://firms.modaps.eosdis.nasa.gov", "火灾监测"},
		{"Flood Map", "https://www.floodmap.net", "洪水地图"},
		{"USGS Water", "https://waterdata.usgs.gov", "水文数据"},
		{"Sea Level Rise", "https://sealevel.nasa.gov", "海平面上升"},
		{"Tide Forecast", "https://www.tide-forecast.com", "潮汐预报"},
		{"SpaceWeather", "https://spaceweather.com", "太空天气"},
		{"SolarHam", "https://www.solarham.net", "太阳活动"},
		{"Aurora Forecast", "https://www.swpc.noaa.gov/products/aurora-30-minute-forecast", "极光预报"},
		{"Spaceweather Live", "https://www.spaceweatherlive.com", "太空天气实时"},
	}
}

func forumEx() []S {
	return []S{
		{"Reddit", "https://www.reddit.com", "Reddit社区"},
		{"Hacker News", "https://news.ycombinator.com", "黑客新闻"},
		{"Stack Exchange", "https://stackexchange.com", "问答网络"},
		{"Quora", "https://www.quora.com", "知识问答"},
		{"4chan", "https://www.4chan.org", "匿名论坛"},
		{"Something Awful", "https://www.somethingawful.com", "SA论坛"},
		{"Discourse", "https://www.discourse.org", "开源论坛"},
		{"Flarum", "https://flarum.org", "现代论坛"},
		{"NodeBB", "https://nodebb.org", "Node.js论坛"},
		{"Vanilla Forums", "https://vanillaforums.com", "社区论坛"},
		{"phpBB", "https://www.phpbb.com", "PHP论坛"},
		{"vBulletin", "https://www.vbulletin.com", "论坛软件"},
		{"XenForo", "https://xenforo.com", "论坛软件"},
		{"MyBB", "https://mybb.com", "免费论坛"},
		{"Invision Community", "https://invisioncommunity.com", "社区平台"},
		{"Circle", "https://circle.so", "社区平台"},
		{"Tribe", "https://tribe.so", "社区平台"},
		{"Mighty Networks", "https://www.mightynetworks.com", "社区网络"},
		{"Discord", "https://discord.com", "实时社区"},
		{"Slack Community", "https://slack.com", "团队社区"},
		{"Guilded", "https://www.guilded.gg", "游戏社区"},
		{"Matrix", "https://matrix.org", "开源通信"},
		{"Element", "https://element.io", "Matrix客户端"},
		{"Mastodon", "https://joinmastodon.org", "去中心化社交"},
		{"Lemmy", "https://join-lemmy.org", "去中心化Reddit"},
		{"Kbin", "https://kbin.pub", "联邦宇宙聚合"},
		{"Tildes", "https://tildes.net", "优质讨论"},
		{"Lobsters", "https://lobste.rs", "技术社区"},
		{"MetaFilter", "https://www.metafilter.com", "社区博客"},
		{"Slashdot", "https://slashdot.org", "科技新闻"},
		{"Voat", "https://voat.xyz", "言论自由社区"},
		{"知乎", "https://www.zhihu.com", "中国知识问答"},
		{"贴吧", "https://tieba.baidu.com", "百度贴吧"},
		{"豆瓣小组", "https://www.douban.com/group", "豆瓣讨论组"},
		{"虎扑社区", "https://bbs.hupu.com", "虎扑论坛"},
		{"天涯社区", "https://www.tianya.cn", "天涯论坛"},
		{"V2EX", "https://www.v2ex.com", "创意工作者"},
		{"水木社区", "https://www.newsmth.net", "清华BBS"},
		{"NGA", "https://bbs.nga.cn", "游戏社区"},
		{"Stage1st", "https://bbs.saraba1st.com", "S1论坛"},
		{"什么值得买", "https://www.smzdm.com", "消费社区"},
		{"吾爱破解", "https://www.52pojie.cn", "技术论坛"},
		{"远景论坛", "https://bbs.pcbeta.com", "系统论坛"},
		{"看雪安全论坛", "https://bbs.pediy.com", "安全论坛"},
		{"FreeBuf社区", "https://www.freebuf.com", "安全社区"},
		{"CSDN论坛", "https://bbs.csdn.net", "技术论坛"},
		{"博客园", "https://www.cnblogs.com", "技术博客社区"},
		{"开源中国", "https://www.oschina.net", "开源社区"},
		{"SegmentFault", "https://segmentfault.com", "问答社区"},
		{"Ruby China", "https://ruby-china.org", "Ruby社区"},
		{"Node.js中文", "https://cnodejs.org", "Node社区"},
		{"掘金沸点", "https://juejin.cn/pins", "开发者广场"},
		{"Product Hunt Discussions", "https://www.producthunt.com/discussions", "产品讨论"},
		{"Dev Community", "https://dev.to", "开发者社区"},
		{"Hashnode Discussions", "https://hashnode.com/discussions", "技术讨论"},
		{"StackOverflow", "https://stackoverflow.com", "编程问答"},
		{"ServerFault", "https://serverfault.com", "运维问答"},
		{"SuperUser", "https://superuser.com", "超级用户"},
		{"Ask Ubuntu", "https://askubuntu.com", "Ubuntu问答"},
		{"Unix StackExchange", "https://unix.stackexchange.com", "Unix问答"},
		{"Math StackExchange", "https://math.stackexchange.com", "数学问答"},
		{"Physics StackExchange", "https://physics.stackexchange.com", "物理问答"},
		{"GameDev StackExchange", "https://gamedev.stackexchange.com", "游戏开发问答"},
		{"GIS StackExchange", "https://gis.stackexchange.com", "GIS问答"},
		{"CrossValidated", "https://stats.stackexchange.com", "统计问答"},
		{"Data Science StackExchange", "https://datascience.stackexchange.com", "数据科学问答"},
		{"Arduino Forum", "https://forum.arduino.cc", "Arduino社区"},
		{"Raspberry Pi Forum", "https://forums.raspberrypi.com", "树莓派社区"},
		{"XDA Developers", "https://www.xda-developers.com", "Android开发"},
		{"MacRumors Forum", "https://forums.macrumors.com", "苹果论坛"},
		{"Windows Central", "https://www.windowscentral.com/forums", "Windows论坛"},
		{"Arch Linux Forum", "https://bbs.archlinux.org", "Arch论坛"},
		{"Ubuntu Forums", "https://ubuntuforums.org", "Ubuntu论坛"},
		{"LinuxQuestions", "https://www.linuxquestions.org", "Linux问题"},
		{"Gentoo Forums", "https://forums.gentoo.org", "Gentoo论坛"},
		{"FreeBSD Forum", "https://forums.freebsd.org", "FreeBSD论坛"},
		{"Tom's Hardware Forum", "https://forums.tomshardware.com", "硬件论坛"},
		{"AnandTech Forum", "https://forums.anandtech.com", "科技论坛"},
		{"Overclock.net", "https://www.overclock.net", "超频社区"},
		{"Head-Fi", "https://www.head-fi.org", "耳机论坛"},
		{"AVS Forum", "https://www.avsforum.com", "影音论坛"},
		{"Photography Forum", "https://www.photographyforum.com", "摄影论坛"},
		{"DPreview Forum", "https://www.dpreview.com/forums", "相机论坛"},
		{"NeoGAF", "https://www.neogaf.com", "游戏论坛"},
		{"ResetEra", "https://www.resetera.com", "游戏社区"},
		{"IGN Boards", "https://www.ignboards.com", "IGN论坛"},
		{"GameFAQs", "https://gamefaqs.gamespot.com", "游戏问答"},
		{"RPGNet", "https://www.rpg.net", "RPG社区"},
		{"BoardGameGeek", "https://boardgamegeek.com", "桌游社区"},
		{"Bodybuilding Forum", "https://forum.bodybuilding.com", "健身论坛"},
		{"MyFitnessPal Forum", "https://community.myfitnesspal.com", "健身社区"},
		{"Mumsnet", "https://www.mumsnet.com", "英国妈妈论坛"},
		{"Baby Bumps", "https://www.reddit.com/r/BabyBumps", "孕妈社区"},
		{"City-Data", "https://www.city-data.com/forum", "城市数据论坛"},
		{"Expatica Forum", "https://www.expatica.com", "海外生活"},
		{"InterNations", "https://www.internations.org", "海外社区"},
		{"Reddit AMA", "https://www.reddit.com/r/IAmA", "名人问答"},
		{"小众软件论坛", "https://meta.appinn.net", "小众软件"},
		{"少数派社区", "https://sspai.com/community", "数字生活"},
	}
}

func wikiEx() []S {
	return []S{
		{"Wikipedia", "https://www.wikipedia.org", "维基百科"},
		{"Wiktionary", "https://www.wiktionary.org", "维基词典"},
		{"Wikimedia Commons", "https://commons.wikimedia.org", "维基媒体"},
		{"Wikidata", "https://www.wikidata.org", "维基数据"},
		{"Wikisource", "https://wikisource.org", "维基文库"},
		{"Wikiquote", "https://www.wikiquote.org", "维基语录"},
		{"Wikibooks", "https://www.wikibooks.org", "维基教科书"},
		{"Wikiversity", "https://www.wikiversity.org", "维基学院"},
		{"Wikinews", "https://www.wikinews.org", "维基新闻"},
		{"Wikispecies", "https://species.wikimedia.org", "维基物种"},
		{"Wikivoyage", "https://www.wikivoyage.org", "维基导游"},
		{"百度百科", "https://baike.baidu.com", "百度百科"},
		{"搜狗百科", "https://baike.sogou.com", "搜狗百科"},
		{"互动百科", "https://www.baike.com", "互动百科"},
		{"头条百科", "https://www.baike.com", "头条百科"},
		{"MBA智库百科", "https://wiki.mbalib.com", "商业百科"},
		{"Encyclopaedia Britannica", "https://www.britannica.com", "大英百科全书"},
		{"World Book", "https://www.worldbook.com", "世界百科全书"},
		{"Infoplease", "https://www.infoplease.com", "信息百科"},
		{"Encyclopedia.com", "https://www.encyclopedia.com", "百科全书"},
		{"Stanford Encyclopedia", "https://plato.stanford.edu", "斯坦福哲学百科"},
		{"Internet Encyclopedia", "https://iep.utm.edu", "互联网哲学百科"},
		{"Citizendium", "https://citizendium.org", "公民百科"},
		{"Scholarpedia", "https://www.scholarpedia.org", "学术百科"},
		{"Wolfram Alpha", "https://www.wolframalpha.com", "计算知识引擎"},
		{"Fandom", "https://www.fandom.com", "粉丝百科"},
		{"TVTropes", "https://tvtropes.org", "影视套路百科"},
		{"IMDb", "https://www.imdb.com", "电影数据库"},
		{"TMDb", "https://www.themoviedb.org", "电影数据库"},
		{"MusicBrainz", "https://musicbrainz.org", "音乐数据库"},
		{"Discogs", "https://www.discogs.com", "音乐唱片百科"},
		{"AllMusic", "https://www.allmusic.com", "音乐数据"},
		{"Genius", "https://genius.com", "歌词百科"},
		{"Songkick", "https://www.songkick.com", "演出数据"},
		{"Setlist.fm", "https://www.setlist.fm", "演出曲目"},
		{"IGDB", "https://www.igdb.com", "游戏数据库"},
		{"Giant Bomb", "https://www.giantbomb.com", "游戏百科"},
		{"MobyGames", "https://www.mobygames.com", "游戏档案"},
		{"How Long to Beat", "https://howlongtobeat.com", "游戏时长"},
		{"RAWG", "https://rawg.io", "游戏数据库"},
		{"PCGamingWiki", "https://www.pcgamingwiki.com", "PC游戏百科"},
		{"StrategyWiki", "https://strategywiki.org", "游戏攻略"},
		{"Bulbapedia", "https://bulbapedia.bulbagarden.net", "宝可梦百科"},
		{"Mario Wiki", "https://www.mariowiki.com", "马里奥百科"},
		{"Zelda Wiki", "https://zelda.fandom.com", "塞尔达百科"},
		{"Wookieepedia", "https://starwars.fandom.com", "星球大战百科"},
		{"Memory Alpha", "https://memory-alpha.fandom.com", "星际迷航百科"},
		{"Tolkien Gateway", "https://tolkiengateway.net", "托尔金百科"},
		{"Marvel Wiki", "https://marvel.fandom.com", "漫威百科"},
		{"DC Wiki", "https://dc.fandom.com", "DC百科"},
		{"Harry Potter Wiki", "https://harrypotter.fandom.com", "哈利波特百科"},
		{"Narutopedia", "https://naruto.fandom.com", "火影百科"},
		{"One Piece Wiki", "https://onepiece.fandom.com", "海贼王百科"},
		{"Dragon Ball Wiki", "https://dragonball.fandom.com", "龙珠百科"},
		{"Minecraft Wiki", "https://minecraft.wiki", "我的世界百科"},
		{"Terraria Wiki", "https://terraria.wiki.gg", "泰拉瑞亚百科"},
		{"Stardew Valley Wiki", "https://stardewvalleywiki.com", "星露谷百科"},
		{"Factorio Wiki", "https://wiki.factorio.com", "异星工厂百科"},
		{"Dwarf Fortress Wiki", "https://dwarffortresswiki.org", "矮人要塞百科"},
		{"Arch Wiki", "https://wiki.archlinux.org", "Arch百科"},
		{"Gentoo Wiki", "https://wiki.gentoo.org", "Gentoo百科"},
		{"FreeBSD Handbook", "https://docs.freebsd.org/en/books/handbook", "FreeBSD手册"},
		{"Debian Wiki", "https://wiki.debian.org", "Debian百科"},
		{"Ubuntu Wiki", "https://wiki.ubuntu.com", "Ubuntu百科"},
		{"Fedora Docs", "https://docs.fedoraproject.org", "Fedora文档"},
		{"openSUSE Wiki", "https://en.opensuse.org", "openSUSE百科"},
		{"NixOS Wiki", "https://nixos.wiki", "NixOS百科"},
		{"Docker Docs", "https://docs.docker.com", "Docker文档"},
		{"Kubernetes Docs", "https://kubernetes.io/docs", "K8s文档"},
		{"Go Wiki", "https://go.dev/wiki", "Go语言百科"},
		{"Python Wiki", "https://wiki.python.org", "Python百科"},
		{"Rust Wiki", "https://doc.rust-lang.org", "Rust文档"},
		{"MDN Web Docs", "https://developer.mozilla.org", "Web开发文档"},
		{"DevDocs", "https://devdocs.io", "API文档聚合"},
		{"Dash", "https://kapeli.com/dash", "离线文档"},
		{"Zeal", "https://zealdocs.org", "离线文档浏览"},
		{"Confluence", "https://www.atlassian.com/software/confluence", "企业知识库"},
		{"Notion Wiki", "https://www.notion.so", "Notion知识库"},
		{"BookStack", "https://www.bookstackapp.com", "开源知识库"},
		{"Wiki.js", "https://wiki.js.org", "现代Wiki"},
		{"MediaWiki", "https://www.mediawiki.org", "Wiki引擎"},
		{"DokuWiki", "https://www.dokuwiki.org", "轻量Wiki"},
		{"TiddlyWiki", "https://tiddlywiki.com", "个人Wiki"},
		{"Outline", "https://www.getoutline.com", "团队知识库"},
		{"GitBook", "https://www.gitbook.com", "文档平台"},
		{"Read the Docs", "https://readthedocs.org", "文档托管"},
		{"Docusaurus", "https://docusaurus.io", "文档网站"},
		{"MkDocs", "https://www.mkdocs.org", "项目文档"},
		{"VuePress", "https://vuepress.vuejs.org", "Vue文档"},
		{"Nextra", "https://nextra.site", "Next.js文档"},
		{"Starlight", "https://starlight.astro.build", "Astro文档"},
		{"Logseq Wiki", "https://docs.logseq.com", "Logseq文档"},
		{"Obsidian Publish", "https://obsidian.md/publish", "知识发布"},
		{"Notion API", "https://developers.notion.com", "Notion API"},
		{"How Stuff Works", "https://www.howstuffworks.com", "万物原理"},
		{"Simple Wikipedia", "https://simple.wikipedia.org", "简单维基"},
		{"WikiHow", "https://www.wikihow.com", "万事指南"},
		{"eHow", "https://www.ehow.com", "生活百科"},
		{"Investopedia", "https://www.investopedia.com", "投资百科"},
		{"WebMD", "https://www.webmd.com", "医学百科"},
		{"Healthline", "https://www.healthline.com", "健康百科"},
	}
}

func cloudServiceEx() []S {
	return []S{
		{"AWS", "https://aws.amazon.com", "亚马逊云"},
		{"Microsoft Azure", "https://azure.microsoft.com", "微软云"},
		{"Google Cloud", "https://cloud.google.com", "谷歌云"},
		{"IBM Cloud", "https://www.ibm.com/cloud", "IBM云"},
		{"Oracle Cloud", "https://www.oracle.com/cloud", "甲骨文云"},
		{"Alibaba Cloud", "https://www.alibabacloud.com", "阿里云国际"},
		{"阿里云", "https://www.aliyun.com", "阿里云"},
		{"腾讯云", "https://cloud.tencent.com", "腾讯云"},
		{"华为云", "https://www.huaweicloud.com", "华为云"},
		{"百度智能云", "https://cloud.baidu.com", "百度云"},
		{"天翼云", "https://www.ctyun.cn", "中国电信云"},
		{"移动云", "https://ecloud.10086.cn", "中国移动云"},
		{"金山云", "https://www.ksyun.com", "金山云"},
		{"京东云", "https://www.jdcloud.com", "京东云"},
		{"UCloud", "https://www.ucloud.cn", "UCloud"},
		{"七牛云", "https://www.qiniu.com", "七牛云"},
		{"又拍云", "https://www.upyun.com", "又拍云"},
		{"DigitalOcean", "https://www.digitalocean.com", "数字海洋"},
		{"Linode", "https://www.linode.com", "Akamai云"},
		{"Vultr", "https://www.vultr.com", "云服务器"},
		{"Hetzner", "https://www.hetzner.com", "德国云服务"},
		{"OVHcloud", "https://www.ovhcloud.com", "欧洲云"},
		{"Scaleway", "https://www.scaleway.com", "欧洲云"},
		{"UpCloud", "https://upcloud.com", "芬兰云"},
		{"Kamatera", "https://www.kamatera.com", "全球云"},
		{"Contabo", "https://contabo.com", "经济云"},
		{"Hostinger VPS", "https://www.hostinger.com/vps", "VPS主机"},
		{"AWS Lambda", "https://aws.amazon.com/lambda", "无服务器计算"},
		{"Azure Functions", "https://azure.microsoft.com/en-us/products/functions", "无服务器"},
		{"Google Cloud Functions", "https://cloud.google.com/functions", "无服务器"},
		{"Cloudflare Workers", "https://workers.cloudflare.com", "边缘计算"},
		{"Vercel", "https://vercel.com", "前端部署"},
		{"Netlify", "https://www.netlify.com", "前端托管"},
		{"Render", "https://render.com", "云应用平台"},
		{"Railway", "https://railway.app", "部署平台"},
		{"Fly.io", "https://fly.io", "边缘部署"},
		{"Deno Deploy", "https://deno.com/deploy", "Deno部署"},
		{"Supabase", "https://supabase.com", "Firebase替代"},
		{"Firebase", "https://firebase.google.com", "谷歌Firebase"},
		{"Appwrite", "https://appwrite.io", "开源后端"},
		{"PocketBase", "https://pocketbase.io", "Go后端"},
		{"Nhost", "https://nhost.io", "GraphQL后端"},
		{"Convex", "https://www.convex.dev", "实时后端"},
		{"Planetscale", "https://planetscale.com", "MySQL云"},
		{"Neon", "https://neon.tech", "Serverless Postgres"},
		{"CockroachDB Cloud", "https://www.cockroachlabs.com/product/cockroachdb-cloud", "分布式SQL"},
		{"MongoDB Atlas", "https://www.mongodb.com/cloud/atlas", "MongoDB云"},
		{"Redis Cloud", "https://redis.com/cloud", "Redis云"},
		{"Upstash", "https://upstash.com", "Serverless Redis"},
		{"Aiven", "https://aiven.io", "数据库云"},
		{"Confluent Cloud", "https://www.confluent.io/confluent-cloud", "Kafka云"},
		{"AWS S3", "https://aws.amazon.com/s3", "对象存储"},
		{"Cloudflare R2", "https://developers.cloudflare.com/r2", "对象存储"},
		{"Backblaze B2", "https://www.backblaze.com/cloud-storage", "云存储"},
		{"Wasabi", "https://wasabi.com", "热云存储"},
		{"MinIO", "https://min.io", "开源对象存储"},
		{"Terraform Cloud", "https://app.terraform.io", "基础设施即代码"},
		{"Pulumi", "https://www.pulumi.com", "基础设施即代码"},
		{"Spacelift", "https://spacelift.io", "IaC管理"},
		{"env0", "https://www.env0.com", "环境管理"},
		{"Datadog", "https://www.datadoghq.com", "云监控"},
		{"New Relic", "https://newrelic.com", "可观测性"},
		{"Grafana Cloud", "https://grafana.com/products/cloud", "可视化监控"},
		{"Splunk Cloud", "https://www.splunk.com/en_us/products/splunk-cloud-platform.html", "日志分析"},
		{"Elastic Cloud", "https://www.elastic.co/cloud", "Elasticsearch云"},
		{"PagerDuty", "https://www.pagerduty.com", "事件管理"},
		{"OpsGenie", "https://www.atlassian.com/software/opsgenie", "告警管理"},
		{"StatusPage", "https://www.atlassian.com/software/statuspage", "状态页"},
		{"Better Uptime", "https://betteruptime.com", "正常运行监控"},
		{"Twilio", "https://www.twilio.com", "通信API"},
		{"SendGrid", "https://sendgrid.com", "邮件API"},
		{"Mailgun", "https://www.mailgun.com", "邮件服务"},
		{"Postmark", "https://postmarkapp.com", "事务邮件"},
		{"Resend", "https://resend.com", "现代邮件API"},
		{"Stripe", "https://stripe.com", "支付API"},
		{"Braintree", "https://www.braintreepayments.com", "支付平台"},
		{"Adyen", "https://www.adyen.com", "全球支付"},
		{"Square", "https://squareup.com", "商业支付"},
		{"Auth0", "https://auth0.com", "身份认证"},
		{"Okta", "https://www.okta.com", "身份管理"},
		{"Clerk", "https://clerk.com", "用户认证"},
		{"WorkOS", "https://workos.com", "企业SSO"},
		{"Cloudflare", "https://www.cloudflare.com", "CDN安全"},
		{"Fastly", "https://www.fastly.com", "边缘云"},
		{"Akamai", "https://www.akamai.com", "CDN"},
		{"KeyCDN", "https://www.keycdn.com", "CDN"},
		{"BunnyCDN", "https://bunny.net", "快速CDN"},
		{"Imgix", "https://www.imgix.com", "图片CDN"},
		{"Cloudinary", "https://cloudinary.com", "媒体管理"},
		{"Uploadcare", "https://uploadcare.com", "文件上传"},
		{"Transloadit", "https://transloadit.com", "文件处理"},
		{"Stream", "https://getstream.io", "聊天/Feed API"},
		{"Ably", "https://ably.com", "实时消息"},
		{"Pusher", "https://pusher.com", "实时API"},
		{"Liveblocks", "https://liveblocks.io", "实时协作"},
		{"Algolia", "https://www.algolia.com", "搜索API"},
		{"Meilisearch", "https://www.meilisearch.com", "开源搜索"},
		{"Typesense Cloud", "https://cloud.typesense.org", "搜索云"},
		{"LaunchDarkly", "https://launchdarkly.com", "功能标记"},
		{"Statsig", "https://www.statsig.com", "实验平台"},
		{"Amplitude", "https://amplitude.com", "产品分析"},
		{"Mixpanel", "https://mixpanel.com", "用户分析"},
		{"Segment", "https://segment.com", "客户数据平台"},
	}
}
