package main

// Batch 2 extension data: Government, Photography, Anime, Cryptocurrency, Science, Writing, Podcast

func governmentEx() []S {
	return []S{
		{"中华人民共和国中央人民政府", "https://www.gov.cn", "中国政府门户"},
		{"国务院", "https://www.gov.cn/guowuyuan", "国务院信息"},
		{"全国人大", "https://www.npc.gov.cn", "人大网站"},
		{"最高人民法院", "https://www.court.gov.cn", "最高法"},
		{"最高人民检察院", "https://www.spp.gov.cn", "最高检"},
		{"中国政协", "https://www.cppcc.gov.cn", "政协网站"},
		{"中国人大网", "https://www.npc.gov.cn", "全国人大"},
		{"国家税务总局", "https://www.chinatax.gov.cn", "税务总局"},
		{"公安部", "https://www.mps.gov.cn", "公安部门户"},
		{"教育部", "https://www.moe.gov.cn", "教育部门户"},
		{"科技部", "https://www.most.gov.cn", "科技部门户"},
		{"工信部", "https://www.miit.gov.cn", "工信部门户"},
		{"交通运输部", "https://www.mot.gov.cn", "交通部门户"},
		{"商务部", "https://www.mofcom.gov.cn", "商务部门户"},
		{"人社部", "https://www.mohrss.gov.cn", "人社部门户"},
		{"自然资源部", "https://www.mnr.gov.cn", "自然资源部"},
		{"生态环境部", "https://www.mee.gov.cn", "环境部门户"},
		{"住建部", "https://www.mohurd.gov.cn", "住建部门户"},
		{"农业农村部", "https://www.moa.gov.cn", "农业部门户"},
		{"文旅部", "https://www.mct.gov.cn", "文旅部门户"},
		{"国家卫健委", "https://www.nhc.gov.cn", "卫健委门户"},
		{"中国人民银行", "https://www.pbc.gov.cn", "央行"},
		{"证监会", "https://www.csrc.gov.cn", "证监会"},
		{"银保监会", "https://www.cbirc.gov.cn", "银保监会"},
		{"海关总署", "https://www.customs.gov.cn", "海关总署"},
		{"市场监管总局", "https://www.samr.gov.cn", "市场监管"},
		{"国家统计局", "https://www.stats.gov.cn", "统计局"},
		{"国家知识产权局", "https://www.cnipa.gov.cn", "知识产权局"},
		{"信用中国", "https://www.creditchina.gov.cn", "信用查询"},
		{"国家企业信用信息", "https://www.gsxt.gov.cn", "企业信用"},
		{"USA.gov", "https://www.usa.gov", "美国政府门户"},
		{"White House", "https://www.whitehouse.gov", "白宫"},
		{"Congress.gov", "https://www.congress.gov", "美国国会"},
		{"Federal Register", "https://www.federalregister.gov", "联邦公报"},
		{"IRS", "https://www.irs.gov", "美国国税局"},
		{"SSA", "https://www.ssa.gov", "社会保障局"},
		{"USCIS", "https://www.uscis.gov", "移民局"},
		{"State Department", "https://www.state.gov", "美国国务院"},
		{"NASA", "https://www.nasa.gov", "美国航天局"},
		{"FDA", "https://www.fda.gov", "食品药品监管"},
		{"EPA", "https://www.epa.gov", "环保署"},
		{"SEC", "https://www.sec.gov", "证券交易委员会"},
		{"FTC", "https://www.ftc.gov", "联邦贸易委员会"},
		{"FCC", "https://www.fcc.gov", "联邦通信委员会"},
		{"GOV.UK", "https://www.gov.uk", "英国政府门户"},
		{"Parliament UK", "https://www.parliament.uk", "英国议会"},
		{"HMRC", "https://www.gov.uk/government/organisations/hm-revenue-customs", "英国税务"},
		{"EU Europa", "https://europa.eu", "欧盟门户"},
		{"European Parliament", "https://www.europarl.europa.eu", "欧洲议会"},
		{"Bundesregierung", "https://www.bundesregierung.de", "德国联邦政府"},
		{"Gouvernement.fr", "https://www.gouvernement.fr", "法国政府"},
		{"e-Gov Japan", "https://www.e-gov.go.jp", "日本政府"},
		{"India.gov.in", "https://www.india.gov.in", "印度政府"},
		{"Government of Canada", "https://www.canada.ca", "加拿大政府"},
		{"Australia.gov.au", "https://www.australia.gov.au", "澳大利亚政府"},
		{"Gov.br", "https://www.gov.br", "巴西政府"},
		{"Singapore Gov", "https://www.gov.sg", "新加坡政府"},
		{"Korea.go.kr", "https://www.korea.go.kr", "韩国政府"},
		{"UN", "https://www.un.org", "联合国"},
		{"World Bank", "https://www.worldbank.org", "世界银行"},
		{"IMF", "https://www.imf.org", "国际货币基金"},
		{"WTO", "https://www.wto.org", "世界贸易组织"},
		{"WHO", "https://www.who.int", "世界卫生组织"},
		{"OECD", "https://www.oecd.org", "经合组织"},
		{"UNESCO", "https://www.unesco.org", "联合国教科文"},
		{"UNICEF", "https://www.unicef.org", "联合国儿童基金"},
		{"Red Cross", "https://www.icrc.org", "红十字会"},
		{"Transparency International", "https://www.transparency.org", "透明国际"},
		{"Freedom House", "https://freedomhouse.org", "自由之家"},
		{"Amnesty International", "https://www.amnesty.org", "国际特赦组织"},
		{"Human Rights Watch", "https://www.hrw.org", "人权观察"},
		{"Data.gov", "https://data.gov", "美国开放数据"},
		{"Data.gov.uk", "https://data.gov.uk", "英国开放数据"},
		{"European Data Portal", "https://data.europa.eu", "欧洲数据门户"},
		{"中国政府数据", "https://data.gov.cn", "中国开放数据"},
		{"Open Data Barometer", "https://opendatabarometer.org", "开放数据指数"},
		{"CKAN", "https://ckan.org", "开放数据平台"},
		{"GovTech Singapore", "https://www.tech.gov.sg", "新加坡政府科技"},
		{"Digital.gov", "https://digital.gov", "美国数字政务"},
		{"GDS UK", "https://gds.blog.gov.uk", "英国数字服务"},
		{"National Archives", "https://www.archives.gov", "美国国家档案"},
		{"Library of Congress", "https://www.loc.gov", "美国国会图书馆"},
		{"Smithsonian", "https://www.si.edu", "史密森学会"},
		{"CIA World Factbook", "https://www.cia.gov/the-world-factbook", "世界概况"},
		{"USPTO", "https://www.uspto.gov", "美国专利商标局"},
		{"EPO", "https://www.epo.org", "欧洲专利局"},
		{"WIPO", "https://www.wipo.int", "世界知识产权"},
		{"日本特许厅", "https://www.jpo.go.jp", "日本专利厅"},
		{"政务服务网", "https://gjzwfw.www.gov.cn", "国家政务服务"},
		{"个人所得税", "https://etax.chinatax.gov.cn", "个税服务"},
		{"社保查询", "https://si.12333.gov.cn", "社保服务"},
		{"住房公积金", "https://www.gjj.com", "公积金查询"},
		{"出入境管理", "https://s.nia.gov.cn", "出入境服务"},
		{"交管12123", "https://gab.122.gov.cn", "交通管理"},
		{"中国裁判文书网", "https://wenshu.court.gov.cn", "裁判文书"},
		{"中国执行信息公开网", "https://zxgk.court.gov.cn", "执行信息"},
		{"天眼查", "https://www.tianyancha.com", "企业信息查询"},
		{"企查查", "https://www.qcc.com", "企业工商信息"},
		{"爱企查", "https://aiqicha.baidu.com", "百度企业查询"},
		{"12345热线", "https://www.12345.gov.cn", "政务服务热线"},
		{"国家邮政局", "https://www.spb.gov.cn", "邮政管理"},
		{"民政部", "https://www.mca.gov.cn", "民政部门户"},
		{"司法部", "https://www.moj.gov.cn", "司法部门户"},
		{"退役军人事务部", "https://www.mva.gov.cn", "退役军人"},
		{"应急管理部", "https://www.mem.gov.cn", "应急管理"},
		{"中国气象局", "https://www.cma.gov.cn", "气象局"},
		{"国家体育总局", "https://www.sport.gov.cn", "体育总局"},
		{"国家医保局", "https://www.nhsa.gov.cn", "医保局"},
		{"国家药监局", "https://www.nmpa.gov.cn", "药品监管"},
		{"中国地震局", "https://www.cea.gov.cn", "地震局"},
		{"国家移民管理局", "https://www.nia.gov.cn", "移民管理"},
		{"密码管理局", "https://www.sca.gov.cn", "密码管理"},
	}
}

func photographyEx() []S {
	return []S{
		{"500px", "https://500px.com", "摄影社区"},
		{"Flickr", "https://www.flickr.com", "照片分享"},
		{"SmugMug", "https://www.smugmug.com", "摄影作品集"},
		{"ViewBug", "https://www.viewbug.com", "摄影比赛"},
		{"1x", "https://1x.com", "精品摄影"},
		{"EyeEm", "https://www.eyeem.com", "摄影市场"},
		{"PhotoShelter", "https://www.photoshelter.com", "摄影师网站"},
		{"Zenfolio", "https://www.zenfolio.com", "摄影师作品集"},
		{"Format", "https://www.format.com", "创意作品集"},
		{"Pixieset", "https://pixieset.com", "客户照片库"},
		{"ShootProof", "https://www.shootproof.com", "摄影师交付"},
		{"Pic-Time", "https://www.pic-time.com", "摄影师画廊"},
		{"Shutterstock", "https://www.shutterstock.com", "图库素材"},
		{"Getty Images", "https://www.gettyimages.com", "专业图库"},
		{"iStock", "https://www.istockphoto.com", "图片素材"},
		{"Adobe Stock", "https://stock.adobe.com", "Adobe图库"},
		{"Alamy", "https://www.alamy.com", "独立图库"},
		{"123RF", "https://www.123rf.com", "图片素材"},
		{"Depositphotos", "https://depositphotos.com", "图片素材"},
		{"Dreamstime", "https://www.dreamstime.com", "图片素材"},
		{"Stocksy", "https://www.stocksy.com", "精品图库"},
		{"Offset", "https://www.offset.com", "高端图库"},
		{"Unsplash", "https://unsplash.com", "免费高质图片"},
		{"Pexels", "https://www.pexels.com", "免费图片视频"},
		{"Pixabay", "https://pixabay.com", "免费素材"},
		{"StockSnap", "https://stocksnap.io", "免费图片"},
		{"Burst", "https://burst.shopify.com", "Shopify免费图"},
		{"Kaboompics", "https://kaboompics.com", "免费图片"},
		{"Reshot", "https://www.reshot.com", "免费图标图片"},
		{"Gratisography", "https://gratisography.com", "趣味免费图"},
		{"Life of Pix", "https://www.lifeofpix.com", "免费生活图"},
		{"Negative Space", "https://negativespace.co", "免费图片"},
		{"PicJumbo", "https://picjumbo.com", "免费图片"},
		{"SplitShire", "https://www.splitshire.com", "免费图片"},
		{"FoodiesFeed", "https://www.foodiesfeed.com", "免费美食图"},
		{"Styled Stock", "https://styledstock.co", "女性风格图"},
		{"图虫", "https://tuchong.com", "中国摄影社区"},
		{"站酷海洛", "https://www.hellorf.com", "中国正版图库"},
		{"千图网", "https://www.58pic.com", "中国设计素材"},
		{"昵图网", "https://www.nipic.com", "中国图片共享"},
		{"摄图网", "https://699pic.com", "中国图片素材"},
		{"Veer", "https://www.veer.com", "中国视觉素材"},
		{"全景视觉", "https://www.quanjing.com", "中国图库"},
		{"DPReview", "https://www.dpreview.com", "数码相机评测"},
		{"PetaPixel", "https://petapixel.com", "摄影新闻"},
		{"Fstoppers", "https://fstoppers.com", "摄影教程社区"},
		{"DIY Photography", "https://www.diyphotography.net", "摄影DIY"},
		{"SLR Lounge", "https://www.slrlounge.com", "摄影教育"},
		{"Phlearn", "https://phlearn.com", "PS修图教程"},
		{"Photography Life", "https://photographylife.com", "摄影技巧"},
		{"Digital Photography School", "https://digital-photography-school.com", "摄影学校"},
		{"Strobist", "https://strobist.blogspot.com", "闪灯摄影"},
		{"Improve Photography", "https://improvephotography.com", "摄影进阶"},
		{"Cambridge in Colour", "https://www.cambridgeincolour.com", "摄影教程"},
		{"Ken Rockwell", "https://www.kenrockwell.com", "器材评测"},
		{"The Phoblographer", "https://www.thephoblographer.com", "摄影文化"},
		{"Lomography", "https://www.lomography.com", "胶片摄影"},
		{"Magnum Photos", "https://www.magnumphotos.com", "马格南图片社"},
		{"National Geographic Photo", "https://www.nationalgeographic.com/photography", "国家地理摄影"},
		{"World Press Photo", "https://www.worldpressphoto.org", "世界新闻摄影"},
		{"Sony World Photography", "https://www.worldphoto.org", "索尼世界摄影"},
		{"Hasselblad Awards", "https://www.hasselbladfoundation.org", "哈苏奖"},
		{"Leica Camera", "https://leica-camera.com", "徕卡相机"},
		{"Canon", "https://www.usa.canon.com", "佳能"},
		{"Nikon", "https://www.nikon.com", "尼康"},
		{"Sony Alpha", "https://www.sony.com/en/articles/product-specifications-ilce-7m4", "索尼微单"},
		{"Fujifilm", "https://www.fujifilm.com", "富士胶片"},
		{"Panasonic Lumix", "https://www.panasonic.com/lumix", "松下相机"},
		{"Olympus", "https://www.olympus.com", "奥林巴斯"},
		{"DJI", "https://www.dji.com", "大疆无人机"},
		{"GoPro", "https://gopro.com", "运动相机"},
		{"Insta360", "https://www.insta360.com", "全景相机"},
		{"B&H Photo", "https://www.bhphotovideo.com", "摄影器材"},
		{"Adorama", "https://www.adorama.com", "摄影器材商店"},
		{"KEH Camera", "https://www.keh.com", "二手相机"},
		{"MPB", "https://www.mpb.com", "二手器材交易"},
		{"LensRentals", "https://www.lensrentals.com", "镜头租赁"},
		{"BorrowLenses", "https://www.borrowlenses.com", "器材租赁"},
		{"Adobe Lightroom", "https://www.adobe.com/products/photoshop-lightroom.html", "照片编辑"},
		{"Capture One", "https://www.captureone.com", "专业RAW处理"},
		{"Luminar", "https://skylum.com/luminar", "AI照片编辑"},
		{"DxO PhotoLab", "https://www.dxo.com/dxo-photolab", "照片处理"},
		{"ON1 Photo RAW", "https://www.on1.com", "照片编辑"},
		{"Affinity Photo", "https://affinity.serif.com/photo", "照片编辑"},
		{"GIMP", "https://www.gimp.org", "免费图片编辑"},
		{"RawTherapee", "https://rawtherapee.com", "开源RAW处理"},
		{"darktable", "https://www.darktable.org", "开源照片管理"},
		{"PhotoPrism", "https://www.photoprism.app", "AI照片管理"},
		{"Immich", "https://immich.app", "自托管照片"},
		{"Google Photos", "https://photos.google.com", "谷歌相册"},
		{"Apple Photos", "https://www.apple.com/ios/photos", "苹果相册"},
		{"Amazon Photos", "https://www.amazon.com/photos", "亚马逊相册"},
		{"Remove.bg", "https://www.remove.bg", "AI去背景"},
		{"Canva Photo", "https://www.canva.com/photo-editor", "在线图片编辑"},
		{"Fotor", "https://www.fotor.com", "在线修图"},
		{"BeFunky", "https://www.befunky.com", "照片编辑"},
		{"Photopea", "https://www.photopea.com", "在线PS替代"},
		{"Pixlr", "https://pixlr.com", "在线图片编辑"},
		{"Snapseed", "https://snapseed.online", "移动修图"},
		{"VSCO", "https://vsco.co", "滤镜+社区"},
		{"Lightroom Mobile", "https://lightroom.adobe.com", "移动版LR"},
		{"Halide", "https://halide.cam", "iOS相机应用"},
		{"ProCamera", "https://www.procamera-app.com", "专业手机摄影"},
		{"Moment", "https://www.shopmoment.com", "手机摄影配件"},
		{"美图秀秀", "https://www.meitu.com", "中国修图应用"},
		{"Poco摄影", "https://www.poco.cn", "中国摄影社区"},
		{"蜂鸟网", "https://www.fengniao.com", "中国摄影门户"},
		{"色影无忌", "https://www.xitek.com", "中国摄影论坛"},
		{"中关村摄影", "https://dcdv.zol.com.cn", "相机评测"},
	}
}

func animeEx() []S {
	return []S{
		{"Crunchyroll", "https://www.crunchyroll.com", "日本动漫流媒体"},
		{"Funimation", "https://www.funimation.com", "动漫流媒体"},
		{"HIDIVE", "https://www.hidive.com", "动漫流媒体"},
		{"AnimeLab", "https://www.animelab.com", "澳洲动漫"},
		{"VRV", "https://vrv.co", "动漫聚合"},
		{"9anime", "https://9anime.to", "免费动漫"},
		{"MyAnimeList", "https://myanimelist.net", "动漫数据库"},
		{"AniList", "https://anilist.co", "动漫追踪"},
		{"AniDB", "https://anidb.net", "动漫数据库"},
		{"Anime-Planet", "https://www.anime-planet.com", "动漫推荐"},
		{"Kitsu", "https://kitsu.io", "动漫社交追踪"},
		{"LiveChart", "https://www.livechart.me", "动漫放送表"},
		{"AniChart", "https://anichart.net", "季度动漫表"},
		{"Anime News Network", "https://www.animenewsnetwork.com", "动漫新闻"},
		{"Crunchyroll News", "https://www.crunchyroll.com/news", "动漫资讯"},
		{"Otaku USA", "https://www.otakuusamagazine.com", "御宅杂志"},
		{"Tokyo Otaku Mode", "https://otakumode.com", "御宅文化"},
		{"Japan Times Anime", "https://www.japantimes.co.jp/tag/anime", "日本动漫新闻"},
		{"Manga Plus", "https://mangaplus.shueisha.co.jp", "集英社漫画"},
		{"Shonen Jump", "https://www.viz.com/shonenjump", "少年Jump"},
		{"VIZ Media", "https://www.viz.com", "漫画出版"},
		{"Manga Dex", "https://mangadex.org", "漫画阅读"},
		{"Manga Fox", "https://mangafox.me", "在线漫画"},
		{"Manga Rock", "https://mangarock.com", "漫画聚合"},
		{"Webtoon", "https://www.webtoons.com", "条漫平台"},
		{"Tapas", "https://tapas.io", "网络漫画"},
		{"Lezhin Comics", "https://www.lezhin.com", "韩国漫画"},
		{"Tappytoon", "https://www.tappytoon.com", "韩漫平台"},
		{"Pixiv", "https://www.pixiv.net", "日本插画社区"},
		{"DeviantArt Anime", "https://www.deviantart.com/tag/anime", "动漫插画"},
		{"ArtStation Anime", "https://www.artstation.com/channels/anime", "动漫美术"},
		{"Danbooru", "https://danbooru.donmai.us", "动漫图库"},
		{"Gelbooru", "https://gelbooru.com", "动漫标签图库"},
		{"Konachan", "https://konachan.com", "动漫壁纸"},
		{"Zerochan", "https://www.zerochan.net", "动漫图片"},
		{"Wallhaven Anime", "https://wallhaven.cc/search?categories=010&purity=100&sorting=favorites", "动漫壁纸"},
		{"哔哩哔哩", "https://www.bilibili.com", "B站"},
		{"哔哩哔哩漫画", "https://manga.bilibili.com", "B站漫画"},
		{"腾讯动漫", "https://ac.qq.com", "腾讯漫画"},
		{"快看漫画", "https://www.kuaikanmanhua.com", "快看漫画"},
		{"有妖气", "https://www.u17.com", "有妖气漫画"},
		{"动漫之家", "https://www.dmzj.com", "动漫门户"},
		{"半次元", "https://bcy.net", "ACG社区"},
		{"LOFTER同人", "https://www.lofter.com", "同人创作"},
		{"AcFun", "https://www.acfun.cn", "A站"},
		{"萌娘百科", "https://zh.moegirl.org.cn", "ACG百科"},
		{"Bangumi番组计划", "https://bangumi.tv", "ACG数据库"},
		{"Anitama", "https://www.anitama.cn", "动画评论"},
		{"Anime Trending", "https://anitrendz.net", "动漫投票"},
		{"Anime Corner", "https://animecorner.me", "动漫排名"},
		{"Gigguk", "https://www.youtube.com/c/Gigguk", "动漫UP主"},
		{"Mother's Basement", "https://www.youtube.com/c/MothersBasement", "动漫分析"},
		{"Niconico", "https://www.nicovideo.jp", "日本弹幕视频"},
		{"AbemaTV", "https://abema.tv", "日本网络电视"},
		{"d Anime Store", "https://animestore.docomo.ne.jp", "日本动漫点播"},
		{"Wakanim", "https://www.wakanim.tv", "欧洲动漫"},
		{"AnimeSuge", "https://animesuge.to", "动漫流媒体"},
		{"Novel Updates", "https://www.novelupdates.com", "轻小说更新"},
		{"Light Novel World", "https://www.lightnovelworld.com", "轻小说阅读"},
		{"Syosetu", "https://syosetu.com", "日本小说投稿"},
		{"Kakuyomu", "https://kakuyomu.jp", "角川小说"},
		{"起点中文网", "https://www.qidian.com", "中国网文"},
		{"晋江文学城", "https://www.jjwxc.net", "中国女性文学"},
		{"纵横中文网", "https://www.zongheng.com", "中国小说"},
		{"Amiami", "https://www.amiami.com", "动漫手办"},
		{"Good Smile Company", "https://www.goodsmile.info", "黏土人"},
		{"Kotobukiya", "https://www.kotobukiya.co.jp", "寿屋模型"},
		{"Mandarake", "https://www.mandarake.co.jp", "二手动漫商品"},
		{"Suruga-ya", "https://www.suruga-ya.com", "二手动漫"},
		{"HobbySearch", "https://www.1999.co.jp", "模型商店"},
		{"HLJ", "https://www.hlj.com", "日本手办"},
		{"CDJapan", "https://www.cdjapan.co.jp", "日本商品"},
		{"PlayAsia", "https://www.play-asia.com", "亚洲游戏动漫"},
		{"Rightstuf", "https://www.rightstufanime.com", "北美动漫商店"},
		{"Crunchyroll Store", "https://store.crunchyroll.com", "动漫周边"},
		{"Bookwalker", "https://global.bookwalker.jp", "数字漫画"},
		{"ComicWalker", "https://comic-walker.com", "角川免费漫画"},
		{"Comico", "https://www.comico.jp", "日本条漫"},
		{"Piccoma", "https://piccoma.com", "漫画平台"},
		{"Naver Webtoon", "https://comic.naver.com", "韩国条漫"},
		{"Kakao Page", "https://page.kakao.com", "韩国漫画小说"},
		{"Toomics", "https://toomics.com", "韩国漫画"},
		{"Manga UP!", "https://manga-up.com", "Square Enix漫画"},
		{"Jump+", "https://shonenjumpplus.com", "少年Jump+"},
		{"Sunday Webry", "https://www.sunday-webry.com", "小学馆漫画"},
		{"Magazine Pocket", "https://pocket.shonenmagazine.com", "讲谈社漫画"},
		{"Champion Cross", "https://championcross.jp", "秋田书店漫画"},
		{"Comic Days", "https://comic-days.com", "讲谈社免费漫画"},
		{"Ganganonline", "https://www.ganganonline.com", "SE漫画"},
		{"漫画台", "https://www.manhuatai.com", "中国漫画"},
		{"看漫画", "https://www.kmanhua.com", "漫画阅读"},
		{"漫漫漫画", "https://www.manmanapp.com", "国产漫画"},
		{"咚漫", "https://www.dongmanmanhua.cn", "Webtoon中国"},
		{"ComiXology", "https://www.comixology.com", "数字漫画平台"},
		{"Marvel Comics", "https://www.marvel.com/comics", "漫威漫画"},
		{"DC Comics", "https://www.dc.com", "DC漫画"},
		{"Dark Horse", "https://www.darkhorse.com", "黑马漫画"},
		{"Image Comics", "https://imagecomics.com", "Image漫画"},
		{"IDW Publishing", "https://www.idwpublishing.com", "IDW漫画"},
		{"Boom Studios", "https://www.boom-studios.com", "Boom漫画"},
		{"Sakugabooru", "https://www.sakugabooru.com", "作画分析"},
		{"Behind the Voice", "https://www.behindthevoiceactors.com", "声优数据"},
		{"Seiyuu Database", "https://www.animenewsnetwork.com/encyclopedia/people.php", "声优百科"},
		{"cosplay.com", "https://www.cosplay.com", "Cosplay社区"},
		{"WorldCosplay", "https://worldcosplay.net", "世界Cosplay"},
		{"CosplayGen", "https://cosplaygen.com", "AI Cosplay"},
		{"Anime Japan", "https://anime-japan.jp", "动漫展"},
		{"Comiket", "https://www.comiket.co.jp", "同人展"},
		{"Anime Expo", "https://www.anime-expo.org", "美国动漫展"},
		{"Otakon", "https://www.otakon.com", "美国动漫大会"},
	}
}

func cryptocurrencyEx() []S {
	return []S{
		{"Coinbase", "https://www.coinbase.com", "加密货币交易所"},
		{"Kraken", "https://www.kraken.com", "加密货币交易"},
		{"Gemini", "https://www.gemini.com", "加密货币交易所"},
		{"Bitstamp", "https://www.bitstamp.net", "欧洲交易所"},
		{"Crypto.com", "https://crypto.com", "加密货币平台"},
		{"KuCoin", "https://www.kucoin.com", "加密货币交易"},
		{"Gate.io", "https://www.gate.io", "加密交易所"},
		{"Bybit", "https://www.bybit.com", "衍生品交易所"},
		{"OKX", "https://www.okx.com", "加密交易平台"},
		{"Bitget", "https://www.bitget.com", "加密交易"},
		{"MEXC", "https://www.mexc.com", "加密交易所"},
		{"Bitfinex", "https://www.bitfinex.com", "专业交易所"},
		{"Huobi", "https://www.huobi.com", "火币交易所"},
		{"Upbit", "https://upbit.com", "韩国交易所"},
		{"Bithumb", "https://www.bithumb.com", "韩国交易所"},
		{"bitFlyer", "https://bitflyer.com", "日本交易所"},
		{"CoinGecko", "https://www.coingecko.com", "加密货币数据"},
		{"CoinMarketCap", "https://coinmarketcap.com", "加密市值排名"},
		{"CryptoCompare", "https://www.cryptocompare.com", "加密数据对比"},
		{"Messari", "https://messari.io", "加密研究分析"},
		{"Glassnode", "https://glassnode.com", "链上数据分析"},
		{"Nansen", "https://www.nansen.ai", "区块链分析"},
		{"Dune Analytics", "https://dune.com", "链上数据查询"},
		{"DefiLlama", "https://defillama.com", "DeFi数据"},
		{"DeFi Pulse", "https://www.defipulse.com", "DeFi排名"},
		{"L2Beat", "https://l2beat.com", "Layer2数据"},
		{"Token Terminal", "https://tokenterminal.com", "协议数据"},
		{"Etherscan", "https://etherscan.io", "以太坊浏览器"},
		{"BscScan", "https://bscscan.com", "BSC浏览器"},
		{"Polygonscan", "https://polygonscan.com", "Polygon浏览器"},
		{"Arbiscan", "https://arbiscan.io", "Arbitrum浏览器"},
		{"Solscan", "https://solscan.io", "Solana浏览器"},
		{"Blockchain.com", "https://www.blockchain.com/explorer", "BTC浏览器"},
		{"Bitcoin.org", "https://bitcoin.org", "比特币官网"},
		{"Ethereum.org", "https://ethereum.org", "以太坊官网"},
		{"Solana", "https://solana.com", "Solana区块链"},
		{"Cardano", "https://cardano.org", "Cardano区块链"},
		{"Polkadot", "https://polkadot.network", "波卡网络"},
		{"Avalanche", "https://www.avax.network", "雪崩区块链"},
		{"Near Protocol", "https://near.org", "NEAR区块链"},
		{"Cosmos", "https://cosmos.network", "Cosmos生态"},
		{"Algorand", "https://www.algorand.com", "Algorand区块链"},
		{"Aptos", "https://aptoslabs.com", "Aptos区块链"},
		{"Sui", "https://sui.io", "Sui区块链"},
		{"zkSync", "https://zksync.io", "以太坊L2"},
		{"StarkNet", "https://www.starknet.io", "零知识L2"},
		{"Optimism", "https://www.optimism.io", "乐观Rollup"},
		{"Arbitrum", "https://arbitrum.io", "Arbitrum L2"},
		{"Base", "https://base.org", "Coinbase L2"},
		{"Uniswap", "https://uniswap.org", "去中心化交易"},
		{"SushiSwap", "https://www.sushi.com", "DEX"},
		{"PancakeSwap", "https://pancakeswap.finance", "BSC DEX"},
		{"Curve", "https://curve.fi", "稳定币DEX"},
		{"Balancer", "https://balancer.fi", "自动做市商"},
		{"1inch", "https://1inch.io", "DEX聚合器"},
		{"Aave", "https://aave.com", "借贷协议"},
		{"Compound", "https://compound.finance", "借贷协议"},
		{"MakerDAO", "https://makerdao.com", "稳定币协议"},
		{"Lido", "https://lido.fi", "流动性质押"},
		{"Rocket Pool", "https://rocketpool.net", "ETH质押"},
		{"EigenLayer", "https://www.eigenlayer.xyz", "再质押"},
		{"OpenSea", "https://opensea.io", "NFT市场"},
		{"Blur", "https://blur.io", "NFT交易"},
		{"Rarible", "https://rarible.com", "NFT创作交易"},
		{"Foundation", "https://foundation.app", "NFT艺术"},
		{"SuperRare", "https://superrare.com", "数字艺术"},
		{"Zora", "https://zora.co", "NFT协议"},
		{"Magic Eden", "https://magiceden.io", "Solana NFT"},
		{"LooksRare", "https://looksrare.org", "NFT市场"},
		{"MetaMask", "https://metamask.io", "以太坊钱包"},
		{"Phantom", "https://phantom.app", "Solana钱包"},
		{"Trust Wallet", "https://trustwallet.com", "多链钱包"},
		{"Rainbow", "https://rainbow.me", "以太坊钱包"},
		{"Rabby", "https://rabby.io", "Web3钱包"},
		{"Safe", "https://safe.global", "多签钱包"},
		{"Ledger", "https://www.ledger.com", "硬件钱包"},
		{"Trezor", "https://trezor.io", "硬件钱包"},
		{"Zerion", "https://zerion.io", "DeFi资产管理"},
		{"Zapper", "https://zapper.xyz", "DeFi仪表盘"},
		{"DeBank", "https://debank.com", "DeFi资产追踪"},
		{"Arkham", "https://www.arkhamintelligence.com", "链上情报"},
		{"Chainalysis", "https://www.chainalysis.com", "区块链合规"},
		{"Elliptic", "https://www.elliptic.co", "加密合规"},
		{"CipherTrace", "https://ciphertrace.com", "区块链安全"},
		{"Immunefi", "https://immunefi.com", "Web3漏洞赏金"},
		{"Certik", "https://www.certik.com", "智能合约审计"},
		{"Trail of Bits", "https://www.trailofbits.com", "安全审计"},
		{"Snapshot", "https://snapshot.org", "DAO治理"},
		{"Tally", "https://www.tally.xyz", "链上治理"},
		{"Boardroom", "https://boardroom.io", "DAO治理聚合"},
		{"Mirror", "https://mirror.xyz", "Web3写作"},
		{"Farcaster", "https://www.farcaster.xyz", "去中心化社交"},
		{"Lens Protocol", "https://www.lens.xyz", "社交图谱"},
		{"Friend.tech", "https://www.friend.tech", "社交代币"},
		{"The Block", "https://www.theblock.co", "加密新闻"},
		{"CoinDesk", "https://www.coindesk.com", "加密新闻"},
		{"Decrypt", "https://decrypt.co", "加密新闻"},
		{"Blockworks", "https://blockworks.co", "加密金融新闻"},
		{"Bankless", "https://www.bankless.com", "加密教育"},
		{"Unchained", "https://unchainedcrypto.com", "加密播客"},
		{"CryptoSlate", "https://cryptoslate.com", "加密信息"},
		{"Cointelegraph", "https://cointelegraph.com", "加密新闻"},
		{"PANews", "https://www.panewslab.com", "中文加密新闻"},
		{"链闻", "https://www.chainnews.com", "中文区块链"},
		{"区块律动", "https://www.theblockbeats.info", "中文加密资讯"},
		{"Odaily星球日报", "https://www.odaily.news", "中文区块链"},
		{"金色财经", "https://www.jinse.com", "中文区块链"},
		{"巴比特", "https://www.8btc.com", "中文区块链社区"},
		{"Alchemy", "https://www.alchemy.com", "Web3开发平台"},
		{"Infura", "https://www.infura.io", "以太坊API"},
		{"QuickNode", "https://www.quicknode.com", "区块链节点"},
		{"Moralis", "https://moralis.io", "Web3 API"},
		{"Thirdweb", "https://thirdweb.com", "Web3开发SDK"},
		{"Hardhat", "https://hardhat.org", "以太坊开发"},
		{"Foundry", "https://getfoundry.sh", "智能合约工具"},
		{"OpenZeppelin", "https://www.openzeppelin.com", "合约安全库"},
		{"Remix IDE", "https://remix.ethereum.org", "Solidity IDE"},
		{"Tenderly", "https://tenderly.co", "合约调试"},
	}
}

func scienceEx() []S {
	return []S{
		{"Nature", "https://www.nature.com", "自然期刊"},
		{"Science", "https://www.science.org", "科学杂志"},
		{"Cell", "https://www.cell.com", "细胞期刊"},
		{"PNAS", "https://www.pnas.org", "美国科学院院刊"},
		{"Scientific American", "https://www.scientificamerican.com", "科学美国人"},
		{"New Scientist", "https://www.newscientist.com", "新科学家"},
		{"Popular Science", "https://www.popsci.com", "大众科学"},
		{"Wired Science", "https://www.wired.com/category/science", "连线科学"},
		{"Ars Technica Science", "https://arstechnica.com/science", "科学技术"},
		{"Quanta Magazine", "https://www.quantamagazine.org", "量子杂志"},
		{"ScienceDaily", "https://www.sciencedaily.com", "科学日报"},
		{"Phys.org", "https://phys.org", "物理学资讯"},
		{"Space.com", "https://www.space.com", "太空新闻"},
		{"Astronomy.com", "https://astronomy.com", "天文学"},
		{"Sky & Telescope", "https://skyandtelescope.org", "天空与望远镜"},
		{"Earthsky", "https://earthsky.org", "地球与天空"},
		{"Discover Magazine", "https://www.discovermagazine.com", "发现杂志"},
		{"Live Science", "https://www.livescience.com", "活科学"},
		{"IFLScience", "https://www.iflscience.com", "趣味科学"},
		{"Futurism", "https://futurism.com", "未来科技"},
		{"MIT Technology Review", "https://www.technologyreview.com", "MIT技术评论"},
		{"ACS Publications", "https://pubs.acs.org", "美国化学会"},
		{"RSC Journals", "https://www.rsc.org/journals", "英国皇家化学"},
		{"Wiley Online Library", "https://onlinelibrary.wiley.com", "Wiley期刊"},
		{"SpringerNature", "https://www.springernature.com", "Springer出版"},
		{"Elsevier", "https://www.elsevier.com", "爱思唯尔"},
		{"Taylor & Francis", "https://www.tandfonline.com", "学术出版"},
		{"MDPI", "https://www.mdpi.com", "开放获取期刊"},
		{"Frontiers", "https://www.frontiersin.org", "开放获取"},
		{"PLOS", "https://www.plos.org", "开放获取"},
		{"bioRxiv", "https://www.biorxiv.org", "生物预印本"},
		{"medRxiv", "https://www.medrxiv.org", "医学预印本"},
		{"ChemRxiv", "https://chemrxiv.org", "化学预印本"},
		{"EarthArXiv", "https://eartharxiv.org", "地球科学预印本"},
		{"PhilSci Archive", "https://philsci-archive.pitt.edu", "科学哲学"},
		{"CERN", "https://home.cern", "欧洲核子研究"},
		{"Fermilab", "https://www.fnal.gov", "费米国家实验室"},
		{"SLAC", "https://www6.slac.stanford.edu", "斯坦福线性加速器"},
		{"Brookhaven Lab", "https://www.bnl.gov", "布鲁克海文实验室"},
		{"Los Alamos", "https://www.lanl.gov", "洛斯阿拉莫斯"},
		{"Max Planck", "https://www.mpg.de", "马克斯普朗克"},
		{"RIKEN", "https://www.riken.jp", "日本理化研究所"},
		{"Chinese Academy of Sciences", "https://english.cas.cn", "中国科学院"},
		{"科学网", "https://www.sciencenet.cn", "中国科学社区"},
		{"果壳", "https://www.guokr.com", "中国科普社区"},
		{"知乎科学", "https://www.zhihu.com/topic/19554298", "知乎科学话题"},
		{"环球科学", "https://www.huanqiukexue.com", "科学美国人中文"},
		{"中国科学报", "https://www.sciencenet.cn/sbhtml", "科学报"},
		{"中国科普网", "https://www.kepu.gov.cn", "中国科普"},
		{"Wolfram MathWorld", "https://mathworld.wolfram.com", "数学百科"},
		{"Khan Academy", "https://www.khanacademy.org", "可汗学院"},
		{"PhET Simulations", "https://phet.colorado.edu", "物理模拟"},
		{"HyperPhysics", "https://hyperphysics.phy-astr.gsu.edu", "物理百科"},
		{"Periodic Table", "https://ptable.com", "交互元素周期表"},
		{"Wolfram Demonstrations", "https://demonstrations.wolfram.com", "数学演示"},
		{"Galaxy Zoo", "https://www.zooniverse.org/projects/zookeeper/galaxy-zoo", "公民科学"},
		{"Zooniverse", "https://www.zooniverse.org", "公民科学平台"},
		{"Fold.it", "https://fold.it", "蛋白质折叠游戏"},
		{"Einstein@Home", "https://einsteinathome.org", "分布式计算"},
		{"SETI@Home", "https://setiathome.berkeley.edu", "搜寻外星智能"},
		{"Rosetta@Home", "https://boinc.bakerlab.org/rosetta", "蛋白质研究"},
		{"BOINC", "https://boinc.berkeley.edu", "分布式计算"},
		{"Folding@Home", "https://foldingathome.org", "蛋白质折叠"},
		{"Hubble Site", "https://hubblesite.org", "哈勃太空望远镜"},
		{"James Webb", "https://webbtelescope.org", "韦伯望远镜"},
		{"SpaceX", "https://www.spacex.com", "SpaceX航天"},
		{"Blue Origin", "https://www.blueorigin.com", "蓝色起源"},
		{"Rocket Lab", "https://www.rocketlabusa.com", "火箭实验室"},
		{"ESA", "https://www.esa.int", "欧洲航天局"},
		{"JAXA", "https://www.jaxa.jp", "日本宇宙航空"},
		{"ISRO", "https://www.isro.gov.in", "印度空间研究"},
		{"CNSA", "https://www.cnsa.gov.cn", "中国国家航天局"},
		{"Planetary Society", "https://www.planetary.org", "行星学会"},
		{"Science Friday", "https://www.sciencefriday.com", "科学星期五"},
		{"Radiolab", "https://radiolab.org", "科学播客"},
		{"StarTalk", "https://www.startalkradio.net", "科学脱口秀"},
		{"Cosmos Magazine", "https://cosmosmagazine.com", "宇宙杂志"},
		{"Atlas of Living Australia", "https://www.ala.org.au", "生物多样性"},
		{"GBIF", "https://www.gbif.org", "全球生物多样性"},
		{"iNaturalist", "https://www.inaturalist.org", "自然观察"},
		{"eBird", "https://ebird.org", "鸟类观察"},
		{"GenBank", "https://www.ncbi.nlm.nih.gov/genbank", "基因序列数据库"},
		{"UniProt", "https://www.uniprot.org", "蛋白质数据库"},
		{"PDB", "https://www.rcsb.org", "蛋白质结构"},
		{"AlphaFold", "https://alphafold.ebi.ac.uk", "蛋白质结构预测"},
		{"EMBL-EBI", "https://www.ebi.ac.uk", "欧洲生物信息学"},
		{"NCBI", "https://www.ncbi.nlm.nih.gov", "美国生物信息中心"},
		{"Sci-Hub", "https://sci-hub.se", "论文获取"},
		{"LibGen", "https://libgen.is", "学术资料"},
		{"Z-Library", "https://z-lib.org", "电子图书馆"},
		{"Internet Archive Scholar", "https://scholar.archive.org", "学术搜索"},
		{"Dimensions", "https://www.dimensions.ai", "学术数据库"},
		{"Lens.org", "https://www.lens.org", "专利学术搜索"},
		{"Connected Papers", "https://www.connectedpapers.com", "论文关系图"},
		{"Papers with Code", "https://paperswithcode.com", "论文+代码"},
		{"Hugging Face Papers", "https://huggingface.co/papers", "AI论文"},
		{"Distill.pub", "https://distill.pub", "可视化ML研究"},
		{"OpenReview", "https://openreview.net", "同行评审"},
		{"PeerJ", "https://peerj.com", "开放获取期刊"},
		{"eLife", "https://elifesciences.org", "生命科学"},
		{"Science Advances", "https://www.science.org/journal/sciadv", "科学进展"},
		{"Nature Communications", "https://www.nature.com/ncomms", "自然通讯"},
		{"APS Physics", "https://www.aps.org", "美国物理学会"},
		{"AIP Publishing", "https://publishing.aip.org", "美国物理联合会"},
		{"IOP Publishing", "https://ioppublishing.org", "英国物理学会"},
		{"IEEE Spectrum", "https://spectrum.ieee.org", "IEEE技术杂志"},
		{"ACM Queue", "https://queue.acm.org", "ACM技术杂志"},
		{"Scholarpedia", "https://www.scholarpedia.org", "学术百科"},
		{"Encyclopedia of Life", "https://eol.org", "生命百科全书"},
		{"Smithsonian Science", "https://www.si.edu/science", "史密森科学"},
		{"European Science Foundation", "https://www.esf.org", "欧洲科学基金"},
		{"National Science Foundation", "https://www.nsf.gov", "美国国家科学基金"},
	}
}

func writingEx() []S {
	return []S{
		{"Medium", "https://medium.com", "写作平台"},
		{"Substack", "https://substack.com", "Newsletter平台"},
		{"Ghost", "https://ghost.org", "独立博客平台"},
		{"WordPress.com", "https://wordpress.com", "博客平台"},
		{"Blogger", "https://www.blogger.com", "谷歌博客"},
		{"Wix Blog", "https://www.wix.com/blog", "Wix博客"},
		{"Hashnode", "https://hashnode.com", "开发者博客"},
		{"DEV.to", "https://dev.to", "开发者社区"},
		{"Write.as", "https://write.as", "极简写作"},
		{"Svbtle", "https://svbtle.com", "简约博客"},
		{"Bear Blog", "https://bearblog.dev", "极简博客"},
		{"Micro.blog", "https://micro.blog", "微博客"},
		{"Telegraph", "https://telegra.ph", "快速发布"},
		{"Penzu", "https://penzu.com", "在线日记"},
		{"Day One", "https://dayoneapp.com", "日记应用"},
		{"Journey", "https://journey.cloud", "日记应用"},
		{"Scrivener", "https://www.literatureandlatte.com/scrivener", "写作软件"},
		{"Ulysses", "https://ulysses.app", "Mac写作"},
		{"iA Writer", "https://ia.net/writer", "专注写作"},
		{"Typora", "https://typora.io", "Markdown编辑器"},
		{"Bear App", "https://bear.app", "Markdown笔记"},
		{"Notion Writing", "https://www.notion.so", "Notion写作"},
		{"Craft", "https://www.craft.do", "文档应用"},
		{"Coda", "https://coda.io", "文档协作"},
		{"Google Docs", "https://docs.google.com", "谷歌文档"},
		{"Dropbox Paper", "https://www.dropbox.com/paper", "协作文档"},
		{"Quip", "https://quip.com", "团队文档"},
		{"Zoho Writer", "https://www.zoho.com/writer", "在线文档"},
		{"Etherpad", "https://etherpad.org", "开源协作编辑"},
		{"HackMD", "https://hackmd.io", "协作Markdown"},
		{"CoCalc", "https://cocalc.com", "协作计算"},
		{"Overleaf", "https://www.overleaf.com", "LaTeX协作"},
		{"Authorea", "https://www.authorea.com", "学术写作协作"},
		{"Manuscripts.io", "https://www.manuscripts.io", "学术写作"},
		{"Scrintal", "https://www.scrintal.com", "视觉思维写作"},
		{"Heptabase", "https://heptabase.com", "可视化笔记"},
		{"Tana", "https://tana.inc", "智能笔记"},
		{"Capacities", "https://capacities.io", "对象笔记"},
		{"Reflect", "https://reflect.app", "AI笔记"},
		{"Mem", "https://mem.ai", "AI笔记工具"},
		{"Wattpad", "https://www.wattpad.com", "小说社区"},
		{"Royal Road", "https://www.royalroad.com", "网络小说"},
		{"Webnovel", "https://www.webnovel.com", "起点国际"},
		{"Archive of Our Own", "https://archiveofourown.org", "同人小说"},
		{"FanFiction.net", "https://www.fanfiction.net", "同人小说"},
		{"NaNoWriMo", "https://nanowrimo.org", "全国小说写作月"},
		{"Reedsy", "https://reedsy.com", "独立出版"},
		{"Draft2Digital", "https://www.draft2digital.com", "电子书分发"},
		{"Amazon KDP", "https://kdp.amazon.com", "亚马逊自出版"},
		{"Smashwords", "https://www.smashwords.com", "电子书出版"},
		{"Lulu", "https://www.lulu.com", "自出版"},
		{"BookBaby", "https://www.bookbaby.com", "图书出版"},
		{"IngramSpark", "https://www.ingramspark.com", "图书分发"},
		{"Kindle Vella", "https://www.amazon.com/kindle-vella", "连载小说"},
		{"Radish Fiction", "https://www.radishfiction.com", "连载小说"},
		{"Vocal", "https://vocal.media", "创作者平台"},
		{"NewsBreak Creator", "https://creators.newsbreak.com", "新闻创作"},
		{"Contently", "https://contently.com", "内容营销"},
		{"Skyword", "https://www.skyword.com", "内容平台"},
		{"ClearVoice", "https://www.clearvoice.com", "内容创作"},
		{"ContentFly", "https://contentfly.com", "写作服务"},
		{"Jasper", "https://www.jasper.ai", "AI写作助手"},
		{"Copy.ai", "https://www.copy.ai", "AI文案"},
		{"Writesonic", "https://writesonic.com", "AI内容生成"},
		{"Sudowrite", "https://www.sudowrite.com", "AI小说助手"},
		{"NovelAI", "https://novelai.net", "AI小说生成"},
		{"Simplified", "https://simplified.com", "AI写作设计"},
		{"Wordtune", "https://www.wordtune.com", "AI改写工具"},
		{"QuillBot", "https://quillbot.com", "AI改写释义"},
		{"DeepL Write", "https://www.deepl.com/write", "AI写作优化"},
		{"Rytr", "https://rytr.me", "AI写作"},
		{"Anyword", "https://anyword.com", "AI营销文案"},
		{"Writer.com", "https://writer.com", "企业AI写作"},
		{"Grammarly", "https://www.grammarly.com", "语法检查"},
		{"ProWritingAid", "https://prowritingaid.com", "写作分析"},
		{"AutoCrit", "https://www.autocrit.com", "小说编辑"},
		{"Fictionary", "https://fictionary.co", "故事编辑"},
		{"Plottr", "https://plottr.com", "小说规划"},
		{"Campfire", "https://www.campfirewriting.com", "世界观构建"},
		{"World Anvil", "https://www.worldanvil.com", "世界设定百科"},
		{"LegendKeeper", "https://www.legendkeeper.com", "世界构建"},
		{"简书", "https://www.jianshu.com", "中文写作平台"},
		{"知乎专栏", "https://zhuanlan.zhihu.com", "知乎写作"},
		{"微信公众号", "https://mp.weixin.qq.com", "公众号写作"},
		{"今日头条号", "https://mp.toutiao.com", "头条创作"},
		{"百家号", "https://baijiahao.baidu.com", "百度创作"},
		{"豆瓣阅读", "https://read.douban.com", "豆瓣写作"},
		{"起点中文网", "https://www.qidian.com", "网络小说"},
		{"晋江文学城", "https://www.jjwxc.net", "女频小说"},
		{"番茄小说", "https://fanqienovel.com", "免费小说"},
		{"飞卢小说", "https://www.faloo.com", "同人小说"},
		{"刺猬猫", "https://www.ciweimao.com", "二次元小说"},
		{"长佩文学", "https://www.changpei.com", "耽美小说"},
		{"Penana", "https://www.penana.com", "社交写作"},
		{"Inkitt", "https://www.inkitt.com", "数据驱动出版"},
		{"Kindle Unlimited", "https://www.amazon.com/kindle-unlimited", "Kindle包月"},
		{"Scribd", "https://www.scribd.com", "电子书订阅"},
		{"Kobo Writing Life", "https://www.kobo.com/writinglife", "Kobo自出版"},
		{"Barnes & Noble Press", "https://press.barnesandnoble.com", "B&N自出版"},
		{"Apple Books Author", "https://www.apple.com/apple-books", "苹果出版"},
		{"Pubby", "https://pubby.co", "图书营销"},
		{"BookSirens", "https://booksirens.com", "图书评论"},
		{"Goodreads", "https://www.goodreads.com", "图书社区"},
		{"BookBub", "https://www.bookbub.com", "图书推广"},
		{"StoryGraph", "https://www.thestorygraph.com", "阅读追踪"},
		{"LibraryThing", "https://www.librarything.com", "图书社区"},
		{"Litsy", "https://www.litsy.com", "图书社交"},
		{"Bookshop.org", "https://bookshop.org", "独立书店"},
	}
}

func podcastEx() []S {
	return []S{
		{"Apple Podcasts", "https://podcasts.apple.com", "苹果播客"},
		{"Spotify Podcasts", "https://podcasters.spotify.com", "Spotify播客"},
		{"Google Podcasts", "https://podcasts.google.com", "谷歌播客"},
		{"Pocket Casts", "https://www.pocketcasts.com", "播客应用"},
		{"Overcast", "https://overcast.fm", "iOS播客应用"},
		{"Castro", "https://castro.fm", "播客应用"},
		{"Podcast Addict", "https://podcastaddict.com", "安卓播客"},
		{"AntennaPod", "https://antennapod.org", "开源播客"},
		{"Podbean", "https://www.podbean.com", "播客托管"},
		{"Buzzsprout", "https://www.buzzsprout.com", "播客托管"},
		{"Anchor", "https://anchor.fm", "免费播客托管"},
		{"Transistor", "https://transistor.fm", "播客托管"},
		{"Simplecast", "https://www.simplecast.com", "播客托管"},
		{"Captivate", "https://www.captivate.fm", "播客增长"},
		{"RSS.com", "https://rss.com", "播客托管"},
		{"Spreaker", "https://www.spreaker.com", "播客创作"},
		{"Acast", "https://www.acast.com", "播客分发"},
		{"Megaphone", "https://www.megaphone.fm", "企业播客"},
		{"Libsyn", "https://libsyn.com", "播客托管"},
		{"Blubrry", "https://blubrry.com", "WordPress播客"},
		{"Castos", "https://castos.com", "播客托管"},
		{"RedCircle", "https://redcircle.com", "播客平台"},
		{"Descript", "https://www.descript.com", "音视频编辑"},
		{"Riverside.fm", "https://riverside.fm", "远程录制"},
		{"Zencastr", "https://zencastr.com", "远程录音"},
		{"SquadCast", "https://squadcast.fm", "远程录制"},
		{"Cleanfeed", "https://cleanfeed.net", "在线录音"},
		{"Hindenburg", "https://hindenburg.com", "播客编辑"},
		{"Adobe Podcast", "https://podcast.adobe.com", "AI音频编辑"},
		{"Auphonic", "https://auphonic.com", "自动音频处理"},
		{"Alitu", "https://alitu.com", "播客制作工具"},
		{"Headliner", "https://www.headliner.app", "播客视频片段"},
		{"Wavve", "https://wavve.co", "音频转视频"},
		{"Audiogram", "https://audiogram.sparemin.com", "音频可视化"},
		{"Podcastle", "https://podcastle.ai", "AI播客工具"},
		{"Listen Notes", "https://www.listennotes.com", "播客搜索引擎"},
		{"Podchaser", "https://www.podchaser.com", "播客数据库"},
		{"Podcast Index", "https://podcastindex.org", "播客目录"},
		{"Chartable", "https://chartable.com", "播客分析"},
		{"Podtrac", "https://analytics.podtrac.com", "播客统计"},
		{"RadioPublic", "https://radiopublic.com", "播客发现"},
		{"Goodpods", "https://goodpods.com", "播客社交"},
		{"Podyssey", "https://podyssey.fm", "播客推荐"},
		{"PlayerFM", "https://player.fm", "播客发现"},
		{"TuneIn", "https://tunein.com", "网络电台"},
		{"iHeartRadio", "https://www.iheart.com", "广播播客"},
		{"Stitcher", "https://www.stitcher.com", "播客平台"},
		{"Luminary", "https://luminarypodcasts.com", "付费播客"},
		{"Wondery", "https://wondery.com", "播客工作室"},
		{"Gimlet", "https://gimletmedia.com", "播客工作室"},
		{"The Ringer Podcasts", "https://www.theringer.com/podcasts", "Ringer播客"},
		{"NPR Podcasts", "https://www.npr.org/podcasts", "NPR播客"},
		{"BBC Sounds", "https://www.bbc.co.uk/sounds", "BBC音频"},
		{"Podcast Republic", "https://www.podcastrepublic.net", "播客应用"},
		{"PodNova", "https://www.podnova.com", "播客目录"},
		{"Podcast.co", "https://www.podcast.co", "播客目录"},
		{"Himalaya", "https://www.himalaya.com", "喜马拉雅国际"},
		{"喜马拉雅", "https://www.ximalaya.com", "中国音频平台"},
		{"蜻蜓FM", "https://www.qingting.fm", "中国音频"},
		{"荔枝FM", "https://www.lizhi.fm", "中国播客"},
		{"小宇宙", "https://www.xiaoyuzhoufm.com", "中国播客应用"},
		{"皮艇", "https://www.piyingtv.com", "中国播客"},
		{"得到", "https://www.igetget.com", "知识付费"},
		{"樊登读书", "https://www.dushu365.com", "读书会"},
		{"看理想", "https://www.vistopia.com.cn", "文化播客"},
		{"三联中读", "https://www.lifeweek.com.cn", "三联内容"},
		{"PodLink", "https://pod.link", "播客链接工具"},
		{"Podpage", "https://www.podpage.com", "播客网站"},
		{"Podsite", "https://podsite.com", "播客网站生成"},
		{"Canva Podcast", "https://www.canva.com/podcast-covers", "播客封面设计"},
		{"Spotify for Podcasters", "https://podcasters.spotify.com", "播客管理"},
		{"SoundCloud", "https://soundcloud.com", "音频分享"},
		{"Mixcloud", "https://www.mixcloud.com", "DJ混音"},
		{"Audioboom", "https://audioboom.com", "播客广告"},
		{"AdvertiseCast", "https://www.advertisecast.com", "播客广告"},
		{"Podcorn", "https://podcorn.com", "播客赞助"},
		{"Patreon Podcasts", "https://www.patreon.com/podcasts", "播客订阅"},
		{"Supercast", "https://www.supercast.com", "付费播客"},
		{"Supporting Cast", "https://www.supportingcast.fm", "付费播客"},
		{"Glow.fm", "https://www.glow.fm", "播客会员"},
		{"Memberful Podcasts", "https://memberful.com/podcasts", "播客会员"},
		{"Fireside", "https://fireside.fm", "播客托管"},
		{"Whooshkaa", "https://www.whooshkaa.com", "播客平台"},
		{"Omny Studio", "https://omnystudio.com", "播客托管"},
		{"Audiomack", "https://audiomack.com", "音乐播客"},
		{"Castbox", "https://castbox.fm", "播客应用"},
		{"Podcast Guru", "https://podcastguru.io", "播客应用"},
		{"CastMix", "https://castmix.com", "播客应用"},
		{"Moon FM", "https://moon.fm", "播客应用"},
		{"Snipd", "https://www.snipd.com", "AI播客笔记"},
		{"Airr", "https://www.airr.io", "播客高亮"},
		{"Otter for Podcasts", "https://otter.ai", "播客转录"},
		{"Happy Scribe", "https://www.happyscribe.com", "音频转文字"},
		{"Rev Transcription", "https://www.rev.com", "转录服务"},
		{"Trint", "https://trint.com", "AI转录"},
		{"Sonix", "https://sonix.ai", "自动转录"},
		{"Whisper API", "https://openai.com/research/whisper", "OpenAI语音"},
		{"Podscribe", "https://podscribe.com", "播客分析"},
		{"Magellan AI", "https://www.magellan.ai", "播客广告分析"},
		{"Backtracks", "https://backtracks.fm", "播客分析"},
		{"Voxalyze", "https://voxalyze.com", "播客分析"},
		{"Podsights", "https://podsights.com", "播客归因"},
		{"Barometer", "https://barometerpodcasts.com", "播客统计"},
		{"Op3", "https://op3.dev", "开源播客统计"},
		{"ElevenLabs", "https://elevenlabs.io", "AI语音合成"},
		{"WellSaid Labs", "https://www.wellsaidlabs.com", "AI配音"},
		{"Murf AI", "https://murf.ai", "AI配音"},
		{"Play.ht", "https://play.ht", "AI语音"},
		{"Resemble AI", "https://www.resemble.ai", "AI语音克隆"},
		{"Podimo", "https://podimo.com", "付费播客平台"},
	}
}
