package main

func searchEngine() []S {
	return []S{
		{"Google", "https://www.google.com", "全球最大搜索引擎"},
		{"Bing", "https://www.bing.com", "微软搜索引擎"},
		{"DuckDuckGo", "https://duckduckgo.com", "隐私搜索引擎"},
		{"Yahoo", "https://www.yahoo.com", "雅虎搜索"},
		{"百度", "https://www.baidu.com", "中国最大搜索引擎"},
		{"搜狗", "https://www.sogou.com", "搜狗搜索"},
		{"360搜索", "https://www.so.com", "360搜索引擎"},
		{"神马搜索", "https://m.sm.cn", "UC神马移动搜索"},
		{"头条搜索", "https://so.toutiao.com", "字节头条搜索"},
		{"Yandex", "https://yandex.com", "俄罗斯搜索引擎"},
		{"Naver", "https://www.naver.com", "韩国最大搜索引擎"},
		{"Daum", "https://www.daum.net", "韩国搜索门户"},
		{"Yahoo Japan", "https://www.yahoo.co.jp", "日本雅虎搜索"},
		{"Ecosia", "https://www.ecosia.org", "环保搜索引擎"},
		{"Brave Search", "https://search.brave.com", "Brave隐私搜索"},
		{"Startpage", "https://www.startpage.com", "隐私Google代理搜索"},
		{"Qwant", "https://www.qwant.com", "法国隐私搜索"},
		{"SearXNG", "https://searx.space", "开源元搜索引擎"},
		{"Mojeek", "https://www.mojeek.com", "英国独立搜索"},
		{"Kagi", "https://kagi.com", "付费无广告搜索"},
		{"You.com", "https://you.com", "AI搜索引擎"},
		{"Phind", "https://www.phind.com", "开发者AI搜索"},
		{"Wolfram Alpha", "https://www.wolframalpha.com", "计算知识引擎"},
		{"Ask.com", "https://www.ask.com", "问答搜索引擎"},
		{"Dogpile", "https://www.dogpile.com", "元搜索引擎"},
		{"Swisscows", "https://swisscows.com", "瑞士隐私搜索"},
		{"Metager", "https://metager.org", "德国元搜索引擎"},
		{"Baidu Scholar", "https://xueshu.baidu.com", "百度学术搜索"},
		{"Google Scholar", "https://scholar.google.com", "Google学术搜索"},
		{"BASE", "https://www.base-search.net", "学术搜索引擎"},
		{"Shodan", "https://www.shodan.io", "IoT搜索引擎"},
		{"Censys", "https://search.censys.io", "互联网设备搜索"},
		{"ZoomEye", "https://www.zoomeye.org", "网络空间搜索"},
		{"FOFA", "https://fofa.info", "网络资产搜索"},
		{"Google Images", "https://images.google.com", "Google图片搜索"},
		{"TinEye", "https://tineye.com", "反向图片搜索"},
		{"Google Trends", "https://trends.google.com", "搜索趋势分析"},
		{"百度指数", "https://index.baidu.com", "百度搜索趋势"},
		{"微信搜一搜", "https://weixin.sogou.com", "微信公众号搜索"},
		{"多吉搜索", "https://www.dogedoge.com", "中国隐私搜索"},
		{"Andi", "https://andisearch.com", "AI对话搜索"},
		{"Exa", "https://exa.ai", "AI语义搜索"},
		{"SimilarWeb", "https://www.similarweb.com", "网站流量分析"},
		{"BuiltWith", "https://builtwith.com", "网站技术栈搜索"},
		{"Sourcegraph", "https://sourcegraph.com", "代码搜索引擎"},
		{"grep.app", "https://grep.app", "Git仓库代码搜索"},
		{"SearchCode", "https://searchcode.com", "代码搜索引擎"},
		{"Presearch", "https://presearch.io", "去中心化搜索"},
		{"Yacy", "https://yacy.net", "P2P搜索引擎"},
		{"Marginalia", "https://search.marginalia.nu", "非商业网页搜索"},
		{"CC Search", "https://search.creativecommons.org", "CC许可搜索"},
		{"Openverse", "https://openverse.org", "开放版权媒体搜索"},
	}
}

func email() []S {
	return []S{
		{"Gmail", "https://mail.google.com", "Google邮箱"},
		{"Outlook", "https://outlook.live.com", "微软邮箱"},
		{"Yahoo Mail", "https://mail.yahoo.com", "雅虎邮箱"},
		{"iCloud Mail", "https://www.icloud.com/mail", "Apple邮箱"},
		{"ProtonMail", "https://proton.me/mail", "端到端加密邮箱"},
		{"Tutanota", "https://tutanota.com", "加密邮箱"},
		{"Zoho Mail", "https://mail.zoho.com", "Zoho企业邮箱"},
		{"Fastmail", "https://www.fastmail.com", "付费隐私邮箱"},
		{"Mailbox.org", "https://mailbox.org", "德国隐私邮箱"},
		{"Posteo", "https://posteo.de", "绿色环保邮箱"},
		{"QQ邮箱", "https://mail.qq.com", "腾讯QQ邮箱"},
		{"网易邮箱", "https://mail.163.com", "网易163邮箱"},
		{"新浪邮箱", "https://mail.sina.com.cn", "新浪免费邮箱"},
		{"139邮箱", "https://mail.10086.cn", "中国移动邮箱"},
		{"189邮箱", "https://mail.189.cn", "中国电信邮箱"},
		{"阿里邮箱", "https://mail.aliyun.com", "阿里云邮箱"},
		{"腾讯企业邮箱", "https://exmail.qq.com", "腾讯企业邮箱"},
		{"126邮箱", "https://mail.126.com", "网易126邮箱"},
		{"GMX Mail", "https://www.gmx.com", "GMX免费邮箱"},
		{"Mail.com", "https://www.mail.com", "免费邮箱服务"},
		{"AOL Mail", "https://mail.aol.com", "AOL邮箱"},
		{"Yandex Mail", "https://mail.yandex.com", "Yandex邮箱"},
		{"Mail.ru", "https://mail.ru", "俄罗斯邮箱"},
		{"Naver Mail", "https://mail.naver.com", "韩国Naver邮箱"},
		{"Mailchimp", "https://mailchimp.com", "邮件营销平台"},
		{"Brevo", "https://www.brevo.com", "邮件营销服务"},
		{"ConvertKit", "https://convertkit.com", "创作者邮件营销"},
		{"Buttondown", "https://buttondown.email", "简洁Newsletter"},
		{"Beehiiv", "https://www.beehiiv.com", "Newsletter平台"},
		{"Constant Contact", "https://www.constantcontact.com", "邮件营销"},
		{"AWeber", "https://www.aweber.com", "邮件自动化"},
		{"GetResponse", "https://www.getresponse.com", "邮件营销"},
		{"ActiveCampaign", "https://www.activecampaign.com", "营销自动化"},
		{"Mailgun", "https://www.mailgun.com", "邮件API服务"},
		{"SendGrid", "https://sendgrid.com", "邮件递送服务"},
		{"Amazon SES", "https://aws.amazon.com/ses", "AWS邮件服务"},
		{"Postmark", "https://postmarkapp.com", "事务邮件服务"},
		{"SparkPost", "https://www.sparkpost.com", "邮件递送"},
		{"Resend", "https://resend.com", "现代邮件API"},
		{"Mailtrap", "https://mailtrap.io", "邮件测试平台"},
		{"Temp Mail", "https://temp-mail.org", "临时邮箱"},
		{"Guerrilla Mail", "https://www.guerrillamail.com", "一次性邮箱"},
		{"Mailfence", "https://mailfence.com", "安全邮箱服务"},
		{"Thunderbird", "https://www.thunderbird.net", "开源邮件客户端"},
		{"Spark", "https://sparkmailapp.com", "智能邮件客户端"},
		{"Airmail", "https://airmailapp.com", "macOS邮件客户端"},
		{"Edison Mail", "https://mail.edison.tech", "AI邮件助手"},
		{"Hey", "https://www.hey.com", "Basecamp邮箱"},
		{"Superhuman", "https://superhuman.com", "极速邮件客户端"},
		{"Missive", "https://missiveapp.com", "团队邮箱协作"},
		{"Front", "https://front.com", "共享收件箱平台"},
	}
}

func finance() []S {
	return []S{
		{"Yahoo Finance", "https://finance.yahoo.com", "雅虎财经"},
		{"Bloomberg", "https://www.bloomberg.com", "彭博社财经"},
		{"Investing.com", "https://www.investing.com", "全球金融数据"},
		{"MarketWatch", "https://www.marketwatch.com", "市场观察"},
		{"CNBC", "https://www.cnbc.com", "CNBC财经频道"},
		{"Seeking Alpha", "https://seekingalpha.com", "投资分析平台"},
		{"TradingView", "https://www.tradingview.com", "图表与交易分析"},
		{"Robinhood", "https://robinhood.com", "免佣金交易"},
		{"E*TRADE", "https://www.etrade.com", "在线券商"},
		{"Charles Schwab", "https://www.schwab.com", "嘉信理财"},
		{"Fidelity", "https://www.fidelity.com", "富达投资"},
		{"Vanguard", "https://investor.vanguard.com", "先锋集团"},
		{"Interactive Brokers", "https://www.interactivebrokers.com", "盈透证券"},
		{"TD Ameritrade", "https://www.tdameritrade.com", "德美利证券"},
		{"Webull", "https://www.webull.com", "微牛证券"},
		{"Coinbase", "https://www.coinbase.com", "加密货币交易所"},
		{"Binance", "https://www.binance.com", "全球加密货币交易"},
		{"Kraken", "https://www.kraken.com", "加密货币交易"},
		{"PayPal", "https://www.paypal.com", "全球在线支付"},
		{"Stripe", "https://stripe.com", "在线支付API"},
		{"Square", "https://squareup.com", "移动支付"},
		{"Venmo", "https://venmo.com", "社交支付"},
		{"Wise", "https://wise.com", "国际汇款"},
		{"Revolut", "https://www.revolut.com", "数字银行"},
		{"N26", "https://n26.com", "欧洲数字银行"},
		{"Chime", "https://www.chime.com", "美国数字银行"},
		{"NerdWallet", "https://www.nerdwallet.com", "理财建议平台"},
		{"Mint", "https://mint.intuit.com", "个人财务管理"},
		{"YNAB", "https://www.ynab.com", "预算管理工具"},
		{"Personal Capital", "https://www.personalcapital.com", "财富管理"},
		{"Credit Karma", "https://www.creditkarma.com", "信用评分查询"},
		{"Morningstar", "https://www.morningstar.com", "投资研究"},
		{"Motley Fool", "https://www.fool.com", "投资建议"},
		{"Bankrate", "https://www.bankrate.com", "金融利率比较"},
		{"东方财富", "https://www.eastmoney.com", "东方财富网"},
		{"同花顺", "https://www.10jqka.com.cn", "同花顺财经"},
		{"雪球", "https://xueqiu.com", "投资者社区"},
		{"新浪财经", "https://finance.sina.com.cn", "新浪财经"},
		{"腾讯财经", "https://finance.qq.com", "腾讯财经频道"},
		{"网易财经", "https://money.163.com", "网易财经"},
		{"华尔街见闻", "https://wallstreetcn.com", "全球财经资讯"},
		{"第一财经", "https://www.yicai.com", "第一财经"},
		{"财新网", "https://www.caixin.com", "财新传媒"},
		{"Wind金融终端", "https://www.wind.com.cn", "万得金融数据"},
		{"Choice金融终端", "https://choice.eastmoney.com", "东方财富终端"},
		{"大智慧", "https://www.gw.com.cn", "大智慧金融"},
		{"蚂蚁财富", "https://www.antfortune.com", "蚂蚁基金销售"},
		{"天天基金", "https://fund.eastmoney.com", "天天基金网"},
		{"支付宝", "https://www.alipay.com", "蚂蚁集团支付"},
		{"微信支付", "https://pay.weixin.qq.com", "微信支付"},
		{"京东金融", "https://jr.jd.com", "京东数科"},
		{"陆金所", "https://www.lu.com", "陆金所理财"},
		{"富途证券", "https://www.futunn.com", "港美股券商"},
		{"老虎证券", "https://www.itigerup.com", "互联网券商"},
		{"雪盈证券", "https://www.snowballsecurities.com", "雪球旗下券商"},
		{"中信证券", "https://www.cs.ecitic.com", "中信证券"},
		{"华泰证券", "https://www.htsc.com.cn", "华泰证券"},
		{"广发证券", "https://www.gf.com.cn", "广发证券"},
		{"招商银行", "https://www.cmbchina.com", "招商银行"},
		{"工商银行", "https://www.icbc.com.cn", "工商银行"},
		{"建设银行", "https://www.ccb.com", "建设银行"},
		{"XE", "https://www.xe.com", "汇率换算"},
		{"OANDA", "https://www.oanda.com", "外汇交易"},
		{"Forex.com", "https://www.forex.com", "外汇经纪商"},
	}
}

func education() []S {
	return []S{
		{"Coursera", "https://www.coursera.org", "在线教育平台"},
		{"edX", "https://www.edx.org", "MIT在线教育"},
		{"Udemy", "https://www.udemy.com", "在线课程市场"},
		{"Khan Academy", "https://www.khanacademy.org", "免费教育平台"},
		{"Skillshare", "https://www.skillshare.com", "创意技能学习"},
		{"LinkedIn Learning", "https://www.linkedin.com/learning", "职业技能学习"},
		{"Pluralsight", "https://www.pluralsight.com", "技术学习平台"},
		{"MasterClass", "https://www.masterclass.com", "名人授课平台"},
		{"Brilliant", "https://brilliant.org", "数学科学交互学习"},
		{"Duolingo", "https://www.duolingo.com", "免费语言学习"},
		{"Busuu", "https://www.busuu.com", "语言学习社区"},
		{"Babbel", "https://www.babbel.com", "语言学习应用"},
		{"Rosetta Stone", "https://www.rosettastone.com", "语言学习软件"},
		{"italki", "https://www.italki.com", "外教一对一"},
		{"Preply", "https://preply.com", "在线家教平台"},
		{"Chegg", "https://www.chegg.com", "学生学习助手"},
		{"Quizlet", "https://quizlet.com", "闪卡学习工具"},
		{"Anki", "https://apps.ankiweb.net", "间隔重复记忆"},
		{"Notion", "https://www.notion.so", "知识管理笔记"},
		{"Grammarly", "https://www.grammarly.com", "英语语法检查"},
		{"MIT OpenCourseWare", "https://ocw.mit.edu", "MIT开放课程"},
		{"Stanford Online", "https://online.stanford.edu", "斯坦福在线"},
		{"Harvard Online", "https://www.harvardonline.harvard.edu", "哈佛在线课程"},
		{"Yale Open Courses", "https://oyc.yale.edu", "耶鲁公开课"},
		{"Open Yale Courses", "https://oyc.yale.edu", "耶鲁开放课程"},
		{"FutureLearn", "https://www.futurelearn.com", "英国在线学习"},
		{"Alison", "https://alison.com", "免费在线课程"},
		{"OpenLearn", "https://www.open.edu/openlearn", "英国开放大学"},
		{"Class Central", "https://www.classcentral.com", "MOOC课程搜索"},
		{"Udacity", "https://www.udacity.com", "技术纳米学位"},
		{"DataCamp", "https://www.datacamp.com", "数据科学学习"},
		{"Codecademy", "https://www.codecademy.com", "交互式编程学习"},
		{"freeCodeCamp", "https://www.freecodecamp.org", "免费编程学习"},
		{"The Odin Project", "https://www.theodinproject.com", "全栈开发课程"},
		{"Scrimba", "https://scrimba.com", "交互式前端课程"},
		{"Egghead", "https://egghead.io", "Web开发视频教程"},
		{"Frontend Masters", "https://frontendmasters.com", "前端进阶课程"},
		{"Educative", "https://www.educative.io", "交互式编程课程"},
		{"中国大学MOOC", "https://www.icourse163.org", "中国MOOC平台"},
		{"学堂在线", "https://www.xuetangx.com", "清华在线教育"},
		{"网易公开课", "https://open.163.com", "网易公开课"},
		{"腾讯课堂", "https://ke.qq.com", "腾讯在线课堂"},
		{"慕课网", "https://www.imooc.com", "IT技能学习"},
		{"极客时间", "https://time.geekbang.org", "技术人学习"},
		{"得到", "https://www.dedao.cn", "得到知识平台"},
		{"喜马拉雅", "https://www.ximalaya.com", "有声内容平台"},
		{"混沌学园", "https://www.hundun.cn", "创新学习平台"},
		{"万门大学", "https://www.wanmen.org", "综合在线教育"},
		{"VIPKID", "https://www.vipkid.com", "少儿英语在线"},
		{"作业帮", "https://www.zybang.com", "在线学习辅导"},
		{"猿辅导", "https://www.yuanfudao.com", "在线教育辅导"},
		{"学而思", "https://www.xueersi.com", "好未来教育"},
		{"新东方在线", "https://www.koolearn.com", "新东方在线教育"},
		{"沪江网校", "https://www.hujiang.com", "沪江语言学习"},
		{"TED", "https://www.ted.com", "TED演讲"},
		{"TED-Ed", "https://ed.ted.com", "TED教育频道"},
		{"CK-12", "https://www.ck12.org", "免费教科书"},
		{"OpenStax", "https://openstax.org", "免费大学教材"},
		{"Saylor Academy", "https://www.saylor.org", "免费在线课程"},
		{"Academic Earth", "https://academicearth.org", "大学课程聚合"},
		{"JSTOR", "https://www.jstor.org", "学术期刊数据库"},
		{"ResearchGate", "https://www.researchgate.net", "学术社交网络"},
		{"Academia.edu", "https://www.academia.edu", "学术论文分享"},
		{"Google Classroom", "https://classroom.google.com", "Google课堂"},
		{"Canvas LMS", "https://www.instructure.com", "学习管理系统"},
		{"Moodle", "https://moodle.org", "开源学习平台"},
		{"Blackboard", "https://www.blackboard.com", "教育管理系统"},
		{"Kahoot!", "https://kahoot.com", "互动学习游戏"},
		{"Nearpod", "https://nearpod.com", "互动课堂工具"},
		{"Wolfram Alpha", "https://www.wolframalpha.com", "计算知识引擎"},
		{"Symbolab", "https://www.symbolab.com", "数学求解器"},
		{"Mathway", "https://www.mathway.com", "数学问题求解"},
		{"Photomath", "https://photomath.com", "拍照解数学题"},
		{"GeoGebra", "https://www.geogebra.org", "数学可视化工具"},
		{"Desmos", "https://www.desmos.com", "在线图形计算器"},
	}
}

func travel() []S {
	return []S{
		{"Booking.com", "https://www.booking.com", "全球酒店预订"},
		{"Airbnb", "https://www.airbnb.com", "民宿短租平台"},
		{"Expedia", "https://www.expedia.com", "旅行综合预订"},
		{"TripAdvisor", "https://www.tripadvisor.com", "旅行点评平台"},
		{"Kayak", "https://www.kayak.com", "机票酒店比价"},
		{"Skyscanner", "https://www.skyscanner.com", "机票搜索比价"},
		{"Google Flights", "https://www.google.com/travel/flights", "Google航班搜索"},
		{"Agoda", "https://www.agoda.com", "亚洲酒店预订"},
		{"Hotels.com", "https://www.hotels.com", "酒店预订平台"},
		{"Trivago", "https://www.trivago.com", "酒店比价搜索"},
		{"Hostelworld", "https://www.hostelworld.com", "青年旅社预订"},
		{"Vrbo", "https://www.vrbo.com", "度假屋租赁"},
		{"Priceline", "https://www.priceline.com", "旅行折扣预订"},
		{"Hopper", "https://www.hopper.com", "AI预测机票价格"},
		{"Momondo", "https://www.momondo.com", "机票比价搜索"},
		{"Kiwi.com", "https://www.kiwi.com", "航班搜索"},
		{"Rome2Rio", "https://www.rome2rio.com", "全球交通路线"},
		{"Lonely Planet", "https://www.lonelyplanet.com", "旅行指南"},
		{"Wikitravel", "https://wikitravel.org", "旅行维基"},
		{"Wikivoyage", "https://www.wikivoyage.org", "维基旅行指南"},
		{"Atlas Obscura", "https://www.atlasobscura.com", "探索奇妙世界"},
		{"Roadtrippers", "https://roadtrippers.com", "自驾旅行规划"},
		{"AllTrails", "https://www.alltrails.com", "户外徒步路线"},
		{"Google Maps", "https://maps.google.com", "Google地图"},
		{"携程", "https://www.ctrip.com", "携程旅行"},
		{"去哪儿", "https://www.qunar.com", "去哪儿旅行"},
		{"飞猪", "https://www.fliggy.com", "阿里旅行"},
		{"马蜂窝", "https://www.mafengwo.cn", "旅游攻略社区"},
		{"途牛", "https://www.tuniu.com", "途牛旅游"},
		{"同程旅行", "https://www.ly.com", "同程旅行"},
		{"美团旅行", "https://hotel.meituan.com", "美团酒店旅行"},
		{"大众点评旅行", "https://www.dianping.com/travel", "旅行点评"},
		{"穷游网", "https://www.qyer.com", "出境游攻略"},
		{"驴妈妈", "https://www.lvmama.com", "景区门票预订"},
		{"春秋航空", "https://www.ch.com", "春秋航空官网"},
		{"中国国航", "https://www.airchina.com.cn", "国航官网"},
		{"东方航空", "https://www.ceair.com", "东航官网"},
		{"南方航空", "https://www.csair.com", "南航官网"},
		{"海南航空", "https://www.hnair.com", "海南航空"},
		{"12306", "https://www.12306.cn", "中国铁路购票"},
		{"智行火车票", "https://www.zxhcp.com", "火车票预订"},
		{"高铁管家", "https://www.gaotie.cn", "高铁出行服务"},
		{"滴滴出行", "https://www.didiglobal.com", "网约车平台"},
		{"曹操出行", "https://www.caocaokeji.cn", "网约车出行"},
		{"嘀嗒出行", "https://www.didachuxing.com", "顺风车出行"},
		{"哈啰出行", "https://www.hellobike.com", "共享单车出行"},
		{"Uber", "https://www.uber.com", "全球网约车"},
		{"Lyft", "https://www.lyft.com", "美国网约车"},
		{"Grab", "https://www.grab.com", "东南亚出行"},
		{"Flixbus", "https://www.flixbus.com", "欧洲巴士旅行"},
		{"Trainline", "https://www.thetrainline.com", "欧洲火车票"},
		{"Japan Rail Pass", "https://www.japanrailpass.net", "日本铁路通票"},
		{"Flightradar24", "https://www.flightradar24.com", "航班实时追踪"},
		{"FlightAware", "https://flightaware.com", "航班追踪"},
		{"SeatGuru", "https://www.seatguru.com", "飞机座位指南"},
		{"Nomad List", "https://nomadlist.com", "数字游民城市排名"},
	}
}

func food() []S {
	return []S{
		{"美团外卖", "https://waimai.meituan.com", "美团外卖平台"},
		{"饿了么", "https://www.ele.me", "饿了么外卖"},
		{"大众点评", "https://www.dianping.com", "餐饮点评平台"},
		{"下厨房", "https://www.xiachufang.com", "美食菜谱社区"},
		{"豆果美食", "https://www.douguo.com", "美食菜谱分享"},
		{"美食杰", "https://www.meishij.net", "美食菜谱大全"},
		{"香哈菜谱", "https://www.xiangha.com", "菜谱大全"},
		{"日食记", "https://www.rishiji.com", "美食短视频"},
		{"叮咚买菜", "https://www.100.me", "生鲜配送"},
		{"盒马", "https://www.freshhema.com", "新零售超市"},
		{"每日优鲜", "https://www.missfresh.cn", "生鲜电商"},
		{"朴朴超市", "https://www.pupumall.com", "即时配送超市"},
		{"京东到家", "https://www.jddj.com", "即时零售"},
		{"多点", "https://www.dmall.com", "社区零售"},
		{"瑞幸咖啡", "https://www.luckincoffee.com", "瑞幸咖啡"},
		{"星巴克中国", "https://www.starbucks.com.cn", "星巴克中国"},
		{"麦当劳中国", "https://www.mcdonalds.com.cn", "麦当劳中国"},
		{"肯德基", "https://www.kfc.com.cn", "KFC中国"},
		{"必胜客", "https://www.pizzahut.com.cn", "必胜客中国"},
		{"海底捞", "https://www.haidilao.com", "海底捞火锅"},
		{"Yelp", "https://www.yelp.com", "商户点评平台"},
		{"DoorDash", "https://www.doordash.com", "美国外卖平台"},
		{"Uber Eats", "https://www.ubereats.com", "Uber外卖"},
		{"Grubhub", "https://www.grubhub.com", "美国外卖"},
		{"Just Eat", "https://www.just-eat.com", "欧洲外卖平台"},
		{"Deliveroo", "https://deliveroo.com", "英国外卖"},
		{"Foodpanda", "https://www.foodpanda.com", "亚洲外卖"},
		{"Zomato", "https://www.zomato.com", "印度外卖点评"},
		{"Swiggy", "https://www.swiggy.com", "印度外卖平台"},
		{"Allrecipes", "https://www.allrecipes.com", "全球菜谱网站"},
		{"Food Network", "https://www.foodnetwork.com", "美食电视频道"},
		{"Bon Appetit", "https://www.bonappetit.com", "美食杂志"},
		{"Epicurious", "https://www.epicurious.com", "菜谱与美食"},
		{"Serious Eats", "https://www.seriouseats.com", "深度美食指南"},
		{"Tasty", "https://tasty.co", "Buzzfeed美食"},
		{"BBC Good Food", "https://www.bbcgoodfood.com", "BBC美食菜谱"},
		{"Cookpad", "https://cookpad.com", "全球菜谱分享"},
		{"Yummly", "https://www.yummly.com", "智能菜谱推荐"},
		{"Delish", "https://www.delish.com", "美食内容"},
		{"Food52", "https://food52.com", "美食社区与商店"},
		{"Michelin Guide", "https://guide.michelin.com", "米其林餐厅指南"},
		{"OpenTable", "https://www.opentable.com", "餐厅预订"},
		{"Resy", "https://resy.com", "高端餐厅预订"},
		{"TheFork", "https://www.thefork.com", "欧洲餐厅预订"},
		{"Tabelog", "https://tabelog.com", "日本餐厅评价"},
		{"Gurunavi", "https://www.gnavi.co.jp", "日本美食指南"},
		{"HotPepper", "https://www.hotpepper.jp", "日本餐厅搜索"},
		{"Instacart", "https://www.instacart.com", "美国生鲜配送"},
		{"HelloFresh", "https://www.hellofresh.com", "预制食材配送"},
		{"Blue Apron", "https://www.blueapron.com", "食材配送"},
		{"Nosh", "https://www.nosh.me", "健康餐配送"},
	}
}

func health() []S {
	return []S{
		{"WebMD", "https://www.webmd.com", "健康医疗信息"},
		{"Mayo Clinic", "https://www.mayoclinic.org", "梅奥诊所"},
		{"Healthline", "https://www.healthline.com", "健康资讯"},
		{"MedlinePlus", "https://medlineplus.gov", "美国医学图书馆"},
		{"NHS", "https://www.nhs.uk", "英国国民医疗"},
		{"Cleveland Clinic", "https://my.clevelandclinic.org", "克利夫兰诊所"},
		{"Johns Hopkins Medicine", "https://www.hopkinsmedicine.org", "约翰霍普金斯医学"},
		{"WHO", "https://www.who.int", "世界卫生组织"},
		{"CDC", "https://www.cdc.gov", "美国疾控中心"},
		{"PubMed", "https://pubmed.ncbi.nlm.nih.gov", "医学文献数据库"},
		{"UpToDate", "https://www.uptodate.com", "临床决策支持"},
		{"Drugs.com", "https://www.drugs.com", "药物信息查询"},
		{"RxList", "https://www.rxlist.com", "处方药信息"},
		{"GoodRx", "https://www.goodrx.com", "药品价格比较"},
		{"Zocdoc", "https://www.zocdoc.com", "在线预约医生"},
		{"Teladoc", "https://www.teladoc.com", "远程医疗平台"},
		{"Amwell", "https://www.amwell.com", "远程问诊"},
		{"MDLive", "https://www.mdlive.com", "在线看诊"},
		{"One Medical", "https://www.onemedical.com", "会员制医疗"},
		{"MyFitnessPal", "https://www.myfitnesspal.com", "卡路里追踪"},
		{"Noom", "https://www.noom.com", "健康减重"},
		{"Fitbit", "https://www.fitbit.com", "健康追踪设备"},
		{"Apple Health", "https://www.apple.com/health", "Apple健康"},
		{"Samsung Health", "https://www.samsung.com/us/apps/samsung-health", "三星健康"},
		{"Strava", "https://www.strava.com", "跑步骑行追踪"},
		{"Nike Training Club", "https://www.nike.com/ntc-app", "Nike健身"},
		{"Peloton", "https://www.onepeloton.com", "居家健身"},
		{"Calm", "https://www.calm.com", "冥想放松应用"},
		{"Headspace", "https://www.headspace.com", "冥想引导"},
		{"BetterHelp", "https://www.betterhelp.com", "在线心理咨询"},
		{"Talkspace", "https://www.talkspace.com", "在线心理治疗"},
		{"Psychology Today", "https://www.psychologytoday.com", "心理健康资源"},
		{"丁香园", "https://www.dxy.cn", "中国医疗专业社区"},
		{"丁香医生", "https://dxy.com", "健康科普平台"},
		{"好大夫在线", "https://www.haodf.com", "在线问诊平台"},
		{"微医", "https://www.wedoctor.com", "互联网医疗"},
		{"春雨医生", "https://www.chunyuyisheng.com", "在线问诊"},
		{"平安好医生", "https://www.jk.cn", "平安健康"},
		{"阿里健康", "https://www.alihealth.cn", "阿里健康"},
		{"京东健康", "https://health.jd.com", "京东健康"},
		{"美柚", "https://www.meiyou.com", "女性健康经期管理"},
		{"薄荷健康", "https://www.boohee.com", "热量查询减肥"},
		{"Keep", "https://www.gotokeep.com", "运动健身平台"},
		{"悦跑圈", "https://www.thejoyrun.com", "跑步社交"},
		{"咕咚", "https://www.codoon.com", "运动社交平台"},
		{"小荷健康", "https://www.xiaohehealth.com", "字节健康科普"},
		{"医学界", "https://www.yxj.org.cn", "医学专业资讯"},
		{"梅斯医学", "https://www.medsci.cn", "医学研究平台"},
		{"Examine.com", "https://examine.com", "营养补剂研究"},
		{"Labdoor", "https://labdoor.com", "补剂质量评测"},
		{"Cronometer", "https://cronometer.com", "营养追踪"},
	}
}

func sports() []S {
	return []S{
		{"ESPN", "https://www.espn.com", "美国体育媒体"},
		{"BBC Sport", "https://www.bbc.com/sport", "BBC体育"},
		{"Sky Sports", "https://www.skysports.com", "天空体育"},
		{"Yahoo Sports", "https://sports.yahoo.com", "雅虎体育"},
		{"CBS Sports", "https://www.cbssports.com", "CBS体育"},
		{"Bleacher Report", "https://bleacherreport.com", "体育新闻社区"},
		{"The Athletic", "https://theathletic.com", "深度体育报道"},
		{"Sports Illustrated", "https://www.si.com", "体育画报"},
		{"FIFA", "https://www.fifa.com", "国际足联"},
		{"UEFA", "https://www.uefa.com", "欧洲足联"},
		{"NBA", "https://www.nba.com", "美国职业篮球"},
		{"NFL", "https://www.nfl.com", "美国职业橄榄球"},
		{"MLB", "https://www.mlb.com", "美国职业棒球"},
		{"NHL", "https://www.nhl.com", "美国职业冰球"},
		{"Premier League", "https://www.premierleague.com", "英超联赛"},
		{"La Liga", "https://www.laliga.com", "西甲联赛"},
		{"Bundesliga", "https://www.bundesliga.com", "德甲联赛"},
		{"Serie A", "https://www.legaseriea.it", "意甲联赛"},
		{"Ligue 1", "https://www.ligue1.com", "法甲联赛"},
		{"UEFA Champions League", "https://www.uefa.com/uefachampionsleague", "欧冠联赛"},
		{"ATP Tour", "https://www.atptour.com", "ATP网球巡回赛"},
		{"WTA Tennis", "https://www.wtatennis.com", "WTA女子网球"},
		{"Formula 1", "https://www.formula1.com", "F1赛车"},
		{"MotoGP", "https://www.motogp.com", "MotoGP摩托车"},
		{"PGA Tour", "https://www.pgatour.com", "PGA高尔夫巡回赛"},
		{"UFC", "https://www.ufc.com", "终极格斗冠军赛"},
		{"WWE", "https://www.wwe.com", "世界摔角娱乐"},
		{"Olympics", "https://olympics.com", "奥林匹克运动"},
		{"Transfermarkt", "https://www.transfermarkt.com", "足球转会市场"},
		{"Flashscore", "https://www.flashscore.com", "实时比分"},
		{"SofaScore", "https://www.sofascore.com", "体育比分数据"},
		{"365Scores", "https://www.365scores.com", "体育比分"},
		{"OneFootball", "https://onefootball.com", "足球资讯应用"},
		{"FotMob", "https://www.fotmob.com", "足球比分与数据"},
		{"WhoScored", "https://www.whoscored.com", "足球球员评分"},
		{"FBref", "https://fbref.com", "足球数据统计"},
		{"Basketball Reference", "https://www.basketball-reference.com", "篮球数据库"},
		{"腾讯体育", "https://sports.qq.com", "腾讯体育"},
		{"新浪体育", "https://sports.sina.com.cn", "新浪体育"},
		{"虎扑", "https://www.hupu.com", "体育社区"},
		{"懂球帝", "https://www.dongqiudi.com", "足球资讯社区"},
		{"直播吧", "https://www.zhibo8.cc", "体育直播资讯"},
		{"PP体育", "https://www.ppsport.com", "苏宁体育"},
		{"央视体育", "https://sports.cctv.com", "CCTV体育频道"},
		{"咪咕体育", "https://www.miguvideo.com/mgs/sports.html", "咪咕体育直播"},
		{"DAZN", "https://www.dazn.com", "体育流媒体"},
		{"ESPN+", "https://plus.espn.com", "ESPN流媒体"},
		{"FuboTV", "https://www.fubo.tv", "体育流媒体"},
		{"beIN Sports", "https://www.beinsports.com", "beIN体育"},
		{"Eurosport", "https://www.eurosport.com", "欧洲体育"},
		{"Olympic Channel", "https://olympics.com/en/olympic-channel", "奥运频道"},
		{"Red Bull", "https://www.redbull.com", "红牛极限运动"},
		{"Strava", "https://www.strava.com", "运动追踪社交"},
		{"Garmin Connect", "https://connect.garmin.com", "Garmin运动数据"},
		{"Runkeeper", "https://runkeeper.com", "跑步追踪"},
		{"MapMyRun", "https://www.mapmyrun.com", "跑步路线记录"},
		{"Nike Run Club", "https://www.nike.com/nrc-app", "Nike跑步"},
		{"Adidas Running", "https://www.adidas.com/us/running", "Adidas运动"},
	}
}

func realEstate() []S {
	return []S{
		{"Zillow", "https://www.zillow.com", "美国房产搜索"},
		{"Realtor.com", "https://www.realtor.com", "美国房产网"},
		{"Redfin", "https://www.redfin.com", "房产经纪平台"},
		{"Trulia", "https://www.trulia.com", "美国房产搜索"},
		{"Apartments.com", "https://www.apartments.com", "公寓租赁"},
		{"Rent.com", "https://www.rent.com", "租房平台"},
		{"Rightmove", "https://www.rightmove.co.uk", "英国房产"},
		{"Zoopla", "https://www.zoopla.co.uk", "英国房产搜索"},
		{"Immobilienscout24", "https://www.immobilienscout24.de", "德国房产"},
		{"Idealista", "https://www.idealista.com", "西班牙房产"},
		{"SeLoger", "https://www.seloger.com", "法国房产"},
		{"Domain", "https://www.domain.com.au", "澳洲房产"},
		{"REA Group", "https://www.realestate.com.au", "澳洲房产搜索"},
		{"99.co", "https://www.99.co", "新加坡房产"},
		{"PropertyGuru", "https://www.propertyguru.com", "东南亚房产"},
		{"贝壳找房", "https://www.ke.com", "贝壳找房"},
		{"链家", "https://www.lianjia.com", "链家房产"},
		{"安居客", "https://www.anjuke.com", "安居客找房"},
		{"58同城房产", "https://www.58.com/chuzu", "58同城租房"},
		{"房天下", "https://www.fang.com", "搜房网"},
		{"乐有家", "https://www.leyoujia.com", "乐有家房产"},
		{"我爱我家", "https://www.5i5j.com", "我爱我家"},
		{"中原地产", "https://www.centanet.com", "中原地产"},
		{"自如", "https://www.ziroom.com", "自如租房"},
		{"蛋壳公寓", "https://www.danke.com", "长租公寓"},
		{"青客公寓", "https://www.qk365.com", "白领公寓"},
		{"蘑菇租房", "https://www.mgzf.com", "租房平台"},
		{"诸葛找房", "https://www.zhuge.com", "房产大数据"},
		{"土巴兔", "https://www.to8to.com", "装修服务平台"},
		{"齐家网", "https://www.jia.com", "家居装修"},
		{"住小帮", "https://www.zhuxiaobang.com", "装修灵感平台"},
		{"好好住", "https://www.haohaozhu.com", "家居装修社区"},
		{"一兜糖", "https://www.yidoutang.com", "家居灵感"},
		{"宜家", "https://www.ikea.com", "宜家家居"},
		{"红星美凯龙", "https://www.macalline.com", "家居建材卖场"},
		{"居然之家", "https://www.juran.cn", "家居建材商场"},
		{"Houzz", "https://www.houzz.com", "家居设计灵感"},
		{"Wayfair", "https://www.wayfair.com", "家居电商"},
		{"West Elm", "https://www.westelm.com", "现代家具"},
		{"Pottery Barn", "https://www.potterybarn.com", "家居家具"},
		{"IKEA", "https://www.ikea.com", "宜家全球官网"},
		{"CB2", "https://www.cb2.com", "现代家居"},
		{"Article", "https://www.article.com", "在线家具"},
		{"Home Depot", "https://www.homedepot.com", "家居建材零售"},
		{"Lowes", "https://www.lowes.com", "家居装修零售"},
		{"Architectural Digest", "https://www.architecturaldigest.com", "建筑设计杂志"},
		{"Dwell", "https://www.dwell.com", "现代建筑设计"},
		{"ArchDaily", "https://www.archdaily.com", "建筑设计资讯"},
		{"Dezeen", "https://www.dezeen.com", "建筑与设计"},
		{"Designboom", "https://www.designboom.com", "设计与建筑"},
	}
}

func automotive() []S {
	return []S{
		{"汽车之家", "https://www.autohome.com.cn", "汽车资讯社区"},
		{"懂车帝", "https://www.dongchedi.com", "汽车资讯平台"},
		{"太平洋汽车", "https://www.pcauto.com.cn", "汽车评测网"},
		{"易车", "https://www.yiche.com", "易车汽车"},
		{"爱卡汽车", "https://www.xcar.com.cn", "爱卡汽车社区"},
		{"瓜子二手车", "https://www.guazi.com", "二手车交易"},
		{"优信二手车", "https://www.xin.com", "二手车电商"},
		{"人人车", "https://www.renrenche.com", "二手车直卖"},
		{"弹个车", "https://www.tangeche.com", "汽车金融"},
		{"特斯拉中国", "https://www.tesla.cn", "特斯拉中国"},
		{"蔚来", "https://www.nio.cn", "蔚来汽车"},
		{"小鹏汽车", "https://www.xiaopeng.com", "小鹏汽车"},
		{"理想汽车", "https://www.lixiang.com", "理想汽车"},
		{"比亚迪", "https://www.byd.com", "比亚迪汽车"},
		{"哪吒汽车", "https://www.hozonauto.com", "合众新能源"},
		{"零跑汽车", "https://www.leapmotor.com", "零跑汽车"},
		{"极氪", "https://www.zeekrlife.com", "极氪智能科技"},
		{"智己汽车", "https://www.zhijiauto.com", "智己汽车"},
		{"问界", "https://www.aito.com", "赛力斯华为合作"},
		{"高合汽车", "https://www.hiphi.com", "高合汽车"},
		{"Tesla", "https://www.tesla.com", "特斯拉全球"},
		{"Rivian", "https://rivian.com", "电动皮卡"},
		{"Lucid Motors", "https://www.lucidmotors.com", "豪华电动车"},
		{"Polestar", "https://www.polestar.com", "极星电动车"},
		{"BMW", "https://www.bmw.com", "宝马汽车"},
		{"Mercedes-Benz", "https://www.mercedes-benz.com", "梅赛德斯奔驰"},
		{"Audi", "https://www.audi.com", "奥迪汽车"},
		{"Porsche", "https://www.porsche.com", "保时捷"},
		{"Volkswagen", "https://www.volkswagen.com", "大众汽车"},
		{"Toyota", "https://www.toyota.com", "丰田汽车"},
		{"Honda", "https://www.honda.com", "本田汽车"},
		{"Hyundai", "https://www.hyundai.com", "现代汽车"},
		{"Ford", "https://www.ford.com", "福特汽车"},
		{"Chevrolet", "https://www.chevrolet.com", "雪佛兰"},
		{"Volvo", "https://www.volvocars.com", "沃尔沃汽车"},
		{"Edmunds", "https://www.edmunds.com", "美国汽车评测"},
		{"Kelley Blue Book", "https://www.kbb.com", "汽车估价"},
		{"Car and Driver", "https://www.caranddriver.com", "汽车杂志"},
		{"MotorTrend", "https://www.motortrend.com", "汽车评测媒体"},
		{"AutoTrader", "https://www.autotrader.com", "汽车交易平台"},
		{"Cars.com", "https://www.cars.com", "汽车买卖平台"},
		{"CarGurus", "https://www.cargurus.com", "汽车比价"},
		{"Vroom", "https://www.vroom.com", "在线买卖汽车"},
		{"Carvana", "https://www.carvana.com", "在线购车"},
		{"TrueCar", "https://www.truecar.com", "新车透明定价"},
		{"Autocar", "https://www.autocar.co.uk", "英国汽车媒体"},
		{"Top Gear", "https://www.topgear.com", "BBC汽车节目"},
		{"Jalopnik", "https://jalopnik.com", "汽车文化博客"},
		{"InsideEVs", "https://insideevs.com", "电动车新闻"},
		{"Electrek", "https://electrek.co", "电动交通新闻"},
		{"CleanTechnica", "https://cleantechnica.com", "清洁技术新闻"},
		{"驾考宝典", "https://www.jiakaobaodian.com", "驾照考试学习"},
		{"违章查询", "https://www.weizhangwang.com", "交通违章查询"},
	}
}
