package main

// Batch 6a: dataScience, gameDev, openSource, apiService, marketing, freelance

func dataScienceEx() []S {
	return []S{
		{"Kaggle", "https://www.kaggle.com", "数据科学竞赛平台"},
		{"DataCamp", "https://www.datacamp.com", "数据科学在线课程"},
		{"Towards Data Science", "https://towardsdatascience.com", "数据科学博客"},
		{"KDnuggets", "https://www.kdnuggets.com", "数据挖掘资讯"},
		{"Analytics Vidhya", "https://www.analyticsvidhya.com", "数据分析学习社区"},
		{"Data School", "https://www.dataschool.io", "数据科学教学"},
		{"Mode Analytics", "https://mode.com", "数据分析协作平台"},
		{"Metabase", "https://www.metabase.com", "开源数据可视化"},
		{"Apache Superset", "https://superset.apache.org", "开源BI工具"},
		{"Redash", "https://redash.io", "开源数据查询可视化"},
		{"Grafana", "https://grafana.com", "监控数据可视化"},
		{"Tableau Public", "https://public.tableau.com", "免费数据可视化"},
		{"Power BI", "https://powerbi.microsoft.com", "微软商业智能"},
		{"Looker", "https://looker.com", "Google数据分析"},
		{"Databricks", "https://databricks.com", "统一数据分析平台"},
		{"Snowflake", "https://www.snowflake.com", "云数据仓库"},
		{"dbt", "https://www.getdbt.com", "数据转换工具"},
		{"Airbyte", "https://airbyte.com", "开源数据集成"},
		{"Fivetran", "https://www.fivetran.com", "自动化数据管道"},
		{"Stitch", "https://www.stitchdata.com", "简单数据管道"},
		{"Apache Spark", "https://spark.apache.org", "大数据处理框架"},
		{"Apache Kafka", "https://kafka.apache.org", "分布式流处理"},
		{"Apache Flink", "https://flink.apache.org", "流数据处理引擎"},
		{"Apache Airflow", "https://airflow.apache.org", "工作流编排工具"},
		{"Prefect", "https://www.prefect.io", "现代工作流编排"},
		{"Dagster", "https://dagster.io", "数据编排平台"},
		{"MLflow", "https://mlflow.org", "机器学习生命周期"},
		{"Weights & Biases", "https://wandb.ai", "ML实验追踪"},
		{"Neptune.ai", "https://neptune.ai", "ML元数据管理"},
		{"DVC", "https://dvc.org", "数据版本控制"},
		{"Label Studio", "https://labelstud.io", "数据标注工具"},
		{"Prodigy", "https://prodi.gy", "AI辅助标注"},
		{"Hugging Face Datasets", "https://huggingface.co/datasets", "开源数据集"},
		{"Papers With Code", "https://paperswithcode.com", "论文代码复现"},
		{"Google Dataset Search", "https://datasetsearch.research.google.com", "数据集搜索"},
		{"UCI ML Repository", "https://archive.ics.uci.edu/ml", "经典ML数据集"},
		{"OpenML", "https://www.openml.org", "机器学习数据共享"},
		{"DataHub", "https://datahubproject.io", "数据发现治理平台"},
		{"Great Expectations", "https://greatexpectations.io", "数据质量验证"},
		{"Pandas", "https://pandas.pydata.org", "Python数据分析库"},
		{"NumPy", "https://numpy.org", "Python科学计算"},
		{"SciPy", "https://scipy.org", "Python科学计算库"},
		{"Scikit-learn", "https://scikit-learn.org", "Python机器学习"},
		{"XGBoost", "https://xgboost.readthedocs.io", "梯度提升框架"},
		{"LightGBM", "https://lightgbm.readthedocs.io", "微软梯度提升"},
		{"CatBoost", "https://catboost.ai", "Yandex梯度提升"},
		{"Ray", "https://www.ray.io", "分布式计算框架"},
		{"Dask", "https://www.dask.org", "并行计算库"},
		{"Vaex", "https://vaex.io", "大数据DataFrame"},
		{"Polars", "https://www.pola.rs", "高速DataFrame"},
		{"Streamlit", "https://streamlit.io", "数据应用框架"},
		{"Gradio", "https://gradio.app", "ML演示界面"},
		{"Observable", "https://observablehq.com", "数据可视化笔记"},
		{"Hex", "https://hex.tech", "协作数据工作台"},
		{"Deepnote", "https://deepnote.com", "协作Notebook"},
		{"Google Colab", "https://colab.research.google.com", "免费GPU Notebook"},
		{"Jupyter", "https://jupyter.org", "交互式Notebook"},
		{"DataRobot", "https://www.datarobot.com", "自动化ML平台"},
		{"H2O.ai", "https://h2o.ai", "开源AI平台"},
		{"RapidMiner", "https://rapidminer.com", "数据科学平台"},
		{"KNIME", "https://www.knime.com", "数据分析流程工具"},
		{"D3.js", "https://d3js.org", "数据驱动可视化"},
		{"Plotly", "https://plotly.com", "交互式图表库"},
		{"Altair", "https://altair-viz.github.io", "声明式可视化"},
		{"Seaborn", "https://seaborn.pydata.org", "统计数据可视化"},
		{"ECharts", "https://echarts.apache.org", "百度可视化图表"},
		{"和鲸社区", "https://www.heywhale.com", "中国数据科学社区"},
		{"天池", "https://tianchi.aliyun.com", "阿里数据竞赛平台"},
		{"DataFountain", "https://www.datafountain.cn", "数据竞赛平台"},
		{"Kesci", "https://www.kesci.com", "科赛数据科学平台"},
		{"聚数力", "https://dataju.cn", "开放数据平台"},
		{"数据堂", "https://www.datatang.com", "AI数据服务"},
		{"镝数聚", "https://www.dydata.io", "数据可视化平台"},
		{"百度AI开放平台", "https://ai.baidu.com", "百度AI服务"},
		{"飞桨", "https://www.paddlepaddle.org.cn", "百度深度学习平台"},
		{"ModelScope", "https://modelscope.cn", "阿里模型社区"},
		{"OpenI启智", "https://openi.pcl.ac.cn", "国产AI开源社区"},
		{"统计之都", "https://cosx.org", "统计学社区"},
		{"DataWhale", "https://datawhale.club", "开源学习社区"},
		{"伯克利数据科学", "https://data.berkeley.edu", "数据科学教育"},
		{"Fast.ai", "https://www.fast.ai", "深度学习课程"},
		{"365 Data Science", "https://365datascience.com", "数据科学在线课"},
		{"Data Engineering Wiki", "https://dataengineering.wiki", "数据工程知识库"},
		{"Apache Arrow", "https://arrow.apache.org", "列式内存数据格式"},
		{"DuckDB", "https://duckdb.org", "嵌入式分析数据库"},
		{"ClickHouse", "https://clickhouse.com", "列式分析数据库"},
		{"Apache Druid", "https://druid.apache.org", "实时分析数据库"},
		{"TimescaleDB", "https://www.timescale.com", "时序数据库"},
		{"QuestDB", "https://questdb.io", "高性能时序数据库"},
		{"InfluxDB", "https://www.influxdata.com", "时序数据平台"},
		{"Minio", "https://min.io", "高性能对象存储"},
		{"Delta Lake", "https://delta.io", "数据湖存储层"},
		{"Apache Iceberg", "https://iceberg.apache.org", "数据湖表格式"},
		{"Apache Hudi", "https://hudi.apache.org", "数据湖平台"},
		{"Trino", "https://trino.io", "分布式SQL查询引擎"},
	}
}

func gameDevEx() []S {
	return []S{
		{"Unity", "https://unity.com", "跨平台游戏引擎"},
		{"Unreal Engine", "https://www.unrealengine.com", "虚幻游戏引擎"},
		{"Godot", "https://godotengine.org", "开源游戏引擎"},
		{"GameMaker", "https://gamemaker.io", "2D游戏开发工具"},
		{"RPG Maker", "https://www.rpgmakerweb.com", "RPG游戏制作"},
		{"Construct", "https://www.construct.net", "无代码游戏制作"},
		{"Defold", "https://defold.com", "King游戏引擎"},
		{"Cocos Creator", "https://www.cocos.com", "国产游戏引擎"},
		{"Phaser", "https://phaser.io", "HTML5游戏框架"},
		{"PixiJS", "https://pixijs.com", "2D渲染引擎"},
		{"Three.js", "https://threejs.org", "WebGL 3D库"},
		{"Babylon.js", "https://www.babylonjs.com", "Web 3D引擎"},
		{"PlayCanvas", "https://playcanvas.com", "Web游戏引擎"},
		{"Bevy", "https://bevyengine.org", "Rust游戏引擎"},
		{"Amethyst", "https://amethyst.rs", "Rust ECS引擎"},
		{"LÖVE", "https://love2d.org", "Lua 2D游戏框架"},
		{"Raylib", "https://www.raylib.com", "简单游戏编程库"},
		{"SDL", "https://www.libsdl.org", "多媒体开发库"},
		{"MonoGame", "https://www.monogame.net", "C#游戏框架"},
		{"FNA", "https://fna-xna.github.io", "XNA reimplementation"},
		{"Itch.io", "https://itch.io", "独立游戏平台"},
		{"Game Jolt", "https://gamejolt.com", "独立游戏社区"},
		{"IndieDB", "https://www.indiedb.com", "独立游戏数据库"},
		{"Ludum Dare", "https://ldjam.com", "游戏开发大赛"},
		{"Global Game Jam", "https://globalgamejam.org", "全球游戏创作节"},
		{"GameDev.net", "https://www.gamedev.net", "游戏开发社区"},
		{"GameDev.tv", "https://www.gamedev.tv", "游戏开发课程"},
		{"Game Developer", "https://www.gamedeveloper.com", "游戏开发者资讯"},
		{"GDC Vault", "https://gdcvault.com", "GDC演讲资料"},
		{"Unity Learn", "https://learn.unity.com", "Unity官方教程"},
		{"Unreal Learning", "https://dev.epicgames.com/community/unreal-engine/learning", "虚幻官方学习"},
		{"Kenney", "https://kenney.nl", "免费游戏素材"},
		{"OpenGameArt", "https://opengameart.org", "开源游戏美术"},
		{"CG Cookie", "https://cgcookie.com", "CG教程平台"},
		{"Mixamo", "https://www.mixamo.com", "3D动画工具"},
		{"Spine", "https://esotericsoftware.com", "2D骨骼动画"},
		{"Aseprite", "https://www.aseprite.org", "像素画工具"},
		{"Tiled", "https://www.mapeditor.org", "2D地图编辑器"},
		{"FMOD", "https://www.fmod.com", "游戏音频中间件"},
		{"Wwise", "https://www.audiokinetic.com/wwise", "游戏音效引擎"},
		{"Photon", "https://www.photonengine.com", "多人游戏网络"},
		{"Mirror", "https://mirror-networking.com", "Unity网络框架"},
		{"Nakama", "https://heroiclabs.com", "开源游戏服务器"},
		{"PlayFab", "https://playfab.com", "游戏后端服务"},
		{"GameAnalytics", "https://gameanalytics.com", "游戏数据分析"},
		{"游戏葡萄", "https://youxiputao.com", "游戏行业媒体"},
		{"GameRes游资网", "https://www.gameres.com", "游戏开发资源"},
		{"游戏邦", "https://gamerboom.com", "游戏产业分析"},
		{"游民星空开发者", "https://dev.gamersky.com", "游戏开发者社区"},
		{"TapTap开发者", "https://developer.taptap.cn", "TapTap开发平台"},
		{"游戏茶馆", "https://www.youxichaguan.com", "游戏行业资讯"},
		{"游戏日报", "https://www.yxrb.net", "游戏产业日报"},
		{"游研社", "https://www.yystv.cn", "游戏文化社区"},
		{"游戏陀螺", "https://www.youxituoluo.com", "游戏产业媒体"},
		{"Game Developer中文", "https://www.gamedeveloper.com.cn", "游戏开发中文"},
		{"白鹭引擎", "https://www.egret.com", "H5游戏引擎"},
		{"LayaAir", "https://layaair.layabox.com", "3D游戏引擎"},
		{"CocosStore", "https://store.cocos.com", "Cocos资源商店"},
		{"Unity Asset Store", "https://assetstore.unity.com", "Unity资源商店"},
		{"Unreal Marketplace", "https://www.unrealengine.com/marketplace", "虚幻资源商城"},
		{"Humble Bundle", "https://www.humblebundle.com", "游戏慈善包"},
		{"GDQuest", "https://www.gdquest.com", "Godot教程"},
		{"Game Programming Patterns", "https://gameprogrammingpatterns.com", "游戏编程模式"},
		{"Red Blob Games", "https://www.redblobgames.com", "游戏算法可视化"},
		{"Catlike Coding", "https://catlikecoding.com", "Unity高级教程"},
		{"Shader Toy", "https://www.shadertoy.com", "着色器分享平台"},
		{"GPU Gems", "https://developer.nvidia.com/gpugems", "GPU编程宝典"},
		{"LearnOpenGL", "https://learnopengl.com", "OpenGL教程"},
		{"Vulkan Tutorial", "https://vulkan-tutorial.com", "Vulkan入门教程"},
		{"GameFromScratch", "https://gamefromscratch.com", "游戏开发教程"},
		{"Brackeys", "https://brackeys.com", "Unity教程"},
		{"Sebastian Lague", "https://sebastianlague.com", "编程可视化教学"},
		{"CraftPix", "https://craftpix.net", "2D游戏素材"},
		{"Oryol", "https://itch.io/game-assets", "游戏素材市场"},
		{"LDtk", "https://ldtk.io", "现代关卡编辑器"},
		{"Ink", "https://www.inklestudios.com/ink", "交互式叙事脚本"},
		{"Yarn Spinner", "https://yarnspinner.dev", "对话系统工具"},
		{"Dialogic", "https://dialogic.samsface.com", "Godot对话插件"},
		{"ProBuilder", "https://unity.com/features/probuilder", "Unity建模工具"},
		{"RealityKit", "https://developer.apple.com/augmented-reality/realitykit", "Apple AR框架"},
		{"Steamworks", "https://partner.steamgames.com", "Steam开发者平台"},
		{"Epic Dev Portal", "https://dev.epicgames.com", "Epic开发者门户"},
		{"Xbox Developer", "https://developer.microsoft.com/games", "Xbox开发者中心"},
		{"Nintendo Developer", "https://developer.nintendo.com", "任天堂开发者"},
		{"PlayStation Partners", "https://partners.playstation.net", "PS开发者平台"},
	}
}

func openSourceEx() []S {
	return []S{
		{"GitHub", "https://github.com", "全球最大代码托管"},
		{"GitLab", "https://gitlab.com", "DevOps代码平台"},
		{"Gitee", "https://gitee.com", "中国代码托管平台"},
		{"SourceForge", "https://sourceforge.net", "老牌开源平台"},
		{"Codeberg", "https://codeberg.org", "自由开源平台"},
		{"Bitbucket", "https://bitbucket.org", "Atlassian代码平台"},
		{"Launchpad", "https://launchpad.net", "Ubuntu开源平台"},
		{"OSDN", "https://osdn.net", "日本开源平台"},
		{"sr.ht", "https://sr.ht", "极简代码托管"},
		{"Apache Foundation", "https://www.apache.org", "Apache基金会"},
		{"Linux Foundation", "https://www.linuxfoundation.org", "Linux基金会"},
		{"CNCF", "https://www.cncf.io", "云原生基金会"},
		{"Eclipse Foundation", "https://www.eclipse.org", "Eclipse基金会"},
		{"Mozilla", "https://www.mozilla.org", "Mozilla基金会"},
		{"FSF", "https://www.fsf.org", "自由软件基金会"},
		{"OSI", "https://opensource.org", "开源促进会"},
		{"OpenSSF", "https://openssf.org", "开源安全基金会"},
		{"Open Source Guide", "https://opensource.guide", "GitHub开源指南"},
		{"First Timers Only", "https://www.firsttimersonly.com", "新手友好项目"},
		{"Good First Issue", "https://goodfirstissue.dev", "入门Issue聚合"},
		{"Up For Grabs", "https://up-for-grabs.net", "开源入门项目"},
		{"CodeTriage", "https://www.codetriage.com", "开源代码协助"},
		{"24 Pull Requests", "https://24pullrequests.com", "开源贡献活动"},
		{"Hacktoberfest", "https://hacktoberfest.com", "十月开源节"},
		{"Open Source Friday", "https://opensourcefriday.com", "开源星期五"},
		{"GitHub Trending", "https://github.com/trending", "GitHub热门项目"},
		{"GitHub Stars", "https://stars.github.com", "GitHub明星开发者"},
		{"GitStar Ranking", "https://gitstar-ranking.com", "GitHub Star排名"},
		{"OSSF Scorecard", "https://securityscorecards.dev", "开源安全评分"},
		{"Libraries.io", "https://libraries.io", "开源库搜索"},
		{"Awesome Lists", "https://github.com/sindresorhus/awesome", "Awesome资源列表"},
		{"HelloGitHub", "https://hellogithub.com", "中国开源推荐"},
		{"GitHubDaily", "https://github.com/GitHubDaily", "GitHub每日精选"},
		{"开源中国", "https://www.oschina.net", "中国开源社区"},
		{"思否开源", "https://segmentfault.com/channel/open-source", "思否开源频道"},
		{"Gitcoin", "https://www.gitcoin.co", "开源赏金平台"},
		{"Open Collective", "https://opencollective.com", "开源项目资助"},
		{"GitHub Sponsors", "https://github.com/sponsors", "GitHub赞助"},
		{"Thanks.dev", "https://thanks.dev", "开源依赖赞助"},
		{"IssueHunt", "https://issuehunt.io", "Issue赏金平台"},
		{"Bountysource", "https://www.bountysource.com", "开源悬赏"},
		{"FOSSBilling", "https://fossbilling.org", "开源计费系统"},
		{"CHAOSS", "https://chaoss.community", "开源社区健康度"},
		{"TODO Group", "https://todogroup.org", "企业开源最佳实践"},
		{"OpenChain", "https://www.openchainproject.org", "开源合规标准"},
		{"SPDX", "https://spdx.dev", "软件许可证标准"},
		{"Choose a License", "https://choosealicense.com", "开源许可证选择"},
		{"TLDRLegal", "https://tldrlegal.com", "许可证简要说明"},
		{"FOSSology", "https://www.fossology.org", "开源合规扫描"},
		{"ScanCode", "https://github.com/nexB/scancode-toolkit", "许可证扫描工具"},
		{"开放原子", "https://www.openatom.org", "中国开源基金会"},
		{"木兰社区", "https://portal.mulanos.cn", "木兰开源社区"},
		{"Archlinux", "https://archlinux.org", "Arch Linux"},
		{"Debian", "https://www.debian.org", "Debian Linux"},
		{"Fedora", "https://fedoraproject.org", "Fedora Linux"},
		{"FreeBSD", "https://www.freebsd.org", "FreeBSD操作系统"},
		{"OpenBSD", "https://www.openbsd.org", "安全操作系统"},
		{"NixOS", "https://nixos.org", "声明式Linux"},
		{"Alpine Linux", "https://alpinelinux.org", "轻量级Linux"},
		{"openSUSE", "https://www.opensuse.org", "openSUSE Linux"},
		{"KDE", "https://kde.org", "KDE桌面环境"},
		{"GNOME", "https://www.gnome.org", "GNOME桌面环境"},
		{"Homebrew", "https://brew.sh", "macOS包管理器"},
		{"Chocolatey", "https://chocolatey.org", "Windows包管理器"},
		{"FlatHub", "https://flathub.org", "Linux应用商店"},
		{"Snap Store", "https://snapcraft.io", "Ubuntu应用商店"},
		{"AppImage", "https://appimage.org", "Linux通用格式"},
		{"F-Droid", "https://f-droid.org", "开源安卓商店"},
		{"AlternativeTo", "https://alternativeto.net", "软件替代品搜索"},
		{"PrivacyTools", "https://www.privacytools.io", "隐私工具推荐"},
		{"Awesome Self-Hosted", "https://awesome-selfhosted.net", "自托管服务列表"},
		{"OpenStreetMap", "https://www.openstreetmap.org", "开源地图项目"},
		{"Wikimedia", "https://www.wikimedia.org", "维基媒体基金会"},
		{"Internet Archive", "https://archive.org", "互联网档案馆"},
		{"Creative Commons", "https://creativecommons.org", "知识共享协议"},
		{"Let's Encrypt", "https://letsencrypt.org", "免费SSL证书"},
		{"Tor Project", "https://www.torproject.org", "匿名网络项目"},
		{"Signal", "https://signal.org", "开源加密通讯"},
		{"Matrix", "https://matrix.org", "开源即时通讯协议"},
		{"Mastodon", "https://joinmastodon.org", "开源社交网络"},
		{"WordPress", "https://wordpress.org", "开源建站系统"},
		{"Nextcloud", "https://nextcloud.com", "开源云盘"},
		{"Home Assistant", "https://www.home-assistant.io", "开源智能家居"},
		{"Blender", "https://www.blender.org", "开源3D创作"},
		{"GIMP", "https://www.gimp.org", "开源图片编辑"},
		{"Inkscape", "https://inkscape.org", "开源矢量设计"},
		{"Audacity", "https://www.audacityteam.org", "开源音频编辑"},
		{"OBS Studio", "https://obsproject.com", "开源直播录屏"},
		{"VLC", "https://www.videolan.org", "开源媒体播放器"},
		{"FFmpeg", "https://ffmpeg.org", "多媒体处理框架"},
		{"LibreOffice", "https://www.libreoffice.org", "开源办公套件"},
		{"Thunderbird", "https://www.thunderbird.net", "开源邮件客户端"},
		{"KeePass", "https://keepass.info", "开源密码管理器"},
		{"Bitwarden", "https://bitwarden.com", "开源密码管理"},
	}
}

func apiServiceEx() []S {
	return []S{
		{"RapidAPI", "https://rapidapi.com", "API市场平台"},
		{"Postman", "https://www.postman.com", "API开发测试工具"},
		{"Insomnia", "https://insomnia.rest", "API调试工具"},
		{"Hoppscotch", "https://hoppscotch.io", "开源API调试"},
		{"Paw", "https://paw.cloud", "macOS API工具"},
		{"Thunder Client", "https://www.thunderclient.com", "VSCode API插件"},
		{"Swagger", "https://swagger.io", "API文档规范"},
		{"OpenAPI", "https://www.openapis.org", "API规范标准"},
		{"Stoplight", "https://stoplight.io", "API设计平台"},
		{"Redocly", "https://redocly.com", "API文档生成"},
		{"ReadMe", "https://readme.com", "API文档平台"},
		{"GitBook", "https://www.gitbook.com", "文档协作平台"},
		{"Apidog", "https://apidog.com", "API一体化平台"},
		{"Apifox", "https://apifox.com", "API设计开发平台"},
		{"YApi", "https://yapi.pro", "API管理平台"},
		{"Eolink", "https://www.eolink.com", "API全生命周期"},
		{"ShowDoc", "https://www.showdoc.com.cn", "在线API文档"},
		{"Strapi", "https://strapi.io", "开源Headless CMS"},
		{"Directus", "https://directus.io", "开源数据平台"},
		{"Hasura", "https://hasura.io", "GraphQL引擎"},
		{"Apollo GraphQL", "https://www.apollographql.com", "GraphQL平台"},
		{"Prisma", "https://www.prisma.io", "Node.js ORM"},
		{"tRPC", "https://trpc.io", "端到端类型安全API"},
		{"Kong", "https://konghq.com", "API网关"},
		{"Tyk", "https://tyk.io", "开源API网关"},
		{"Apigee", "https://cloud.google.com/apigee", "Google API管理"},
		{"AWS API Gateway", "https://aws.amazon.com/api-gateway", "AWS API网关"},
		{"MuleSoft", "https://www.mulesoft.com", "API集成平台"},
		{"Twilio", "https://www.twilio.com", "通信API"},
		{"SendGrid", "https://sendgrid.com", "邮件发送API"},
		{"Mailgun", "https://www.mailgun.com", "邮件API服务"},
		{"Vonage", "https://www.vonage.com", "通信API平台"},
		{"Agora", "https://www.agora.io", "声网实时通信"},
		{"融云", "https://www.rongcloud.cn", "即时通讯云"},
		{"环信", "https://www.easemob.com", "即时通讯服务"},
		{"极光推送", "https://www.jiguang.cn", "消息推送服务"},
		{"个推", "https://www.getui.com", "推送技术服务"},
		{"LeanCloud", "https://leancloud.cn", "移动后端云"},
		{"Bmob", "https://www.bmob.cn", "移动后端云服务"},
		{"Stripe", "https://stripe.com", "支付API"},
		{"PayPal Developer", "https://developer.paypal.com", "PayPal开发者"},
		{"Braintree", "https://www.braintreepayments.com", "支付平台"},
		{"Adyen", "https://www.adyen.com", "全球支付平台"},
		{"Wise API", "https://wise.com/gb/business/api", "国际汇款API"},
		{"Plaid", "https://plaid.com", "金融数据API"},
		{"Clearbit", "https://clearbit.com", "商业数据API"},
		{"FullContact", "https://www.fullcontact.com", "身份解析API"},
		{"Abstract API", "https://www.abstractapi.com", "实用API集合"},
		{"ipinfo", "https://ipinfo.io", "IP地理定位API"},
		{"ipapi", "https://ipapi.com", "IP查询API"},
		{"OpenWeatherMap", "https://openweathermap.org/api", "天气数据API"},
		{"Google Maps API", "https://developers.google.com/maps", "谷歌地图API"},
		{"Mapbox", "https://www.mapbox.com", "地图服务API"},
		{"高德开放平台", "https://lbs.amap.com", "高德地图API"},
		{"百度地图开放平台", "https://lbsyun.baidu.com", "百度地图API"},
		{"腾讯位置服务", "https://lbs.qq.com", "腾讯地图API"},
		{"Cloudinary", "https://cloudinary.com", "媒体管理API"},
		{"imgix", "https://imgix.com", "图片处理API"},
		{"又拍云", "https://www.upyun.com", "CDN云存储API"},
		{"七牛云", "https://www.qiniu.com", "云存储服务"},
		{"Auth0", "https://auth0.com", "身份认证API"},
		{"Firebase", "https://firebase.google.com", "Google后端服务"},
		{"Supabase", "https://supabase.com", "开源Firebase替代"},
		{"Appwrite", "https://appwrite.io", "开源后端服务"},
		{"Nhost", "https://nhost.io", "GraphQL后端"},
		{"PocketBase", "https://pocketbase.io", "单文件后端"},
		{"MockAPI", "https://mockapi.io", "模拟API服务"},
		{"JSON Server", "https://github.com/typicode/json-server", "快速REST API"},
		{"Beeceptor", "https://beeceptor.com", "API模拟拦截"},
		{"Mockoon", "https://mockoon.com", "本地API模拟"},
		{"HTTPBin", "https://httpbin.org", "HTTP请求测试"},
		{"JSONPlaceholder", "https://jsonplaceholder.typicode.com", "假数据REST API"},
		{"ReqRes", "https://reqres.in", "模拟REST API"},
		{"Public APIs", "https://github.com/public-apis/public-apis", "公共API列表"},
		{"API List", "https://apilist.fun", "API发现平台"},
		{"聚合数据", "https://www.juhe.cn", "中国数据API平台"},
		{"天行数据", "https://www.tianapi.com", "中国免费API"},
		{"万维易源", "https://www.showapi.com", "API数据服务"},
		{"阿里云API市场", "https://market.aliyun.com/data", "阿里API市场"},
		{"腾讯云API", "https://cloud.tencent.com/product/api", "腾讯云API服务"},
		{"百度云API", "https://cloud.baidu.com/product/ai", "百度云AI API"},
		{"Webhook.site", "https://webhook.site", "Webhook调试工具"},
		{"ngrok", "https://ngrok.com", "内网穿透工具"},
		{"Localtunnel", "https://theboroer.github.io/localtunnel-www", "本地隧道"},
		{"Pinggy", "https://pinggy.io", "快速公网暴露"},
		{"GraphQL Playground", "https://github.com/graphql/graphql-playground", "GraphQL IDE"},
		{"Altair GraphQL", "https://altairgraphql.dev", "GraphQL客户端"},
		{"gRPC", "https://grpc.io", "高性能RPC框架"},
		{"Protocol Buffers", "https://protobuf.dev", "数据序列化协议"},
		{"AsyncAPI", "https://www.asyncapi.com", "异步API规范"},
		{"JSON Schema", "https://json-schema.org", "JSON模式规范"},
	}
}

func marketingEx() []S {
	return []S{
		{"HubSpot", "https://www.hubspot.com", "营销自动化平台"},
		{"Mailchimp", "https://mailchimp.com", "邮件营销平台"},
		{"ConvertKit", "https://convertkit.com", "创作者邮件营销"},
		{"ActiveCampaign", "https://www.activecampaign.com", "营销自动化"},
		{"Brevo", "https://www.brevo.com", "营销传播平台"},
		{"Constant Contact", "https://www.constantcontact.com", "邮件营销"},
		{"Drip", "https://www.drip.com", "电商邮件营销"},
		{"Klaviyo", "https://www.klaviyo.com", "电商营销平台"},
		{"Omnisend", "https://www.omnisend.com", "全渠道营销"},
		{"Moosend", "https://moosend.com", "邮件营销工具"},
		{"Google Analytics", "https://analytics.google.com", "网站分析工具"},
		{"Google Ads", "https://ads.google.com", "谷歌广告"},
		{"Facebook Ads", "https://www.facebook.com/business/ads", "脸书广告"},
		{"Google Search Console", "https://search.google.com/search-console", "搜索分析"},
		{"Semrush", "https://www.semrush.com", "SEO营销工具"},
		{"Ahrefs", "https://ahrefs.com", "SEO分析平台"},
		{"Moz", "https://moz.com", "SEO工具套件"},
		{"Ubersuggest", "https://neilpatel.com/ubersuggest", "SEO关键词工具"},
		{"SpyFu", "https://www.spyfu.com", "竞争对手分析"},
		{"SimilarWeb", "https://www.similarweb.com", "流量分析工具"},
		{"BuzzSumo", "https://buzzsumo.com", "内容营销分析"},
		{"Hootsuite", "https://www.hootsuite.com", "社媒管理平台"},
		{"Buffer", "https://buffer.com", "社媒发布工具"},
		{"Sprout Social", "https://sproutsocial.com", "社媒管理分析"},
		{"Later", "https://later.com", "社媒排程工具"},
		{"SocialBee", "https://socialbee.com", "社媒自动化"},
		{"Canva", "https://www.canva.com", "设计营销素材"},
		{"Unbounce", "https://unbounce.com", "落地页构建"},
		{"Leadpages", "https://www.leadpages.com", "落地页工具"},
		{"Instapage", "https://instapage.com", "广告落地页"},
		{"ClickFunnels", "https://www.clickfunnels.com", "销售漏斗工具"},
		{"Hotjar", "https://www.hotjar.com", "用户行为分析"},
		{"Crazy Egg", "https://www.crazyegg.com", "热力图分析"},
		{"Optimizely", "https://www.optimizely.com", "A/B测试平台"},
		{"VWO", "https://vwo.com", "转化率优化"},
		{"Google Tag Manager", "https://tagmanager.google.com", "标签管理器"},
		{"Segment", "https://segment.com", "客户数据平台"},
		{"Mixpanel", "https://mixpanel.com", "产品分析工具"},
		{"Amplitude", "https://amplitude.com", "数字分析平台"},
		{"Heap", "https://heap.io", "自动化分析"},
		{"百度统计", "https://tongji.baidu.com", "百度网站分析"},
		{"百度推广", "https://e.baidu.com", "百度搜索广告"},
		{"巨量引擎", "https://www.oceanengine.com", "字节广告平台"},
		{"腾讯广告", "https://e.qq.com", "腾讯广告投放"},
		{"微博粉丝通", "https://tui.weibo.com", "微博广告"},
		{"阿里妈妈", "https://www.alimama.com", "阿里营销平台"},
		{"友盟+", "https://www.umeng.com", "移动统计分析"},
		{"GrowingIO", "https://www.growingio.com", "增长分析平台"},
		{"神策数据", "https://www.sensorsdata.cn", "用户行为分析"},
		{"诸葛io", "https://zhugeio.com", "智能分析平台"},
		{"易观", "https://www.analysys.cn", "数字用户分析"},
		{"TalkingData", "https://www.talkingdata.com", "移动数据平台"},
		{"梅花网", "https://www.meihua.info", "营销行业资讯"},
		{"数英网", "https://www.digitaling.com", "数字营销社区"},
		{"广告门", "https://www.adquan.com", "广告创意门户"},
		{"SocialBeta", "https://socialbeta.com", "社会化营销"},
		{"市场部网", "https://www.shichangbu.com", "营销人社区"},
		{"鸟哥笔记", "https://www.niaogebiji.com", "运营推广社区"},
		{"人人都是产品经理", "https://www.woshipm.com", "产品运营社区"},
		{"运营派", "https://www.yunyingpai.com", "运营知识平台"},
		{"Intercom", "https://www.intercom.com", "客户沟通平台"},
		{"Drift", "https://www.drift.com", "对话式营销"},
		{"Crisp", "https://crisp.chat", "客户消息平台"},
		{"Freshdesk", "https://freshdesk.com", "客户支持平台"},
		{"Zendesk", "https://www.zendesk.com", "客服工具"},
		{"Hunter.io", "https://hunter.io", "邮箱查找工具"},
		{"Snov.io", "https://snov.io", "邮箱获取工具"},
		{"Lemlist", "https://www.lemlist.com", "冷邮件工具"},
		{"Reply.io", "https://reply.io", "销售开发平台"},
		{"Apollo.io", "https://www.apollo.io", "销售智能平台"},
		{"ZoomInfo", "https://www.zoominfo.com", "B2B数据平台"},
		{"Lusha", "https://www.lusha.com", "B2B联系人数据"},
		{"Surfer SEO", "https://surferseo.com", "内容SEO工具"},
		{"Frase", "https://www.frase.io", "AI内容优化"},
		{"Jasper", "https://www.jasper.ai", "AI营销文案"},
		{"Copy.ai", "https://www.copy.ai", "AI文案生成"},
		{"Writesonic", "https://writesonic.com", "AI写作助手"},
		{"Grammarly", "https://www.grammarly.com", "英文写作工具"},
		{"Yoast SEO", "https://yoast.com", "WordPress SEO"},
		{"Rank Math", "https://rankmath.com", "WordPress SEO"},
		{"Screaming Frog", "https://www.screamingfrog.co.uk", "SEO爬虫工具"},
		{"GTmetrix", "https://gtmetrix.com", "网站速度测试"},
		{"Google PageSpeed", "https://pagespeed.web.dev", "页面性能测试"},
		{"Bitly", "https://bitly.com", "短链接服务"},
		{"Rebrandly", "https://www.rebrandly.com", "品牌短链接"},
		{"QR Code Generator", "https://www.qr-code-generator.com", "二维码生成"},
		{"草料二维码", "https://cli.im", "中国二维码生成"},
		{"Loom", "https://www.loom.com", "视频消息工具"},
		{"Wistia", "https://wistia.com", "视频营销平台"},
		{"Vidyard", "https://www.vidyard.com", "视频营销工具"},
		{"Calendly", "https://calendly.com", "日程预约工具"},
		{"Typeform", "https://www.typeform.com", "在线表单工具"},
		{"SurveyMonkey", "https://www.surveymonkey.com", "在线调查工具"},
	}
}

func freelanceEx() []S {
	return []S{
		{"Upwork", "https://www.upwork.com", "全球自由职业平台"},
		{"Fiverr", "https://www.fiverr.com", "技能服务市场"},
		{"Freelancer", "https://www.freelancer.com", "自由职业竞标"},
		{"Toptal", "https://www.toptal.com", "顶尖自由职业者"},
		{"99designs", "https://99designs.com", "设计竞赛平台"},
		{"DesignCrowd", "https://www.designcrowd.com", "设计众包"},
		{"PeoplePerHour", "https://www.peopleperhour.com", "英国自由职业"},
		{"Guru", "https://www.guru.com", "自由职业平台"},
		{"SimplyHired", "https://www.simplyhired.com", "求职搜索引擎"},
		{"FlexJobs", "https://www.flexjobs.com", "远程灵活工作"},
		{"Remote OK", "https://remoteok.com", "远程工作列表"},
		{"We Work Remotely", "https://weworkremotely.com", "远程工作社区"},
		{"Remote.co", "https://remote.co", "远程工作资源"},
		{"Remotive", "https://remotive.com", "远程工作招聘"},
		{"Working Nomads", "https://www.workingnomads.com", "数字游民工作"},
		{"Nomad List", "https://nomadlist.com", "数字游民城市"},
		{"AngelList Talent", "https://angel.co", "创业公司招聘"},
		{"Contra", "https://contra.com", "自由职业者社区"},
		{"Malt", "https://www.malt.com", "欧洲自由职业"},
		{"Workana", "https://www.workana.com", "拉美自由职业"},
		{"猪八戒网", "https://www.zbj.com", "中国服务众包"},
		{"一品威客", "https://www.epwk.com", "创意服务平台"},
		{"时间财富网", "https://www.680.com", "威客服务平台"},
		{"程序员客栈", "https://www.proginn.com", "IT自由职业"},
		{"实现网", "https://shixian.com", "技术自由职业"},
		{"BOSS直聘兼职", "https://www.zhipin.com", "兼职招聘"},
		{"Dribbble Freelance", "https://dribbble.com/freelance-jobs", "设计自由职业"},
		{"Behance Freelance", "https://www.behance.net/joblist", "创意自由职业"},
		{"Codementor", "https://www.codementor.io", "编程导师平台"},
		{"Clarity.fm", "https://clarity.fm", "专家咨询平台"},
		{"Calendly", "https://calendly.com", "预约管理工具"},
		{"Harvest", "https://www.getharvest.com", "时间追踪发票"},
		{"Toggl", "https://toggl.com", "时间追踪工具"},
		{"Clockify", "https://clockify.me", "免费时间追踪"},
		{"FreshBooks", "https://www.freshbooks.com", "发票会计工具"},
		{"Wave", "https://www.waveapps.com", "免费发票会计"},
		{"Bonsai", "https://www.hellobonsai.com", "自由职业管理"},
		{"AND CO", "https://www.and.co", "自由职业助手"},
		{"HoneyBook", "https://www.honeybook.com", "客户管理工具"},
		{"Dubsado", "https://www.dubsado.com", "业务管理平台"},
		{"Notion", "https://www.notion.so", "项目管理笔记"},
		{"Trello", "https://trello.com", "看板项目管理"},
		{"Asana", "https://asana.com", "团队项目管理"},
		{"ClickUp", "https://clickup.com", "全能项目管理"},
		{"Linear", "https://linear.app", "产品项目管理"},
		{"Loom", "https://www.loom.com", "异步视频沟通"},
		{"Slack", "https://slack.com", "团队协作通讯"},
		{"Discord", "https://discord.com", "社区通讯平台"},
		{"Zoom", "https://zoom.us", "视频会议"},
		{"Cal.com", "https://cal.com", "开源日程预约"},
		{"Invoice Ninja", "https://invoiceninja.com", "开源发票工具"},
		{"Wise", "https://wise.com", "国际收付款"},
		{"Payoneer", "https://www.payoneer.com", "跨境支付平台"},
		{"TransferWise", "https://transferwise.com", "国际转账"},
		{"Stripe Atlas", "https://stripe.com/atlas", "美国公司注册"},
		{"Deel", "https://www.deel.com", "全球远程雇佣"},
		{"Remote.com", "https://remote.com", "全球HR平台"},
		{"Oyster HR", "https://www.oysterhr.com", "全球雇佣平台"},
		{"Papaya Global", "https://www.papayaglobal.com", "全球薪酬管理"},
		{"即派", "https://jipai.netease.com", "网易灵活用工"},
		{"甜薪工场", "https://www.txgc.com", "远程兼职平台"},
		{"云队友", "https://www.duiyou360.com", "远程工作平台"},
		{"开源众包", "https://zb.oschina.net", "开源技术众包"},
		{"Coding码市", "https://mart.coding.net", "软件众包平台"},
		{"YuanFuDao Work", "https://www.yuanfudao.com", "在线教育兼职"},
		{"Indiehackers", "https://www.indiehackers.com", "独立开发者社区"},
		{"Gumroad", "https://gumroad.com", "数字产品销售"},
		{"Patreon", "https://www.patreon.com", "创作者赞助平台"},
		{"Buy Me a Coffee", "https://www.buymeacoffee.com", "创作者打赏"},
		{"Ko-fi", "https://ko-fi.com", "创作者支持平台"},
		{"Substack", "https://substack.com", "付费通讯平台"},
		{"Ghost", "https://ghost.org", "独立出版平台"},
		{"Memberful", "https://memberful.com", "会员制工具"},
		{"Teachable", "https://teachable.com", "在线课程平台"},
		{"Podia", "https://www.podia.com", "数字产品平台"},
		{"Thinkific", "https://www.thinkific.com", "在线课程创建"},
		{"Skillshare", "https://www.skillshare.com", "创意课程平台"},
		{"Udemy Instructor", "https://www.udemy.com/teaching", "Udemy讲师"},
		{"ProductHunt", "https://www.producthunt.com", "产品发布平台"},
		{"BetaList", "https://betalist.com", "创业项目展示"},
		{"Hacker News", "https://news.ycombinator.com", "技术创业资讯"},
		{"LeanPub", "https://leanpub.com", "电子书出版"},
		{"Creative Market", "https://creativemarket.com", "设计素材市场"},
		{"Envato Market", "https://market.envato.com", "数字资产市场"},
		{"ThemeForest", "https://themeforest.net", "网站主题市场"},
		{"CodeCanyon", "https://codecanyon.net", "代码插件市场"},
		{"AWS Marketplace", "https://aws.amazon.com/marketplace", "AWS软件市场"},
		{"Shopify App Store", "https://apps.shopify.com", "Shopify应用"},
		{"Chrome Web Store", "https://chrome.google.com/webstore", "Chrome扩展商店"},
		{"WordPress Plugins", "https://wordpress.org/plugins", "WP插件市场"},
		{"npm", "https://www.npmjs.com", "Node包市场"},
	}
}
