package main

// Boost3: Final push to reach 10,000+ total sites.

func educationBoost() []S {
	return []S{
		{"Brilliant", "https://brilliant.org", "互动式STEM学习"},
		{"Duolingo", "https://www.duolingo.com", "免费语言学习"},
		{"Babbel", "https://www.babbel.com", "语言学习应用"},
		{"Busuu", "https://www.busuu.com", "语言学习社区"},
		{"Rosetta Stone", "https://www.rosettastone.com", "语言学习软件"},
		{"Memrise", "https://www.memrise.com", "记忆学习平台"},
		{"Anki", "https://apps.ankiweb.net", "间隔重复记忆"},
		{"Quizlet", "https://quizlet.com", "学习卡片工具"},
		{"StudyBlue", "https://www.studyblue.com", "学习卡片平台"},
		{"Chegg", "https://www.chegg.com", "作业辅导平台"},
		{"Wolfram Alpha", "https://www.wolframalpha.com", "计算知识引擎"},
		{"Desmos", "https://www.desmos.com", "图形计算器"},
		{"GeoGebra", "https://www.geogebra.org", "动态数学工具"},
		{"Photomath", "https://photomath.com", "拍照解数学题"},
		{"Mathway", "https://www.mathway.com", "数学问题求解"},
		{"Symbolab", "https://www.symbolab.com", "数学步骤求解"},
		{"Open Yale Courses", "https://oyc.yale.edu", "耶鲁公开课"},
		{"Stanford Online", "https://online.stanford.edu", "斯坦福在线"},
		{"OpenStax", "https://openstax.org", "免费教科书"},
		{"LibreTexts", "https://libretexts.org", "开放教育资源"},
		{"Saylor Academy", "https://www.saylor.org", "免费在线课程"},
		{"Class Central", "https://www.classcentral.com", "课程搜索引擎"},
		{"Skillshare", "https://www.skillshare.com", "创意技能课程"},
		{"LinkedIn Learning", "https://www.linkedin.com/learning", "职业技能学习"},
		{"Domestika", "https://www.domestika.org", "创意在线课程"},
		{"Simplilearn", "https://www.simplilearn.com", "IT认证培训"},
		{"Google Career Certificates", "https://grow.google/certificates", "谷歌职业证书"},
		{"IBM Skills Build", "https://skillsbuild.org", "IBM技能培训"},
		{"AWS Training", "https://aws.amazon.com/training", "AWS技术培训"},
		{"Microsoft Learn", "https://learn.microsoft.com", "微软技术学习"},
	}
}

func travelBoost() []S {
	return []S{
		{"Booking.com", "https://www.booking.com", "全球酒店预订"},
		{"Agoda", "https://www.agoda.com", "亚洲酒店预订"},
		{"Hotels.com", "https://www.hotels.com", "酒店搜索比较"},
		{"Hostelworld", "https://www.hostelworld.com", "青旅预订"},
		{"Vrbo", "https://www.vrbo.com", "度假租房"},
		{"HomeAway", "https://www.homeaway.com", "民宿度假屋"},
		{"Couchsurfing", "https://www.couchsurfing.com", "沙发客旅行"},
		{"Rome2Rio", "https://www.rome2rio.com", "全球交通规划"},
		{"Kayak", "https://www.kayak.com", "旅行搜索比价"},
		{"Momondo", "https://www.momondo.com", "机票搜索比较"},
		{"Skyscanner", "https://www.skyscanner.com", "全球机票比价"},
		{"Google Flights", "https://www.google.com/flights", "谷歌航班搜索"},
		{"Hopper", "https://www.hopper.com", "机票价格预测"},
		{"Scott's Cheap Flights", "https://scottscheapflights.com", "低价机票通知"},
		{"Secret Flying", "https://www.secretflying.com", "特价机票"},
		{"TripIt", "https://www.tripit.com", "行程管理工具"},
		{"Wanderlog", "https://wanderlog.com", "旅行规划App"},
		{"Sygic Travel", "https://travel.sygic.com", "旅行规划地图"},
		{"Culture Trip", "https://theculturetrip.com", "文化旅行灵感"},
		{"Atlas Obscura", "https://www.atlasobscura.com", "奇特景点发现"},
		{"Roadtrippers", "https://roadtrippers.com", "公路旅行规划"},
		{"AllTrails", "https://www.alltrails.com", "徒步路线"},
		{"Komoot", "https://www.komoot.com", "户外路线规划"},
		{"iOverlander", "https://www.ioverlander.com", "自驾旅行信息"},
		{"Workaway", "https://www.workaway.info", "旅行义工平台"},
		{"WWOOF", "https://wwoof.net", "有机农场义工"},
		{"Worldpackers", "https://www.worldpackers.com", "义工旅行平台"},
		{"Numbeo", "https://www.numbeo.com", "生活成本比较"},
		{"Safety Wing", "https://safetywing.com", "数字游民保险"},
		{"World Nomads", "https://www.worldnomads.com", "旅行保险"},
	}
}

func foodBoost() []S {
	return []S{
		{"Epicurious", "https://www.epicurious.com", "美食食谱平台"},
		{"Bon Appétit", "https://www.bonappetit.com", "美食杂志"},
		{"Serious Eats", "https://www.seriouseats.com", "美食科学"},
		{"Food Network", "https://www.foodnetwork.com", "美食电视网"},
		{"Tasty", "https://tasty.co", "美食视频食谱"},
		{"Yummly", "https://www.yummly.com", "智能食谱搜索"},
		{"Paprika", "https://www.paprikaapp.com", "食谱管理App"},
		{"Mealime", "https://www.mealime.com", "膳食计划"},
		{"Eat This Much", "https://www.eatthismuch.com", "自动膳食计划"},
		{"Cronometer", "https://cronometer.com", "营养追踪工具"},
		{"HappyCow", "https://www.happycow.net", "素食餐厅搜索"},
		{"Yelp Food", "https://www.yelp.com/search?cflt=restaurants", "餐厅搜索评价"},
		{"OpenTable", "https://www.opentable.com", "餐厅预订"},
		{"Resy", "https://resy.com", "高档餐厅预订"},
		{"TheFork", "https://www.thefork.com", "欧洲餐厅预订"},
		{"Zomato", "https://www.zomato.com", "全球餐厅平台"},
		{"Swiggy", "https://www.swiggy.com", "印度外卖平台"},
		{"Foodpanda", "https://www.foodpanda.com", "亚洲外卖平台"},
		{"大众点评美食", "https://www.dianping.com/search/category/1/10/g0", "中国美食点评"},
		{"必吃榜", "https://h5.dianping.com/app/bichilist", "大众点评必吃"},
		{"黑珍珠", "https://www.meituan.com/heizhenzhu", "美团餐厅榜单"},
		{"美食杰", "https://www.meishij.net", "中文菜谱网站"},
		{"心食谱", "https://www.xinshipu.com", "中文食谱大全"},
		{"香哈菜谱", "https://www.xiangha.com", "香哈美食"},
		{"日食记", "https://www.rishiji.com", "生活美食"},
		{"米其林指南", "https://guide.michelin.com/cn/zh_CN", "米其林餐厅指南"},
		{"Wine Spectator", "https://www.winespectator.com", "葡萄酒杂志"},
		{"Vivino", "https://www.vivino.com", "葡萄酒评分"},
		{"Untappd", "https://untappd.com", "精酿啤酒社区"},
		{"Specialty Coffee", "https://sca.coffee", "精品咖啡协会"},
	}
}

func healthBoost() []S {
	return []S{
		{"WebMD", "https://www.webmd.com", "医疗健康信息"},
		{"Healthline", "https://www.healthline.com", "健康资讯平台"},
		{"Mayo Clinic", "https://www.mayoclinic.org", "梅奥诊所"},
		{"Cleveland Clinic", "https://my.clevelandclinic.org", "克利夫兰诊所"},
		{"Johns Hopkins Medicine", "https://www.hopkinsmedicine.org", "约翰霍普金斯"},
		{"NHS", "https://www.nhs.uk", "英国国家医疗"},
		{"WHO", "https://www.who.int", "世界卫生组织"},
		{"CDC", "https://www.cdc.gov", "美国疾控中心"},
		{"Drugs.com", "https://www.drugs.com", "药品信息查询"},
		{"GoodRx", "https://www.goodrx.com", "药品价格比较"},
		{"Zocdoc", "https://www.zocdoc.com", "在线预约挂号"},
		{"Teladoc", "https://www.teladoc.com", "远程医疗平台"},
		{"MDLive", "https://www.mdlive.com", "在线问诊"},
		{"BetterHelp", "https://www.betterhelp.com", "在线心理咨询"},
		{"Talkspace", "https://www.talkspace.com", "在线心理治疗"},
		{"Noom", "https://www.noom.com", "减重健康App"},
		{"Fitbit", "https://www.fitbit.com", "运动健康追踪"},
		{"Apple Health", "https://www.apple.com/health", "苹果健康应用"},
		{"Samsung Health", "https://www.samsung.com/global/galaxy/apps/samsung-health", "三星健康"},
		{"Garmin Connect", "https://connect.garmin.com", "佳明运动健康"},
		{"Withings", "https://www.withings.com", "智能健康设备"},
		{"Oura Ring", "https://ouraring.com", "睡眠健康追踪"},
		{"Whoop", "https://www.whoop.com", "运动恢复追踪"},
		{"Strava", "https://www.strava.com", "运动追踪社交"},
		{"Nike Training Club", "https://www.nike.com/ntc-app", "Nike训练App"},
		{"Peloton", "https://www.onepeloton.com", "健身课程平台"},
		{"Sweat", "https://www.sweat.com", "女性健身App"},
		{"Yoga with Adriene", "https://yogawithadriene.com", "瑜伽教程"},
		{"Down Dog", "https://www.downdogapp.com", "AI瑜伽App"},
		{"薄荷健康", "https://www.boohee.com", "饮食健康管理"},
	}
}

func sportsBoost() []S {
	return []S{
		{"ESPN", "https://www.espn.com", "ESPN体育"},
		{"BBC Sport", "https://www.bbc.com/sport", "BBC体育"},
		{"Sky Sports", "https://www.skysports.com", "天空体育"},
		{"Bleacher Report", "https://bleacherreport.com", "体育资讯"},
		{"The Athletic", "https://theathletic.com", "体育深度报道"},
		{"Sports Illustrated", "https://www.si.com", "体育画报"},
		{"Yahoo Sports", "https://sports.yahoo.com", "雅虎体育"},
		{"NBA.com", "https://www.nba.com", "NBA官网"},
		{"FIFA", "https://www.fifa.com", "国际足联"},
		{"UEFA", "https://www.uefa.com", "欧洲足联"},
		{"Premier League", "https://www.premierleague.com", "英超联赛"},
		{"La Liga", "https://www.laliga.com", "西甲联赛"},
		{"Bundesliga", "https://www.bundesliga.com", "德甲联赛"},
		{"Serie A", "https://www.legaseriea.it", "意甲联赛"},
		{"MLB", "https://www.mlb.com", "美国职棒"},
		{"NFL", "https://www.nfl.com", "美国橄榄球"},
		{"NHL", "https://www.nhl.com", "冰球联盟"},
		{"ATP Tour", "https://www.atptour.com", "ATP网球"},
		{"WTA Tennis", "https://www.wtatennis.com", "WTA网球"},
		{"World Athletics", "https://worldathletics.org", "世界田联"},
		{"Formula 1", "https://www.formula1.com", "F1赛车"},
		{"MotoGP", "https://www.motogp.com", "MotoGP摩托"},
		{"UFC", "https://www.ufc.com", "终极格斗"},
		{"WWE", "https://www.wwe.com", "世界摔角"},
		{"Tour de France", "https://www.letour.fr", "环法自行车"},
		{"Olympic.org", "https://olympics.com", "奥运会官网"},
		{"Transfermarkt", "https://www.transfermarkt.com", "球员转会市场"},
		{"WhoScored", "https://www.whoscored.com", "足球数据评分"},
		{"FBref", "https://fbref.com", "足球统计数据"},
		{"FlashScore", "https://www.flashscore.com", "实时比分"},
	}
}

func photographyBoost() []S {
	return []S{
		{"500px", "https://500px.com", "摄影师社区"},
		{"Flickr", "https://www.flickr.com", "图片分享社区"},
		{"SmugMug", "https://www.smugmug.com", "摄影师网站"},
		{"Glass", "https://glass.photo", "摄影社交平台"},
		{"VSCO", "https://vsco.co", "照片编辑社区"},
		{"Adobe Lightroom", "https://www.adobe.com/products/photoshop-lightroom.html", "专业修图软件"},
		{"Capture One", "https://www.captureone.com", "专业RAW处理"},
		{"DxO", "https://www.dxo.com", "照片光学处理"},
		{"Darktable", "https://www.darktable.org", "开源RAW编辑"},
		{"RawTherapee", "https://rawtherapee.com", "开源RAW处理"},
		{"DPReview", "https://www.dpreview.com", "相机评测"},
		{"Photography Life", "https://photographylife.com", "摄影教程评测"},
		{"Fstoppers", "https://fstoppers.com", "摄影师社区"},
		{"PetaPixel", "https://petapixel.com", "摄影资讯博客"},
		{"DIY Photography", "https://www.diyphotography.net", "摄影DIY"},
		{"ShotKit", "https://shotkit.com", "摄影器材推荐"},
		{"Ken Rockwell", "https://www.kenrockwell.com", "摄影器材评测"},
		{"The Phoblographer", "https://www.thephoblographer.com", "摄影评论"},
		{"LensTip", "https://www.lenstip.com", "镜头测试数据"},
		{"Photopills", "https://www.photopills.com", "摄影计划App"},
		{"色影无忌", "https://www.xitek.com", "中文摄影论坛"},
		{"蜂鸟网", "https://www.fengniao.com", "摄影器材资讯"},
		{"图虫", "https://tuchong.com", "摄影师社区"},
		{"米拍", "https://www.mepai.me", "摄影作品分享"},
		{"POCO摄影", "https://www.poco.cn", "摄影社区"},
		{"影像视觉", "https://www.photoworld.com.cn", "摄影杂志"},
		{"Pixieset", "https://pixieset.com", "摄影师交付平台"},
		{"ShootProof", "https://www.shootproof.com", "摄影师画廊"},
		{"Pic-Time", "https://pic-time.com", "摄影师交付"},
		{"Format", "https://www.format.com", "作品集网站"},
	}
}
