package main

// Batch 3 extension data: Startup, Legal, Pets, Fashion, Kids, Agriculture, Environment

func startupEx() []S {
	return []S{
		{"Y Combinator", "https://www.ycombinator.com", "YC加速器"},
		{"Techstars", "https://www.techstars.com", "创业加速器"},
		{"500 Global", "https://500.co", "创业投资"},
		{"Sequoia Capital", "https://www.sequoiacap.com", "红杉资本"},
		{"Andreessen Horowitz", "https://a16z.com", "a16z"},
		{"Benchmark", "https://www.benchmark.com", "Benchmark资本"},
		{"Accel", "https://www.accel.com", "Accel创投"},
		{"Greylock", "https://greylock.com", "Greylock合伙人"},
		{"Lightspeed", "https://lsvp.com", "光速创投"},
		{"Index Ventures", "https://www.indexventures.com", "Index创投"},
		{"Kleiner Perkins", "https://www.kleinerperkins.com", "KPCB"},
		{"NEA", "https://www.nea.com", "新企业联合"},
		{"GGV Capital", "https://www.ggvc.com", "纪源资本"},
		{"Tiger Global", "https://www.tigerglobal.com", "老虎基金"},
		{"SoftBank Vision", "https://visionfund.com", "软银愿景"},
		{"First Round Capital", "https://firstround.com", "首轮资本"},
		{"Union Square Ventures", "https://www.usv.com", "联合广场"},
		{"Founders Fund", "https://foundersfund.com", "创始人基金"},
		{"General Catalyst", "https://www.generalcatalyst.com", "通用催化"},
		{"Bessemer", "https://www.bvp.com", "Bessemer创投"},
		{"Insight Partners", "https://www.insightpartners.com", "Insight合伙人"},
		{"Battery Ventures", "https://www.battery.com", "Battery创投"},
		{"Sapphire Ventures", "https://sapphireventures.com", "蓝宝石创投"},
		{"Spark Capital", "https://www.sparkcapital.com", "Spark资本"},
		{"Ribbit Capital", "https://ribbitcap.com", "Ribbit资本"},
		{"Crunchbase", "https://www.crunchbase.com", "创业数据库"},
		{"PitchBook", "https://pitchbook.com", "风投数据"},
		{"CB Insights", "https://www.cbinsights.com", "创投分析"},
		{"Dealroom", "https://dealroom.co", "创业数据"},
		{"TechCrunch", "https://techcrunch.com", "科技创业新闻"},
		{"VentureBeat", "https://venturebeat.com", "创业科技"},
		{"The Information", "https://www.theinformation.com", "科技深度报道"},
		{"Sifted", "https://sifted.eu", "欧洲创业"},
		{"TechInAsia", "https://www.techinasia.com", "亚洲科技"},
		{"KrASIA", "https://kr-asia.com", "亚洲创业"},
		{"e27", "https://e27.co", "东南亚创业"},
		{"ProductHunt", "https://www.producthunt.com", "产品发现"},
		{"BetaList", "https://betalist.com", "创业产品"},
		{"Launching Next", "https://www.launchingnext.com", "新产品发现"},
		{"StartupStash", "https://startupstash.com", "创业工具"},
		{"StartupResources", "https://startupresources.io", "创业资源"},
		{"Indie Hackers", "https://www.indiehackers.com", "独立开发者"},
		{"MicroConf", "https://microconf.com", "小型SaaS"},
		{"SaaStr", "https://www.saastr.com", "SaaS社区"},
		{"OpenVC", "https://www.openvc.app", "融资对接"},
		{"Carta", "https://carta.com", "股权管理"},
		{"Pulley", "https://pulley.com", "股权管理"},
		{"Capbase", "https://capbase.com", "创业法务"},
		{"Clerky", "https://www.clerky.com", "创业法律文件"},
		{"Stripe Atlas", "https://stripe.com/atlas", "创业注册"},
		{"Firstbase", "https://firstbase.io", "美国公司注册"},
		{"Gust", "https://gust.com", "天使投资平台"},
		{"AngelList", "https://www.angellist.com", "创业平台"},
		{"Republic", "https://republic.com", "股权众筹"},
		{"Wefunder", "https://wefunder.com", "众筹投资"},
		{"SeedInvest", "https://www.seedinvest.com", "股权众筹"},
		{"StartEngine", "https://www.startengine.com", "众筹平台"},
		{"Kickstarter", "https://www.kickstarter.com", "众筹平台"},
		{"Indiegogo", "https://www.indiegogo.com", "众筹平台"},
		{"GoFundMe", "https://www.gofundme.com", "个人众筹"},
		{"36氪", "https://36kr.com", "中国科技创业"},
		{"IT桔子", "https://www.itjuzi.com", "中国创投数据"},
		{"投资界", "https://www.pedaily.cn", "中国PE/VC"},
		{"创业邦", "https://www.cyzone.cn", "中国创业媒体"},
		{"猎云网", "https://www.lieyunwang.com", "创业投资"},
		{"虎嗅", "https://www.huxiu.com", "科技商业"},
		{"钛媒体", "https://www.tmtpost.com", "科技财经"},
		{"品玩", "https://www.pingwest.com", "全球科技"},
		{"少数派", "https://sspai.com", "数字生活"},
		{"极客公园", "https://www.geekpark.net", "创业科技"},
		{"IDG资本", "https://www.idgcapital.com", "IDG资本"},
		{"红杉中国", "https://www.hongshan.com", "红杉中国"},
		{"高瓴", "https://www.hillhousecapital.com", "高瓴资本"},
		{"真格基金", "https://www.zhenfund.com", "真格基金"},
		{"经纬中国", "https://www.matrixpartners.com.cn", "经纬创投"},
		{"源码资本", "https://www.sourcecodecapital.com", "源码资本"},
		{"金沙江创投", "https://www.gobi.com.cn", "金沙江"},
		{"Notion for Startups", "https://www.notion.so/startups", "Notion创业版"},
		{"AWS Startups", "https://aws.amazon.com/startups", "AWS创业支持"},
		{"Google for Startups", "https://startup.google.com", "谷歌创业"},
		{"Microsoft for Startups", "https://www.microsoft.com/en-us/startups", "微软创业"},
		{"Startup Genome", "https://startupgenome.com", "创业生态报告"},
		{"Startup Grind", "https://www.startupgrind.com", "创业社区"},
		{"Founder Collective", "https://foundercollective.com", "种子基金"},
		{"Village Global", "https://www.villageglobal.vc", "创投基金"},
		{"NFX", "https://www.nfx.com", "网络效应创投"},
		{"Hustle Fund", "https://www.hustlefund.vc", "Pre-seed基金"},
		{"Pioneer", "https://pioneer.app", "在线加速器"},
		{"Entrepreneur First", "https://www.joinef.com", "人才优先创业"},
		{"Antler", "https://www.antler.co", "全球创业平台"},
		{"On Deck", "https://www.beondeck.com", "创始人社区"},
		{"Lean Startup", "https://theleanstartup.com", "精益创业"},
		{"Startup School", "https://www.startupschool.org", "YC创业学校"},
		{"How to Start a Startup", "https://startupclass.samaltman.com", "创业课程"},
		{"Paul Graham Essays", "https://www.paulgraham.com/articles.html", "PG文章"},
		{"First Round Review", "https://review.firstround.com", "创业管理知识"},
		{"a16z Podcast", "https://a16z.com/podcasts", "a16z播客"},
		{"This Week in Startups", "https://thisweekinstartups.com", "创业播客"},
		{"Masters of Scale", "https://mastersofscale.com", "规模化播客"},
		{"How I Built This", "https://www.npr.org/series/how-i-built-this", "创业故事"},
		{"My First Million", "https://www.mfmpod.com", "商业创意"},
		{"Acquired", "https://www.acquired.fm", "科技并购故事"},
		{"Lenny's Newsletter", "https://www.lennysnewsletter.com", "产品增长"},
		{"Stratechery", "https://stratechery.com", "科技商业分析"},
		{"Not Boring", "https://www.notboring.co", "创业分析"},
		{"The Generalist", "https://www.readthegeneralist.com", "科技深度"},
		{"Failory", "https://www.failory.com", "创业失败案例"},
	}
}

func legalEx() []S {
	return []S{
		{"LexisNexis", "https://www.lexisnexis.com", "法律数据库"},
		{"Westlaw", "https://www.westlaw.com", "法律研究"},
		{"Bloomberg Law", "https://www.bloomberglaw.com", "法律新闻数据"},
		{"Casetext", "https://casetext.com", "AI法律搜索"},
		{"Fastcase", "https://www.fastcase.com", "法律研究"},
		{"Google Scholar Legal", "https://scholar.google.com/scholar?as_sdt=4", "判例法搜索"},
		{"CourtListener", "https://www.courtlistener.com", "法院判决搜索"},
		{"Justia", "https://www.justia.com", "免费法律信息"},
		{"FindLaw", "https://www.findlaw.com", "法律信息"},
		{"Nolo", "https://www.nolo.com", "法律自助"},
		{"Avvo", "https://www.avvo.com", "找律师"},
		{"LegalZoom", "https://www.legalzoom.com", "在线法律服务"},
		{"Rocket Lawyer", "https://www.rocketlawyer.com", "在线法律"},
		{"LawDepot", "https://www.lawdepot.com", "法律文件模板"},
		{"DocuSign", "https://www.docusign.com", "电子签名"},
		{"HelloSign", "https://www.hellosign.com", "电子签名"},
		{"PandaDoc", "https://www.pandadoc.com", "文档签名"},
		{"Ironclad", "https://ironcladapp.com", "合同管理"},
		{"ContractPodAi", "https://contractpodai.com", "AI合同管理"},
		{"Juro", "https://juro.com", "合同自动化"},
		{"Agiloft", "https://www.agiloft.com", "合同生命周期"},
		{"Clio", "https://www.clio.com", "律所管理软件"},
		{"MyCase", "https://www.mycase.com", "法律实践管理"},
		{"PracticePanther", "https://www.practicepanther.com", "律所管理"},
		{"Smokeball", "https://www.smokeball.com", "律所管理"},
		{"CosmoLex", "https://www.cosmolex.com", "法律实践软件"},
		{"ActionStep", "https://www.actionstep.com", "法律工作流"},
		{"LawPay", "https://lawpay.com", "律师收款"},
		{"TimeSolv", "https://www.timesolv.com", "律师计时"},
		{"ROSS Intelligence", "https://rossintelligence.com", "AI法律研究"},
		{"Harvey AI", "https://www.harvey.ai", "AI法律助手"},
		{"Spellbook", "https://www.spellbook.legal", "AI合同起草"},
		{"EvenUp", "https://www.evenuplaw.com", "AI伤害索赔"},
		{"Luminance", "https://www.luminance.com", "AI法律分析"},
		{"Kira Systems", "https://kirasystems.com", "合同分析"},
		{"Relativity", "https://www.relativity.com", "电子取证"},
		{"Logikcull", "https://www.logikcull.com", "文档发现"},
		{"Everlaw", "https://www.everlaw.com", "诉讼平台"},
		{"Lex Machina", "https://lexmachina.com", "法律分析"},
		{"Premonition", "https://premonition.ai", "诉讼预测"},
		{"北大法宝", "https://www.pkulaw.com", "中国法律数据库"},
		{"中国法律信息网", "https://www.law-lib.com", "法律信息网"},
		{"裁判文书网", "https://wenshu.court.gov.cn", "中国裁判文书"},
		{"中国庭审公开网", "https://tingshen.court.gov.cn", "庭审直播"},
		{"无讼", "https://www.itslaw.com", "中国法律检索"},
		{"法信", "https://www.faxin.cn", "法律知识"},
		{"律师365", "https://www.64365.com", "找律师"},
		{"华律网", "https://www.66law.cn", "法律咨询"},
		{"法律快车", "https://www.lawtime.cn", "法律服务"},
		{"法大大", "https://www.fadada.com", "电子合同"},
		{"e签宝", "https://www.esign.cn", "电子签章"},
		{"上上签", "https://www.bestsign.cn", "电子签名"},
		{"中国专利信息", "https://www.cnipa.gov.cn", "专利信息"},
		{"SooPAT", "https://www.soopat.com", "专利搜索"},
		{"佰腾", "https://www.baiten.cn", "专利检索"},
		{"Cornell LII", "https://www.law.cornell.edu", "法律信息学院"},
		{"Oyez", "https://www.oyez.org", "最高法院音频"},
		{"SCOTUSblog", "https://www.scotusblog.com", "最高法院博客"},
		{"Law.com", "https://www.law.com", "法律新闻"},
		{"Above the Law", "https://abovethelaw.com", "法律博客"},
		{"The Lawyer", "https://www.thelawyer.com", "英国法律"},
		{"Legal Cheek", "https://www.legalcheek.com", "法律职业"},
		{"JD Supra", "https://www.jdsupra.com", "法律文章"},
		{"Mondaq", "https://www.mondaq.com", "法律商业"},
		{"Chambers", "https://chambers.com", "律所排名"},
		{"Legal 500", "https://www.legal500.com", "律所排名"},
		{"Martindale", "https://www.martindale.com", "律师目录"},
		{"Super Lawyers", "https://www.superlawyers.com", "律师推荐"},
		{"ABA", "https://www.americanbar.org", "美国律师协会"},
		{"NALP", "https://www.nalp.org", "法律就业"},
		{"Lawtrina", "https://lawtrina.com", "法律教育"},
		{"BarBri", "https://www.barbri.com", "律师考试备考"},
		{"Themis Bar", "https://www.themisbar.com", "律师资格"},
		{"Kaplan Bar", "https://www.kaptest.com/bar-exam", "律师考试"},
		{"AdaptiBar", "https://www.adaptibar.com", "律考练习"},
		{"EUR-Lex", "https://eur-lex.europa.eu", "欧盟法律"},
		{"BAILII", "https://www.bailii.org", "英国法律"},
		{"Legislation.gov.uk", "https://www.legislation.gov.uk", "英国法规"},
		{"Bundesrecht", "https://www.gesetze-im-internet.de", "德国法律"},
		{"Légifrance", "https://www.legifrance.gouv.fr", "法国法律"},
		{"e-Justice Portal", "https://e-justice.europa.eu", "欧洲司法"},
		{"ICLG", "https://iclg.com", "国际比较法"},
		{"GlobaLex", "https://www.nyulawglobal.org/globalex", "国际法律研究"},
		{"WIPO Lex", "https://www.wipo.int/wipolex", "知识产权法"},
		{"Free Law Project", "https://free.law", "法律开放数据"},
		{"Clerk.io", "https://www.clerk.io", "法律科技"},
		{"ContractExpress", "https://www.contractexpress.com", "合同自动化"},
		{"LegalSifter", "https://www.legalsifter.com", "AI合同审查"},
		{"LawGeex", "https://www.lawgeex.com", "AI合同分析"},
		{"Diligence Engine", "https://kirasystems.com", "尽职调查"},
		{"Legal.io", "https://www.legal.io", "法律科技社区"},
		{"Artificial Lawyer", "https://www.artificiallawyer.com", "法律AI新闻"},
		{"LawSites", "https://www.lawnext.com", "法律科技博客"},
		{"TechnoLawyer", "https://www.technolawyer.com", "法律技术"},
		{"DoNotPay", "https://donotpay.com", "AI法律助手"},
		{"LegalNature", "https://www.legalnature.com", "法律文件"},
		{"Incfile", "https://www.incfile.com", "公司注册"},
		{"Northwest RA", "https://www.northwestregisteredagent.com", "注册代理"},
		{"ZenBusiness", "https://www.zenbusiness.com", "公司注册"},
		{"BizFilings", "https://www.bizfilings.com", "公司注册"},
		{"Legalese Decoder", "https://legalesedecoder.com", "法律术语解读"},
		{"Plain Language", "https://www.plainlanguage.gov", "简明语言"},
	}
}

func petsEx() []S {
	return []S{
		{"PetFinder", "https://www.petfinder.com", "宠物领养"},
		{"Adopt-a-Pet", "https://www.adoptapet.com", "宠物收养"},
		{"ASPCA", "https://www.aspca.org", "动物保护协会"},
		{"Humane Society", "https://www.humanesociety.org", "人道主义协会"},
		{"Best Friends", "https://bestfriends.org", "动物救助"},
		{"AKC", "https://www.akc.org", "美国犬业俱乐部"},
		{"Westminster Dog Show", "https://www.westminsterkennelclub.org", "威斯敏斯特犬展"},
		{"The Kennel Club", "https://www.thekennelclub.org.uk", "英国犬业"},
		{"FCI", "https://www.fci.be", "世界犬业联盟"},
		{"CFA", "https://cfa.org", "猫爱好者协会"},
		{"TICA", "https://tica.org", "国际猫协会"},
		{"Rover", "https://www.rover.com", "宠物寄养遛狗"},
		{"Wag!", "https://wagwalking.com", "遛狗服务"},
		{"Care.com Pets", "https://www.care.com/pet-care", "宠物护理"},
		{"TrustedHousesitters", "https://www.trustedhousesitters.com", "看房看宠物"},
		{"Chewy", "https://www.chewy.com", "宠物用品电商"},
		{"Petco", "https://www.petco.com", "宠物用品商店"},
		{"PetSmart", "https://www.petsmart.com", "宠物用品"},
		{"BarkBox", "https://www.barkbox.com", "狗狗订阅盒"},
		{"KitNipBox", "https://www.kitnipbox.com", "猫咪订阅盒"},
		{"PetPlate", "https://www.petplate.com", "鲜食狗粮"},
		{"The Farmer's Dog", "https://www.thefarmersdog.com", "定制狗粮"},
		{"Ollie", "https://www.myollie.com", "鲜食狗粮"},
		{"NomNomNow", "https://www.nomnomnow.com", "宠物鲜食"},
		{"JustFoodForDogs", "https://www.justfoodfordogs.com", "狗粮"},
		{"Nom Nom", "https://www.nomnomnow.com", "定制宠物食品"},
		{"Petcube", "https://petcube.com", "宠物摄像头"},
		{"Furbo", "https://shopus.furbo.com", "狗狗摄像头"},
		{"Fi Collar", "https://tryfi.com", "智能狗项圈"},
		{"Whistle", "https://www.whistle.com", "宠物GPS追踪"},
		{"Litter-Robot", "https://www.litter-robot.com", "自动猫砂盆"},
		{"PetSafe", "https://www.petsafe.net", "宠物安全产品"},
		{"Kong", "https://www.kongcompany.com", "宠物玩具"},
		{"PetMD", "https://www.petmd.com", "宠物健康"},
		{"VCA Hospitals", "https://vcahospitals.com", "宠物医院"},
		{"Banfield Pet Hospital", "https://www.banfield.com", "宠物医院"},
		{"VetStreet", "https://www.vetstreet.com", "宠物护理信息"},
		{"PetCoach", "https://www.petcoach.co", "宠物健康咨询"},
		{"Fuzzy Pet Health", "https://www.fuzzy.com", "在线宠物医疗"},
		{"Dutch", "https://www.dutch.com", "远程宠物医生"},
		{"Pawp", "https://pawp.com", "宠物远程医疗"},
		{"Vetster", "https://vetster.com", "在线兽医"},
		{"Trupanion", "https://trupanion.com", "宠物保险"},
		{"Healthy Paws", "https://www.healthypawspetinsurance.com", "宠物保险"},
		{"Lemonade Pet", "https://www.lemonade.com/pet", "宠物保险"},
		{"FIGO", "https://figopetinsurance.com", "宠物保险"},
		{"Embrace", "https://www.embracepetinsurance.com", "宠物保险"},
		{"Pumpkin", "https://www.pumpkin.care", "宠物保险"},
		{"Dogster", "https://www.dogster.com", "狗狗杂志"},
		{"Catster", "https://www.catster.com", "猫咪杂志"},
		{"The Dodo", "https://www.thedodo.com", "动物故事"},
		{"BarkPost", "https://barkpost.com", "狗狗内容"},
		{"Cat Time", "https://cattime.com", "猫咪资讯"},
		{"DogTime", "https://dogtime.com", "狗狗资讯"},
		{"Pets4Homes", "https://www.pets4homes.co.uk", "英国宠物"},
		{"Gumtree Pets", "https://www.gumtree.com/pets", "英国宠物"},
		{"Zooplus", "https://www.zooplus.com", "欧洲宠物电商"},
		{"波奇网", "https://www.boqii.com", "中国宠物平台"},
		{"E宠商城", "https://www.epet.com", "中国宠物电商"},
		{"有宠", "https://www.youchong.com", "中国宠物社区"},
		{"狗民网", "https://www.goumin.com", "中国养狗社区"},
		{"猫扑", "https://www.mop.com", "宠物社区"},
		{"宠物家", "https://www.petjia.com", "宠物服务"},
		{"瑞鹏宠物", "https://www.rpvet.cn", "宠物医疗"},
		{"新瑞鹏", "https://www.newruipeng.com", "宠物连锁医院"},
		{"Vetoquinol", "https://www.vetoquinol.com", "动物药品"},
		{"Zoetis", "https://www.zoetis.com", "动物保健"},
		{"Mars Petcare", "https://www.mars.com/made-by-mars/petcare", "宠物食品"},
		{"Royal Canin", "https://www.royalcanin.com", "皇家宠物食品"},
		{"Hill's Pet", "https://www.hillspet.com", "希尔斯宠物"},
		{"Purina", "https://www.purina.com", "普瑞纳"},
		{"Blue Buffalo", "https://www.bluebuffalo.com", "蓝馔"},
		{"Orijen", "https://www.orijen.ca", "渴望猫狗粮"},
		{"Acana", "https://www.acana.com", "爱肯拿"},
		{"Ziwi Peak", "https://www.ziwipets.com", "巅峰"},
		{"Canidae", "https://www.canidae.com", "狗粮"},
		{"Taste of the Wild", "https://www.tasteofthewildpetfood.com", "荒野盛宴"},
		{"Wellness Pet", "https://www.wellnesspetfood.com", "自然宠物粮"},
		{"Reddit Pets", "https://www.reddit.com/r/pets", "Reddit宠物社区"},
		{"Reddit Cats", "https://www.reddit.com/r/cats", "Reddit猫咪"},
		{"Reddit Dogs", "https://www.reddit.com/r/dogs", "Reddit狗狗"},
		{"Instagram Pets", "https://www.instagram.com/explore/tags/pets", "宠物Instagram"},
		{"TikTok Pets", "https://www.tiktok.com/tag/pets", "宠物TikTok"},
		{"Bored Panda Pets", "https://www.boredpanda.com/animals", "宠物趣图"},
		{"Cuteness", "https://www.cuteness.com", "可爱宠物"},
		{"Animal Planet", "https://www.animalplanet.com", "动物星球"},
		{"National Geographic Animals", "https://www.nationalgeographic.com/animals", "国家地理动物"},
		{"World Wildlife Fund", "https://www.worldwildlife.org", "世界自然基金"},
		{"Wildlife Conservation", "https://www.wcs.org", "野生动物保护"},
		{"Jane Goodall Institute", "https://www.janegoodall.org", "珍·古道尔研究"},
		{"Born Free", "https://www.bornfree.org.uk", "生而自由"},
		{"RSPCA", "https://www.rspca.org.uk", "皇家防虐动物"},
		{"PETA", "https://www.peta.org", "动物权利组织"},
		{"World Animal Protection", "https://www.worldanimalprotection.org", "世界动物保护"},
		{"PetRescue", "https://www.petrescue.com.au", "澳洲宠物救助"},
		{"Rescue Me!", "https://www.rescueme.org", "动物救助"},
		{"Embark", "https://embarkvet.com", "狗狗基因检测"},
		{"Wisdom Panel", "https://www.wisdompanel.com", "宠物DNA"},
		{"Basepaws", "https://www.basepaws.com", "猫咪基因测试"},
		{"GoodDog", "https://www.gooddog.com", "犬种信息"},
		{"PuppyFind", "https://www.puppyfind.com", "找小狗"},
		{"NextDayPets", "https://www.nextdaypets.com", "宠物市场"},
		{"PetCoach", "https://www.petcoach.co", "宠物训练"},
		{"Pupford", "https://www.pupford.com", "狗狗训练"},
		{"GoodPup", "https://goodpup.com", "在线狗狗训练"},
		{"SpiritDog", "https://spiritdogtraining.com", "狗狗训练"},
		{"Zak George", "https://www.youtube.com/c/zakgeorge", "狗狗训练视频"},
	}
}

func fashionEx() []S {
	return []S{
		{"Vogue", "https://www.vogue.com", "时尚杂志"},
		{"Elle", "https://www.elle.com", "时尚杂志"},
		{"Harper's Bazaar", "https://www.harpersbazaar.com", "时尚杂志"},
		{"Marie Claire", "https://www.marieclaire.com", "女性时尚"},
		{"Cosmopolitan", "https://www.cosmopolitan.com", "时尚生活"},
		{"GQ", "https://www.gq.com", "男性时尚"},
		{"Esquire", "https://www.esquire.com", "男性杂志"},
		{"W Magazine", "https://www.wmagazine.com", "艺术时尚"},
		{"Allure", "https://www.allure.com", "美妆杂志"},
		{"Glamour", "https://www.glamour.com", "时尚美妆"},
		{"InStyle", "https://www.instyle.com", "时尚生活"},
		{"Vanity Fair", "https://www.vanityfair.com", "时尚文化"},
		{"Dazed", "https://www.dazeddigital.com", "先锋时尚"},
		{"i-D", "https://i-d.vice.com", "时尚文化"},
		{"Highsnobiety", "https://www.highsnobiety.com", "潮流文化"},
		{"Hypebeast", "https://hypebeast.com", "潮流资讯"},
		{"Complex", "https://www.complex.com", "潮流文化"},
		{"Refinery29", "https://www.refinery29.com", "女性时尚"},
		{"Who What Wear", "https://www.whowhatwear.com", "时尚穿搭"},
		{"The Cut", "https://www.thecut.com", "时尚生活"},
		{"Business of Fashion", "https://www.businessoffashion.com", "时尚商业"},
		{"Fashionista", "https://fashionista.com", "时尚行业"},
		{"WWD", "https://wwd.com", "时尚日报"},
		{"Vogue Business", "https://www.voguebusiness.com", "时尚商业"},
		{"Drapers", "https://www.drapersonline.com", "时尚零售"},
		{"LVMH", "https://www.lvmh.com", "奢侈品集团"},
		{"Kering", "https://www.kering.com", "开云集团"},
		{"Richemont", "https://www.richemont.com", "历峰集团"},
		{"Farfetch", "https://www.farfetch.com", "奢侈品电商"},
		{"Net-a-Porter", "https://www.net-a-porter.com", "高端时尚电商"},
		{"MatchesFashion", "https://www.matchesfashion.com", "设计师时尚"},
		{"Ssense", "https://www.ssense.com", "高端时尚"},
		{"Mytheresa", "https://www.mytheresa.com", "奢侈品电商"},
		{"24S", "https://www.24s.com", "LVMH电商"},
		{"Nordstrom", "https://www.nordstrom.com", "百货商店"},
		{"Saks Fifth Avenue", "https://www.saksfifthavenue.com", "高端百货"},
		{"Neiman Marcus", "https://www.neimanmarcus.com", "奢侈品百货"},
		{"Bergdorf Goodman", "https://www.bergdorfgoodman.com", "高端百货"},
		{"Zara", "https://www.zara.com", "快时尚"},
		{"H&M", "https://www.hm.com", "快时尚"},
		{"Uniqlo", "https://www.uniqlo.com", "优衣库"},
		{"ASOS", "https://www.asos.com", "在线时尚"},
		{"Boohoo", "https://www.boohoo.com", "快时尚"},
		{"Shein", "https://www.shein.com", "超快时尚"},
		{"Temu Fashion", "https://www.temu.com", "拼多多海外"},
		{"Revolve", "https://www.revolve.com", "网红时尚"},
		{"Free People", "https://www.freepeople.com", "波西米亚时尚"},
		{"Anthropologie", "https://www.anthropologie.com", "生活方式时尚"},
		{"Urban Outfitters", "https://www.urbanoutfitters.com", "青年时尚"},
		{"Everlane", "https://www.everlane.com", "透明定价时尚"},
		{"Reformation", "https://www.thereformation.com", "可持续时尚"},
		{"Patagonia", "https://www.patagonia.com", "环保户外"},
		{"The RealReal", "https://www.therealreal.com", "二手奢侈品"},
		{"Vestiaire Collective", "https://www.vestiairecollective.com", "二手奢侈品"},
		{"Poshmark", "https://poshmark.com", "二手时尚"},
		{"ThredUp", "https://www.thredup.com", "二手衣物"},
		{"Depop", "https://www.depop.com", "年轻人二手"},
		{"Mercari Fashion", "https://www.mercari.com", "二手市场"},
		{"StockX", "https://stockx.com", "球鞋交易"},
		{"GOAT", "https://www.goat.com", "球鞋交易"},
		{"Grailed", "https://www.grailed.com", "男装二手"},
		{"Sephora", "https://www.sephora.com", "美妆电商"},
		{"Ulta Beauty", "https://www.ulta.com", "美妆零售"},
		{"Glossier", "https://www.glossier.com", "美妆品牌"},
		{"Fenty Beauty", "https://fentybeauty.com", "Rihanna美妆"},
		{"Charlotte Tilbury", "https://www.charlottetilbury.com", "彩妆品牌"},
		{"Drunk Elephant", "https://www.drunkelephant.com", "护肤品牌"},
		{"The Ordinary", "https://theordinary.com", "平价护肤"},
		{"CeraVe", "https://www.cerave.com", "药妆护肤"},
		{"Paula's Choice", "https://www.paulaschoice.com", "成分护肤"},
		{"BeautyCounter", "https://www.beautycounter.com", "清洁美妆"},
		{"Beautylish", "https://www.beautylish.com", "美妆社区"},
		{"Temptalia", "https://www.temptalia.com", "美妆评测"},
		{"Into The Gloss", "https://intothegloss.com", "美妆博客"},
		{"Beauty Insider", "https://www.allure.com/beauty-products", "美妆内幕"},
		{"小红书时尚", "https://www.xiaohongshu.com/explore/fashion", "时尚笔记"},
		{"得物", "https://www.dewu.com", "潮流鉴定交易"},
		{"毒", "https://www.poizon.com", "球鞋潮流"},
		{"天猫时尚", "https://www.tmall.com", "天猫时尚"},
		{"唯品会", "https://www.vip.com", "品牌特卖"},
		{"寺库", "https://www.secoo.com", "中国奢侈品电商"},
		{"Lookastic", "https://lookastic.com", "穿搭建议"},
		{"Polyvore", "https://www.polyvore.com", "穿搭搭配"},
		{"StyleCraze", "https://www.stylecraze.com", "美妆时尚"},
		{"Byrdie", "https://www.byrdie.com", "美妆护肤"},
		{"Coveteur", "https://coveteur.com", "时尚内幕"},
		{"Man Repeller", "https://www.leandracohen.com", "时尚博客"},
		{"The Sartorialist", "https://www.thesartorialist.com", "街拍时尚"},
		{"Lookbook.nu", "https://lookbook.nu", "穿搭社区"},
		{"Chictopia", "https://www.chictopia.com", "穿搭分享"},
		{"Lyst", "https://www.lyst.com", "时尚搜索"},
		{"ShopStyle", "https://www.shopstyle.com", "时尚购物搜索"},
		{"Rent the Runway", "https://www.renttherunway.com", "租衣服"},
		{"Nuuly", "https://www.nuuly.com", "服装租赁"},
		{"Stitch Fix", "https://www.stitchfix.com", "个性化造型"},
		{"Trunk Club", "https://www.trunkclub.com", "造型服务"},
		{"FashionPhile", "https://www.fashionphile.com", "二手奢包"},
		{"Rebag", "https://www.rebag.com", "奢侈包交易"},
		{"Tradesy", "https://www.tradesy.com", "二手时尚"},
		{"Vestiaire", "https://www.vestiairecollective.com", "二手奢侈"},
		{"美丽说", "https://www.meilishuo.com", "中国时尚社区"},
		{"蘑菇街", "https://www.mogujie.com", "女性时尚电商"},
		{"YOHO", "https://www.yoho.cn", "中国潮流"},
		{"ICY全球设计师", "https://www.icydesign.com", "设计师电商"},
		{"Farfetch中国", "https://www.farfetch.cn", "奢侈品电商"},
	}
}

func kidsEx() []S {
	return []S{
		{"BabyCenter", "https://www.babycenter.com", "孕育指南"},
		{"What to Expect", "https://www.whattoexpect.com", "孕期指南"},
		{"The Bump", "https://www.thebump.com", "孕产育儿"},
		{"Parents Magazine", "https://www.parents.com", "育儿杂志"},
		{"Motherly", "https://www.mother.ly", "母亲社区"},
		{"Scary Mommy", "https://www.scarymommy.com", "育儿博客"},
		{"Romper", "https://www.romper.com", "育儿生活"},
		{"Fatherly", "https://www.fatherly.com", "爸爸育儿"},
		{"Today's Parent", "https://www.todaysparent.com", "今日父母"},
		{"Parenting Science", "https://parentingscience.com", "育儿科学"},
		{"Zero to Three", "https://www.zerotothree.org", "0-3岁发展"},
		{"HealthyChildren", "https://www.healthychildren.org", "儿童健康"},
		{"KidsHealth", "https://kidshealth.org", "儿童健康信息"},
		{"CDC Child Development", "https://www.cdc.gov/ncbddd/childdevelopment", "儿童发展"},
		{"Understood", "https://www.understood.org", "学习差异"},
		{"Child Mind", "https://childmind.org", "儿童心理"},
		{"PBS Kids", "https://pbskids.org", "PBS儿童"},
		{"Nick Jr", "https://www.nickjr.com", "Nick儿童"},
		{"Disney Junior", "https://disneynow.com/disney-junior", "迪士尼儿童"},
		{"CBeebies", "https://www.bbc.co.uk/cbeebies", "BBC儿童"},
		{"Khan Academy Kids", "https://learn.khanacademy.org/khan-academy-kids", "可汗学院儿童"},
		{"ABCmouse", "https://www.abcmouse.com", "儿童学习"},
		{"Homer", "https://www.learnwithhomer.com", "儿童阅读"},
		{"Epic!", "https://www.getepic.com", "儿童电子书"},
		{"Raz-Kids", "https://www.raz-kids.com", "分级阅读"},
		{"Starfall", "https://www.starfall.com", "儿童识字"},
		{"Education.com", "https://www.education.com", "教育资源"},
		{"IXL", "https://www.ixl.com", "K-12学习"},
		{"Prodigy", "https://www.prodigygame.com", "数学游戏"},
		{"SplashLearn", "https://www.splashlearn.com", "数学阅读"},
		{"DreamBox", "https://www.dreambox.com", "自适应数学"},
		{"Time4Learning", "https://www.time4learning.com", "在家教育"},
		{"Outschool", "https://outschool.com", "在线小班课"},
		{"Varsity Tutors", "https://www.varsitytutors.com", "在线辅导"},
		{"Kumon", "https://www.kumon.com", "公文式学习"},
		{"Mathnasium", "https://www.mathnasium.com", "数学学习中心"},
		{"Sylvan Learning", "https://www.sylvanlearning.com", "辅导中心"},
		{"Club Pilates Kids", "https://www.clubpilates.com", "儿童运动"},
		{"Little Gym", "https://www.thelittlegym.com", "儿童体操"},
		{"Gymboree Play", "https://www.gymboree.com", "亲子活动"},
		{"LEGO", "https://www.lego.com", "乐高"},
		{"Melissa & Doug", "https://www.melissaanddoug.com", "儿童玩具"},
		{"Fisher-Price", "https://www.fisher-price.com", "费雪玩具"},
		{"VTech", "https://www.vtechkids.com", "伟易达玩具"},
		{"LeapFrog", "https://www.leapfrog.com", "学习玩具"},
		{"Tonies", "https://tonies.com", "儿童音频盒"},
		{"Yoto", "https://us.yotoplay.com", "儿童音频播放器"},
		{"KiwiCo", "https://www.kiwico.com", "STEM订阅盒"},
		{"Lovevery", "https://lovevery.com", "早教玩具"},
		{"Babylist", "https://www.babylist.com", "母婴清单"},
		{"Buy Buy Baby", "https://www.buybuybaby.com", "母婴用品"},
		{"Carter's", "https://www.carters.com", "童装"},
		{"Primary", "https://www.primary.com", "基础童装"},
		{"Hanna Andersson", "https://www.hannaandersson.com", "有机童装"},
		{"Tea Collection", "https://www.teacollection.com", "全球风格童装"},
		{"PatPat", "https://www.patpat.com", "平价童装"},
		{"Stokke", "https://www.stokke.com", "婴儿家具"},
		{"UPPAbaby", "https://uppababy.com", "婴儿车"},
		{"Bugaboo", "https://www.bugaboo.com", "婴儿车"},
		{"Ergobaby", "https://ergobaby.com", "婴儿背带"},
		{"BabyBjörn", "https://www.babybjorn.com", "婴儿用品"},
		{"Snoo", "https://www.happiestbaby.com/products/snoo", "智能摇篮"},
		{"Nanit", "https://www.nanit.com", "婴儿监视器"},
		{"Owlet", "https://owletcare.com", "婴儿健康监测"},
		{"Hatch", "https://www.hatched.com", "婴儿音响"},
		{"Cocomelon", "https://cocomelon.com", "儿童动画"},
		{"Blippi", "https://blippi.com", "儿童教育视频"},
		{"Super Simple", "https://supersimple.com", "儿童歌曲"},
		{"BabyTV", "https://www.babytv.com", "婴幼儿频道"},
		{"亲宝宝", "https://www.qinbaobao.com", "中国育儿APP"},
		{"宝宝树", "https://www.babytree.com", "中国母婴社区"},
		{"妈妈网", "https://www.mama.cn", "中国妈妈社区"},
		{"育儿网", "https://www.ci123.com", "中国育儿平台"},
		{"小豆苗", "https://www.xiaodoumiao.com", "疫苗接种"},
		{"丁香妈妈", "https://mama.dxy.com", "科学育儿"},
		{"年糕妈妈", "https://www.niangaomama.com", "母婴课程"},
		{"凯叔讲故事", "https://www.kaishustory.com", "儿童有声故事"},
		{"洪恩", "https://www.ihuman.com", "儿童教育APP"},
		{"叽里呱啦", "https://www.jiliguala.com", "幼儿英语"},
		{"斑马AI", "https://www.banmaaike.com", "AI启蒙课"},
		{"火花思维", "https://www.huohua.cn", "儿童思维训练"},
		{"编程猫", "https://www.codemao.cn", "少儿编程"},
		{"Scratch", "https://scratch.mit.edu", "儿童编程"},
		{"Code.org", "https://code.org", "编程教育"},
		{"Tynker", "https://www.tynker.com", "儿童编程"},
		{"Swift Playgrounds", "https://www.apple.com/swift/playgrounds", "苹果编程"},
		{"Roblox Education", "https://education.roblox.com", "Roblox教育"},
		{"Minecraft Education", "https://education.minecraft.net", "我的世界教育"},
		{"Common Sense Media", "https://www.commonsensemedia.org", "媒体评级"},
		{"Family Online Safety", "https://www.fosi.org", "在线安全"},
		{"NetSmartz", "https://www.missingkids.org/netsmartz", "网络安全教育"},
		{"Internet Matters", "https://www.internetmatters.org", "数字安全"},
		{"Bark", "https://www.bark.us", "儿童上网监控"},
		{"Qustodio", "https://www.qustodio.com", "家长控制"},
		{"Circle", "https://meetcircle.com", "家庭网络管理"},
		{"FamilyTime", "https://familytime.io", "家长控制"},
		{"Scholastic", "https://www.scholastic.com", "学乐教育"},
		{"National Geographic Kids", "https://kids.nationalgeographic.com", "国家地理儿童"},
		{"Time for Kids", "https://www.timeforkids.com", "时代儿童"},
		{"Highlights", "https://www.highlights.com", "儿童杂志"},
		{"Brainly", "https://brainly.com", "学生问答"},
		{"Chegg Study", "https://www.chegg.com/study", "学习帮助"},
		{"Photomath Kids", "https://photomath.com", "数学解题"},
		{"Duolingo Kids", "https://www.duolingo.com", "儿童语言"},
		{"Lingokids", "https://lingokids.com", "儿童英语"},
		{"Cambly Kids", "https://www.cambly.com/kids", "外教一对一"},
		{"Novakid", "https://www.novakidschool.com", "儿童英语"},
		{"BrainPOP", "https://www.brainpop.com", "动画教育"},
		{"Funbrain", "https://www.funbrain.com", "游戏学习"},
		{"Cool Math Games", "https://www.coolmathgames.com", "数学游戏"},
	}
}

func agricultureEx() []S {
	return []S{
		{"FAO", "https://www.fao.org", "联合国粮农组织"},
		{"USDA", "https://www.usda.gov", "美国农业部"},
		{"Agriculture.com", "https://www.agriculture.com", "农业资讯"},
		{"Farm Journal", "https://www.agweb.com", "农场杂志"},
		{"Successful Farming", "https://www.agriculture.com/successful-farming", "成功农场"},
		{"Modern Farmer", "https://modernfarmer.com", "现代农民"},
		{"The Farmer's Almanac", "https://www.farmersalmanac.com", "农民年鉴"},
		{"Progressive Farmer", "https://www.dtnpf.com", "进步农民"},
		{"Farmweek", "https://www.farmweek.com", "农场周刊"},
		{"Ag Professional", "https://www.agprofessional.com", "农业专业"},
		{"DTN", "https://www.dtn.com", "农业数据"},
		{"Farm Futures", "https://www.farmfutures.com", "农场期货"},
		{"John Deere", "https://www.deere.com", "约翰迪尔"},
		{"Case IH", "https://www.caseih.com", "凯斯农机"},
		{"CLAAS", "https://www.claas.com", "科乐收农机"},
		{"New Holland", "https://www.newholland.com", "纽荷兰农机"},
		{"Kubota", "https://www.kubota.com", "久保田"},
		{"AGCO", "https://www.agcocorp.com", "爱科集团"},
		{"Trimble Agriculture", "https://agriculture.trimble.com", "精准农业"},
		{"Climate Corporation", "https://climate.com", "气候数据农业"},
		{"FarmLogs", "https://www.farmlogs.com", "农场管理"},
		{"Granular", "https://granular.ag", "农场软件"},
		{"Bushel", "https://www.bushelpowered.com", "粮食交易"},
		{"Agrivi", "https://www.agrivi.com", "农场管理软件"},
		{"FarmERP", "https://www.farmerp.com", "农业ERP"},
		{"Cropio", "https://about.cropio.com", "作物监测"},
		{"OneSoil", "https://onesoil.ai", "AI农业"},
		{"Arable", "https://www.arable.com", "农业物联网"},
		{"Sentera", "https://sentera.com", "农业无人机"},
		{"DJI Agriculture", "https://ag.dji.com", "大疆农业"},
		{"PrecisionHawk", "https://www.precisionhawk.com", "精准农业无人机"},
		{"Indigo Agriculture", "https://www.indigoag.com", "微生物农业"},
		{"Pivot Bio", "https://www.pivotbio.com", "生物固氮"},
		{"Bayer Crop Science", "https://www.cropscience.bayer.com", "拜耳作物"},
		{"Syngenta", "https://www.syngenta.com", "先正达"},
		{"Corteva", "https://www.corteva.com", "科迪华"},
		{"BASF Agriculture", "https://agriculture.basf.com", "巴斯夫农业"},
		{"FMC Corporation", "https://www.fmc.com", "富美实"},
		{"Nufarm", "https://www.nufarm.com", "纽发姆"},
		{"UPL", "https://www.upl-ltd.com", "联合磷化"},
		{"Netafim", "https://www.netafim.com", "滴灌技术"},
		{"Lindsay Corporation", "https://www.lindsay.com", "灌溉系统"},
		{"Valmont Industries", "https://www.valmont.com", "灌溉设备"},
		{"Rain Bird", "https://www.rainbird.com", "灌溉产品"},
		{"Cargill", "https://www.cargill.com", "嘉吉粮商"},
		{"ADM", "https://www.adm.com", "ADM粮商"},
		{"Bunge", "https://www.bunge.com", "邦吉粮商"},
		{"Louis Dreyfus", "https://www.ldc.com", "路易达孚"},
		{"Farmers Edge", "https://www.farmersedge.ca", "数字农业"},
		{"CropX", "https://www.cropx.com", "土壤传感器"},
		{"Taranis", "https://www.taranis.com", "AI作物监测"},
		{"Prospera", "https://www.prospera.ag", "计算机视觉农业"},
		{"AppHarvest", "https://www.appharvest.com", "室内农业"},
		{"AeroFarms", "https://www.aerofarms.com", "垂直农场"},
		{"Plenty", "https://www.plenty.ag", "室内农业"},
		{"Bowery Farming", "https://boweryfarming.com", "垂直农场"},
		{"Gotham Greens", "https://www.gothamgreens.com", "城市温室"},
		{"BrightFarms", "https://www.brightfarms.com", "温室蔬菜"},
		{"Infarm", "https://www.infarm.com", "分布式农业"},
		{"Iron Ox", "https://ironox.com", "机器人农场"},
		{"FarmWise", "https://farmwise.io", "农业机器人"},
		{"Blue River Tech", "https://www.bluerivertechnology.com", "精准喷洒"},
		{"Monarch Tractor", "https://www.monarchtractor.com", "电动拖拉机"},
		{"Naio Technologies", "https://www.naio-technologies.com", "农业机器人"},
		{"中国农业信息网", "https://www.agri.cn", "中国农业信息"},
		{"中国农业网", "https://www.zgny.com.cn", "中国农业门户"},
		{"农民日报", "https://www.farmer.com.cn", "农民报"},
		{"惠农网", "https://www.cnhnb.com", "农产品交易"},
		{"一亩田", "https://www.ymt.com", "农产品电商"},
		{"农管家", "https://www.nongjia.com", "农业服务"},
		{"大丰收", "https://www.dafengshou.com", "农业电商"},
		{"翼龙贷", "https://www.eloancn.com", "三农金融"},
		{"中国种子网", "https://www.chinaseed114.com", "种子信息"},
		{"中国农药信息网", "https://www.chinapesticide.org.cn", "农药信息"},
		{"中国化肥网", "https://www.fert.cn", "化肥信息"},
		{"中国畜牧兽医", "https://www.caas.cn", "畜牧兽医"},
		{"牧原股份", "https://www.muyuanfoods.com", "养猪企业"},
		{"温氏股份", "https://www.wens.com.cn", "畜禽养殖"},
		{"新希望", "https://www.newhopeliuhe.com", "饲料畜牧"},
		{"Impossible Foods", "https://impossiblefoods.com", "植物肉"},
		{"Beyond Meat", "https://www.beyondmeat.com", "植物蛋白"},
		{"Oatly", "https://www.oatly.com", "燕麦奶"},
		{"Perfect Day", "https://perfectday.com", "精密发酵乳蛋白"},
		{"Eat Just", "https://www.ju.st", "植物蛋"},
		{"Aleph Farms", "https://aleph-farms.com", "细胞培养肉"},
		{"Mosa Meat", "https://mosameat.com", "培养肉"},
		{"Memphis Meats", "https://www.upside-foods.com", "细胞肉"},
		{"GreenStar", "https://www.greenstar.org", "绿色农业"},
		{"Rodale Institute", "https://rodaleinstitute.org", "有机农业研究"},
		{"IFOAM", "https://www.ifoam.bio", "国际有机运动"},
		{"Organic Trade Association", "https://ota.com", "有机贸易协会"},
		{"FarmHack", "https://farmhack.org", "农业开源工具"},
		{"Open Food Network", "https://www.openfoodnetwork.org", "开源食品网络"},
		{"FarmOS", "https://farmos.org", "开源农场管理"},
		{"AgriWebb", "https://www.agriwebb.com", "畜牧管理"},
		{"Farmers Business Network", "https://www.fbn.com", "农业网络"},
		{"AgriDigital", "https://www.agridigital.io", "粮食供应链"},
		{"Gro Intelligence", "https://gro-intelligence.com", "农业数据分析"},
		{"Descartes Labs", "https://descarteslabs.com", "遥感农业"},
		{"Planet Labs", "https://www.planet.com", "地球卫星图像"},
		{"Farmers.gov", "https://www.farmers.gov", "美国农民服务"},
		{"Extension", "https://extension.org", "农业推广"},
	}
}

func environmentEx() []S {
	return []S{
		{"Greenpeace", "https://www.greenpeace.org", "绿色和平"},
		{"WWF", "https://www.worldwildlife.org", "世界自然基金"},
		{"Sierra Club", "https://www.sierraclub.org", "塞拉俱乐部"},
		{"Nature Conservancy", "https://www.nature.org", "大自然保护协会"},
		{"EDF", "https://www.edf.org", "环保基金"},
		{"NRDC", "https://www.nrdc.org", "自然资源保护"},
		{"Conservation International", "https://www.conservation.org", "国际保护"},
		{"Rainforest Alliance", "https://www.rainforest-alliance.org", "雨林联盟"},
		{"Ocean Conservancy", "https://oceanconservancy.org", "海洋保护"},
		{"Earth.org", "https://earth.org", "环境新闻"},
		{"Mongabay", "https://news.mongabay.com", "环境新闻"},
		{"Grist", "https://grist.org", "环境杂志"},
		{"DeSmog", "https://www.desmog.com", "气候调查"},
		{"Carbon Brief", "https://www.carbonbrief.org", "气候科学"},
		{"Climate Central", "https://www.climatecentral.org", "气候研究"},
		{"Yale Climate", "https://yaleclimateconnections.org", "耶鲁气候"},
		{"Climate Action Tracker", "https://climateactiontracker.org", "气候行动追踪"},
		{"Global Carbon Atlas", "https://globalcarbonatlas.org", "碳排放"},
		{"Our World in Data Climate", "https://ourworldindata.org/co2-and-other-greenhouse-gas-emissions", "气候数据"},
		{"NASA Climate", "https://climate.nasa.gov", "NASA气候"},
		{"IPCC", "https://www.ipcc.ch", "政府间气候委员会"},
		{"UNFCCC", "https://unfccc.int", "联合国气候公约"},
		{"UNEP", "https://www.unep.org", "联合国环境署"},
		{"EPA Climate", "https://www.epa.gov/climate-change", "EPA气候"},
		{"European Environment Agency", "https://www.eea.europa.eu", "欧洲环境署"},
		{"Copernicus Climate", "https://climate.copernicus.eu", "哥白尼气候"},
		{"WRI", "https://www.wri.org", "世界资源研究所"},
		{"IISD", "https://www.iisd.org", "可持续发展研究所"},
		{"Stockholm Resilience", "https://www.stockholmresilience.org", "恢复力中心"},
		{"Ellen MacArthur Foundation", "https://www.ellenmacarthurfoundation.org", "循环经济"},
		{"Circular Economy Club", "https://www.circulareconomyclub.com", "循环经济社区"},
		{"TreeHugger", "https://www.treehugger.com", "绿色生活"},
		{"Earth911", "https://earth911.com", "回收信息"},
		{"RecycleNow", "https://www.recyclenow.com", "回收指南"},
		{"iRecycle", "https://www.irecycleri.com", "回收站查找"},
		{"Zero Waste Home", "https://zerowastehome.com", "零废弃生活"},
		{"Package Free", "https://packagefreeshop.com", "无包装商店"},
		{"EcoWatch", "https://www.ecowatch.com", "环保新闻"},
		{"Inhabitat", "https://inhabitat.com", "绿色设计"},
		{"Green Building Advisor", "https://www.greenbuildingadvisor.com", "绿色建筑"},
		{"LEED", "https://www.usgbc.org/leed", "绿色建筑认证"},
		{"BREEAM", "https://www.breeam.com", "英国绿色建筑"},
		{"Passive House Institute", "https://passivehouse.com", "被动房研究所"},
		{"Tesla Energy", "https://www.tesla.com/energy", "特斯拉能源"},
		{"SunPower", "https://us.sunpower.com", "太阳能"},
		{"Enphase Energy", "https://enphase.com", "微逆变器"},
		{"SolarEdge", "https://www.solaredge.com", "光伏优化"},
		{"Vestas", "https://www.vestas.com", "风力发电"},
		{"Siemens Gamesa", "https://www.siemensgamesa.com", "风电设备"},
		{"GE Renewable", "https://www.ge.com/renewableenergy", "可再生能源"},
		{"NextEra Energy", "https://www.nexteraenergy.com", "清洁能源"},
		{"Ørsted", "https://orsted.com", "海上风电"},
		{"IRENA", "https://www.irena.org", "国际可再生能源"},
		{"REN21", "https://www.ren21.net", "可再生能源网络"},
		{"BloombergNEF", "https://about.bnef.com", "能源金融"},
		{"CleanTechnica", "https://cleantechnica.com", "清洁技术"},
		{"PV Magazine", "https://www.pv-magazine.com", "光伏杂志"},
		{"Wind Power Monthly", "https://www.windpowermonthly.com", "风电月刊"},
		{"Renewable Energy World", "https://www.renewableenergyworld.com", "可再生能源"},
		{"Energy Storage News", "https://www.energy-storage.news", "储能新闻"},
		{"Utility Dive", "https://www.utilitydive.com", "公用事业"},
		{"Energy Central", "https://energycentral.com", "能源中心"},
		{"Carbon Trust", "https://www.carbontrust.com", "碳信托"},
		{"Gold Standard", "https://www.goldstandard.org", "碳标准"},
		{"Verra", "https://verra.org", "碳信用验证"},
		{"South Pole", "https://www.southpole.com", "碳减排项目"},
		{"Patch", "https://www.patch.io", "碳补偿API"},
		{"Watershed", "https://watershed.com", "企业碳管理"},
		{"Persefoni", "https://persefoni.com", "碳核算"},
		{"Planetly", "https://www.planetly.com", "碳管理"},
		{"Ecologi", "https://ecologi.com", "植树补碳"},
		{"One Tree Planted", "https://onetreeplanted.org", "植树公益"},
		{"TeamTrees", "https://teamtrees.org", "植树项目"},
		{"Eden Reforestation", "https://www.edenprojects.org", "森林恢复"},
		{"Terrapass", "https://terrapass.com", "碳补偿"},
		{"Cool Effect", "https://www.cooleffect.org", "碳减排"},
		{"Wren", "https://www.wren.co", "个人碳补偿"},
		{"Ecosia", "https://www.ecosia.org", "植树搜索引擎"},
		{"Good On You", "https://goodonyou.eco", "可持续时尚"},
		{"B Corp", "https://www.bcorporation.net", "共益企业"},
		{"1% for the Planet", "https://onepercentfortheplanet.org", "环保公益"},
		{"Cradle to Cradle", "https://c2ccertified.org", "摇篮到摇篮"},
		{"EWG", "https://www.ewg.org", "环境工作组"},
		{"Toxic-Free Future", "https://toxicfreefuture.org", "无毒未来"},
		{"中国环境报", "https://www.cenews.com.cn", "中国环境报"},
		{"中国生态环境部", "https://www.mee.gov.cn", "环境部"},
		{"中华环保联合会", "https://www.acef.com.cn", "环保联合会"},
		{"自然之友", "https://www.fon.org.cn", "中国环保组织"},
		{"阿拉善SEE", "https://www.see.org.cn", "生态保护"},
		{"绿色和平中国", "https://www.greenpeace.org.cn", "绿色和平中国"},
		{"公众环境研究中心", "https://www.ipe.org.cn", "环境数据"},
		{"蔚蓝地图", "https://www.ipe.org.cn/MapEnvironment", "环境地图"},
		{"国际能源署", "https://www.iea.org", "IEA"},
		{"World Energy Council", "https://www.worldenergy.org", "世界能源委"},
		{"Rocky Mountain Institute", "https://rmi.org", "落基山研究所"},
		{"Project Drawdown", "https://drawdown.org", "气候解决方案"},
		{"Rewilding Europe", "https://rewildingeurope.com", "欧洲野化"},
		{"Wildlife Trusts", "https://www.wildlifetrusts.org", "野生动物信托"},
		{"Sea Shepherd", "https://seashepherd.org", "海洋守护"},
		{"Coral Reef Alliance", "https://coral.org", "珊瑚礁保护"},
		{"Surfrider Foundation", "https://www.surfrider.org", "海浪骑手基金"},
		{"Water.org", "https://water.org", "清洁饮水"},
		{"Charity: Water", "https://www.charitywater.org", "水资源公益"},
		{"Plastic Pollution Coalition", "https://www.plasticpollutioncoalition.org", "塑料污染"},
		{"Break Free From Plastic", "https://www.breakfreefromplastic.org", "减塑运动"},
		{"4ocean", "https://www.4ocean.com", "海洋清洁"},
		{"The Ocean Cleanup", "https://theoceancleanup.com", "海洋垃圾清理"},
	}
}
