package main

func developer() []S {
	return []S{
		{"GitHub", "https://github.com", "全球最大代码托管平台"},
		{"Stack Overflow", "https://stackoverflow.com", "开发者问答社区"},
		{"MDN Web Docs", "https://developer.mozilla.org", "Web 技术文档"},
		{"Dev.to", "https://dev.to", "开发者社区"},
		{"CodePen", "https://codepen.io", "在线代码编辑器"},
		{"GitLab", "https://gitlab.com", "DevOps 平台"},
		{"npm", "https://www.npmjs.com", "Node.js 包管理"},
		{"PyPI", "https://pypi.org", "Python 包索引"},
		{"Crates.io", "https://crates.io", "Rust 包管理"},
		{"Maven Central", "https://search.maven.org", "Java 包仓库"},
		{"NuGet", "https://www.nuget.org", ".NET 包管理"},
		{"Go.dev", "https://go.dev", "Go 语言官网"},
		{"Rust Lang", "https://www.rust-lang.org", "Rust 语言官网"},
		{"Python.org", "https://www.python.org", "Python 官网"},
		{"TypeScript", "https://www.typescriptlang.org", "TypeScript 官网"},
		{"Node.js", "https://nodejs.org", "Node.js 官网"},
		{"Deno", "https://deno.land", "现代 JS/TS 运行时"},
		{"Bun", "https://bun.sh", "全栈 JS 运行时"},
		{"Bitbucket", "https://bitbucket.org", "Atlassian 代码托管"},
		{"SourceForge", "https://sourceforge.net", "开源项目托管"},
		{"Gitee", "https://gitee.com", "码云代码托管"},
		{"Coding", "https://coding.net", "腾讯云开发者平台"},
		{"JSFiddle", "https://jsfiddle.net", "在线 JS 编辑器"},
		{"CodeSandbox", "https://codesandbox.io", "在线开发环境"},
		{"StackBlitz", "https://stackblitz.com", "在线全栈 IDE"},
		{"Replit", "https://replit.com", "在线 IDE 与部署"},
		{"Codespace", "https://github.com/codespaces", "GitHub 云开发环境"},
		{"Gitpod", "https://gitpod.io", "云端开发环境"},
		{"Glitch", "https://glitch.com", "在线应用构建"},
		{"Observable", "https://observablehq.com", "数据可视化 notebook"},
		{"LeetCode", "https://leetcode.com", "算法刷题平台"},
		{"HackerRank", "https://www.hackerrank.com", "编程挑战平台"},
		{"Codeforces", "https://codeforces.com", "竞赛编程平台"},
		{"TopCoder", "https://www.topcoder.com", "编程竞赛"},
		{"牛客网", "https://www.nowcoder.com", "IT 面试刷题"},
		{"力扣中国", "https://leetcode.cn", "力扣中文版"},
		{"CSDN", "https://www.csdn.net", "中国开发者社区"},
		{"掘金", "https://juejin.cn", "技术社区"},
		{"思否", "https://segmentfault.com", "SegmentFault 社区"},
		{"开源中国", "https://www.oschina.net", "中文开源社区"},
		{"V2EX", "https://www.v2ex.com", "创意工作者社区"},
		{"InfoQ", "https://www.infoq.cn", "技术内容平台"},
		{"CTO Club", "https://www.ctoclub.com", "CTO 社区"},
		{"博客园", "https://www.cnblogs.com", "开发者博客平台"},
		{"OSChina", "https://www.oschina.net/project", "开源项目合集"},
		{"Hacker News", "https://news.ycombinator.com", "Hacker 新闻"},
		{"Product Hunt", "https://www.producthunt.com", "产品发现平台"},
		{"AlternativeTo", "https://alternativeto.net", "软件替代品搜索"},
		{"Awesome", "https://github.com/sindresorhus/awesome", "Awesome 列表合集"},
		{"freeCodeCamp", "https://www.freecodecamp.org", "免费编程学习"},
		{"Codecademy", "https://www.codecademy.com", "交互式编程学习"},
		{"Udemy", "https://www.udemy.com", "在线课程平台"},
		{"Coursera", "https://www.coursera.org", "在线教育平台"},
		{"edX", "https://www.edx.org", "MIT 在线教育"},
		{"Pluralsight", "https://www.pluralsight.com", "技术学习平台"},
		{"Egghead", "https://egghead.io", "Web 开发视频教程"},
		{"Frontend Masters", "https://frontendmasters.com", "前端进阶课程"},
		{"Educative", "https://www.educative.io", "交互式编程课"},
		{"Exercism", "https://exercism.io", "编程练习平台"},
		{"Codewars", "https://www.codewars.com", "编程挑战kata"},
		{"CodingGame", "https://www.codingame.com", "游戏化编程"},
		{"Advent of Code", "https://adventofcode.com", "年度编程挑战"},
		{"Regex101", "https://regex101.com", "正则表达式测试"},
		{"DevDocs", "https://devdocs.io", "API 文档聚合"},
		{"Can I Use", "https://caniuse.com", "浏览器兼容性查询"},
		{"JSONPlaceholder", "https://jsonplaceholder.typicode.com", "假 REST API"},
		{"httpbin", "https://httpbin.org", "HTTP 请求测试"},
		{"Postman", "https://www.postman.com", "API 开发平台"},
		{"Insomnia", "https://insomnia.rest", "REST/GraphQL 客户端"},
		{"Swagger", "https://swagger.io", "API 文档工具"},
		{"GraphQL", "https://graphql.org", "GraphQL 官网"},
		{"gRPC", "https://grpc.io", "高性能 RPC 框架"},
		{"Protocol Buffers", "https://protobuf.dev", "Google 序列化格式"},
		{"WebAssembly", "https://webassembly.org", "WebAssembly 官网"},
		{"WASI", "https://wasi.dev", "WebAssembly 系统接口"},
		{"Wasmer", "https://wasmer.io", "WebAssembly 运行时"},
		{"The Twelve-Factor App", "https://12factor.net", "12因素应用方法论"},
		{"Refactoring Guru", "https://refactoring.guru", "设计模式与重构"},
		{"Clean Code", "https://www.cleancoders.com", "整洁代码实践"},
		{"Martin Fowler", "https://martinfowler.com", "软件架构博客"},
		{"Daily.dev", "https://daily.dev", "开发者新闻聚合"},
		{"Hashnode", "https://hashnode.com", "开发者博客平台"},
		{"Medium", "https://medium.com", "内容发布平台"},
		{"Substack", "https://substack.com", "Newsletter 平台"},
		{"DEV Community", "https://dev.to", "开发者社区博客"},
		{"Lobsters", "https://lobste.rs", "技术社区"},
		{"HN Algolia", "https://hn.algolia.com", "Hacker News 搜索"},
		{"GitBook", "https://www.gitbook.com", "文档协作平台"},
		{"Read the Docs", "https://readthedocs.org", "文档托管平台"},
		{"Docusaurus", "https://docusaurus.io", "文档站点生成器"},
		{"VitePress", "https://vitepress.dev", "Vue 文档生成器"},
		{"Nextra", "https://nextra.site", "Next.js 文档生成"},
	}
}

func shopping() []S {
	return []S{
		{"Amazon", "https://www.amazon.com", "全球最大电商平台"},
		{"淘宝", "https://www.taobao.com", "淘宝购物"},
		{"京东", "https://www.jd.com", "京东购物"},
		{"eBay", "https://www.ebay.com", "全球拍卖购物"},
		{"拼多多", "https://www.pinduoduo.com", "拼多多购物"},
		{"AliExpress", "https://www.aliexpress.com", "阿里国际站"},
		{"天猫", "https://www.tmall.com", "天猫品牌旗舰"},
		{"唯品会", "https://www.vip.com", "品牌特卖"},
		{"苏宁易购", "https://www.suning.com", "苏宁电商"},
		{"国美", "https://www.gome.com.cn", "国美电器"},
		{"当当网", "https://www.dangdang.com", "图书与百货"},
		{"亚马逊中国", "https://www.amazon.cn", "Amazon 中国"},
		{"1号店", "https://www.yhd.com", "网上超市"},
		{"考拉海购", "https://www.kaola.com", "网易考拉海淘"},
		{"洋码头", "https://www.ymatou.com", "海外购物"},
		{"蘑菇街", "https://www.mogujie.com", "女性时尚购物"},
		{"美丽说", "https://www.meilishuo.com", "时尚电商"},
		{"闲鱼", "https://www.xianyu.com", "二手交易平台"},
		{"转转", "https://www.zhuanzhuan.com", "二手交易"},
		{"多点", "https://www.dmall.com", "社区零售电商"},
		{"盒马", "https://www.freshhema.com", "阿里生鲜超市"},
		{"叮咚买菜", "https://www.100.me", "生鲜配送"},
		{"每日优鲜", "https://www.missfresh.cn", "前置仓生鲜"},
		{"Walmart", "https://www.walmart.com", "沃尔玛购物"},
		{"Target", "https://www.target.com", "Target 零售"},
		{"Costco", "https://www.costco.com", "Costco 会员制零售"},
		{"Best Buy", "https://www.bestbuy.com", "Best Buy 电子零售"},
		{"Etsy", "https://www.etsy.com", "手工艺品市场"},
		{"Shopify", "https://www.shopify.com", "电商建站平台"},
		{"Wish", "https://www.wish.com", "移动端购物平台"},
		{"SHEIN", "https://www.shein.com", "快时尚电商"},
		{"Temu", "https://www.temu.com", "拼多多国际版"},
		{"Zalando", "https://www.zalando.com", "欧洲时尚电商"},
		{"ASOS", "https://www.asos.com", "英国时尚电商"},
		{"Farfetch", "https://www.farfetch.com", "奢侈品电商"},
		{"NET-A-PORTER", "https://www.net-a-porter.com", "奢侈品时尚"},
		{"Rakuten", "https://www.rakuten.com", "日本乐天购物"},
		{"Yahoo! Shopping", "https://shopping.yahoo.co.jp", "雅虎购物日本"},
		{"Mercado Libre", "https://www.mercadolibre.com", "拉美电商"},
		{"Flipkart", "https://www.flipkart.com", "印度电商"},
		{"Snapdeal", "https://www.snapdeal.com", "印度电商"},
		{"Coupang", "https://www.coupang.com", "韩国电商"},
		{"Gmarket", "https://www.gmarket.co.kr", "韩国电商"},
		{"Lazada", "https://www.lazada.com", "东南亚电商"},
		{"Shopee", "https://shopee.com", "东南亚电商平台"},
		{"Tokopedia", "https://www.tokopedia.com", "印尼电商"},
		{"Bukalapak", "https://www.bukalapak.com", "印尼电商"},
		{"Jumia", "https://www.jumia.com", "非洲电商平台"},
		{"Noon", "https://www.noon.com", "中东电商"},
		{"Souq", "https://www.amazon.ae", "中东亚马逊"},
		{"Ozon", "https://www.ozon.ru", "俄罗斯电商"},
		{"Wildberries", "https://www.wildberries.ru", "俄罗斯时尚电商"},
		{"Allegro", "https://allegro.pl", "波兰电商"},
		{"Bol.com", "https://www.bol.com", "荷兰电商"},
		{"CDiscount", "https://www.cdiscount.com", "法国电商"},
		{"Otto", "https://www.otto.de", "德国电商"},
		{"Depop", "https://www.depop.com", "二手时尚交易"},
		{"Poshmark", "https://poshmark.com", "二手时尚平台"},
		{"ThredUp", "https://www.thredup.com", "二手衣物电商"},
		{"StockX", "https://stockx.com", "运动鞋交易平台"},
		{"GOAT", "https://www.goat.com", "运动鞋验证交易"},
		{"得物", "https://www.dewu.com", "潮流电商"},
		{"什么值得买", "https://www.smzdm.com", "消费决策平台"},
		{"慢慢买", "https://www.manmanbuy.com", "比价购物助手"},
		{"返利网", "https://www.fanli.com", "购物返利"},
		{"淘宝联盟", "https://pub.alimama.com", "淘宝客推广"},
		{"Honey", "https://www.joinhoney.com", "优惠券浏览器插件"},
		{"Rakuten Rewards", "https://www.rakuten.com/r", "购物返现"},
		{"CamelCamelCamel", "https://camelcamelcamel.com", "Amazon 价格追踪"},
		{"Keepa", "https://keepa.com", "Amazon 价格历史"},
		{"PriceGrabber", "https://www.pricegrabber.com", "比价搜索"},
		{"Google Shopping", "https://shopping.google.com", "Google 购物搜索"},
	}
}

func tools() []S {
	return []S{
		{"Google Drive", "https://drive.google.com", "Google 云存储"},
		{"Notion", "https://www.notion.so", "全能工作空间"},
		{"Figma", "https://www.figma.com", "协作设计工具"},
		{"Canva", "https://www.canva.com", "可视化设计平台"},
		{"Trello", "https://trello.com", "项目管理工具"},
		{"Google Docs", "https://docs.google.com", "在线文档编辑"},
		{"Excalidraw", "https://excalidraw.com", "虚拟白板"},
		{"Obsidian", "https://obsidian.md", "知识管理笔记"},
		{"Logseq", "https://logseq.com", "双向链接笔记"},
		{"Roam Research", "https://roamresearch.com", "网状笔记工具"},
		{"Craft", "https://www.craft.do", "文档与笔记"},
		{"Evernote", "https://evernote.com", "印象笔记"},
		{"OneNote", "https://www.onenote.com", "微软笔记"},
		{"Bear", "https://bear.app", "Markdown 笔记"},
		{"Typora", "https://typora.io", "Markdown 编辑器"},
		{"语雀", "https://www.yuque.com", "专业云端知识库"},
		{"飞书文档", "https://docs.feishu.cn", "飞书在线文档"},
		{"石墨文档", "https://shimo.im", "协同办公云文档"},
		{"腾讯文档", "https://docs.qq.com", "腾讯在线文档"},
		{"金山文档", "https://www.kdocs.cn", "金山WPS在线"},
		{"ProcessOn", "https://www.processon.com", "在线作图协作"},
		{"Miro", "https://miro.com", "在线协作白板"},
		{"FigJam", "https://www.figma.com/figjam", "Figma 白板"},
		{"Whimsical", "https://whimsical.com", "快速线框与流程图"},
		{"Lucidchart", "https://www.lucidchart.com", "在线流程图"},
		{"Draw.io", "https://draw.io", "免费在线画图"},
		{"Mermaid", "https://mermaid.live", "代码生成图表"},
		{"Asana", "https://asana.com", "项目管理平台"},
		{"Monday.com", "https://monday.com", "工作管理平台"},
		{"ClickUp", "https://clickup.com", "生产力平台"},
		{"Linear", "https://linear.app", "团队项目管理"},
		{"Jira", "https://www.atlassian.com/software/jira", "敏捷项目管理"},
		{"Todoist", "https://todoist.com", "任务管理"},
		{"TickTick", "https://ticktick.com", "滴答清单"},
		{"Things 3", "https://culturedcode.com/things", "Apple 任务管理"},
		{"Microsoft To Do", "https://to-do.microsoft.com", "微软待办"},
		{"Google Calendar", "https://calendar.google.com", "Google 日历"},
		{"Calendly", "https://calendly.com", "日程预约"},
		{"Cal.com", "https://cal.com", "开源日程调度"},
		{"Airtable", "https://airtable.com", "智能电子表格"},
		{"Coda", "https://coda.io", "文档+应用平台"},
		{"Google Sheets", "https://sheets.google.com", "Google 电子表格"},
		{"Loom", "https://www.loom.com", "异步视频通讯"},
		{"Krisp", "https://krisp.ai", "AI 降噪"},
		{"Otter.ai", "https://otter.ai", "AI 会议记录"},
		{"Grammarly", "https://www.grammarly.com", "AI 语法检查"},
		{"DeepL", "https://www.deepl.com", "AI 翻译工具"},
		{"TinyPNG", "https://tinypng.com", "图片压缩"},
		{"Squoosh", "https://squoosh.app", "Google 图片压缩"},
		{"Remove.bg", "https://www.remove.bg", "AI 背景移除"},
		{"Photopea", "https://www.photopea.com", "在线图片编辑"},
		{"Pixlr", "https://pixlr.com", "在线图片编辑器"},
		{"CleanUp.pictures", "https://cleanup.pictures", "AI 移除物体"},
		{"PDF24", "https://tools.pdf24.org", "PDF 在线工具"},
		{"SmallPDF", "https://smallpdf.com", "PDF 文件工具"},
		{"iLovePDF", "https://www.ilovepdf.com", "PDF 在线工具集"},
		{"PDF.co", "https://pdf.co", "PDF API 服务"},
		{"1Password", "https://1password.com", "密码管理器"},
		{"Bitwarden", "https://bitwarden.com", "开源密码管理"},
		{"LastPass", "https://www.lastpass.com", "密码管理器"},
		{"KeePass", "https://keepass.info", "开源密码管理"},
		{"NordVPN", "https://nordvpn.com", "VPN 服务"},
		{"Speedtest", "https://www.speedtest.net", "网速测试"},
		{"Fast.com", "https://fast.com", "Netflix 网速测试"},
		{"Wayback Machine", "https://web.archive.org", "互联网档案馆"},
		{"VirusTotal", "https://www.virustotal.com", "在线病毒扫描"},
		{"Have I Been Pwned", "https://haveibeenpwned.com", "数据泄露检查"},
		{"Temp Mail", "https://temp-mail.org", "临时邮箱"},
		{"10 Minute Mail", "https://10minutemail.com", "10分钟临时邮箱"},
		{"Pastebin", "https://pastebin.com", "文本粘贴分享"},
		{"Carbon", "https://carbon.now.sh", "代码截图工具"},
		{"Ray.so", "https://ray.so", "代码截图"},
		{"Warp", "https://www.warp.dev", "现代终端"},
		{"iTerm2", "https://iterm2.com", "macOS 终端"},
		{"Hyper", "https://hyper.is", "跨平台终端"},
		{"WezTerm", "https://wezfurlong.org/wezterm", "GPU 加速终端"},
		{"Alacritty", "https://alacritty.org", "GPU 加速终端"},
		{"VS Code", "https://code.visualstudio.com", "代码编辑器"},
		{"JetBrains", "https://www.jetbrains.com", "IDE 套件"},
		{"Sublime Text", "https://www.sublimetext.com", "文本编辑器"},
		{"Vim", "https://www.vim.org", "Vim 编辑器"},
		{"Neovim", "https://neovim.io", "现代 Vim"},
		{"Zed", "https://zed.dev", "高性能编辑器"},
		{"Helix", "https://helix-editor.com", "后现代编辑器"},
		{"Nova", "https://nova.app", "macOS 原生编辑器"},
		{"微信文件传输助手", "https://filehelper.weixin.qq.com", "微信文件传输"},
		{"奶牛快传", "https://cowtransfer.com", "大文件传输"},
		{"文叔叔", "https://www.wenshushu.cn", "文件传输工具"},
		{"蓝奏云", "https://www.lanzoui.com", "文件分享下载"},
		{"123云盘", "https://www.123pan.com", "不限速云存储"},
	}
}

func design() []S {
	return []S{
		{"Dribbble", "https://dribbble.com", "设计作品展示平台"},
		{"Behance", "https://www.behance.net", "创意作品展示"},
		{"Unsplash", "https://unsplash.com", "免费高分辨率图片"},
		{"Pexels", "https://www.pexels.com", "免费图片视频素材"},
		{"Wallhaven", "https://wallhaven.cc", "壁纸搜索引擎"},
		{"Pinterest", "https://www.pinterest.com", "视觉灵感发现平台"},
		{"Figma Community", "https://www.figma.com/community", "Figma 设计社区"},
		{"Sketch", "https://www.sketch.com", "macOS 设计工具"},
		{"Adobe Creative Cloud", "https://www.adobe.com/creativecloud.html", "Adobe 创意套件"},
		{"InVision", "https://www.invisionapp.com", "设计原型工具"},
		{"Framer", "https://www.framer.com", "网站设计构建器"},
		{"Webflow", "https://webflow.com", "可视化网站构建"},
		{"Principle", "https://principleformac.com", "交互动画设计"},
		{"ProtoPie", "https://www.protopie.io", "高保真交互原型"},
		{"Zeplin", "https://zeplin.io", "设计交接工具"},
		{"Abstract", "https://www.abstract.com", "设计版本控制"},
		{"Coolors", "https://coolors.co", "配色方案生成器"},
		{"Color Hunt", "https://colorhunt.co", "配色灵感"},
		{"Adobe Color", "https://color.adobe.com", "色轮与配色"},
		{"Khroma", "https://www.khroma.co", "AI 配色工具"},
		{"Muzli", "https://muz.li", "设计灵感浏览器插件"},
		{"Awwwards", "https://www.awwwards.com", "网页设计奖项"},
		{"CSS Design Awards", "https://www.cssdesignawards.com", "CSS 设计奖"},
		{"Siteinspire", "https://www.siteinspire.com", "网页设计灵感"},
		{"Webdesign Inspiration", "https://www.webdesign-inspiration.com", "网页设计灵感"},
		{"Mobbin", "https://mobbin.com", "移动 UI 设计参考"},
		{"Screenlane", "https://screenlane.com", "UI 设计参考"},
		{"Pttrns", "https://www.pttrns.com", "移动端设计模式"},
		{"UI8", "https://ui8.net", "UI 设计资源"},
		{"Creative Market", "https://creativemarket.com", "设计资源市场"},
		{"Envato Elements", "https://elements.envato.com", "设计素材订阅"},
		{"Freepik", "https://www.freepik.com", "免费矢量图素材"},
		{"Flaticon", "https://www.flaticon.com", "免费图标库"},
		{"Icons8", "https://icons8.com", "图标与插画"},
		{"Heroicons", "https://heroicons.com", "Tailwind 图标库"},
		{"Phosphor Icons", "https://phosphoricons.com", "灵活图标库"},
		{"Lucide", "https://lucide.dev", "开源图标集"},
		{"Google Fonts", "https://fonts.google.com", "Google 免费字体"},
		{"Font Awesome", "https://fontawesome.com", "图标字体库"},
		{"Material Design", "https://material.io", "Google 设计系统"},
		{"Ant Design", "https://ant.design", "蚂蚁设计系统"},
		{"Chakra UI", "https://chakra-ui.com", "React 组件库"},
		{"shadcn/ui", "https://ui.shadcn.com", "可复制 React 组件"},
		{"Tailwind UI", "https://tailwindui.com", "Tailwind 组件"},
		{"DaisyUI", "https://daisyui.com", "Tailwind 组件库"},
		{"Radix UI", "https://www.radix-ui.com", "无样式组件库"},
		{"Headless UI", "https://headlessui.com", "无样式 UI 组件"},
		{"Storybook", "https://storybook.js.org", "UI 组件开发"},
		{"Chromatic", "https://www.chromatic.com", "视觉回归测试"},
		{"LottieFiles", "https://lottiefiles.com", "动画资源平台"},
		{"Rive", "https://rive.app", "交互动画设计"},
		{"Spline", "https://spline.design", "3D 网页设计"},
		{"Blender", "https://www.blender.org", "开源 3D 创作套件"},
		{"Cinema 4D", "https://www.maxon.net", "3D 设计与动画"},
		{"3ds Max", "https://www.autodesk.com/products/3ds-max", "3D 建模动画"},
		{"站酷", "https://www.zcool.com.cn", "中国设计师社区"},
		{"花瓣网", "https://huaban.com", "设计灵感采集"},
		{"UI中国", "https://www.ui.cn", "UI 设计师社区"},
		{"蓝色理想", "https://www.blueidea.com", "Web 设计社区"},
		{"优设网", "https://www.uisdc.com", "设计师学习平台"},
		{"包图网", "https://ibaotu.com", "原创设计素材"},
		{"摄图网", "https://699pic.com", "正版图片素材"},
		{"觅元素", "https://www.51yuansu.com", "免扣素材"},
		{"千图网", "https://www.58pic.com", "设计素材下载"},
		{"千库网", "https://588ku.com", "免费PNG素材"},
		{"我图网", "https://www.ooopic.com", "图片素材模板"},
		{"图怪兽", "https://818ps.com", "在线平面设计"},
		{"创客贴", "https://www.chuangkit.com", "在线设计工具"},
		{"稿定设计", "https://www.gaoding.com", "在线设计工具"},
		{"Pixso", "https://pixso.cn", "国产协同设计"},
		{"即时设计", "https://js.design", "国产在线设计"},
		{"MasterGo", "https://mastergo.com", "协作式设计工具"},
		{"蓝湖", "https://lanhuapp.com", "产品设计协作"},
		{"墨刀", "https://modao.cc", "原型设计工具"},
		{"Axure", "https://www.axure.com", "原型设计工具"},
		{"Balsamiq", "https://balsamiq.com", "线框图工具"},
		{"Sketch Cloud", "https://www.sketch.com/s", "Sketch 云端"},
		{"Marvel", "https://marvelapp.com", "设计与原型工具"},
		{"Maze", "https://maze.co", "用户测试平台"},
		{"Hotjar", "https://www.hotjar.com", "用户行为分析"},
		{"FullStory", "https://www.fullstory.com", "用户体验分析"},
		{"Mixpanel", "https://mixpanel.com", "产品分析平台"},
		{"Amplitude", "https://amplitude.com", "数字分析平台"},
	}
}
