// Package main generates a SQL migration file with 10,000+ preset sites.
// Usage:
//
//	cd backend && go run ./tools/sitegen -o migrations/011_mass_import_sites.sql
package main

import (
	"flag"
	"fmt"
	"os"
	"strings"
)

// S is a compact site entry: {Title, URL, Description}.
type S = [3]string

// Cat holds a category definition.
type Cat struct {
	ID, Name, ZH, Icon string
	Order              int
}

func main() {
	outFile := flag.String("o", "", "output SQL file (default: stdout)")
	flag.Parse()

	cats := categories()
	data := siteData()

	total := 0
	for _, v := range data {
		total += len(v)
	}
	fmt.Fprintf(os.Stderr, "✅ %d categories, %d sites\n", len(cats), total)

	w := os.Stdout
	if *outFile != "" {
		f, err := os.Create(*outFile)
		if err != nil {
			fmt.Fprintf(os.Stderr, "create file: %v\n", err)
			os.Exit(1)
		}
		defer f.Close()
		w = f
	}

	fmt.Fprintln(w, "-- 011: Mass import preset sites (10,000+ sites across 60 categories)")
	fmt.Fprintln(w, "-- Generated by: cd backend && go run ./tools/sitegen")
	fmt.Fprintln(w, "-- Idempotent: uses ON CONFLICT DO NOTHING / DO UPDATE")
	fmt.Fprintln(w)

	for _, c := range cats {
		fmt.Fprintf(w, "INSERT INTO preset_categories (id, name, icon, sort_order) VALUES\n    ('%s','%s','%s',%d)\nON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;\n\n",
			c.ID, esc(c.Name), c.Icon, c.Order)
	}

	for _, c := range cats {
		sites := data[c.ID]
		if len(sites) == 0 {
			continue
		}
		fmt.Fprintf(w, "-- === %s (%s) — %d sites ===\n", c.ZH, c.Name, len(sites))
		for i := 0; i < len(sites); i += 80 {
			end := min(i+80, len(sites))
			fmt.Fprintln(w, "INSERT INTO preset_sites (category_id, title, url, icon, sort_order, description) VALUES")
			for j := i; j < end; j++ {
				s := sites[j]
				comma := ","
				if j == end-1 {
					comma = ""
				}
				fmt.Fprintf(w, "    ('%s','%s','%s','', %d,'%s')%s\n", c.ID, esc(s[0]), esc(s[1]), j+1, esc(s[2]), comma)
			}
			fmt.Fprintln(w, "ON CONFLICT (url) DO NOTHING;")
			fmt.Fprintln(w)
		}
	}
}

func esc(s string) string { return strings.ReplaceAll(s, "'", "''") }

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
